# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_mexc.futures.core import AuthFuturesMixin
from typed_mexc.core import validator


class ChangeRiskLevelRequest(TypedDict):
  """Change futures risk level request body."""

  symbol: str
  """Contract symbol whose risk level would be changed."""
  level: int
  """Target risk limit level."""


class ChangeRiskLevelResponse(TypedDict):
  """Disabled risk-level change response envelope."""

  success: bool
  """Whether the API request succeeded."""
  code: NotRequired[int]
  """MEXC response code; zero indicates success when present."""
  message: NotRequired[str]
  """Error or status message when present."""
  data: NotRequired[None]
  """No success data is returned by the disabled endpoint."""


adapter = validator(ChangeRiskLevelResponse)


class ChangeRiskLevel(AuthFuturesMixin):
  async def change_risk_level(
    self,
    change_risk_level_request: ChangeRiskLevelRequest,
    *,
    validate: bool | None = None,
  ) -> ChangeRiskLevelResponse:
    """Disabled risk-level switch endpoint documented by MEXC; calls return error code 8817 according to the official docs.

    Args:
      change_risk_level_request: Request parameter.
      validate: Validation override for this request.

    Returns:
      The validated endpoint response.

    References:
      - [MEXC API docs](https://mexcdevelop.github.io/apidocs/contract_v1_en/#switch-the-risk-level)
    """
    params = {}
    r = await self.signed_post(
      '/api/v1/private/account/change_risk_level', json=change_risk_level_request
    )
    return self.envelope_output(r, adapter, validate)
