# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import NotRequired, TypedDict
from typed_binance.core.endpoint.rpc import RpcEndpoint


class SubAccountMarginAccountSummaryItem(TypedDict):
  """One sub-account's margin account totals."""

  email: NotRequired[str]
  """Sub-account email."""
  totalAssetOfBtc: NotRequired[str]
  """Total asset value, in BTC."""
  totalLiabilityOfBtc: NotRequired[str]
  """Total liability, in BTC."""
  totalNetAssetOfBtc: NotRequired[str]
  """Total net asset value, in BTC."""


class SubAccountMarginAccountSummary(TypedDict):
  """Aggregated margin account summary."""

  totalAssetOfBtc: Decimal
  """Total asset value across all sub-accounts, in BTC."""
  totalLiabilityOfBtc: Decimal
  """Total liability across all sub-accounts, in BTC."""
  totalNetAssetOfBtc: Decimal
  """Total net asset value across all sub-accounts, in BTC."""
  subAccountList: list[SubAccountMarginAccountSummaryItem]
  """Per-sub-account breakdown."""


class MarginAccountSummary(RpcEndpoint):
  """Get an aggregated summary of every sub-account's cross-margin account, for the master account."""

  async def margin_account_summary(
    self,
    *,
    validate: bool | None = None,
  ) -> SubAccountMarginAccountSummary:
    """Get an aggregated summary of every sub-account's cross-margin account, for the master account.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/vip-and-institutional-sub-account/api/rest-api/asset-management#get-summary-of-sub-accounts-margin-account)
    """
    return await self.request(
      None,
      method='GET',
      path='/sapi/v1/sub-account/margin/accountSummary',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      response_type=SubAccountMarginAccountSummary,
    )
