# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core.grpc import GrpcEndpoint, wrap_exceptions
from typed_dydx.protos.cosmos.auth.v1beta1 import (
  QueryAccountInfoRequest,
  QueryAccountInfoResponse,
  QueryStub,
)


class AccountInfo(GrpcEndpoint):
  """Query account info which is common to all account types."""

  @wrap_exceptions
  async def account_info(
    self,
    address: str,
  ) -> QueryAccountInfoResponse:
    """Query account info which is common to all account types.

    References:
      - [Official docs](https://docs.cosmos.network/main/build/modules/auth)
    """
    return await QueryStub(self.channel).account_info(
      QueryAccountInfoRequest(address=address)
    )
