# Generated by typed-dev — see CONTRIBUTING.md.
"""`uta.copytrading.current_followers` -- generated from `spec/endpoints/`."""

from typing_extensions import AsyncIterator, Literal, NotRequired
from typed_core.validation import TypedDict, validator
from bitget.core import Timestamp
from bitget.core.endpoint.rpc import RpcEndpoint


class CurrentFollower(TypedDict):
  """One follower currently following the lead account."""

  followerName: str
  """Follower nickname."""
  estimateAssets: str
  """Estimated asset value, in USDT."""
  totalProfit: str
  """Total profit, in USDT."""
  totalShareProfit: str
  """Total profit share paid to the lead account, in USDT."""
  totalInvestment: str
  """Total amount invested, in USDT."""
  canRemove: Literal['yes', 'no']
  """Whether the lead account can remove this follower."""
  followDays: str
  """Number of days this follower has been following, as a decimal string."""
  totalAssets: str
  """Follower's account equity, in USDT."""
  startTime: Timestamp
  """Follow start time."""


class CurrentFollowersPage(TypedDict):
  """One page of current followers."""

  list: list[CurrentFollower]
  """Followers on this page."""
  endId: NotRequired[str | None]
  """Cursor to pass as `cursor` on the next call to page forward; absent/null once there are no further pages. Not shown in the documented response example (which had a single row) but implied by the `cursor` parameter's own description; unconfirmed live."""


class CurrentFollowers(RpcEndpoint):
  """`uta.copytrading.current_followers`."""

  async def current_followers(
    self,
    *,
    limit: int | None = None,
    cursor: str | None = None,
  ) -> CurrentFollowersPage:
    """List the copy-trading lead account's currently-following followers.

    Args:
      limit: Number of results. Default 20, max 100.
      cursor: Cursor ID. Pass the `endId` returned from the previous call to paginate forward (newer records).

    References:
      - [Official docs](https://www.bitget.com/api-doc/uta/copy/futures-public/Get-Current-Followers)
    """
    params = {}
    if limit is not None:
      params['limit'] = limit
    if cursor is not None:
      params['cursor'] = cursor
    return await self.authed_request(
      'GET',
      '/api/v3/copy/futures/current-follower',
      params=params,
      validator=validator(CurrentFollowersPage),
    )

  async def current_followers_paged(
    self,
    *,
    limit: int | None = None,
    max_pages: int | None = None,
  ) -> AsyncIterator[CurrentFollowersPage]:
    """Yield successive pages of `current_followers`.

    Passes each page's token back as `cursor` and stops when a response carries no
    `endId`, or after `max_pages` pages when one is given.
    """
    cursor: str | None = None
    pages = 0
    while True:
      response = await self.current_followers(limit=limit, cursor=cursor)
      yield response
      pages += 1
      if max_pages is not None and pages >= max_pages:
        break
      cursor = response.get('endId') if response is not None else None
      if not cursor:
        break
