# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint
from typed_bitget.schemas import MixHoldSide, MixProductType


class MixClosePositionFailure(TypedDict):
  """One position that failed to close."""

  orderId: str
  """Order ID, if one was assigned before rejection."""
  clientOid: str
  """Client order ID, if one was assigned before rejection."""
  symbol: str
  """Futures symbol."""
  errorMsg: str
  """Human-readable rejection reason."""
  errorCode: str
  """Venue error code for the rejection."""


class MixClosePositionSuccess(TypedDict):
  """One closed position."""

  orderId: str
  """Order ID of the closing order."""
  clientOid: str
  """Client order ID of the closing order."""
  symbol: str
  """Futures symbol."""


class MixClosePositionsResult(TypedDict):
  """Per-position outcome of the flash-close."""

  successList: list[MixClosePositionSuccess]
  """Positions closed."""
  failureList: list[MixClosePositionFailure]
  """Positions not closed."""


class Request(TypedDict):
  """Flash-close request."""

  symbol: NotRequired[str]
  """Restrict to one futures symbol, e.g. "BTCUSDT". Omit to close every open position of the product type."""
  productType: MixProductType
  holdSide: NotRequired[MixHoldSide]


class Close(RpcEndpoint):
  """Flash-close one or all open positions at market price, private."""

  async def close(
    self,
    symbol: str | None = None,
    *,
    product_type: MixProductType,
    hold_side: MixHoldSide | None = None,
    validate: bool | None = None,
  ) -> MixClosePositionsResult:
    """Flash-close one or all open positions at market price, private.

    Args:
      symbol: Restrict to one futures symbol, e.g. "BTCUSDT". Omit to close every open position of the product type.
      product_type:
      hold_side:
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-contract-trade/classic-contract-trade#flash-close-position)
    """
    request: Request = Request(productType=product_type)
    if symbol is not None:
      request['symbol'] = symbol
    if hold_side is not None:
      request['holdSide'] = hold_side
    return await self.request(
      request,
      method='POST',
      path='/api/v2/mix/order/close-positions',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=MixClosePositionsResult,
    )
