# Generated by typed-dev — see CONTRIBUTING.md.
from .bind import Bind
from .create import Create
from .list import List
from .transfer import Transfer
from .update import Update


class SubAccounts(Bind, Create, List, Transfer, Update):
  """Sub-accounts: bind or create sub-account wallets under a master account, list and update them, and transfer between them.

  References:
    - [Upstream docs](https://asterdex.github.io/aster-api-website/futures-v3/account&trades/#bind-sub-account-user_data)
  """
