# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_bybit.core import TimestampMillis
from typed_bybit.core.http import RpcEndpoint


class InsurancePool(TypedDict):
  """One insurance pool."""

  coin: str
  """Coin held by the pool."""
  symbols: str
  """Comma-separated contracts backed by the pool; a single contract means the pool is isolated."""
  balance: str
  """Pool balance, in `coin`."""
  value: str
  """Pool balance valued in USD."""


class Request(TypedDict):
  coin: NotRequired[str]
  """Coin."""


class InsurancePools(TypedDict):
  """Insurance pool balances."""

  updatedTime: TimestampMillis
  """Time the balances were last updated, as a millisecond timestamp."""
  list: list[InsurancePool]
  """Insurance pools."""


class Insurance(RpcEndpoint):
  """Get the balance of each Bybit insurance pool and the contracts it backs."""

  async def insurance(
    self,
    coin: str | None = None,
    *,
    validate: bool | None = None,
  ) -> InsurancePools:
    """Get the balance of each Bybit insurance pool and the contracts it backs.

    Args:
      coin: Coin.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://bybit-exchange.github.io/docs/v5/market/insurance)
    """
    request: Request = Request()
    if coin is not None:
      request['coin'] = coin
    return await self.request(
      request,
      method='GET',
      path='/v5/market/insurance',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=InsurancePools,
    )
