# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class LoanSymbols(TypedDict):
  """Spot symbols tradable under one institutional loan product."""

  productId: str
  """The loan product id."""
  spotSymbols: list[str]
  """Spot trading pairs tradable under this loan product."""


class Request(TypedDict):
  productId: str
  """The loan product id."""


class Symbols(RpcEndpoint):
  """Get the spot trading pairs tradable under a given institutional loan product."""

  async def symbols(
    self, product_id: str, *, validate: bool | None = None
  ) -> LoanSymbols:
    """Get the spot trading pairs tradable under a given institutional loan product.

    Args:
      product_id: The loan product id.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-instloan-public/classic-instloan-public#get-spot-symbols)
    """
    return await self.request(
      Request(productId=product_id),
      method='GET',
      path='/api/v2/spot/ins-loan/symbols',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=LoanSymbols,
    )
