# Generated by typed-dev — see CONTRIBUTING.md.
"""`POST /v5/earn/pwm/asset-manager/manage-order` — Manage Order."""

from typing_extensions import Literal, NotRequired, TypedDict
from typed_bybit.core import Endpoint, TimestampMillis, validator


class PwmManageOrderRequest(TypedDict):
  """Fund order approval or rejection."""

  orderId: str
  """Order identifier. Must currently be in `Pending Review` status."""
  action: Literal['approve', 'reject']
  """Action to take on the order."""
  reqLinkId: str
  """Caller-supplied request ID, max 36 characters, used for idempotency."""


class PwmManageOrderResult(TypedDict):
  """A fund order after approval or rejection."""

  orderId: str
  """Order identifier."""
  fundId: str
  """Fund identifier."""
  accountUid: str
  """Sub-account UID this order applies to."""
  orderStatus: Literal[
    'PendingReview', 'Pass', 'Rejected', 'Processing', 'Success', 'Failed'
  ]
  """Current order status."""
  orderType: Literal['Subscribe', 'Redeem']
  """Order direction."""
  action: Literal['approve', 'reject']
  """Action performed on the order."""
  coin: str
  """Fund base currency."""
  amount: NotRequired[str]
  """Order amount, for a `Subscribe` order."""
  shares: NotRequired[str]
  """Order share count, for a `Redeem` order."""
  updatedTime: TimestampMillis
  """Time of this action, as a millisecond timestamp."""


adapter = validator[PwmManageOrderResult](PwmManageOrderResult)


class ManageOrder(Endpoint):
  """`Manage Order` — mixed into the router that owns `finance.pwm.asset_manager.manage_order`."""

  async def manage_order(
    self,
    pwm_manage_order_request: PwmManageOrderRequest,
    *,
    validate: bool | None = None,
  ) -> PwmManageOrderResult:
    """Approve or reject a pending-review fund subscribe/redeem order. Institution-only.

    Args:
      pwm_manage_order_request: Order approval/rejection.
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/finance/pwm/asset-manager/manage-order)
    """
    r = await self.authed_request(
      'POST', '/v5/earn/pwm/asset-manager/manage-order', json=pwm_manage_order_request
    )
    return self.result(r, adapter, validate)
