# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core.util import StreamManager
from typing_extensions import Any, Literal, NotRequired, TypedDict
from typed_bitget.core import TimestampMillis
from typed_bitget.core.endpoint.stream import StreamEndpoint
from typed_bitget.schemas import ClassicPlanOrdersArg


class MixPlanOrder(TypedDict):
  """One mix (futures) plan/trigger order lifecycle update -- covers preset, partial, position TP/SL and trailing-stop sub-types via `planType`."""

  instId: str
  """Product ID, e.g. `BTCUSDT`."""
  orderId: str
  """Plan (trigger) order ID."""
  clientOid: str
  """Customized plan order ID."""
  triggerPrice: str
  """Trigger price."""
  triggerType: Literal['fill_price', 'mark_price']
  """Trigger reference price."""
  triggerTime: TimestampMillis
  """Trigger time, Unix epoch milliseconds as a string."""
  planType: Literal['pl', 'tp', 'sl', 'ptp', 'psl', 'track', 'mtpsl']
  """Trigger-order sub-type. `pl`: default trigger order. `tp`/`sl`: partial take-profit/stop-loss. `ptp`/`psl`: position take-profit/stop-loss. `track`: trailing stop. `mtpsl`: trailing TP/SL."""
  price: str
  """Order price."""
  executePrice: str
  """Execution price."""
  size: str
  """Original order amount, in the base coin."""
  actualSize: str
  """Actual order amount placed, in the base coin."""
  orderType: Literal['limit', 'market']
  """Order type to place once triggered."""
  side: Literal['buy', 'sell']
  """Order direction."""
  tradeSide: str
  """Trading direction."""
  posSide: str
  """Position direction."""
  marginCoin: str
  """Margin coin."""
  status: Literal['live', 'executed', 'fail_execute', 'cancelled', 'executing']
  """Plan order status."""
  posMode: Literal['one_way_mode', 'hedge_mode']
  """Position mode."""
  enterPointSource: str
  """Order source, e.g. `web`, `API`, `SYS`, `ANDROID`, `IOS`."""
  stopSurplusPrice: NotRequired[str]
  """Take-profit execution price. Meaning depends on `planType`: preset (pl), partial (tp), or position (ptp) take-profit."""
  stopSurplusTriggerPrice: NotRequired[str]
  """Take-profit trigger price; empty when not set."""
  stopSurplusTriggerType: NotRequired[str]
  """Take-profit trigger reference price type; empty when not set."""
  stopLossPrice: NotRequired[str]
  """Stop-loss execution price. Meaning depends on `planType`: preset (pl), partial (sl), or position (psl) stop-loss."""
  stopLossTriggerPrice: NotRequired[str]
  """Stop-loss trigger price."""
  stopLossTriggerType: NotRequired[str]
  """Stop-loss trigger reference price type."""
  uTime: TimestampMillis
  """Update time, Unix epoch milliseconds as a string."""
  cTime: NotRequired[TimestampMillis]
  """Creation time, Unix epoch milliseconds as a string."""
  stpMode: Literal['none', 'cancel_taker', 'cancel_maker', 'cancel_both']
  """Self-trade-prevention mode."""


class Parameters(TypedDict):
  instType: Literal['SPOT', 'USDT-FUTURES', 'COIN-FUTURES', 'USDC-FUTURES']
  """Product line type: `SPOT`, or a futures product type (`USDT-FUTURES`, `COIN-FUTURES`, `USDC-FUTURES`)."""
  instId: NotRequired[str]
  """Product ID, or `default` for all symbols."""


class SpotPlanOrder(TypedDict):
  """One spot plan (trigger) order lifecycle update."""

  instId: str
  """Product ID, e.g. `BTCUSDT`."""
  orderId: str
  """Plan (trigger) order ID."""
  clientOid: str
  """Customized plan order ID."""
  triggerPrice: str
  """Trigger price."""
  triggerType: Literal['fill_price', 'mark_price']
  """Trigger reference price."""
  planType: Literal['amount', 'total']
  """Plan-order sizing type."""
  price: str
  """Order price to place once triggered."""
  size: str
  """Original order amount, in the base coin."""
  actualSize: str
  """Actual order amount placed, in the base coin."""
  orderType: Literal['limit', 'market']
  """Order type to place once triggered."""
  side: Literal['buy', 'sell']
  """Order direction."""
  status: str
  """Plan order status."""
  executePrice: str
  """Execution price."""
  enterPointSource: str
  """Order source, e.g. `web`, `API`, `SYS`, `ANDROID`, `IOS`."""
  cTime: TimestampMillis
  """Creation time, Unix epoch milliseconds as a string."""
  uTime: TimestampMillis
  """Update time, Unix epoch milliseconds as a string."""
  stpMode: Literal['none', 'cancel_taker', 'cancel_maker', 'cancel_both']
  """Self-trade-prevention mode."""


class PlanOrdersPush(TypedDict):
  """Push frame for the `PlanOrdersPush` channel. The core performs no envelope unwrap for streams (see spec/core.md WebSocket): callers receive this whole frame, not one unwrapped `data` element."""

  action: Literal['snapshot', 'update']
  """Push action."""
  arg: ClassicPlanOrdersArg
  data: list[SpotPlanOrder | MixPlanOrder]
  """Subscription data."""
  ts: TimestampMillis
  """Message generation time, Unix epoch milliseconds."""


class PlanOrders(StreamEndpoint):
  """Get plan (trigger) order lifecycle updates, private. Pushed when a trigger plan is opened, cancelled, modified, or triggered."""

  def plan_orders(
    self,
    inst_type: Literal['SPOT', 'USDT-FUTURES', 'COIN-FUTURES', 'USDC-FUTURES'],
    *,
    inst_id: str | None = None,
    validate: bool | None = None,
  ) -> StreamManager[PlanOrdersPush, Any, Any]:
    """Get plan (trigger) order lifecycle updates, private. Pushed when a trigger plan is opened, cancelled, modified, or triggered.

    Args:
      inst_type: Product line type: `SPOT`, or a futures product type (`USDT-FUTURES`, `COIN-FUTURES`, `USDC-FUTURES`).
      inst_id: Product ID, or `default` for all symbols.
      validate: Override this call's pushed-payload validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/classic/websocket/spot/private/Plan-Order-Channel)
    """
    parameters: Parameters = Parameters(instType=inst_type)
    if inst_id is not None:
      parameters['instId'] = inst_id
    return self.subscribe(
      'orders-algo',
      parameters,
      meta={'private': True},
      validate=validate,
      request_type=Parameters,
      response_type=PlanOrdersPush,
    )
