# Generated by typed-dev — see CONTRIBUTING.md.
from .fund_info import FundInfo
from .fund_nav_history import FundNavHistoryEndpoint
from .investor_history import InvestorHistory
from .redemption_calendar import RedemptionCalendarEndpoint


class FundAccount(
  FundInfo, FundNavHistoryEndpoint, InvestorHistory, RedemptionCalendarEndpoint
):
  """Fund Account endpoints -- fund info, NAV history, investor operation history, and the redemption calendar for a VIP fund-manager master account.

  References:
    - [Upstream docs](https://developers.binance.com/en/docs/catalog/vip-and-institutional-fund-account/api/rest-api/~)
  """
