# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import Literal, NotRequired, TypedDict
from typed_coinbase.core import TimestampIso
from typed_coinbase.core.endpoint.rpc import RpcEndpoint


class ExchangeAuctionBook(TypedDict):
  """Indicative auction quote, present only while `auction_mode` is true."""

  open_price: Decimal
  """Indicative auction open price."""
  open_size: Decimal
  """Indicative auction open size."""
  best_bid_price: Decimal
  """Best indicative bid price."""
  best_bid_size: Decimal
  """Best indicative bid size."""
  best_ask_price: Decimal
  """Best indicative ask price."""
  best_ask_size: Decimal
  """Best indicative ask size."""
  auction_state: str
  """Auction phase, e.g. `collection`. Not documented as a closed set."""
  can_open: NotRequired[str]
  """Whether the auction can open, e.g. `yes`/`no`. Not documented as a closed set."""
  time: NotRequired[TimestampIso]
  """Time this indicative quote was generated."""


class Request(TypedDict):
  product_id: str
  """Trading pair id, e.g. `BTC-USD`."""
  level: NotRequired[Literal[1, 2, 3]]
  """Order book detail level: `1` (best bid/ask only), `2` (top 50 aggregated levels, order count per level), or `3` (full non-aggregated book, one row per order)."""


class ExchangeProductBook(TypedDict):
  """A snapshot of a product's order book at a given aggregation level."""

  bids: list[tuple[Decimal, Decimal, int | str]]
  """Bid rows, best (highest) price first."""
  asks: list[tuple[Decimal, Decimal, int | str]]
  """Ask rows, best (lowest) price first."""
  sequence: int
  """Order book sequence number at the time of this snapshot."""
  auction_mode: bool
  """Whether the product is currently in auction mode."""
  auction: ExchangeAuctionBook | None
  """Indicative auction quote, or null when the product is not in auction mode -- confirmed live (null on a non-auction product)."""
  time: TimestampIso
  """Time this snapshot was generated."""


class Book(RpcEndpoint):
  """Get a snapshot of open orders (the order book) for a product. The amount of detail shown is controlled by `level`. No authentication required."""

  async def book(
    self,
    product_id: str,
    *,
    level: Literal[1, 2, 3] | None = None,
    validate: bool | None = None,
  ) -> ExchangeProductBook:
    """Get a snapshot of open orders (the order book) for a product. The amount of detail shown is controlled by `level`. No authentication required.

    Args:
      product_id: Trading pair id, e.g. `BTC-USD`.
      level: Order book detail level: `1` (best bid/ask only), `2` (top 50 aggregated levels, order count per level), or `3` (full non-aggregated book, one row per order).
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.cdp.coinbase.com/exchange/rest-api/api-reference)
    """
    request: Request = Request(product_id=product_id)
    if level is not None:
      request['level'] = level
    return await self.request(
      request,
      method='GET',
      path='/products/{product_id}/book',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=ExchangeProductBook,
    )
