# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, TypedDict
from typed_moralis.core import RpcEndpoint
from pydantic import TypeAdapter


class NativeBalanceResponse(TypedDict):
  """Schema inferred from a live Moralis response captured by spec collection."""

  lamports: str
  """Lamports."""
  solana: str
  """Solana."""


native_balance_adapter = TypeAdapter(NativeBalanceResponse)


class NativeBalance(RpcEndpoint):
  async def native_balance(
    self,
    network: Literal['mainnet', 'devnet'],
    address: str,
    *,
    validate: bool | None = None,
  ) -> NativeBalanceResponse:
    """Gets native balance owned by the given address

    Args:
      network: The network to query
      address: The address to query
      validate: Per-call response validation override.

    References:
      - [Moralis API docs](https://docs.moralis.com/data-api/solana/wallet/native-balance)
    """
    response = await self.request('GET', f'/account/{network}/{address}/balance')
    if self.should_validate(validate):
      return native_balance_adapter.validate_json(response.text)
    return response.json()
