# Generated by typed-dev — see CONTRIBUTING.md.
from .detailed_positions import DetailedPositions
from .wallet_positions import WalletPositions
from .wallet_protocols import WalletProtocols


class Legacy(DetailedPositions, WalletPositions, WalletProtocols):
  """Grouped Moralis Legacy endpoints."""
