# Generated by typed-dev — see CONTRIBUTING.md.
from dataclasses import dataclass
from typed_coinbase.core.endpoint.rpc import RpcClient
from .crypto import Crypto
from .list import List


@dataclass(frozen=True, kw_only=True)
class Currencies(Crypto, List):
  """`currencies` endpoints."""

  @classmethod
  def new(cls, *, client: RpcClient) -> 'Currencies':
    return cls(client=client)
