# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core import PaginatedResponse
from typing_extensions import Literal, NotRequired, Sequence, TypedDict
from typed_etherscan.core import TimestampSeconds
from typed_etherscan.core.rest import RpcEndpoint


L2PlasmaDepositKeywords = TypedDict(
  'L2PlasmaDepositKeywords', {'from': NotRequired[str]}
)
"""
- `from`: Address that initiated the deposit.
"""


class L2PlasmaDeposit(L2PlasmaDepositKeywords):
  """Result item returned by Etherscan."""

  hash: NotRequired[str]
  """Transaction hash."""
  blockNumber: NotRequired[int]
  """Block number containing the transaction."""
  timeStamp: NotRequired[TimestampSeconds]
  """Time the block was mined, as a Unix timestamp in seconds."""
  address: NotRequired[str]
  """Address that received the deposit."""
  amount: NotRequired[int]
  """Amount deposited, in the token's smallest unit."""
  tokenName: NotRequired[str]
  """Name of the deposited token."""
  symbol: NotRequired[str]
  """Symbol of the deposited token."""
  contractAddress: NotRequired[str]
  """Contract address of the deposited token."""
  divisor: NotRequired[int]
  """Number of decimals the deposited token uses."""


class Request(TypedDict):
  chainid: NotRequired[str]
  """Chain ID of the Etherscan-supported network to query for this endpoint."""
  module: Literal['account']
  """Fixed Etherscan API module selector for this operation; use `account`."""
  action: Literal['txnbridge']
  """Fixed Etherscan API action selector for this operation; use `txnbridge`."""
  address: str
  """Address to check for the documented L2 bridge transaction type."""
  page: NotRequired[int]
  """Page number for paginated results, starting at 1."""
  offset: NotRequired[int]
  """Maximum number of records to return per page."""


class EtherscanResponse(TypedDict):
  status: Literal['0', '1']
  """Etherscan status code."""
  message: str
  """Etherscan status message."""
  result: list[L2PlasmaDeposit]
  """List of result objects returned by Etherscan."""


class PlasmaDeposits(RpcEndpoint):
  """Get Plasma bridge deposit transactions for an address."""

  def plasma_deposits_paged(
    self,
    *,
    chainid: str | None = None,
    module: Literal['account'] = 'account',
    action: Literal['txnbridge'] = 'txnbridge',
    address: str,
    offset: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[L2PlasmaDeposit, int]:
    """Get Plasma bridge deposit transactions for an address.

    Paged variant of `plasma_deposits`: Requests `page` from 1 upwards and stops on the first page shorter than `offset`. Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      chainid: Chain ID of the Etherscan-supported network to query for this endpoint.
      module: Fixed Etherscan API module selector for this operation; use `account`.
      action: Fixed Etherscan API action selector for this operation; use `txnbridge`.
      address: Address to check for the documented L2 bridge transaction type.
      offset: Maximum number of records to return per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.etherscan.io/api-reference/endpoint/txnbridge)
    """

    async def next(page: int) -> tuple[Sequence[L2PlasmaDeposit], int | None]:
      response = await self.plasma_deposits(
        chainid=chainid,
        module=module,
        action=action,
        address=address,
        offset=offset,
        page=page,
        validate=validate,
      )
      rows = response.get('result')
      rows = rows if rows is not None else []
      if not rows or len(rows) < (offset if offset is not None else 100):
        return rows, None
      return rows, page + 1

    return PaginatedResponse(1, next)

  async def plasma_deposits(
    self,
    *,
    chainid: str | None = None,
    module: Literal['account'] = 'account',
    action: Literal['txnbridge'] = 'txnbridge',
    address: str,
    page: int | None = None,
    offset: int | None = None,
    validate: bool | None = None,
  ) -> EtherscanResponse:
    """Get Plasma bridge deposit transactions for an address.

    Args:
      chainid: Chain ID of the Etherscan-supported network to query for this endpoint.
      module: Fixed Etherscan API module selector for this operation; use `account`.
      action: Fixed Etherscan API action selector for this operation; use `txnbridge`.
      address: Address to check for the documented L2 bridge transaction type.
      page: Page number for paginated results, starting at 1.
      offset: Maximum number of records to return per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.etherscan.io/api-reference/endpoint/txnbridge)
    """
    request: Request = Request(module=module, action=action, address=address)
    if chainid is not None:
      request['chainid'] = chainid
    if page is not None:
      request['page'] = page
    if offset is not None:
      request['offset'] = offset
    return await self.request(
      request,
      method='GET',
      path='/v2/api',
      meta={'credentials': True},
      validate=validate,
      request_type=Request,
      response_type=EtherscanResponse,
    )
