# Generated by typed-dev — see CONTRIBUTING.md.
"""`GET /v5/account/instruments-info` — Get Account Instruments Info."""

from typing_extensions import AsyncIterator, Literal, NotRequired, TypedDict
from typed_bybit.core import Endpoint, TimestampMillis, validator


class AccountContractLotSizeFilter(TypedDict):
  """Quantity constraints for a linear or inverse contract."""

  maxOrderQty: str
  """Maximum quantity of a limit or PostOnly order."""
  minOrderQty: str
  """Minimum order quantity."""
  qtyStep: str
  """Quantity increment."""
  minNotionalValue: NotRequired[str]
  """Minimum notional value of an order."""


class AccountContractPriceFilter(TypedDict):
  """Price constraints for a contract."""

  minPrice: str
  """Minimum order price."""
  maxPrice: str
  """Maximum order price."""
  tickSize: str
  """Price increment."""


class AccountContractRiskParameters(TypedDict):
  """Price limit ratios used for risk management."""

  priceLimitRatioX: NotRequired[str]
  """Upper price limit ratio."""
  priceLimitRatioY: NotRequired[str]
  """Lower price limit ratio."""


class AccountLeverageFilter(TypedDict):
  """Leverage constraints for a contract."""

  minLeverage: str
  """Minimum leverage."""
  maxLeverage: str
  """Maximum leverage."""
  leverageStep: str
  """Leverage increment."""


class AccountRiskParameters(TypedDict):
  """Price limit ratios used for risk management."""

  priceLimitRatioX: NotRequired[str]
  """Upper price limit ratio."""
  priceLimitRatioY: NotRequired[str]
  """Lower price limit ratio."""


class AccountSpotLotSizeFilter(TypedDict):
  """Quantity and amount constraints for a spot pair."""

  basePrecision: str
  """Decimal precision of the base coin quantity."""
  quotePrecision: str
  """Decimal precision of the quote coin amount."""
  minOrderQty: str
  """Minimum order quantity. Deprecated upstream in favour of `minOrderAmt`."""
  maxOrderQty: str
  """Maximum order quantity. Deprecated upstream."""
  minOrderAmt: str
  """Minimum order amount in the quote coin."""
  maxOrderAmt: str
  """Maximum order amount in the quote coin. Deprecated upstream."""
  maxLimitOrderQty: str
  """Maximum quantity of a limit order."""
  maxMarketOrderQty: str
  """Maximum quantity of a market order."""
  postOnlyMaxLimitOrderSize: str
  """Maximum size of a PostOnly or RPI limit order."""


class AccountSpotPriceFilter(TypedDict):
  """Price constraints for a spot pair."""

  tickSize: str
  """Price increment."""


class AccountContractInstrument(TypedDict):
  """A linear or inverse contract tradable from this account."""

  symbol: str
  """Symbol name."""
  symbolId: NotRequired[int]
  """Numeric symbol identifier."""
  contractType: Literal[
    'InversePerpetual', 'LinearPerpetual', 'LinearFutures', 'InverseFutures'
  ]
  """Contract type."""
  status: Literal['PreLaunch', 'Trading', 'Delivering', 'Closed']
  """Trading status of the contract."""
  baseCoin: str
  """Base coin."""
  quoteCoin: str
  """Quote coin."""
  launchTime: TimestampMillis
  """Launch time, as a millisecond timestamp."""
  deliveryTime: TimestampMillis
  """Delivery or delisting time, as a millisecond timestamp; `0` for perpetuals."""
  priceScale: str
  """Number of decimal places used for the price."""
  leverageFilter: AccountLeverageFilter
  priceFilter: AccountContractPriceFilter
  lotSizeFilter: AccountContractLotSizeFilter
  fundingInterval: int
  """Funding interval in minutes."""
  settleCoin: str
  """Settlement coin."""
  copyTrading: NotRequired[Literal['none', 'both', 'utaOnly', 'normalOnly']]
  """Copy trading eligibility of the contract."""
  riskParameters: NotRequired[AccountContractRiskParameters]
  isPreListing: NotRequired[bool]
  """Whether the contract is a pre-market contract."""
  isPublicRpi: NotRequired[bool]
  """Whether the contract supports Retail Price Improvement orders."""


class AccountSpotInstrument(TypedDict):
  """A spot pair tradable from this account."""

  symbolId: int
  """Numeric symbol identifier."""
  symbol: str
  """Symbol name."""
  baseCoin: str
  """Base coin."""
  quoteCoin: str
  """Quote coin."""
  innovation: NotRequired[Literal['0', '1']]
  """Whether the pair is in the innovation zone."""
  status: Literal['PreLaunch', 'Trading', 'Delivering', 'Closed']
  """Trading status of the pair."""
  marginTrading: Literal['none', 'both', 'utaOnly', 'normalSpotOnly']
  """Margin trading support for the pair."""
  stTag: NotRequired[Literal['0', '1']]
  """Whether the pair carries the special treatment tag."""
  lotSizeFilter: AccountSpotLotSizeFilter
  priceFilter: AccountSpotPriceFilter
  riskParameters: NotRequired[AccountRiskParameters]
  symbolType: NotRequired[str]
  """Regional or thematic classification, for example `stock` or an empty string."""
  isPublicRpi: NotRequired[bool]
  """Whether the pair supports Retail Price Improvement orders."""
  myRpiPermission: NotRequired[bool]
  """Whether this account may submit RPI orders on the pair."""
  xstockMultiplier: NotRequired[str]
  """Share multiplier; only meaningful for tokenised stock pairs."""


class AccountContractInstrumentsInfo(TypedDict):
  """Instrument definitions for linear or inverse contracts tradable from this account. Not live-verified -- see notes."""

  category: Literal['linear', 'inverse']
  """Product type."""
  nextPageCursor: NotRequired[str]
  """Opaque cursor for the next page. Pass it back as `cursor`; an empty string means there are no further pages."""
  list: list[AccountContractInstrument]
  """Linear or inverse contracts."""


class AccountSpotInstrumentsInfo(TypedDict):
  """Instrument definitions for spot pairs tradable from this account."""

  category: Literal['spot']
  """Product type."""
  list: list[AccountSpotInstrument]
  """Spot pairs."""


adapter = validator[AccountSpotInstrumentsInfo | AccountContractInstrumentsInfo](
  AccountSpotInstrumentsInfo | AccountContractInstrumentsInfo
)


class InstrumentsInfo(Endpoint):
  """`Get Account Instruments Info` — mixed into the router that owns `account.instruments_info`."""

  async def instruments_info(
    self,
    *,
    category: Literal['spot', 'linear', 'inverse'],
    symbol: str | None = None,
    limit: int | None = None,
    cursor: str | None = None,
    validate: bool | None = None,
  ) -> AccountSpotInstrumentsInfo | AccountContractInstrumentsInfo:
    """Get the trading rules of every instrument tradable from this account, in a product category: tick size, quantity step, leverage bounds, launch and delivery times.

    Args:
      category: Product type.
      symbol: Symbol name, uppercase only.
      limit: Number of instruments per page. Range [1, 200]; defaults to 200. Ignored for spot.
      cursor: Opaque pagination cursor. Pass the `nextPageCursor` returned by the previous page; omit it for the first page. Ignored for spot.
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/account/instrument)
    """
    params: dict = {
      'category': category,
    }
    if symbol is not None:
      params['symbol'] = symbol
    if limit is not None:
      params['limit'] = limit
    if cursor is not None:
      params['cursor'] = cursor
    r = await self.authed_request('GET', '/v5/account/instruments-info', params=params)
    return self.result(r, adapter, validate)

  async def instruments_info_paged(
    self,
    *,
    category: Literal['spot', 'linear', 'inverse'],
    symbol: str | None = None,
    limit: int | None = None,
    max_pages: int | None = None,
    validate: bool | None = None,
  ) -> AsyncIterator[AccountSpotInstrumentsInfo | AccountContractInstrumentsInfo]:
    """Yield successive pages of `instruments_info`.

    Passes each page's token back as `cursor` and stops when a response carries no
    `nextPageCursor`, or after `max_pages` pages when one is given.
    """
    cursor: str | None = None
    pages = 0
    while True:
      response = await self.instruments_info(
        category=category, symbol=symbol, limit=limit, cursor=cursor, validate=validate
      )
      yield response
      pages += 1
      if max_pages is not None and pages >= max_pages:
        break
      cursor = response.get('nextPageCursor') if response is not None else None
      if not cursor:
        break
