# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, TypedDict
from typed_lighter.core.endpoint.rpc import RpcEndpoint
from typed_lighter.schemas import Txs


class BlockTxsByCommitment(TypedDict):
  by: Literal['block_commitment']
  """Look the block up by commitment."""
  value: str
  """Block commitment (hex)."""


class BlockTxsByHeight(TypedDict):
  by: Literal['block_height']
  """Look the block up by height."""
  value: int
  """Block height."""


Request = BlockTxsByHeight | BlockTxsByCommitment


class BlockTxs(RpcEndpoint):
  """Get the transactions of one L2 block, by block height or block commitment. Lighter's mainnet host currently refuses it (CloudFront `403 Request blocked`, raised as `ApiError(403)`); it works on testnet."""

  async def block_txs(
    self,
    block_txs_lookup: Request,
    *,
    validate: bool | None = None,
  ) -> Txs:
    """Get the transactions of one L2 block, by block height or block commitment. Lighter's mainnet host currently refuses it (CloudFront `403 Request blocked`, raised as `ApiError(403)`); it works on testnet.

    Args:
      block_txs_lookup: The block whose transactions to fetch: by height or by commitment.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
    """
    return await self.request(
      block_txs_lookup,
      method='GET',
      path='/api/v1/blockTxs',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=Txs,
    )
