# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import TypedDict
from typed_core.validation import validator
from binance.core.endpoint.ws_rpc import WsRpcEndpoint


class ListenTokenSubscription(TypedDict):
  """The resulting subscription."""

  subscriptionId: int
  """Id of the new subscription."""
  expirationTime: int
  """Expiration time of the underlying listen token. Unit is unconfirmed -- the documented example value has too many digits for Unix epoch milliseconds; no `format` is declared pending confirmation against a live call."""


class SubscribeListenToken(WsRpcEndpoint):
  """Subscribe to User Data Stream through listenToken"""

  async def subscribe_listen_token(
    self,
    *,
    listen_token: str,
    validate: bool | None = None,
  ) -> ListenTokenSubscription:
    """Subscribe this WebSocket API connection to the (margin) User Data Stream using a listen token obtained from `POST /sapi/v1/userListenToken`.

    Args:
      listen_token: Listen token obtained from `POST /sapi/v1/userListenToken`.

    References:
      - [Official docs](https://developers.binance.com/docs/margin_trading/trade-data-stream/Listen-Token-Websocket-API)
    """
    params: dict = {
      'listenToken': listen_token,
    }
    _Response = ListenTokenSubscription
    _validator = validator[_Response](_Response)
    return await self.request(
      'userDataStream.subscribe.listenToken',
      params=params,
      validator=_validator,
      validate=validate,
    )
