# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_coinbase.core import TimestampIso
from typed_coinbase.core.endpoint.rpc import RpcEndpoint
from typed_coinbase.schemas import Money, PaymentMethodReference, TransactionReference


class Request(TypedDict):
  account_id: str
  """The fiat account the deposit belongs to."""
  deposit_id: str
  """The deposit to fetch."""


class Deposit(TypedDict):
  """A deposit of funds into a fiat account using a linked payment method. Each committed deposit also has an associated transaction."""

  id: str
  """Resource id."""
  status: Literal['created', 'completed', 'canceled']
  """Status of the deposit."""
  payment_method: PaymentMethodReference
  transaction: TransactionReference
  amount: Money
  subtotal: Money
  fee: Money
  created_at: TimestampIso
  """When this deposit was created, RFC3339."""
  updated_at: TimestampIso
  """When this deposit was last updated, RFC3339."""
  resource: Literal['deposit']
  """Resource type, always `deposit`."""
  resource_path: str
  """API path to fetch this deposit resource."""
  payout_at: NotRequired[TimestampIso | None]
  """When a deposit that isn't executed instantly will pay out, RFC3339, or null when not applicable."""
  commited: bool
  """Whether this deposit has been committed. Verified live: the wire key is `commited` (single 't'), not `committed` as documented."""


class GetDepositResponse(TypedDict):
  """Wrapper around a single deposit."""

  data: Deposit


class Get(RpcEndpoint):
  """Get one deposit by id."""

  async def get(
    self,
    *,
    account_id: str,
    deposit_id: str,
    validate: bool | None = None,
  ) -> GetDepositResponse:
    """Get one deposit by id.

    Args:
      account_id: The fiat account the deposit belongs to.
      deposit_id: The deposit to fetch.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.cdp.coinbase.com/coinbase-app/transfer-apis/deposit-fiat)
    """
    return await self.request(
      Request(account_id=account_id, deposit_id=deposit_id),
      method='GET',
      path='/v2/accounts/{account_id}/deposits/{deposit_id}',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=GetDepositResponse,
    )
