from typing_extensions import Literal, NotRequired, TypedDict
from typed_core.validation import validator
from binance.core import Timestamp
from binance.core.endpoint.rpc import RpcEndpoint


class PmNewMarginOrderFills(TypedDict):
  """PmNewMarginOrderFills."""

  price: NotRequired[str]
  """Price."""
  qty: NotRequired[str]
  """Qty."""
  commission: NotRequired[str]
  """Commission."""
  commissionAsset: NotRequired[str]
  """Commission Asset."""


class PmNewMarginOrder(TypedDict):
  """New Margin Order."""

  symbol: NotRequired[str]
  """Trade symbol, if existing."""
  orderId: NotRequired[int]
  """Normal orderID after trigger if appliable, only have when the strategy is triggered."""
  clientOrderId: NotRequired[str]
  """Client Order ID."""
  transactTime: NotRequired[Timestamp]
  """Transact Time."""
  price: NotRequired[str]
  """Price."""
  origQty: NotRequired[str]
  """Orig Qty."""
  executedQty: NotRequired[str]
  """Executed Qty."""
  cummulativeQuoteQty: NotRequired[str]
  """Cummulative Quote Qty."""
  status: NotRequired[str]
  """Enum：completed，processing."""
  timeInForce: NotRequired[Literal['GTC', 'IOC', 'FOK']]
  """Time In Force."""
  type: NotRequired[
    Literal[
      'LIMIT',
      'MARKET',
      'STOP_LOSS',
      'STOP_LOSS_LIMIT',
      'TAKE_PROFIT',
      'TAKE_PROFIT_LIMIT',
      'LIMIT_MAKER',
    ]
  ]
  """Normal order type after trigger if appliable."""
  side: NotRequired[Literal['BUY', 'SELL']]
  """Side."""
  marginBuyBorrowAmount: NotRequired[str]
  """will not return if no margin trade happens."""
  marginBuyBorrowAsset: NotRequired[str]
  """will not return if no margin trade happens."""
  fills: NotRequired[list[PmNewMarginOrderFills]]
  """Fills."""


class NewMarginOrder(RpcEndpoint):
  """New Margin Order"""

  async def new_margin_order(
    self,
    *,
    symbol: str,
    side: Literal['BUY', 'SELL'],
    type: Literal[
      'LIMIT',
      'MARKET',
      'STOP_LOSS',
      'STOP_LOSS_LIMIT',
      'TAKE_PROFIT',
      'TAKE_PROFIT_LIMIT',
      'LIMIT_MAKER',
    ],
    quantity: float | None = None,
    quote_order_qty: float | None = None,
    price: float | None = None,
    stop_price: float | None = None,
    new_client_order_id: str | None = None,
    new_order_resp_type: Literal['ACK', 'RESULT', 'FULL'] | None = None,
    iceberg_qty: float | None = None,
    side_effect_type: Literal[
      'NO_SIDE_EFFECT', 'MARGIN_BUY', 'AUTO_REPAY', 'AUTO_BORROW_REPAY'
    ]
    | None = None,
    time_in_force: Literal['GTC', 'IOC', 'FOK'] | None = None,
    self_trade_prevention_mode: Literal[
      'NONE', 'EXPIRE_TAKER', 'EXPIRE_BOTH', 'EXPIRE_MAKER'
    ]
    | None = None,
    auto_repay_at_cancel: bool | None = None,
    validate: bool | None = None,
  ) -> PmNewMarginOrder:
    """New Margin Order.

    Args:
      symbol: Trading pair symbol.
      side: Order side.
      type: Order type.
      quantity: Order quantity, in the base asset.
      quote_order_qty: Order quantity, in the quote asset.
      price: Order price.
      stop_price: Used with `STOP_LOSS`, `STOP_LOSS_LIMIT`, `TAKE_PROFIT`, and `TAKE_PROFIT_LIMIT` orders.
      new_client_order_id: A unique id among open orders. Automatically generated if not sent.
      new_order_resp_type: Set the response JSON. ACK, RESULT, or FULL.
      iceberg_qty: Used with `LIMIT`, `STOP_LOSS_LIMIT`, and `TAKE_PROFIT_LIMIT` to create an iceberg order.
      side_effect_type: Margin borrow/repay side effect triggered by the order.
      time_in_force: Time in force.
      self_trade_prevention_mode: `NONE`:No STP / `EXPIRE_TAKER`:expire taker order when STP triggers/ `EXPIRE_MAKER`:expire taker order when STP triggers/ `EXPIRE_BOTH`:expire both orders when STP triggers.
      auto_repay_at_cancel: Only when MARGIN_BUY or AUTO_BORROW_REPAY order takes effect, true means that the debt generated by the order needs to be repaid after the order is cancelled.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/trade#new-margin-order)
    """
    params: dict = {
      'symbol': symbol,
      'side': side,
      'type': type,
    }
    if quantity is not None:
      params['quantity'] = quantity
    if quote_order_qty is not None:
      params['quoteOrderQty'] = quote_order_qty
    if price is not None:
      params['price'] = price
    if stop_price is not None:
      params['stopPrice'] = stop_price
    if new_client_order_id is not None:
      params['newClientOrderId'] = new_client_order_id
    if new_order_resp_type is not None:
      params['newOrderRespType'] = new_order_resp_type
    if iceberg_qty is not None:
      params['icebergQty'] = iceberg_qty
    if side_effect_type is not None:
      params['sideEffectType'] = side_effect_type
    if time_in_force is not None:
      params['timeInForce'] = time_in_force
    if self_trade_prevention_mode is not None:
      params['selfTradePreventionMode'] = self_trade_prevention_mode
    if auto_repay_at_cancel is not None:
      params['autoRepayAtCancel'] = auto_repay_at_cancel
    _Response = PmNewMarginOrder
    _validator = validator[_Response](_Response)
    return await self.authed_request(
      'POST',
      '/papi/v1/margin/order',
      params=params,
      validator=_validator,
      validate=validate,
    )
