# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_core.validation import validator
from binance.core import Timestamp
from binance.core.endpoint.rpc import RpcEndpoint


class PmUmOrder(TypedDict):
  """Check an UM order's status."""

  avgPrice: NotRequired[str]
  """Avg Price."""
  clientOrderId: NotRequired[str]
  """Client Order ID."""
  cumQuote: NotRequired[str]
  """Cum Quote."""
  executedQty: NotRequired[str]
  """Executed Qty."""
  orderId: NotRequired[int]
  """Normal orderID after trigger if appliable, only have when the strategy is triggered."""
  origQty: NotRequired[str]
  """Orig Qty."""
  origType: NotRequired[str]
  """Orig Type."""
  price: NotRequired[str]
  """Price."""
  reduceOnly: NotRequired[bool]
  """Reduce Only."""
  side: NotRequired[Literal['BUY', 'SELL']]
  """Side."""
  positionSide: NotRequired[Literal['BOTH', 'LONG', 'SHORT']]
  """BOTH means that it is the position of One-way Mode."""
  status: NotRequired[str]
  """Enum：completed，processing."""
  symbol: NotRequired[str]
  """Trade symbol, if existing."""
  time: NotRequired[Timestamp]
  """order time."""
  timeInForce: NotRequired[str]
  """Time In Force."""
  type: NotRequired[str]
  """Normal order type after trigger if appliable."""
  updateTime: NotRequired[Timestamp]
  """update time."""
  selfTradePreventionMode: NotRequired[str]
  """self trading preventation mode."""
  goodTillDate: NotRequired[int]
  """order pre-set auot cancel time for TIF GTD order."""
  priceMatch: NotRequired[
    Literal[
      'OPPONENT',
      'OPPONENT_5',
      'OPPONENT_10',
      'OPPONENT_20',
      'QUEUE',
      'QUEUE_5',
      'QUEUE_10',
      'QUEUE_20',
    ]
  ]
  """Price Match."""


class UmOrder(RpcEndpoint):
  """Query UM Order"""

  async def um_order(
    self,
    *,
    symbol: str,
    order_id: int | None = None,
    orig_client_order_id: str | None = None,
    validate: bool | None = None,
  ) -> PmUmOrder:
    """Check an UM order's status.

    Args:
      symbol: Symbol.
      order_id: Order id to act on.
      orig_client_order_id: Caller-supplied id of the order to act on, as given on placement.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/trade#query-um-order)
    """
    params: dict = {
      'symbol': symbol,
    }
    if order_id is not None:
      params['orderId'] = order_id
    if orig_client_order_id is not None:
      params['origClientOrderId'] = orig_client_order_id
    _Response = PmUmOrder
    _validator = validator[_Response](_Response)
    return await self.authed_request(
      'GET', '/papi/v1/um/order', params=params, validator=_validator, validate=validate
    )
