# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import NotRequired, TypedDict
from typed_binance.core.endpoint.rpc import RpcEndpoint


class EthStakingQuota(TypedDict):
  """This account's current ETH staking quota and product state."""

  leftStakingPersonalQuota: Decimal
  """Remaining amount this account may stake, as a decimal string (the lesser of the daily available limit and this account's total personal staking quota)."""
  leftRedemptionPersonalQuota: Decimal
  """Remaining amount this account may redeem, as a decimal string (the lesser of the daily personal redeem quota and the total redemption limit)."""
  minStakeAmount: Decimal
  """Minimum amount of ETH that can be staked in one call, as a decimal string."""
  minRedeemAmount: Decimal
  """Minimum amount of WBETH/BETH that can be redeemed in one call, as a decimal string."""
  redeemPeriod: int
  """Redemption processing period, in days."""
  stakeable: bool
  """Whether ETH staking is currently open to this account."""
  redeemable: bool
  """Whether ETH redemption is currently open to this account."""
  commissionFee: Decimal
  """Commission fee rate charged on staking rewards, as a decimal string."""
  calculating: NotRequired[bool]
  """Whether the quota figures above are still being recalculated and may not yet be final."""


class Quota(RpcEndpoint):
  """Get this account's current ETH staking subscription and redemption quota."""

  async def quota(self, *, validate: bool | None = None) -> EthStakingQuota:
    """Get this account's current ETH staking subscription and redemption quota.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#get-current-eth-staking-quota)
    """
    return await self.request(
      None,
      method='GET',
      path='/sapi/v1/eth-staking/eth/quota',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      response_type=EthStakingQuota,
    )
