# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_hyperliquid.core import TimestampMillis
from typed_hyperliquid.exchange.core import ExchangeCore


class PerpDeployDefaultResponse(TypedDict):
  """Acknowledgement returned for a perpDeploy action that carries no per-item batch data."""

  type: Literal['default']
  """Fixed response-kind discriminator for this action."""


class Request(TypedDict):
  dex: str
  """Name of the perp dex to disable."""
  expiresAfter: NotRequired[TimestampMillis]
  """Optional expiration timestamp for the signed action."""


class DisableDex(ExchangeCore):
  """Deactivate an entire HIP-3 perp dex through Hyperliquid POST /exchange using perpDeploy sub-action `disableDex`."""

  async def disable_dex(
    self,
    dex: str,
    *,
    expires_after: TimestampMillis | None = None,
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> PerpDeployDefaultResponse:
    """Deactivate an entire HIP-3 perp dex through Hyperliquid POST /exchange using perpDeploy sub-action `disableDex`.

    Args:
      dex: Name of the perp dex to disable.
      expires_after: Optional expiration timestamp for the signed action.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/hip-3-deployer-actions)
    """
    request: Request = Request(dex=dex)
    if expires_after is not None:
      request['expiresAfter'] = expires_after
    return await self.request(
      request,
      method='POST',
      path='perpDeploy.disableDex',
      meta={'scheme': 'l1'},
      validate=validate,
      transport=transport,
      request_type=Request,
      response_type=PerpDeployDefaultResponse,
    )
