# Generated by typed-dev — see CONTRIBUTING.md.
"""`POST /v5/crypto-loan-fixed/borrow-order-cancel` — Cancel Borrow Order."""

from typing_extensions import Any, TypedDict
from typed_bybit.core import Endpoint, validator


class FixedCancelBorrowRequest(TypedDict):
  """Cancel-borrow-order parameters."""

  orderId: str
  """Loan order ID to cancel."""


adapter = validator[dict[str, Any]](dict[str, Any])


class CancelBorrow(Endpoint):
  """`Cancel Borrow Order` — mixed into the router that owns `crypto_loan.fixed.cancel_borrow`."""

  async def cancel_borrow(
    self,
    fixed_cancel_borrow_request: FixedCancelBorrowRequest,
    *,
    validate: bool | None = None,
  ) -> dict[str, Any]:
    """Cancel an existing, not-yet-fully-filled fixed-term borrow order.

    Args:
      fixed_cancel_borrow_request: Order to cancel.
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/cancel-borrow)
    """
    r = await self.authed_request(
      'POST',
      '/v5/crypto-loan-fixed/borrow-order-cancel',
      json=fixed_cancel_borrow_request,
    )
    return self.result(r, adapter, validate)
