# Generated by typed-dev — see CONTRIBUTING.md.
"""`POST /v5/crypto-loan-fixed/repay-collateral` — Collateral Repayment."""

from typing_extensions import Any, NotRequired, TypedDict
from typed_bybit.core import Endpoint, validator


class FixedRepayCollateralRequest(TypedDict):
  """Fixed-term collateral-repayment parameters."""

  loanId: NotRequired[str]
  """Loan contract ID. When omitted, repayment is applied by currency offset across contracts automatically."""
  loanCurrency: str
  """Borrowed coin being repaid."""
  collateralCoin: str
  """Collateral coin(s) to convert, comma-separated for more than one."""
  amount: str
  """Repayment quantity, in the loan currency."""


adapter = validator[dict[str, Any]](dict[str, Any])


class RepayCollateral(Endpoint):
  """`Collateral Repayment` — mixed into the router that owns `crypto_loan.fixed.repay_collateral`."""

  async def repay_collateral(
    self,
    fixed_repay_collateral_request: FixedRepayCollateralRequest,
    *,
    validate: bool | None = None,
  ) -> dict[str, Any]:
    """Repay a fixed-term loan by converting posted collateral assets into the loan currency, instead of repaying with the loan currency directly.

    Args:
      fixed_repay_collateral_request: Collateral repayment to apply.
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/new-crypto-loan/fixed/repay-collateral)
    """
    r = await self.authed_request(
      'POST',
      '/v5/crypto-loan-fixed/repay-collateral',
      json=fixed_repay_collateral_request,
    )
    return self.result(r, adapter, validate)
