# Generated by typed-dev — see CONTRIBUTING.md.
"""`GET /v5/spot-margin-trade/fixedborrow-order-quote` — Get Fixed-Rate Borrow Order Quote."""

from typing_extensions import Literal, TypedDict
from typed_bybit.core import Endpoint, validator


class FixedBorrowQuote(TypedDict):
  """One available quote."""

  orderCurrency: str
  """Coin name."""
  term: Literal[7, 14, 30, 60, 90, 180]
  """Fixed term, in days."""
  annualRate: str
  """Annual interest rate for this quote."""
  qty: str
  """Quantity available at this rate."""


class FixedBorrowOrderQuoteResult(TypedDict):
  """Available fixed-rate borrow quotes."""

  list: list[FixedBorrowQuote]
  """One available quote."""


adapter = validator[FixedBorrowOrderQuoteResult](FixedBorrowOrderQuoteResult)


class OrderQuote(Endpoint):
  """`Get Fixed-Rate Borrow Order Quote` — mixed into the router that owns `spot_margin.fixedborrow.order_quote`."""

  async def order_quote(
    self,
    *,
    order_currency: str,
    term: Literal['7', '14', '30', '90', '180'] | None = None,
    order_by: Literal['apy', 'term', 'quantity'] | None = None,
    sort: Literal[0, 1] | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> FixedBorrowOrderQuoteResult:
    """Query available fixed-rate borrow quotes for a coin, to see lending terms and rates before initiating a borrow.

    Args:
      order_currency: Coin name.
      term: Fixed term, in days.
      order_by: Field to sort by.
      sort: Sort direction.
      limit: Results per page.
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/spot-margin-uta/fixedborrow-order-quote)
    """
    params: dict = {
      'orderCurrency': order_currency,
    }
    if term is not None:
      params['term'] = term
    if order_by is not None:
      params['orderBy'] = order_by
    if sort is not None:
      params['sort'] = sort
    if limit is not None:
      params['limit'] = limit
    r = await self.authed_request(
      'GET', '/v5/spot-margin-trade/fixedborrow-order-quote', params=params
    )
    return self.result(r, adapter, validate)
