# Generated by typed-dev — see CONTRIBUTING.md.
from typed_moralis.schemas import StreamProjectSettings
from typed_moralis.core import RpcEndpoint
from pydantic import TypeAdapter

set_project_settings_adapter = TypeAdapter(StreamProjectSettings)


class SetProjectSettings(RpcEndpoint):
  async def set_project_settings(
    self,
    stream_project_settings: StreamProjectSettings,
    *,
    validate: bool | None = None,
  ) -> StreamProjectSettings:
    """Set the settings for the current project based on the project api-key.

    Args:
      stream_project_settings: Request payload for set project settings.
      validate: Per-call response validation override.

    References:
      - [Moralis API docs](https://docs.moralis.com/streams/api-reference/project/set-project-settings)
    """
    response = await self.request('POST', '/settings', json=stream_project_settings)
    if self.should_validate(validate):
      return set_project_settings_adapter.validate_json(response.text)
    return response.json()
