# Generated by typed-dev — see CONTRIBUTING.md.
from .create import Create
from .get import Get
from .increase_guarantee import IncreaseGuarantee
from .list import List
from .payback import Payback


class Orders(Create, Get, IncreaseGuarantee, List, Payback):
  """Creating, listing, and retrieving crypto-backed loan orders.

  References:
    - [Upstream docs](https://api.bit2me.com/doc#tag/loan)
  """
