# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core import PaginatedResponse
from typing_extensions import Literal, NotRequired, TypedDict
from typed_binance.core import TimestampMillis
from typed_binance.core.endpoint.rpc import RpcEndpoint


class FlexibleRedemptionRecord(TypedDict):
  """One flexible product redemption."""

  amount: str
  """Redeemed amount, as a decimal string."""
  asset: str
  """Underlying asset redeemed."""
  time: TimestampMillis
  """Millisecond epoch time the redemption was recorded."""
  projectId: str
  """Flexible product identifier the redemption was made from."""
  redeemId: int
  """Identifier of the redemption."""
  destAccount: Literal['SPOT', 'FUND']
  """Wallet the redeemed amount was credited to."""
  status: str
  """Redemption status."""


class Request(TypedDict):
  """Request parameters."""

  productId: NotRequired[str]
  """Restrict results to this flexible product."""
  redeemId: NotRequired[str]
  """Restrict results to this redemption."""
  asset: NotRequired[str]
  """Restrict results to this underlying asset."""
  startTime: NotRequired[TimestampMillis]
  """Millisecond epoch start of the queried window."""
  endTime: NotRequired[TimestampMillis]
  """Millisecond epoch end of the queried window."""
  current: NotRequired[int]
  """Currently querying page. Starts from 1."""
  size: NotRequired[int]
  """Number of results per page."""


class FlexibleRedemptionRecordPage(TypedDict):
  """One page of this account's flexible product redemption history."""

  rows: list[FlexibleRedemptionRecord]
  """Matching records on this page."""
  total: int
  """Total number of matching records."""


class RedemptionRecord(RpcEndpoint):
  """Get this account's Simple Earn flexible product redemption history."""

  def redemption_record_paged(
    self,
    *,
    product_id: str | None = None,
    redeem_id: str | None = None,
    asset: str | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    size: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[FlexibleRedemptionRecord, int]:
    """Get this account's Simple Earn flexible product redemption history.

    Paged variant of `redemption_record`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      product_id: Restrict results to this flexible product.
      redeem_id: Restrict results to this redemption.
      asset: Restrict results to this underlying asset.
      start_time: Millisecond epoch start of the queried window.
      end_time: Millisecond epoch end of the queried window.
      size: Number of results per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-flexible-redemption-record)
    """

    async def next(current: int) -> tuple[list[FlexibleRedemptionRecord], int | None]:
      response = await self.redemption_record(
        product_id=product_id,
        redeem_id=redeem_id,
        asset=asset,
        start_time=start_time,
        end_time=end_time,
        size=size,
        current=current,
        validate=validate,
      )
      rows = response.get('rows')
      rows = rows if rows is not None else []
      total = response.get('total')
      total = int(total) if total is not None else None
      if total is None or size is None or (current - 1 + 1) * size >= total:
        return rows, None
      return rows, current + 1

    return PaginatedResponse(1, next)

  async def redemption_record(
    self,
    *,
    product_id: str | None = None,
    redeem_id: str | None = None,
    asset: str | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    current: int | None = None,
    size: int | None = None,
    validate: bool | None = None,
  ) -> FlexibleRedemptionRecordPage:
    """Get this account's Simple Earn flexible product redemption history.

    Args:
      product_id: Restrict results to this flexible product.
      redeem_id: Restrict results to this redemption.
      asset: Restrict results to this underlying asset.
      start_time: Millisecond epoch start of the queried window.
      end_time: Millisecond epoch end of the queried window.
      current: Currently querying page. Starts from 1.
      size: Number of results per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-flexible-redemption-record)
    """
    request: Request = Request()
    if product_id is not None:
      request['productId'] = product_id
    if redeem_id is not None:
      request['redeemId'] = redeem_id
    if asset is not None:
      request['asset'] = asset
    if start_time is not None:
      request['startTime'] = start_time
    if end_time is not None:
      request['endTime'] = end_time
    if current is not None:
      request['current'] = current
    if size is not None:
      request['size'] = size
    return await self.request(
      request,
      method='GET',
      path='/sapi/v1/simple-earn/flexible/history/redemptionRecord',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=FlexibleRedemptionRecordPage,
    )
