# Generated by typed-dev — see CONTRIBUTING.md.
from .dcp import Dcp
from .execution import Execution
from .fast_execution import FastExecution
from .greek import Greek
from .order import Order
from .position import Position
from .spread_execution import SpreadExecution
from .spread_order import SpreadOrder
from .strategy import Strategy
from .wallet import Wallet


class Private(
  Dcp,
  Execution,
  FastExecution,
  Greek,
  Order,
  Position,
  SpreadExecution,
  SpreadOrder,
  Strategy,
  Wallet,
):
  """Private (authenticated) WebSocket topics — real-time pushes for the caller's own account: order and position lifecycle, fills (both the standard execution feed and the low-latency fast-execution variant), wallet balance, spread-combination orders and fills, options Greeks, algo-strategy updates, and per-category Disconnect-Cancel-Protect arming.

  References:
    - [Upstream docs](https://bybit-exchange.github.io/docs/v5/websocket/private/position)
  """
