# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import TypedDict
from typed_coinbase.core.endpoint.rpc import RpcEndpoint
from typed_coinbase.schemas import ExchangeCoinbaseAccountTransfer


class Request(TypedDict):
  """A transfer between this profile and a linked www.coinbase.com wallet (deposit or withdrawal)."""

  coinbase_account_id: str
  """Id of the `coinbase_accounts` wallet to deposit from."""
  amount: Decimal
  """Amount to deposit, denominated in `currency`."""
  currency: str
  """Currency to deposit."""


class CoinbaseAccount(RpcEndpoint):
  """Withdraws funds from the specified `profile_id` to a www.coinbase.com wallet."""

  async def coinbase_account(
    self,
    *,
    coinbase_account_id: str,
    amount: Decimal,
    currency: str,
    validate: bool | None = None,
  ) -> ExchangeCoinbaseAccountTransfer:
    """Withdraws funds from the specified `profile_id` to a www.coinbase.com wallet.

    Args:
      coinbase_account_id: Id of the `coinbase_accounts` wallet to deposit from.
      amount: Amount to deposit, denominated in `currency`.
      currency: Currency to deposit.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.cdp.coinbase.com/exchange/rest-api/api-reference)
    """
    return await self.request(
      Request(
        coinbase_account_id=coinbase_account_id, amount=amount, currency=currency
      ),
      method='POST',
      path='/withdrawals/coinbase-account',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=ExchangeCoinbaseAccountTransfer,
    )
