# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typed_core import PaginatedResponse
from typing_extensions import Literal, NotRequired, Sequence, TypedDict
from typed_binance.core import TimestampMillis
from typed_binance.core.endpoint.rpc import RpcEndpoint


class OnChainYieldsLockedPosition(TypedDict):
  """One On-chain Yields locked product position held by this account."""

  positionId: str
  """Identifier of this locked position."""
  projectId: str
  """Locked product identifier this position belongs to."""
  asset: str
  """Underlying asset held."""
  amount: Decimal
  """Amount held in this position, as a decimal string."""
  purchaseTime: TimestampMillis
  """Millisecond epoch time the position was opened, as a numeric string."""
  duration: int
  """Lock duration in days, as a numeric string."""
  accrualDays: int
  """Number of days rewards have accrued so far, as a numeric string."""
  rewardAsset: str
  """Asset the base rewards are paid in."""
  APY: Decimal
  """Annual percentage yield, as a decimal string."""
  rewardAmt: Decimal
  """Base rewards accrued so far, as a decimal string."""
  nextPay: Decimal
  """Amount of the next reward payment, as a decimal string."""
  nextPayDate: TimestampMillis
  """Millisecond epoch time of the next reward payment, as a numeric string."""
  payPeriod: int
  """Reward payment interval in days, as a numeric string."""
  rewardsPayDate: TimestampMillis
  """Millisecond epoch time of the next scheduled rewards payment, as a numeric string."""
  rewardsEndDate: TimestampMillis
  """Millisecond epoch time reward accrual ends, as a numeric string."""
  deliverDate: TimestampMillis
  """Millisecond epoch time principal (and final rewards) are delivered, as a numeric string."""
  nextSubscriptionDate: TimestampMillis
  """Millisecond epoch time the position would next be eligible to auto-renew into, as a numeric string."""
  redeemingAmt: Decimal
  """Amount currently in the process of being redeemed, as a decimal string."""
  redeemTo: Literal['SPOT', 'FLEXIBLE']
  """Wallet this position redeems to."""
  canRedeemEarly: bool
  """Whether this position can be redeemed before maturity."""
  autoSubscribe: bool
  """Whether this position auto-renews at maturity."""
  type: str
  """Position type."""
  status: str
  """Position status."""


class Request(TypedDict):
  """Request parameters."""

  asset: NotRequired[str]
  """Restrict results to positions in this underlying asset."""
  positionId: NotRequired[str]
  """Restrict results to this locked position."""
  projectId: NotRequired[str]
  """Restrict results to this locked product."""
  current: NotRequired[int]
  """Page index, starting from 1."""
  size: NotRequired[int]
  """Number of results per page."""


class OnChainYieldsLockedPositionPage(TypedDict):
  """One page of this account's On-chain Yields locked product positions."""

  rows: list[OnChainYieldsLockedPosition]
  """Matching records on this page."""
  total: int
  """Total number of matching records."""


class Position(RpcEndpoint):
  """Get this account's On-chain Yields locked product positions."""

  def position_paged(
    self,
    *,
    asset: str | None = None,
    position_id: str | None = None,
    project_id: str | None = None,
    size: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[OnChainYieldsLockedPosition, int]:
    """Get this account's On-chain Yields locked product positions.

    Paged variant of `position`: Requests `current` from 1 upwards and stops once it has covered the `total` items the response reports, or on an empty page. Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      asset: Restrict results to positions in this underlying asset.
      position_id: Restrict results to this locked position.
      project_id: Restrict results to this locked product.
      size: Number of results per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-product-position)
    """

    async def next(
      current: int,
    ) -> tuple[Sequence[OnChainYieldsLockedPosition], int | None]:
      response = await self.position(
        asset=asset,
        position_id=position_id,
        project_id=project_id,
        size=size,
        current=current,
        validate=validate,
      )
      rows = response.get('rows')
      rows = rows if rows is not None else []
      total = response.get('total')
      total = int(total) if total is not None else None
      if not rows or (
        total is not None and size is not None and (current - 1 + 1) * size >= total
      ):
        return rows, None
      return rows, current + 1

    return PaginatedResponse(1, next)

  async def position(
    self,
    *,
    asset: str | None = None,
    position_id: str | None = None,
    project_id: str | None = None,
    current: int | None = None,
    size: int | None = None,
    validate: bool | None = None,
  ) -> OnChainYieldsLockedPositionPage:
    """Get this account's On-chain Yields locked product positions.

    Args:
      asset: Restrict results to positions in this underlying asset.
      position_id: Restrict results to this locked position.
      project_id: Restrict results to this locked product.
      current: Page index, starting from 1.
      size: Number of results per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-product-position)
    """
    request: Request = Request()
    if asset is not None:
      request['asset'] = asset
    if position_id is not None:
      request['positionId'] = position_id
    if project_id is not None:
      request['projectId'] = project_id
    if current is not None:
      request['current'] = current
    if size is not None:
      request['size'] = size
    return await self.request(
      request,
      method='GET',
      path='/sapi/v1/onchain-yields/locked/position',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=OnChainYieldsLockedPositionPage,
    )
