# Generated by typed-dev — see CONTRIBUTING.md.
"""`uta.account.reality_fills` -- generated from `spec/endpoints/`."""

from typing_extensions import Literal
from typed_core.validation import TypedDict, validator
from typed_bitget.core import TimestampMillis
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class RealityFill(TypedDict):
  """One public fill."""

  execId: str
  """Fill ID."""
  price: str
  """Fill price."""
  size: str
  """Fill quantity, in the base coin."""
  side: Literal['buy', 'sell']
  """Trade side."""
  ts: TimestampMillis
  """Fill time."""


class RealityFills(RpcEndpoint):
  """`uta.account.reality_fills`."""

  async def reality_fills(
    self,
    *,
    symbol: str,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> list[RealityFill]:
    """List recent public fills for a Reality (tokenized-stock) trading pair.

    Args:
      symbol: Reality trading pair, e.g. `RAAPLUSDT`. Only Reality pairs are supported.
      limit: Results per page. Default and maximum: 100.

    References:
      - [Official docs](https://www.bitget.com/api-doc/uta/reality/market/Reality-Fills)
    """
    params: dict = {
      'symbol': symbol,
    }
    if limit is not None:
      params['limit'] = limit
    return await self.authed_request(
      'GET',
      '/api/v3/account/reality-fills',
      params=params,
      validator=validator(list[RealityFill]),
      validate=validate,
    )
