# Generated by typed-dev — see CONTRIBUTING.md.
"""Bybit v5 `token_splash` endpoints."""

from .project_list import ProjectList
from .user_activity_params import UserActivityParams


class TokenSplash(
  ProjectList,
  UserActivityParams,
):
  """Bybit v5 `token_splash` endpoints."""
