"""`streams.trading.add_order` -- WebSocket trading method."""

from typing_extensions import Literal, NotRequired
from typed_core.validation import TypedDict, validator
from ...core.endpoint.ws_rpc import WsRpcEndpoint


class AddOrderResult(TypedDict):
  """Result of a successful `add_order` call."""

  order_id: NotRequired[str]
  """Unique order identifier generated by Kraken. Absent when `validate=true`, since no order actually reaches the matching engine."""
  cl_ord_id: NotRequired[str]
  """The client identifier specified in the request `params`, if any."""
  order_userref: NotRequired[int]
  """The client identifier specified in the request `params`, if any."""
  warnings: NotRequired[list[str]]
  """Non-fatal warnings about the order, if any."""


class ConditionalCloseOrder(TypedDict):
  """Template for the secondary close order generated on each fill of the primary order (One-Triggers-Other). The secondary order matches the executed quantity and takes the opposite side."""

  order_type: NotRequired[
    Literal[
      'limit',
      'stop-loss',
      'stop-loss-limit',
      'take-profit',
      'take-profit-limit',
      'trailing-stop',
      'trailing-stop-limit',
    ]
  ]
  """Order type of the secondary close order created on each fill."""
  limit_price: NotRequired[float]
  """Limit price on the secondary close order. Required for secondary order types that support a limit price: `limit`, `stop-loss-limit`, `take-profit-limit`."""
  limit_price_type: NotRequired[Literal['static', 'pct', 'quote']]
  """Units for `limit_price` on the secondary order. Only available on trailing-stop-limit orders; for that order type the value is an offset from the trigger price (`0` sets the limit price equal to the trigger price)."""
  trigger_price: NotRequired[float]
  """Amount for the trigger price on the secondary close order -- static or relative, per `trigger_price_type`. Required on triggered secondary order types: `stop-loss`, `stop-loss-limit`, `take-profit`, `take-profit-limit`."""
  trigger_price_type: NotRequired[Literal['static', 'pct', 'quote']]
  """Units for `trigger_price` on the secondary order."""
  stop_price: NotRequired[float]
  """Deprecated -- use `trigger_price`. Trigger price on the secondary close order, for triggered secondary order types."""


class OrderTriggers(TypedDict):
  """Trigger price conditions for triggered order types."""

  reference: NotRequired[Literal['index', 'last']]
  """Reference price to track for triggering orders: `index` (the broader-market index price for this pair -- falls back to `last` during index-feed connectivity issues) or `last` (the last traded price in the Kraken order book for this pair)."""
  price: float
  """Amount for the trigger price -- static or relative, per `price_type`. E.g. 29000.5 with `price_type=static` triggers at that price; 5 with `pct` triggers when price rises 5%; -150 with `quote` triggers when price drops 150 quote-currency units. For `trailing-stop`/`trailing-stop-limit`, represents the reversion from the peak price and is always positive."""
  price_type: NotRequired[Literal['static', 'pct', 'quote']]
  """Units for `price`: `static` (a static market price), `pct` (a percentage offset from the reference price), or `quote` (a notional offset in the quote currency)."""


validate_add_order = validator(AddOrderResult)


class AddOrder(WsRpcEndpoint):
  """`streams.trading.add_order`."""

  async def add_order(
    self,
    *,
    order_type: Literal[
      'limit',
      'market',
      'iceberg',
      'stop-loss',
      'stop-loss-limit',
      'take-profit',
      'take-profit-limit',
      'trailing-stop',
      'trailing-stop-limit',
      'settle-position',
    ],
    side: Literal['buy', 'sell'],
    order_qty: float,
    symbol: str,
    limit_price: float | None = None,
    limit_price_type: Literal['static', 'pct', 'quote'] | None = None,
    triggers: OrderTriggers | None = None,
    time_in_force: Literal['gtc', 'gtd', 'ioc', 'fok'] | None = None,
    margin: bool | None = None,
    post_only: bool | None = None,
    reduce_only: bool | None = None,
    effective_time: str | None = None,
    expire_time: str | None = None,
    deadline: str | None = None,
    cl_ord_id: str | None = None,
    order_userref: int | None = None,
    conditional: ConditionalCloseOrder | None = None,
    display_qty: float | None = None,
    fee_preference: Literal['base', 'quote'] | None = None,
    no_mpp: bool | None = None,
    stp_type: Literal['cancel_newest', 'cancel_oldest', 'cancel_both'] | None = None,
    cash_order_qty: float | None = None,
    validate: bool | None = None,
    sender_sub_id: str | None = None,
    stop_price: float | None = None,
    trigger: Literal['index', 'last'] | None = None,
  ) -> AddOrderResult:
    """Sends a single, new order into the exchange. A range of order types, Time-In-Force (TIF) settings and order flags can be specified. For triggered order types (`stop-loss`, `take-profit`, `trailing-stop`), `triggers` carries the price-tracking and trigger-threshold parameters. For One-Triggers-Other (OTO) orders, `conditional` carries the parameters for a secondary close order attached to the primary order.

    Args:
      order_type: The execution model of the order: `limit` (rests at a limit price or better), `market` (executes immediately at the best available price), `iceberg` (shows only `display_qty` in the book), `stop-loss`/`take-profit` (market order triggered from an unfavourable/favourable direction), `stop-loss-limit`/`take-profit-limit` (limit-order variants), `trailing-stop`/`trailing-stop-limit` (triggered on reversion from the peak price), or `settle-position` (settles an open leveraged position at the current market price).
      side: Side of the order.
      order_qty: Order quantity in terms of the base asset.
      symbol: The symbol of the currency pair, e.g. `BTC/USD`.
      limit_price: Limit price, for order types that support a limit price restriction.
      limit_price_type: Units for `limit_price`: `static` (a static market price), `pct` (a percentage offset from the reference price), or `quote` (a notional offset in the quote currency). Only available on `trailing-stop-limit` orders, where it is an offset from the trigger price (`0` sets the limit price equal to the trigger price).
      triggers: Trigger price conditions for triggered order types.
      time_in_force: How long the order remains in effect before expiring: `gtc` (Good Till Canceled), `gtd` (Good Till Date -- until `expire_time`), `ioc` (Immediate Or Cancel -- cancels any unfilled remainder on arrival), or `fok` (Fill Or Kill -- fills the full quantity or cancels entirely; `limit` orders only).
      margin: Funds the order on margin using the maximum leverage for the pair (max leverage of 5).
      post_only: Cancels the order if it would take liquidity on arrival; post-only orders are always posted passively in the book. Only for orders with a limit price.
      reduce_only: Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets.
      effective_time: Scheduled start time, RFC3339, precision to seconds.
      expire_time: Expiration time of the order, RFC3339, precision to seconds. GTD orders can expire up to one month in the future.
      deadline: RFC3339 timestamp, millisecond precision. Valid offsets from the current time range from 500ms to 60s (default 5s). The engine will not match this order after this time -- protection against latency on time-sensitive orders.
      cl_ord_id: Alphanumeric client order identifier uniquely identifying an open order for this client. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters.
      order_userref: Optional non-unique numeric identifier associable with any number of orders by the client (e.g. a timestamp). Not enforced unique by Kraken, so it can also group orders by pair/side/strategy for querying or cancelling. Mutually exclusive with `cl_ord_id`.
      conditional: Template for the secondary close order generated on each fill of the primary order (One-Triggers-Other). The secondary order matches the executed quantity and takes the opposite side.
      display_qty: For `iceberg` orders only: quantity to show in the book while the rest of `order_qty` remains hidden. Minimum value is 1/15 of `order_qty`.
      fee_preference: Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders.
      no_mpp: Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection (which protects market orders from filling at a bad price during slippage) for market orders.
      stp_type: Self Trade Prevention mode, protecting against inadvertently trading against oneself: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`.
      cash_order_qty: Order volume expressed in the quote currency. For buy market orders without margin funding.
      validate: If `true`, the order is validated only -- it never reaches the matching engine and no `order_id` is returned.
      sender_sub_id: Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. Same three accepted formats as `cl_ord_id`.
      stop_price: Deprecated -- use the `triggers` object. Stop price for trigger order types.
      trigger: Deprecated -- use `triggers.reference`. Reference price to trigger the order, for triggered order types only.

    References:
      - [Official docs](https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/add_order)
    """
    params: dict = {
      'order_type': order_type,
      'side': side,
      'order_qty': order_qty,
      'symbol': symbol,
    }
    if limit_price is not None:
      params['limit_price'] = limit_price
    if limit_price_type is not None:
      params['limit_price_type'] = limit_price_type
    if triggers is not None:
      params['triggers'] = triggers
    if time_in_force is not None:
      params['time_in_force'] = time_in_force
    if margin is not None:
      params['margin'] = margin
    if post_only is not None:
      params['post_only'] = post_only
    if reduce_only is not None:
      params['reduce_only'] = reduce_only
    if effective_time is not None:
      params['effective_time'] = effective_time
    if expire_time is not None:
      params['expire_time'] = expire_time
    if deadline is not None:
      params['deadline'] = deadline
    if cl_ord_id is not None:
      params['cl_ord_id'] = cl_ord_id
    if order_userref is not None:
      params['order_userref'] = order_userref
    if conditional is not None:
      params['conditional'] = conditional
    if display_qty is not None:
      params['display_qty'] = display_qty
    if fee_preference is not None:
      params['fee_preference'] = fee_preference
    if no_mpp is not None:
      params['no_mpp'] = no_mpp
    if stp_type is not None:
      params['stp_type'] = stp_type
    if cash_order_qty is not None:
      params['cash_order_qty'] = cash_order_qty
    if validate is not None:
      params['validate'] = validate
    if sender_sub_id is not None:
      params['sender_sub_id'] = sender_sub_id
    if stop_price is not None:
      params['stop_price'] = stop_price
    if trigger is not None:
      params['trigger'] = trigger

    return await self.request('add_order', params, validator=validate_add_order)
