"""`streams.trading.batch_add` -- WebSocket trading method."""

from typing_extensions import Literal, NotRequired
from typed_core.validation import TypedDict, validator
from ...core.endpoint.ws_rpc import WsRpcEndpoint


class BatchOrderResult(TypedDict):
  """Result of one order within a successful `batch_add` call."""

  order_id: NotRequired[str]
  """Unique order identifier generated by Kraken."""
  cl_ord_id: NotRequired[str]
  """The client identifier specified for this order in the request, if any."""
  order_userref: NotRequired[int]
  """The client identifier specified for this order in the request, if any."""
  warnings: NotRequired[list[str]]
  """Non-fatal warnings about the order, if any."""


class ConditionalCloseOrder(TypedDict):
  """Template for the secondary close order generated on each fill of the primary order (One-Triggers-Other). The secondary order matches the executed quantity and takes the opposite side."""

  order_type: NotRequired[
    Literal[
      'limit',
      'stop-loss',
      'stop-loss-limit',
      'take-profit',
      'take-profit-limit',
      'trailing-stop',
      'trailing-stop-limit',
    ]
  ]
  """Order type of the secondary close order created on each fill."""
  limit_price: NotRequired[float]
  """Limit price on the secondary close order. Required for secondary order types that support a limit price: `limit`, `stop-loss-limit`, `take-profit-limit`."""
  limit_price_type: NotRequired[Literal['static', 'pct', 'quote']]
  """Units for `limit_price` on the secondary order. Only available on trailing-stop-limit orders; for that order type the value is an offset from the trigger price (`0` sets the limit price equal to the trigger price)."""
  trigger_price: NotRequired[float]
  """Amount for the trigger price on the secondary close order -- static or relative, per `trigger_price_type`. Required on triggered secondary order types: `stop-loss`, `stop-loss-limit`, `take-profit`, `take-profit-limit`."""
  trigger_price_type: NotRequired[Literal['static', 'pct', 'quote']]
  """Units for `trigger_price` on the secondary order."""
  stop_price: NotRequired[float]
  """Deprecated -- use `trigger_price`. Trigger price on the secondary close order, for triggered secondary order types."""


class OrderTriggers(TypedDict):
  """Trigger price conditions for triggered order types."""

  reference: NotRequired[Literal['index', 'last']]
  """Reference price to track for triggering orders: `index` (the broader-market index price for this pair -- falls back to `last` during index-feed connectivity issues) or `last` (the last traded price in the Kraken order book for this pair)."""
  price: float
  """Amount for the trigger price -- static or relative, per `price_type`. E.g. 29000.5 with `price_type=static` triggers at that price; 5 with `pct` triggers when price rises 5%; -150 with `quote` triggers when price drops 150 quote-currency units. For `trailing-stop`/`trailing-stop-limit`, represents the reversion from the peak price and is always positive."""
  price_type: NotRequired[Literal['static', 'pct', 'quote']]
  """Units for `price`: `static` (a static market price), `pct` (a percentage offset from the reference price), or `quote` (a notional offset in the quote currency)."""


class BatchOrderSpec(TypedDict):
  """One order within a `batch_add` request. All orders in a batch share one pair."""

  cash_order_qty: NotRequired[float]
  """Order volume expressed in the quote currency. Market orders only."""
  conditional: NotRequired[ConditionalCloseOrder]
  display_qty: NotRequired[float]
  """For iceberg orders only: quantity to show in the book while the rest of `order_qty` remains hidden. Minimum value is 1/15 of `order_qty`."""
  effective_time: NotRequired[str]
  """Scheduled start time, RFC3339, precision to seconds."""
  expire_time: NotRequired[str]
  """Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future."""
  fee_preference: NotRequired[Literal['base', 'quote']]
  """Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders."""
  limit_price: NotRequired[float]
  """Limit price, for order types that support a limit price restriction."""
  limit_price_type: NotRequired[Literal['static', 'pct', 'quote']]
  """Units for `limit_price`. Only available on trailing-stop orders."""
  margin: NotRequired[bool]
  """Funds the order on margin using the maximum leverage for the pair (max leverage of 5)."""
  no_mpp: NotRequired[bool]
  """Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders."""
  cl_ord_id: NotRequired[str]
  """Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters."""
  order_userref: NotRequired[int]
  """Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`."""
  order_qty: float
  """Order quantity in terms of the base asset."""
  order_type: Literal[
    'limit',
    'market',
    'iceberg',
    'stop-loss',
    'stop-loss-limit',
    'take-profit',
    'take-profit-limit',
    'trailing-stop',
    'trailing-stop-limit',
    'settle-position',
  ]
  """The execution model of the order."""
  post_only: NotRequired[bool]
  """Cancels the order if it would take liquidity on arrival. For orders with a limit price only."""
  reduce_only: NotRequired[bool]
  """Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets."""
  side: Literal['buy', 'sell']
  """Side of the order."""
  stp_type: NotRequired[Literal['cancel_newest', 'cancel_oldest', 'cancel_both']]
  """Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`."""
  time_in_force: NotRequired[Literal['gtc', 'gtd', 'ioc', 'fok']]
  """How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only)."""
  triggers: NotRequired[OrderTriggers]
  sender_sub_id: NotRequired[str]
  """Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP."""
  stop_price: NotRequired[float]
  """Deprecated -- use the `triggers` object."""
  trigger: NotRequired[Literal['index', 'last']]
  """Deprecated -- use `triggers.reference`. Triggered order types only."""


validate_batch_add = validator(list[BatchOrderResult])


class BatchAdd(WsRpcEndpoint):
  """`streams.trading.batch_add`."""

  async def batch_add(
    self,
    *,
    symbol: str,
    orders: list[BatchOrderSpec],
    deadline: str | None = None,
    validate: bool | None = None,
  ) -> list[BatchOrderResult]:
    """Sends a batch of 2-15 orders in a single request, all sharing one pair. Validation runs against the whole batch before submission to the engine -- if any order fails validation, the whole batch is rejected. Once submitted, an order failing a pre-match check (e.g. insufficient funding) is rejected individually and the rest of the batch is processed.

    Args:
      symbol: The symbol of the currency pair for every order in the batch, e.g. `BTC/USD`.
      orders: The orders in the batch, 2 to 15 of them, all on `symbol`.
      deadline: RFC3339 timestamp, millisecond precision. Valid offsets from the current time range from 500ms to 60s (default 5s). The engine will not match orders in this batch after this time.
      validate: If `true`, every order in the batch is validated only -- none reaches the matching engine.

    References:
      - [Official docs](https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/batch_add)
    """
    params: dict = {
      'symbol': symbol,
      'orders': orders,
    }
    if deadline is not None:
      params['deadline'] = deadline
    if validate is not None:
      params['validate'] = validate

    return await self.request('batch_add', params, validator=validate_batch_add)
