# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class BatchCancelOrderItem(TypedDict):
  """One order to cancel within a batch-cancel request."""

  orderId: NotRequired[str]
  """Client-assigned order identifier, 1-32 characters matching `^[\\.A-Z\\:/a-z0-9_-]{1,32}$`. Either `orderId` or `clientOid` must be supplied on lookups/cancels/modifies; when both are given `orderId` takes precedence."""
  clientOid: NotRequired[str]
  """Client-assigned order identifier, 1-32 characters matching `^[\\.A-Z\\:/a-z0-9_-]{1,32}$`. Either `orderId` or `clientOid` must be supplied on lookups/cancels/modifies; when both are given `orderId` takes precedence."""
  category: Literal['SPOT', 'MARGIN', 'USDT-FUTURES', 'COIN-FUTURES', 'USDC-FUTURES']
  """Product type."""
  symbol: str
  """Trading pair, e.g. `BTCUSDT`."""


class BatchCancelResult(TypedDict):
  """Result of one order within a bulk cancel/close/place operation."""

  orderId: str
  """Venue-assigned order identifier."""
  clientOid: str
  """Client-assigned order identifier echoed back."""
  code: NotRequired[str]
  """Per-item result code; `"00000"` on success, a venue error code otherwise."""
  msg: NotRequired[str]
  """Per-item result message."""


CancelBatchOrdersResult = list[BatchCancelResult]


Request = list[BatchCancelOrderItem]


class CancelBatch(RpcEndpoint):
  """Cancel multiple open orders in a single request. Each item succeeds or fails independently."""

  async def cancel_batch(
    self,
    cancel_batch_orders_request: Request,
    *,
    validate: bool | None = None,
  ) -> CancelBatchOrdersResult:
    """Cancel multiple open orders in a single request. Each item succeeds or fails independently.

    Args:
      cancel_batch_orders_request: Orders to cancel, one entry per order.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/trading-order-management/uta-trade-order#batch-cancel)
    """
    return await self.request(
      cancel_batch_orders_request,
      method='POST',
      path='/api/v3/trade/cancel-batch',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=CancelBatchOrdersResult,
    )
