# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core.util import StreamManager
from typing_extensions import Any, Literal, TypedDict
from typed_mexc.core import TimestampMillis
from typed_mexc.futures.streams.core import FuturesStreamsEndpoint


class Parameters(TypedDict):
  symbol: str
  """Futures contract symbol, for example `BTC_USDT`."""


class Trade(TypedDict):
  """Trade payload."""

  p: float
  """Transaction price."""
  v: float
  """Transaction volume."""
  T: Literal[1, 2]
  """Transaction direction: 1 purchase, 2 sell."""
  O: Literal[1, 2, 3]
  """Open/close marker: 1 open position, 2 close position, 3 position unchanged (volume is the additional position opened when O is 1)."""
  M: Literal[1, 2]
  """Whether this trade was auto-executed: 1 yes, 2 no."""
  t: TimestampMillis
  """Transaction time in milliseconds."""


class DealPushMessage(TypedDict):
  channel: Literal['push.deal']
  """Trade push channel."""
  symbol: str
  """Contract symbol."""
  data: Trade
  ts: TimestampMillis
  """Server timestamp in milliseconds."""


class Deal(FuturesStreamsEndpoint):
  """Subscribes to recent trade updates for a single MEXC futures contract."""

  def deal(
    self,
    symbol: str,
    *,
    validate: bool | None = None,
  ) -> StreamManager[DealPushMessage, Any, Any]:
    """Subscribes to recent trade updates for a single MEXC futures contract.

    Args:
      symbol: Futures contract symbol, for example `BTC_USDT`.
      validate: Override this call's pushed-payload validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.mexc.com/api-docs/futures/websocket-api/deal)
    """
    return self.subscribe(
      'sub.deal',
      Parameters(symbol=symbol),
      validate=validate,
      request_type=Parameters,
      response_type=DealPushMessage,
    )
