# Generated by typed-dev — see CONTRIBUTING.md.
"""`classic.spot.current_plan_orders` -- generated from `spec/endpoints/`."""

from typing_extensions import AsyncIterator, Literal
from typed_core.validation import TypedDict, validator
from typed_bitget.core import TimestampMillis, timestamp_millis
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class SpotCurrentPlanOrder(TypedDict):
  """One pending plan order."""

  orderId: str
  """Exchange plan-order ID."""
  clientOid: str
  """Client order ID."""
  symbol: str
  """Trading pair symbol."""
  size: str
  """Order size, as a decimal string."""
  executePrice: str
  """Limit price of the order once triggered, as a decimal string."""
  triggerPrice: str
  """Price that triggers submission of the order, as a decimal string."""
  status: str
  """Current plan-order status."""
  orderType: Literal['limit', 'market']
  """Order type."""
  side: Literal['buy', 'sell']
  """Order side."""
  planType: Literal['amount', 'total']
  """Whether `size` is the base-coin amount to trade (`amount`) or the total quote-coin value (`total`)."""
  triggerType: Literal['fill_price', 'mark_price']
  """Price type the trigger condition is evaluated against."""
  enterPointSource: str
  """Origin of the order (e.g. API, web, app)."""
  uTime: TimestampMillis
  """Last update time, Unix millisecond timestamp, as a string."""
  cTime: TimestampMillis
  """Creation time, Unix millisecond timestamp, as a string."""


class SpotCurrentPlanOrderList(TypedDict):
  """A page of pending plan orders."""

  nextFlag: bool
  """Whether a further page is available."""
  idLessThan: str
  """Cursor for the next page: pass as `idLessThan` to continue."""
  orderList: list[SpotCurrentPlanOrder]
  """Pending plan orders."""


class CurrentPlanOrders(RpcEndpoint):
  """`classic.spot.current_plan_orders`."""

  async def current_plan_orders(
    self,
    *,
    symbol: str,
    limit: int | None = None,
    id_less_than: str | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    validate: bool | None = None,
  ) -> SpotCurrentPlanOrderList:
    """List currently pending (not-yet-triggered) spot plan orders for a symbol.

    Args:
      symbol: Trading pair symbol, e.g. `BTCUSDT`.
      limit: Number of plan orders to return.
      id_less_than: Pagination cursor: return entries with an id less than this value (a `orderId`/`billId`/`tradeId` read out of the last row of the previous page).
      start_time: Range start, Unix millisecond timestamp.
      end_time: Range end, Unix millisecond timestamp.

    References:
      - [Official docs](https://www.bitget.com/api-doc/classic/spot/plan/Get-Current-Plan-Order)
    """
    params: dict = {
      'symbol': symbol,
    }
    if limit is not None:
      params['limit'] = limit
    if id_less_than is not None:
      params['idLessThan'] = id_less_than
    if start_time is not None:
      params['startTime'] = timestamp_millis.dump(start_time)
    if end_time is not None:
      params['endTime'] = timestamp_millis.dump(end_time)
    return await self.authed_request(
      'GET',
      '/api/v2/spot/trade/current-plan-order',
      params=params,
      validator=validator(SpotCurrentPlanOrderList),
      validate=validate,
    )

  async def current_plan_orders_paged(
    self,
    *,
    symbol: str,
    limit: int | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    max_pages: int | None = None,
    validate: bool | None = None,
  ) -> AsyncIterator[SpotCurrentPlanOrderList]:
    """Yield successive pages of `current_plan_orders`.

    Passes each page's token back as `idLessThan` and stops on the first empty page, or
    after `max_pages` pages when one is given.
    """
    id_less_than: str | None = None
    pages = 0
    while True:
      response = await self.current_plan_orders(
        symbol=symbol,
        limit=limit,
        start_time=start_time,
        end_time=end_time,
        id_less_than=id_less_than,
        validate=validate,
      )
      yield response
      pages += 1
      if max_pages is not None and pages >= max_pages:
        break
      rows = response.get('orderList') if response is not None else None
      if not rows:
        break
      id_less_than = response.get('idLessThan') if response is not None else None
