# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_binance.core import TimestampMillis
from typed_binance.core.endpoint.rpc import RpcEndpoint


class PmAllCmOrders(TypedDict):
  """PmAllCmOrders."""

  avgPrice: NotRequired[str]
  """Avg Price."""
  clientOrderId: NotRequired[str]
  """Client Order ID."""
  cumBase: NotRequired[str]
  """Cum Base."""
  executedQty: NotRequired[str]
  """Executed Qty."""
  orderId: NotRequired[int]
  """Normal orderID after trigger if appliable, only have when the strategy is triggered."""
  origQty: NotRequired[str]
  """Orig Qty."""
  origType: NotRequired[str]
  """Orig Type."""
  price: NotRequired[str]
  """Price."""
  reduceOnly: NotRequired[bool]
  """Reduce Only."""
  side: NotRequired[Literal['BUY', 'SELL']]
  """Side."""
  positionSide: NotRequired[Literal['BOTH', 'LONG', 'SHORT']]
  """BOTH means that it is the position of One-way Mode."""
  status: NotRequired[
    Literal['NEW', 'PARTIALLY_FILLED', 'FILLED', 'CANCELED', 'EXPIRED']
  ]
  """Order status."""
  symbol: NotRequired[str]
  """Trade symbol, if existing."""
  pair: NotRequired[str]
  """Pair."""
  time: NotRequired[TimestampMillis]
  """order time."""
  timeInForce: NotRequired[Literal['GTC', 'IOC', 'FOK', 'GTX']]
  """Time In Force."""
  type: NotRequired[
    Literal[
      'LIMIT',
      'MARKET',
      'STOP',
      'STOP_MARKET',
      'TAKE_PROFIT',
      'TAKE_PROFIT_MARKET',
      'TRAILING_STOP_MARKET',
    ]
  ]
  """Normal order type after trigger if appliable."""
  updateTime: NotRequired[TimestampMillis]
  """update time."""


class Request(TypedDict):
  """Request parameters."""

  symbol: NotRequired[str]
  """Trading pair symbol."""
  pair: NotRequired[str]
  """Trading pair."""


Response = list[PmAllCmOrders]


class CmOpenOrders(RpcEndpoint):
  """Get all open orders on a symbol. * If the symbol is not sent, orders for all symbols will be returned in an array. Weight: - 1 for a single `symbol` - 40 when `symbol` is omitted Security Type: USER_DATA Args: symbol (Optional[str] = None): pair (Optional[str] = None): recv_window (Optional[int] = None): Returns: ApiResponse[QueryAllCurrentCmOpenOrdersResponse] Raises: RequiredError: If a required parameter is missing."""

  async def cm_open_orders(
    self,
    *,
    symbol: str | None = None,
    pair: str | None = None,
    validate: bool | None = None,
  ) -> Response:
    """Get all open orders on a symbol. * If the symbol is not sent, orders for all symbols will be returned in an array. Weight: - 1 for a single `symbol` - 40 when `symbol` is omitted Security Type: USER_DATA Args: symbol (Optional[str] = None): pair (Optional[str] = None): recv_window (Optional[int] = None): Returns: ApiResponse[QueryAllCurrentCmOpenOrdersResponse] Raises: RequiredError: If a required parameter is missing.

    Args:
      symbol: Trading pair symbol.
      pair: Trading pair.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/trade#query-all-current-cm-open-orders)
    """
    request: Request = Request()
    if symbol is not None:
      request['symbol'] = symbol
    if pair is not None:
      request['pair'] = pair
    return await self.request(
      request,
      method='GET',
      path='/papi/v1/cm/openOrders',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
