# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_binance.core import TimestampMillis
from typed_binance.core.endpoint.rpc import RpcEndpoint


class PmCurrentMarginOpenOrder(TypedDict):
  """PmCurrentMarginOpenOrder."""

  clientOrderId: NotRequired[str]
  """Client Order ID."""
  cummulativeQuoteQty: NotRequired[str]
  """Cummulative Quote Qty."""
  executedQty: NotRequired[str]
  """Executed Qty."""
  icebergQty: NotRequired[str]
  """Iceberg Qty."""
  isWorking: NotRequired[bool]
  """Is Working."""
  orderId: NotRequired[int]
  """Normal orderID after trigger if appliable, only have when the strategy is triggered."""
  origQty: NotRequired[str]
  """Orig Qty."""
  price: NotRequired[str]
  """Price."""
  side: NotRequired[Literal['BUY', 'SELL']]
  """Side."""
  status: NotRequired[
    Literal[
      'NEW',
      'PENDING_NEW',
      'PARTIALLY_FILLED',
      'FILLED',
      'CANCELED',
      'PENDING_CANCEL',
      'REJECTED',
      'EXPIRED',
      'EXPIRED_IN_MATCH',
    ]
  ]
  """Order status."""
  stopPrice: NotRequired[str]
  """please ignore when order type is TRAILING_STOP_MARKET."""
  symbol: NotRequired[str]
  """Trade symbol, if existing."""
  time: NotRequired[TimestampMillis]
  """Event time."""
  timeInForce: NotRequired[Literal['GTC', 'IOC', 'FOK']]
  """Time In Force."""
  type: NotRequired[
    Literal[
      'LIMIT',
      'MARKET',
      'STOP_LOSS',
      'STOP_LOSS_LIMIT',
      'TAKE_PROFIT',
      'TAKE_PROFIT_LIMIT',
      'LIMIT_MAKER',
    ]
  ]
  """Normal order type after trigger if appliable."""
  updateTime: NotRequired[TimestampMillis]
  """last update time."""
  accountId: NotRequired[int]
  """Account ID."""
  selfTradePreventionMode: NotRequired[str]
  """self trading preventation mode."""
  preventedMatchId: NotRequired[str]
  """Prevented Match ID."""
  preventedQuantity: NotRequired[str]
  """Prevented Quantity."""


class Request(TypedDict):
  """Request parameters."""

  symbol: str
  """Symbol."""


Response = list[PmCurrentMarginOpenOrder]


class MarginOpenOrders(RpcEndpoint):
  """Query Current Margin Open Order."""

  async def margin_open_orders(
    self,
    symbol: str,
    *,
    validate: bool | None = None,
  ) -> Response:
    """Query Current Margin Open Order.

    Args:
      symbol: Symbol.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/trade#query-current-margin-open-order)
    """
    return await self.request(
      Request(symbol=symbol),
      method='GET',
      path='/papi/v1/margin/openOrders',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
