# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Any, NotRequired, TypedDict
from typed_binance.core.endpoint.rpc import RpcEndpoint


PmAllCurrentUmOpenConditionalOrders = dict[str, Any]


class Request(TypedDict):
  """Request parameters."""

  symbol: NotRequired[str]
  """Trading pair symbol."""


class UmOpenConditionalOrders(RpcEndpoint):
  """Get all open conditional orders on a symbol. Weight: - 1 for a single `symbol` - 40 when `symbol` is omitted Security Type: USER_DATA Notes: - If `symbol` is not provided, conditional open orders for all symbols are returned. Args: symbol (Optional[str] = None): recv_window (Optional[int] = None): Returns: ApiResponse[QueryAllCurrentUmOpenConditionalOrdersResponse] Raises: RequiredError: If a required parameter is missing."""

  async def um_open_conditional_orders(
    self,
    symbol: str | None = None,
    *,
    validate: bool | None = None,
  ) -> PmAllCurrentUmOpenConditionalOrders:
    """Get all open conditional orders on a symbol. Weight: - 1 for a single `symbol` - 40 when `symbol` is omitted Security Type: USER_DATA Notes: - If `symbol` is not provided, conditional open orders for all symbols are returned. Args: symbol (Optional[str] = None): recv_window (Optional[int] = None): Returns: ApiResponse[QueryAllCurrentUmOpenConditionalOrdersResponse] Raises: RequiredError: If a required parameter is missing.

    Args:
      symbol: Trading pair symbol.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/trade#query-all-current-um-open-conditional-orders)
    """
    request: Request = Request()
    if symbol is not None:
      request['symbol'] = symbol
    return await self.request(
      request,
      method='GET',
      path='/papi/v1/um/conditional/openOrders',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=PmAllCurrentUmOpenConditionalOrders,
    )
