# Generated by typed-dev — see CONTRIBUTING.md.
"""`GET /v5/earn/advance/product` — Get Dual Asset Product Info."""

from typing_extensions import Literal, NotRequired, TypedDict
from typed_bybit.core import Endpoint, TimestampMillis, validator


class DualAssetProduct(TypedDict):
  """One Dual Asset product."""

  productId: str
  """Unique product identifier."""
  baseCoin: str
  """Base currency of the pair."""
  quoteCoin: str
  """Quote currency of the pair."""
  duration: str
  """Product duration, e.g. "8h", "1d", "3d", "6d", "12d"."""
  status: Literal['Available', 'NotAvailable']
  """Product availability."""
  isVipProduct: bool
  """Whether this product is VIP-exclusive."""
  subscribeStartAt: NotRequired[TimestampMillis]
  """Subscription window opening time, as a millisecond timestamp."""
  subscribeEndAt: NotRequired[TimestampMillis]
  """Subscription window closing time, as a millisecond timestamp."""
  minPurchaseQuoteAmount: str
  """Minimum investment amount, in the quote currency."""
  minPurchaseBaseAmount: str
  """Minimum investment amount, in the base currency."""
  remainingAmountQuote: NotRequired[str]
  """Remaining quota for a Buy Low (quote-side) order."""
  remainingAmountBase: NotRequired[str]
  """Remaining quota for a Sell High (base-side) order."""
  orderPrecisionDigitalQuote: int
  """Decimal precision for a Buy Low order amount."""
  orderPrecisionDigitalBase: int
  """Decimal precision for a Sell High order amount."""


class DualAssetProductList(TypedDict):
  """Dual Asset structured products."""

  category: Literal['DualAssets']
  """Product category, echoed back."""
  list: list[DualAssetProduct]
  """Product records."""


adapter = validator[DualAssetProductList](DualAssetProductList)


class ProductInfo(Endpoint):
  """`Get Dual Asset Product Info` — mixed into the router that owns `finance.advanced_earn.dual_asset.product_info`."""

  async def product_info(
    self,
    *,
    category: Literal['DualAssets'],
    coin: str | None = None,
    duration: str | None = None,
    validate: bool | None = None,
  ) -> DualAssetProductList:
    """Get available Dual Asset structured products. No authentication required.

    Args:
      category: Product category.
      coin: Coin to filter by, uppercase.
      duration: Product duration to filter by, e.g. "8h", "1d", "3d", "6d", "12d".
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/finance/advanced-earn/dual-asset/product-info)
    """
    params: dict = {
      'category': category,
    }
    if coin is not None:
      params['coin'] = coin
    if duration is not None:
      params['duration'] = duration
    r = await self.request('GET', '/v5/earn/advance/product', params=params)
    return self.result(r, adapter, validate)
