# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired
from typed_core.validation import TypedDict
import pydantic

from typed_hyperliquid.core import timestamp_millis
from typed_hyperliquid.exchange.core import (
  ExchangeMixin,
  ExchangeResponse,
  raise_on_error,
  sign_l1_action,
)


class PerpDeployDefaultResponse(TypedDict):
  """Acknowledgement returned for a perpDeploy action that carries no per-item batch data."""

  type: Literal['default']
  """Fixed response-kind discriminator for this action."""


class PerpDeployPerpDexSchema(TypedDict):
  full_name: str
  """Full name of the perp dex."""
  collateral_token: int
  """Collateral token index."""
  oracle_updater: NotRequired[str]
  """User authorized to update oracle prices for this dex. Defaults to the deployer when omitted."""


class PerpDeployRegisterAssetRequestFields(TypedDict):
  coin: str
  """Ticker of the new asset."""
  sz_decimals: int
  """Number of decimals used for order/position size on this asset."""
  oracle_px: str
  """Initial oracle price for the asset, as a decimal string."""
  margin_table_id: int
  """Margin table id to apply to the asset. Must be non-zero."""
  only_isolated: bool
  """Whether the asset only supports isolated margin."""


class RegisterAssetSubAction(TypedDict):
  assetRequest: PerpDeployRegisterAssetRequestFields
  dex: str
  maxGas: NotRequired[int]
  schema: NotRequired[PerpDeployPerpDexSchema]


class RegisterAssetAction(TypedDict):
  type: Literal['perpDeploy']
  registerAsset: RegisterAssetSubAction


adapter = pydantic.TypeAdapter(ExchangeResponse[PerpDeployDefaultResponse])


class RegisterAsset(ExchangeMixin):
  async def register_asset(
    self,
    *,
    asset_request: PerpDeployRegisterAssetRequestFields,
    dex: str,
    max_gas: int | None = None,
    schema: PerpDeployPerpDexSchema | None = None,
    expires_after: int | None = None,
    validate: bool | None = None,
  ) -> PerpDeployDefaultResponse:
    """Register a new asset on a builder-deployed HIP-3 perp dex, optionally initializing the dex itself in the same call, through Hyperliquid POST /exchange using perpDeploy sub-action `registerAsset`. If `schema` is omitted, the dex must already exist and this call adds another asset to it. Structurally identical to `registerAsset2` except its asset request carries a boolean `only_isolated` instead of a 3-way `margin_mode`.

    Args:
      asset_request: New asset listing parameters.
      dex: Name of the perp dex: 2-4 lowercase characters.
      max_gas: Max gas in native token wei. Omit to use the current deploy auction price; `0` forces a reserve deployment at the current auction price even if the auction has ended (a limited number of reserve deployments are allowed).
      schema: New perp dex parameters. Provide only when initializing a new dex in this call; omit to register another asset on an already-deployed dex.
      expires_after: Optional expiration timestamp for the signed action.
      validate: Validate the response against the generated schema.

    References:
      - [Official docs](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/hip-3-deployer-actions)
    """
    ts = timestamp_millis.now()
    sub_action: RegisterAssetSubAction = {
      'assetRequest': asset_request,
      'dex': dex,
    }
    if max_gas is not None:
      sub_action['maxGas'] = max_gas
    if schema is not None:
      sub_action['schema'] = schema
    action: RegisterAssetAction = {'type': 'perpDeploy', 'registerAsset': sub_action}
    sig = sign_l1_action(
      action,
      wallet=self.wallet,
      nonce=ts,
      mainnet=self.mainnet,
      vault_address=None,
      expires_after=expires_after,
    )
    result = await self.client.request(
      {
        'action': action,
        'nonce': ts,
        'signature': sig,
        'vaultAddress': None,
        'expiresAfter': expires_after,
      }
    )
    should_validate = self.validate if validate is None else validate
    return raise_on_error(
      adapter.validate_python(result) if should_validate else result
    )
