# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_hyperliquid.core import TimestampMillis
from typed_hyperliquid.exchange.core import ExchangeCore


class Request(TypedDict):
  riskFreeRate: str
  """Risk-free rate vote, as a decimal string (e.g. "0.04" for 4%)."""
  expiresAfter: NotRequired[TimestampMillis]
  """Optional expiration timestamp for the signed action."""


class ValidatorL1StreamResult(TypedDict):
  type: Literal['default']
  """Response discriminator. Hyperliquid returns the generic `default` marker for this action rather than its own action type name."""


class ValidatorL1Stream(ExchangeCore):
  """Cast a validator's vote on the risk-free rate used for the aligned quote asset, through Hyperliquid POST /exchange using the L1 `validatorL1Stream` action. Only callable by an active validator."""

  async def validator_l1_stream(
    self,
    risk_free_rate: str,
    *,
    expires_after: TimestampMillis | None = None,
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> ValidatorL1StreamResult:
    """Cast a validator's vote on the risk-free rate used for the aligned quote asset, through Hyperliquid POST /exchange using the L1 `validatorL1Stream` action. Only callable by an active validator.

    Args:
      risk_free_rate: Risk-free rate vote, as a decimal string (e.g. "0.04" for 4%).
      expires_after: Optional expiration timestamp for the signed action.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint)
    """
    request: Request = Request(riskFreeRate=risk_free_rate)
    if expires_after is not None:
      request['expiresAfter'] = expires_after
    return await self.request(
      request,
      method='POST',
      path='validatorL1Stream',
      meta={'scheme': 'l1'},
      validate=validate,
      transport=transport,
      request_type=Request,
      response_type=ValidatorL1StreamResult,
    )
