# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_bybit.core.http import RpcEndpoint


class BatchAmendOrderItem(TypedDict):
  """One order to amend."""

  symbol: str
  """Symbol name, uppercase only."""
  orderId: NotRequired[str]
  """Order ID. Either `orderId` or `orderLinkId` is required."""
  orderLinkId: NotRequired[str]
  """User-customised order ID. Either `orderId` or `orderLinkId` is required."""
  orderIv: NotRequired[str]
  """Implied volatility, option only."""
  triggerPrice: NotRequired[str]
  """Conditional order or spot TP/SL trigger price after modification."""
  qty: NotRequired[str]
  """Order quantity after modification. Omit to leave unchanged."""
  price: NotRequired[str]
  """Order price after modification. Omit to leave unchanged."""
  tpslMode: NotRequired[Literal['Full', 'Partial']]
  """TP/SL mode."""
  takeProfit: NotRequired[str]
  """Take profit price after modification. `"0"` cancels the existing take profit."""
  stopLoss: NotRequired[str]
  """Stop loss price after modification. `"0"` cancels the existing stop loss."""
  tpTriggerBy: NotRequired[Literal['LastPrice', 'IndexPrice', 'MarkPrice']]
  """Trigger price type for take profit."""
  slTriggerBy: NotRequired[Literal['LastPrice', 'IndexPrice', 'MarkPrice']]
  """Trigger price type for stop loss."""
  triggerBy: NotRequired[Literal['LastPrice', 'IndexPrice', 'MarkPrice']]
  """Trigger price type."""
  tpLimitPrice: NotRequired[str]
  """Limit order price when take profit triggers. Only with partial limit TP/SL."""
  slLimitPrice: NotRequired[str]
  """Limit order price when stop loss triggers. Only with partial limit TP/SL."""


class BatchAmendedOrder(TypedDict):
  """One amended order."""

  category: Literal['linear', 'option', 'spot', 'inverse']
  """Product type."""
  symbol: str
  """Symbol name."""
  orderId: str
  """Order ID."""
  orderLinkId: str
  """User-customised order ID."""


class BatchAmendOrderResult(TypedDict):
  """Amended order identifiers, one per requested amendment in the same order."""

  list: list[BatchAmendedOrder]
  """Amended orders."""


class Request(TypedDict):
  """Orders to amend."""

  category: Literal['linear', 'option', 'spot', 'inverse']
  """Product type."""
  request: list[BatchAmendOrderItem]
  """Order amendments, up to 20 (10 for spot)."""


class BatchAmendOrder(RpcEndpoint):
  """Amend more than one unfilled or partially filled order in a single request. Conditional orders are not supported. Limits per request: 20 orders (option, inverse, linear), 10 (spot)."""

  async def batch_amend_order(
    self,
    category: Literal['linear', 'option', 'spot', 'inverse'],
    *,
    request: list[BatchAmendOrderItem],
    validate: bool | None = None,
  ) -> BatchAmendOrderResult:
    """Amend more than one unfilled or partially filled order in a single request. Conditional orders are not supported. Limits per request: 20 orders (option, inverse, linear), 10 (spot).

    Args:
      category: Product type.
      request: Order amendments, up to 20 (10 for spot).
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://bybit-exchange.github.io/docs/v5/order/batch-amend)
    """
    return await self.request(
      Request(category=category, request=request),
      method='POST',
      path='/v5/order/amend-batch',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=BatchAmendOrderResult,
    )
