# Generated by typed-dev — see CONTRIBUTING.md.
"""`/contractMarket/snapshot:{symbol}` — Subscribe to periodic 24-hour statistics (price change, volume, turnover) for one futures contract, pushed roughly every 5 seconds."""

from typing_extensions import Any, NotRequired
from typed_core.util import StreamManager
from typed_core.validation import TypedDict, validator
from typed_kucoin.core import StreamEndpoint, TimestampNanos
from typed_kucoin.types import WsSubscriptionAck


class FuturesSymbolSnapshotUpdate(TypedDict):
  """A 24-hour statistics snapshot -- the unwrapped `data` field of the raw WebSocket frame (`SocketStreamClient.subscribe` extracts `data` before handing the stream to the caller; see `spec/core.md`'s WebSocket section)."""

  symbol: str
  """Contract symbol, for example `XBTUSDTM`."""
  lastPrice: float
  """Most recent traded price."""
  highPrice: float
  """Highest traded price in the trailing 24 hours."""
  lowPrice: float
  """Lowest traded price in the trailing 24 hours."""
  price24HoursBefore: float
  """Traded price 24 hours before this push."""
  priceChg: float
  """Absolute price change over the trailing 24 hours."""
  priceChgPct: float
  """Price change over the trailing 24 hours, as a fraction (for example `0.0009` is 0.09%)."""
  volume: float
  """Trailing 24-hour trading volume, in contracts."""
  turnover: float
  """Trailing 24-hour turnover, in the contract's quote currency."""
  fundingRate: NotRequired[float]
  """Current funding rate for this contract. Not part of the venue's own published schema for this channel, but present on every live capture this pass."""
  ts: TimestampNanos
  """Timestamp of this push, in nanoseconds."""


_Type = FuturesSymbolSnapshotUpdate
validate_update = validator[_Type](_Type)  # type: ignore


class SymbolSnapshot(StreamEndpoint):
  """Subscribe to `/contractMarket/snapshot:{symbol}` — mixed into `Market`, the product exposing `streams.futures.symbol_snapshot`."""

  def symbol_snapshot(
    self,
    symbol: str,
    *,
    validate: bool | None = None,
  ) -> StreamManager[FuturesSymbolSnapshotUpdate, Any, Any]:
    """Subscribe to periodic 24-hour statistics (price change, volume, turnover) for one futures contract, pushed roughly every 5 seconds.

    Args:
      symbol: Contract symbol to watch, for example `XBTUSDTM`.
      validate: Whether to validate pushed payloads against the expected schema.

    Returns:
      A manager for the subscription stream.

    References:
      - [KuCoin API docs](https://www.kucoin.com/docs-new)
    """
    return self.subscribe(
      f'/contractMarket/snapshot:{symbol}',
      validator=validate_update,
      validate=validate,
    )
