# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_moralis.core.rest import DeepIndexEndpoint
from typed_moralis.schemas import EvmChain


class NftTransfers(TypedDict):
  """NFT transfers."""

  total: str
  """Total."""


class TokenTransfers(TypedDict):
  """Token transfers."""

  total: str
  """Total."""


class Transactions(TypedDict):
  """Transactions."""

  total: str
  """Total."""


class Request(TypedDict):
  chain: NotRequired[EvmChain]
  address: str
  """Wallet address"""


class WalletStatsResponse(TypedDict):
  """Schema inferred from a live Moralis response captured by spec collection."""

  nfts: str
  """NFTs."""
  collections: str
  """Collections."""
  transactions: Transactions
  nft_transfers: NftTransfers
  token_transfers: TokenTransfers


class WalletStats(DeepIndexEndpoint):
  """Retrieve key statistics for a wallet, such as total transaction count and activity."""

  async def wallet_stats(
    self,
    chain: EvmChain | None = None,
    *,
    address: str,
    validate: bool | None = None,
  ) -> WalletStatsResponse:
    """Retrieve key statistics for a wallet, such as total transaction count and activity.

    Args:
      chain:
      address: Wallet address
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.moralis.com/data-api/evm/wallet/wallet-stats)
    """
    request: Request = Request(address=address)
    if chain is not None:
      request['chain'] = chain
    return await self.request(
      request,
      method='GET',
      path='/wallets/{address}/stats',
      validate=validate,
      request_type=Request,
      response_type=WalletStatsResponse,
    )
