# Generated by typed-dev — see CONTRIBUTING.md.
"""KuCoin OcoOrders endpoints."""

from .add import Add
from .batch_cancel import BatchCancel
from .cancel_by_client_oid import CancelByClientOid
from .cancel_by_order_id import CancelByOrderId
from .get_by_client_oid import GetByClientOid
from .get_by_order_id import GetByOrderId
from .get_detail import GetDetail
from .get_list import GetList


class OcoOrders(
  Add,
  BatchCancel,
  CancelByClientOid,
  CancelByOrderId,
  GetByClientOid,
  GetByOrderId,
  GetDetail,
  GetList,
):
  """KuCoin OcoOrders endpoints."""
