# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class P2pFeeSimulate(TypedDict):
  """Simulated platform fee and tax for a hypothetical P2P trade."""

  feeToken: str
  """Token the simulated platform fee is denominated in."""
  feeAmount: str
  """Simulated platform fee amount, as a decimal string."""
  taxToken: str
  """Token the simulated tax is denominated in."""
  taxAmount: str
  """Simulated tax amount, as a decimal string."""


class Request(TypedDict):
  """A hypothetical P2P trade to simulate fees for."""

  token: str
  """Crypto token of the hypothetical trade, e.g. `USDT`."""
  fiat: str
  """Fiat currency of the hypothetical trade, e.g. `USD`."""
  side: Literal['buy', 'sell']
  """Side of the hypothetical trade."""
  marketType: Literal['public', 'private']
  """Whether the hypothetical trade is against a public advertisement or a private (direct) counterparty."""
  amount: float
  """Fiat amount of the hypothetical trade."""


class FeeSimulate(RpcEndpoint):
  """Simulate the platform fee and tax that would apply to a hypothetical P2P trade, without placing an order."""

  async def fee_simulate(
    self,
    *,
    token: str,
    fiat: str,
    side: Literal['buy', 'sell'],
    market_type: Literal['public', 'private'],
    amount: float,
    validate: bool | None = None,
  ) -> P2pFeeSimulate:
    """Simulate the platform fee and tax that would apply to a hypothetical P2P trade, without placing an order.

    Args:
      token: Crypto token of the hypothetical trade, e.g. `USDT`.
      fiat: Fiat currency of the hypothetical trade, e.g. `USD`.
      side: Side of the hypothetical trade.
      market_type: Whether the hypothetical trade is against a public advertisement or a private (direct) counterparty.
      amount: Fiat amount of the hypothetical trade.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/p2p-ad-management/p2p-ad-management#fee-simulate)
    """
    return await self.request(
      Request(token=token, fiat=fiat, side=side, marketType=market_type, amount=amount),
      method='POST',
      path='/api/v3/p2p/fee-simulate',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=P2pFeeSimulate,
    )
