# Generated by typed-dev — see CONTRIBUTING.md.
from .cancel import Cancel
from .execute import Execute
from .get_status import GetStatus
from .preview import Preview


class Orders(Cancel, Execute, GetStatus, Preview):
  """Bit2Me Teller fiat order lifecycle: preview, execute, cancel, and check status.

  References:
    - [Upstream docs](https://api.bit2me.com/doc#tag/funding)
  """
