# Generated by typed-dev — see CONTRIBUTING.md.
from .nft_transfers_by_contract import NftTransfersByContract
from .nft_transfers_by_token_id import NftTransfersByTokenId


class Transfers(NftTransfersByContract, NftTransfersByTokenId):
  """Grouped Moralis Transfers endpoints."""
