# Generated by typed-dev — see CONTRIBUTING.md.
from functools import cached_property
from .account import Account
from .auth import Auth
from .block_rfq import BlockRfq
from .block_trade import BlockTrade
from .combo_books import ComboBooks
from .market_data import MarketData
from .matching_engine import MatchingEngine
from .session import Session
from .streams import Streams
from .subscription_management import SubscriptionManagement
from .supporting import Supporting
from .trading import Trading
from .wallet import Wallet
from typed_deribit.core.base import ClientBase


class Deribit(ClientBase):
  """Deribit client root — composes the JSON-RPC request/reply method surface (market data, trading, account, block trading, and connectivity domains, each reachable over HTTP or WebSocket) and the WebSocket channel-subscription surface.

  References:
    - [Upstream docs](https://docs.deribit.com/)
  """

  @cached_property
  def account(self) -> Account:
    """Account, sub-account, and API-key management -- credential lifecycle, sub-account creation and administration, account summaries, positions, and portfolio simulation.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/account-management)
    """
    return Account.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def auth(self) -> Auth:
    """Authentication and access-token lifecycle -- exchanging credentials for a session token, forking and exchanging tokens between subjects, and logging out.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/authentication)
    """
    return Auth.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def block_rfq(self) -> BlockRfq:
    """Block RFQ (multi-leg request-for-quote) workflow between takers and makers -- creating, quoting, accepting, and cancelling Block RFQs and their quotes.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/block-rfq)
    """
    return BlockRfq.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def block_trade(self) -> BlockTrade:
    """Bilateral block trade lifecycle -- broker client and trade-request listings, and the approve/reject step that follows matching-engine execution.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/block-trade)
    """
    return BlockTrade.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def combo_books(self) -> ComboBooks:
    """Multi-leg combo instrument books -- creating combos, listing combo ids, and pricing individual legs.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/combo-books)
    """
    return ComboBooks.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def market_data(self) -> MarketData:
    """Public market data -- instruments, order books, tickers, historical trades, funding, volatility, and settlement/delivery prices.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/market-data)
    """
    return MarketData.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def matching_engine(self) -> MatchingEngine:
    """Two-sided block trade verification and execution against the matching engine -- the signature exchange step of the block trade workflow. The venue documents these methods as part of its wider Block Trade API rather than as their own category, and this grouping's own endpoints (execute/simulate/verify_block_trade) are cross-tagged 'Block Trade' there too.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/block-trade)
    """
    return MatchingEngine.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def session(self) -> Session:
    """Per-connection session controls -- heartbeat and cancel-on-disconnect configuration.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/session-management)
    """
    return Session.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def streams(self) -> Streams:
    """The WebSocket streaming surface as a whole -- real-time market-data, Block RFQ, and user-account channels delivered as JSON-RPC notifications once subscribed.

    References:
      - [Upstream docs](https://docs.deribit.com/articles/notifications)
    """
    return Streams(client=self.ws_client)

  @cached_property
  def subscription_management(self) -> SubscriptionManagement:
    """RPC methods that open and close WebSocket channel subscriptions -- public and authenticated subscribe, unsubscribe, and unsubscribe_all.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/subscription-management)
    """
    return SubscriptionManagement.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def supporting(self) -> Supporting:
    """Connectivity and platform-health utility methods -- server time, the hello handshake, platform status, and the test/echo call.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/supporting)
    """
    return Supporting.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def trading(self) -> Trading:
    """Order placement and management -- buy/sell/edit/cancel, open-order and order-history lookups, margins, mass quoting, and market-maker-protection controls.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/trading)
    """
    return Trading.new(self.rpc_client, ws_client=self.ws_client)

  @cached_property
  def wallet(self) -> Wallet:
    """Deposits, withdrawals, transfers, and address-book management for the account's wallet.

    References:
      - [Upstream docs](https://docs.deribit.com/api-reference/wallet)
    """
    return Wallet.new(self.rpc_client, ws_client=self.ws_client)
