# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, TypedDict
from typed_moralis.core import RpcEndpoint, TimestampIso, TimestampSeconds, clean_params
from pydantic import TypeAdapter
from typed_core import PaginatedResponse


class Meta(TypedDict):
  """Meta."""

  syncedAt: TimestampSeconds
  """Synced at."""


class Result(TypedDict):
  timestamp: TimestampIso
  """Timestamp."""
  price: str
  """Price."""


class HistoricalPriceResponse(TypedDict):
  """Schema inferred from a live Moralis response captured by spec collection."""

  chain: str
  """Chain."""
  fromDate: TimestampIso
  """From date."""
  toDate: TimestampIso
  """To date."""
  interval: str
  """Interval."""
  page: int
  """Page."""
  cursor: str | None
  """Cursor."""
  result: list[Result]
  """Result."""
  meta: Meta


historical_price_adapter = TypeAdapter(HistoricalPriceResponse)


class HistoricalPrice(RpcEndpoint):
  async def historical_price(
    self,
    chain_alias: Literal[
      '0x1',
      'ethereum',
      '0x171',
      'pulse',
      '0x2105',
      'base',
      '0x38',
      'binance',
      '0x89',
      'polygon',
      '0xa',
      'optimism',
      '0xa86a',
      'avalanche',
      'bitcoin-mainnet',
      'bitcoin',
      'solana-mainnet',
      'sol',
    ],
    token_alias_or_token_address: str,
    *,
    limit: float | None = None,
    cursor: str | None = None,
    interval: Literal['5m', 'hourly', 'daily', 'weekly', 'monthly'] | None = None,
    from_date: str | None = None,
    to_date: str | None = None,
    forward_fill: bool | None = None,
    validate: bool | None = None,
  ) -> HistoricalPriceResponse:
    """Get historical price data points for a specific token address, suitable for rendering line charts. Supports various time intervals from 5 minutes to monthly.

    Args:
      chain_alias: The alias of the chain.
      token_alias_or_token_address: The token address or alias
      limit: The limit per page
      cursor: The cursor to the next page
      interval: The time interval for price data points. Defaults to 5m if not provided.
      from_date: The starting date (format in seconds or datestring accepted by momentjs). Defaults to 24 hours before toDate if not provided.
      to_date: The ending date (format in seconds or datestring accepted by momentjs). Defaults to now if not provided.
      forward_fill: When true, fills gaps in the time series with interpolated values
      validate: Per-call response validation override.

    References:
      - [Moralis API docs](https://docs.moralis.com/data-api/bitcoin/price/historical-price)
    """
    params = clean_params(
      {
        'limit': limit,
        'cursor': cursor,
        'interval': interval,
        'fromDate': from_date,
        'toDate': to_date,
        'forwardFill': forward_fill,
      }
    )
    response = await self.request(
      'GET',
      f'/v1/chains/{chain_alias}/tokens/{token_alias_or_token_address}/price/timeseries',
      params=params,
    )
    if self.should_validate(validate):
      return historical_price_adapter.validate_json(response.text)
    return response.json()

  def historical_price_paged(
    self,
    chain_alias: Literal[
      '0x1',
      'ethereum',
      '0x171',
      'pulse',
      '0x2105',
      'base',
      '0x38',
      'binance',
      '0x89',
      'polygon',
      '0xa',
      'optimism',
      '0xa86a',
      'avalanche',
      'bitcoin-mainnet',
      'bitcoin',
      'solana-mainnet',
      'sol',
    ],
    token_alias_or_token_address: str,
    *,
    limit: float | None = None,
    interval: Literal['5m', 'hourly', 'daily', 'weekly', 'monthly'] | None = None,
    from_date: str | None = None,
    to_date: str | None = None,
    forward_fill: bool | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[Result, str]:
    """Page through `historical_price`, awaitable (flattens every page) or async-iterable
    (one page at a time).
    """

    async def next(cursor: str) -> tuple[list[Result], str | None]:
      response = await self.historical_price(
        chain_alias,
        token_alias_or_token_address,
        limit=limit,
        interval=interval,
        from_date=from_date,
        to_date=to_date,
        forward_fill=forward_fill,
        cursor=(cursor or None),
        validate=validate,
      )
      rows = response.get('result')
      state = response.get('cursor')
      return rows, state or None

    return PaginatedResponse('', next)
