# Generated by typed-dev — see CONTRIBUTING.md.
"""`classic.mix.leveraged_long_short_ratio` -- generated from `spec/endpoints/`."""

from typed_core.validation import TypedDict, validator
from typed_bitget.core import TimestampMillis
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class MixLeveragedLongShortRatio(TypedDict):
  """Leveraged long/short ratio for one time bucket, for one bucket."""

  ts: TimestampMillis
  """Bucket time."""
  longShortRatio: str
  """Leveraged long/short ratio for the bucket."""


class LeveragedLongShortRatio(RpcEndpoint):
  """`classic.mix.leveraged_long_short_ratio`."""

  async def leveraged_long_short_ratio(
    self,
    *,
    symbol: str,
    coin: str | None = None,
    period: str | None = None,
    validate: bool | None = None,
  ) -> list[MixLeveragedLongShortRatio]:
    """Get the leveraged long/short ratio for one margin coin, public.

    Args:
      symbol: Futures symbol, e.g. "BTCUSDT".
      coin: Margin coin to compute the ratio for, e.g. "USDT".
      period: Bucket interval for the series, e.g. "5m"/"1H"/"1D". Optional; defaults to the venue's own default bucket. See endpoint `notes` on why this is not an `enum`.
    """
    params: dict = {
      'symbol': symbol,
    }
    if coin is not None:
      params['coin'] = coin
    if period is not None:
      params['period'] = period
    return await self.request(
      'GET',
      '/api/v2/mix/market/long-short-ratio',
      params=params,
      validator=validator(list[MixLeveragedLongShortRatio]),
      validate=validate,
    )
