# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_binance.core.endpoint.rpc import RpcEndpoint


class PmCmCurrentPositionMode(TypedDict):
  """Get user's position mode (Hedge Mode or One-way Mode ) on EVERY symbol in CM."""

  dualSidePosition: NotRequired[bool]
  """\"true": Hedge Mode; "false": One-way Mode."""


class CmPositionMode(RpcEndpoint):
  """Get user's position mode (Hedge Mode or One-way Mode ) on EVERY symbol in CM."""

  async def cm_position_mode(
    self,
    *,
    validate: bool | None = None,
  ) -> PmCmCurrentPositionMode:
    """Get user's position mode (Hedge Mode or One-way Mode ) on EVERY symbol in CM.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-cm-current-position-mode)
    """
    return await self.request(
      None,
      method='GET',
      path='/papi/v1/cm/positionSide/dual',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      response_type=PmCmCurrentPositionMode,
    )
