# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_binance.core.endpoint.rpc import RpcEndpoint


class PmChangeAutoRepayFuturesStatus(TypedDict):
  """Change Auto-repay-futures Status."""

  msg: NotRequired[str]
  """Msg."""


class Request(TypedDict):
  """Request parameters."""

  autoRepay: Literal['true', 'false']
  """`false` for turn off the auto-repay futures negative balance function."""


class SetAutoRepayFuturesStatus(RpcEndpoint):
  """Change Auto-repay-futures Status."""

  async def set_auto_repay_futures_status(
    self,
    auto_repay: Literal['true', 'false'],
    *,
    validate: bool | None = None,
  ) -> PmChangeAutoRepayFuturesStatus:
    """Change Auto-repay-futures Status.

    Args:
      auto_repay: `false` for turn off the auto-repay futures negative balance function.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#change-auto-repay-futures-status)
    """
    return await self.request(
      Request(autoRepay=auto_repay),
      method='POST',
      path='/papi/v1/repay-futures-switch',
      meta={'security': 'TRADE', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=PmChangeAutoRepayFuturesStatus,
    )
