# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_core.validation import validator
from typed_binance.core import TimestampMillis, timestamp_millis
from typed_binance.core.endpoint.rpc import RpcEndpoint


class PmDownloadIdForUmFuturesTransactionHistory(TypedDict):
  """Get download id for UM futures transaction history."""

  avgCostTimestampOfLast30d: NotRequired[int]
  """Average time taken for data download in the past 30 days."""
  downloadId: NotRequired[str]
  """Download ID."""


class UmIncomeHistoryDownloadId(RpcEndpoint):
  """Get Download Id For UM Futures Transaction History"""

  async def um_income_history_download_id(
    self,
    *,
    start_time: TimestampMillis,
    end_time: TimestampMillis,
    validate: bool | None = None,
  ) -> PmDownloadIdForUmFuturesTransactionHistory:
    """Get download id for UM futures transaction history.

    Args:
      start_time: Timestamp in ms.
      end_time: Timestamp in ms.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#get-download-id-for-um-futures-transaction-history)
    """
    params: dict = {
      'startTime': timestamp_millis.dump(start_time),
      'endTime': timestamp_millis.dump(end_time),
    }
    _Response = PmDownloadIdForUmFuturesTransactionHistory
    _validator = validator[_Response](_Response)
    return await self.authed_request(
      'GET',
      '/papi/v1/um/income/asyn',
      params=params,
      validator=_validator,
      validate=validate,
    )
