# Generated by typed-dev — see CONTRIBUTING.md.
"""`GET /api/v1/margin/maxWithdrawMargin` — Get Max Withdraw Margin."""

from typed_core.validation import validator
from typed_kucoin.core import RpcEndpoint


_Type = str
adapter = validator[_Type](_Type)  # type: ignore


class GetMaxWithdrawMargin(RpcEndpoint):
  """`Get Max Withdraw Margin` — mixed into `Positions`, the product exposing `futures.positions.get_max_withdraw_margin`."""

  async def get_max_withdraw_margin(
    self,
    *,
    symbol: str,
    validate: bool | None = None,
  ) -> str:
    """Get the maximum amount of margin that the current position for a symbol supports withdrawing (isolated margin only -- see notes).

    Args:
      symbol: Symbol of the contract, e.g. `XBTUSDTM`.
      validate: Validate the response against the generated schema.

    References:
      - [KuCoin API docs](https://www.kucoin.com/docs-new)
    """
    params: dict = {
      'symbol': symbol,
    }
    return await self.authed_request(
      'GET',
      '/api/v1/margin/maxWithdrawMargin',
      params=params,
      validator=adapter,
      validate=validate,
    )
