# Generated by typed-dev — see CONTRIBUTING.md.
from .get_asset_transfers import GetAssetTransfers


class Transfers(GetAssetTransfers):
  """Alchemy's Transfers API -- historical asset transfers (external, internal, and ERC-20/721/1155 transfer events) for an address, without scanning and indexing the chain yourself.

  References:
    - [Upstream docs](https://www.alchemy.com/docs/reference/transfers-api-quickstart)
  """
