# Generated by typed-dev — see CONTRIBUTING.md.
"""`tickers.{symbol}` — Subscribe to option ticker pushes."""

from typing_extensions import TypedDict
from typed_bybit.core import validator
from typed_bybit.core.ws import Reply, WsEndpoint
from typed_core.util import StreamManager
from typed_core.ws.streams import Stream


class OptionTicker(TypedDict):
  """One option ticker snapshot -- always the full field set, `option` pushes no delta."""

  symbol: str
  """Option symbol name."""
  bidPrice: str
  """Best bid price."""
  bidSize: str
  """Best bid size."""
  bidIv: str
  """Implied volatility at the best bid."""
  askPrice: str
  """Best ask price."""
  askSize: str
  """Best ask size."""
  askIv: str
  """Implied volatility at the best ask."""
  lastPrice: str
  """Last traded price."""
  highPrice24h: str
  """24-hour high price."""
  lowPrice24h: str
  """24-hour low price."""
  markPrice: str
  """Mark price."""
  indexPrice: str
  """Underlying index price."""
  markPriceIv: str
  """Implied volatility corresponding to the mark price."""
  underlyingPrice: str
  """Underlying (spot) price used for pricing."""
  openInterest: str
  """Open interest size."""
  turnover24h: str
  """24-hour turnover."""
  volume24h: str
  """24-hour trading volume."""
  totalVolume: str
  """Total traded volume."""
  totalTurnover: str
  """Total turnover."""
  delta: str
  """Delta greek."""
  gamma: str
  """Gamma greek."""
  vega: str
  """Vega greek."""
  theta: str
  """Theta greek."""
  predictedDeliveryPrice: str
  """Predicted delivery price. Populated only in the 30 minutes before delivery."""
  change24h: str
  """Price change over the last 24 hours."""


validate_message = validator[OptionTicker](OptionTicker)


class Ticker(WsEndpoint):
  """Subscribe to option ticker pushes."""

  def ticker(
    self,
    symbol: str,
    *,
    validate: bool | None = None,
  ) -> StreamManager[OptionTicker, Reply, Reply]:
    """Subscribe to ticker snapshots for one option symbol.

    Args:
      symbol: Option symbol name, for example `BTC-21AUG26-72000-C-USDT`.
      validate: Whether to validate pushed payloads against the expected schema.

    Returns:
      A manager for the subscription stream.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/websocket/public/ticker)
    """
    return StreamManager(lambda: self._ticker_impl(symbol, validate=validate))

  async def _ticker_impl(
    self,
    symbol: str,
    *,
    validate: bool | None = None,
  ) -> Stream[OptionTicker, Reply, Reply]:
    stream = await self.socket.subscribe(f'tickers.{symbol}')

    async def parsed_stream():
      async for msg in stream:
        yield validate_message(msg) if self.should_validate(validate) else msg

    return Stream(
      reply=stream.reply, stream=parsed_stream(), unsubscribe=stream.unsubscribe
    )
