# Generated by typed-dev — see CONTRIBUTING.md.
"""`GET /v5/rfq/rfq-realtime` — Get RFQs (Real-Time)."""

from typing_extensions import Literal, NotRequired, TypedDict
from typed_bybit.core import Endpoint, TimestampMillis, validator


class RfqHedgeLeg(TypedDict):
  """A delta hedge leg."""

  category: Literal['spot', 'linear', 'option']
  """Product type."""
  symbol: str
  """Hedge contract name."""
  side: Literal['Buy', 'Sell']
  """Order side."""
  qty: str
  """Trade quantity."""
  price: NotRequired[str]
  """Taker's desired execution price, reference only."""


class RfqLeg(TypedDict):
  """One leg of the combination transaction."""

  category: Literal['spot', 'linear', 'option']
  """Product type."""
  symbol: str
  """Instrument name."""
  side: Literal['Buy', 'Sell']
  """Order side."""
  qty: str
  """Trade quantity."""


class RfqRealtimeRecord(TypedDict):
  """One non-final RFQ."""

  rfqId: str
  """Inquiry ID."""
  rfqLinkId: str
  """Custom inquiry ID; not publicly disclosed."""
  counterparties: list[str]
  """Desk codes of the invited bidders."""
  expiresAt: TimestampMillis
  """Expiration timestamp."""
  strategyType: NotRequired[str]
  """Inquiry strategy label."""
  status: Literal['Active', 'PendingFill', 'Canceled', 'Filled', 'Expired', 'Failed']
  """RFQ status."""
  acceptOtherQuoteStatus: NotRequired[Literal['true', 'false']]
  """Whether non-LP quotes may be accepted."""
  deskCode: str
  """Inquiring party's identifier; hidden if `anonymous`."""
  anonymous: bool
  """Whether the RFQ is anonymous."""
  createdAt: TimestampMillis
  """Creation timestamp."""
  updatedAt: TimestampMillis
  """Last update timestamp."""
  legs: list[RfqLeg]
  """Combination transaction legs."""
  hedge: NotRequired[list[RfqHedgeLeg]]
  """Delta hedge legs, when the RFQ carried one."""


class RfqRealtimeResult(TypedDict):
  """The current non-final RFQs."""

  list: list[RfqRealtimeRecord]
  """Non-final RFQ records."""


adapter = validator[RfqRealtimeResult](RfqRealtimeResult)


class RfqRealtime(Endpoint):
  """`Get RFQs (Real-Time)` — mixed into the router that owns `rfq.trade.rfq_realtime`."""

  async def rfq_realtime(
    self,
    *,
    rfq_id: str | None = None,
    rfq_link_id: str | None = None,
    trader_type: Literal['quote', 'request'] | None = None,
    validate: bool | None = None,
  ) -> RfqRealtimeResult:
    """Obtain real-time (non-final) RFQ information, sorted by creation time descending. Up to 50 requests per second.

    Args:
      rfq_id: Filter to one inquiry ID. If both `rfqId` and `rfqLinkId` are passed, only `rfqId` is honored.
      rfq_link_id: Filter to one custom inquiry ID; invalid when `traderType` is `quote`.
      trader_type: Role to query as. Defaults to `quote`.
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/rfq/trade/rfq-realtime)
    """
    params = {}
    if rfq_id is not None:
      params['rfqId'] = rfq_id
    if rfq_link_id is not None:
      params['rfqLinkId'] = rfq_link_id
    if trader_type is not None:
      params['traderType'] = trader_type
    r = await self.authed_request('GET', '/v5/rfq/rfq-realtime', params=params)
    return self.result(r, adapter, validate)
