# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import TypedDict
from typed_kucoin.core.endpoint.rpc import RpcEndpoint


class Request(TypedDict):
  uid: str
  """Sub-account UID to grant Futures permission to."""


Response = bool | None


class AddFuturesPermission(RpcEndpoint):
  """Grant Futures trading permission to an existing sub-account. The master account's API key must itself carry Futures permission and have Futures trading activated before this call succeeds."""

  async def add_futures_permission(
    self,
    uid: str,
    *,
    validate: bool | None = None,
  ) -> Response:
    """Grant Futures trading permission to an existing sub-account. The master account's API key must itself carry Futures permission and have Futures trading activated before this call succeeds.

    Args:
      uid: Sub-account UID to grant Futures permission to.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.kucoin.com/docs-new/api-3470332)
    """
    return await self.request(
      Request(uid=uid),
      method='POST',
      path='/api/v3/sub/user/futures/enable',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
