# Generated by typed-dev — see CONTRIBUTING.md.
"""`classic.margin.isolated.order.open` -- generated from `spec/endpoints/`."""

from typing_extensions import Literal, NotRequired
from typed_core.validation import TypedDict, validator
from typed_bitget.core import TimestampMillis, timestamp_millis
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class IsolatedMarginOrder(TypedDict):
  """IsolatedMarginOrder."""

  symbol: NotRequired[str]
  """Trading pair."""
  orderId: NotRequired[str]
  """Order id."""
  clientOid: NotRequired[str]
  """Caller-supplied client order id."""
  orderType: NotRequired[Literal['limit', 'market']]
  """Order type."""
  status: NotRequired[
    Literal['live', 'partially_fill', 'filled', 'cancelled', 'reject']
  ]
  """Order status."""
  side: NotRequired[Literal['buy', 'sell']]
  """Order direction."""
  force: NotRequired[Literal['gtc', 'post_only', 'fok', 'ioc']]
  """Time-in-force behavior."""
  loanType: NotRequired[Literal['normal', 'autoLoan', 'autoRepay', 'autoLoanAndRepay']]
  """Margin loan behavior for this order."""
  enterPointSource: NotRequired[Literal['WEB', 'API', 'SYS', 'ANDROID', 'IOS']]
  """Where the order was submitted from."""
  price: NotRequired[str]
  """Order price. Empty for market orders."""
  priceAvg: NotRequired[str]
  """Average fill price."""
  baseSize: NotRequired[str]
  """Order quantity in base coin."""
  quoteSize: NotRequired[str]
  """Order quantity in quote coin."""
  size: NotRequired[str]
  """Filled quantity."""
  amount: NotRequired[str]
  """Filled amount."""
  cTime: NotRequired[TimestampMillis]
  """Creation time, Unix millisecond timestamp."""
  uTime: NotRequired[TimestampMillis]
  """Last update time, Unix millisecond timestamp."""


class IsolatedMarginOpenOrders(TypedDict):
  """Open margin orders."""

  orderList: NotRequired[list[IsolatedMarginOrder]]
  """Open orders, newest first."""
  maxId: NotRequired[str | None]
  """Largest id in this page of results. `null` when the page is empty (confirmed live)."""
  minId: NotRequired[str | None]
  """Smallest id in this page of results. Pass as `idLessThan` to fetch the next page. `null` when the page is empty (confirmed live)."""


class Open(RpcEndpoint):
  """`classic.margin.isolated.order.open`."""

  async def open(
    self,
    *,
    symbol: str,
    order_id: str | None = None,
    client_oid: str | None = None,
    start_time: TimestampMillis,
    end_time: TimestampMillis | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> IsolatedMarginOpenOrders:
    """Query currently open isolated margin orders for one trading pair. Rate limit: 10 requests/second per UID.

    Args:
      symbol: Trading pair.
      order_id: Exact-match order id filter.
      client_oid: Exact-match client order id filter.
      start_time: Start of the query window, Unix millisecond timestamp.
      end_time: End of the query window, Unix millisecond timestamp.
      limit: Number of results to return. Default 100, maximum 500.

    References:
      - [Official docs](https://www.bitget.com/api-doc/classic/margin/isolated/trade/Isolated-Open-Orders)
    """
    params: dict = {
      'symbol': symbol,
      'startTime': timestamp_millis.dump(start_time),
    }
    if order_id is not None:
      params['orderId'] = order_id
    if client_oid is not None:
      params['clientOid'] = client_oid
    if end_time is not None:
      params['endTime'] = timestamp_millis.dump(end_time)
    if limit is not None:
      params['limit'] = limit
    return await self.authed_request(
      'GET',
      '/api/v2/margin/isolated/open-orders',
      params=params,
      validator=validator(IsolatedMarginOpenOrders),
      validate=validate,
    )
