# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_bybit.core.http import RpcEndpoint


class Request(TypedDict):
  """Leverage parameters."""

  leverage: str
  """Leverage value, range [2, 10]."""
  currency: NotRequired[str]
  """Coin name, uppercase only. Omit to set the account-wide leverage."""


class SetLeverageResult(TypedDict):
  """Empty result."""


class SetLeverage(RpcEndpoint):
  """Configure the maximum leverage for spot cross margin trading. The account must have spot margin activated, and the requested leverage cannot exceed the currency's maximum allowable leverage."""

  async def set_leverage(
    self,
    *,
    leverage: str,
    currency: str | None = None,
    validate: bool | None = None,
  ) -> SetLeverageResult:
    """Configure the maximum leverage for spot cross margin trading. The account must have spot margin activated, and the requested leverage cannot exceed the currency's maximum allowable leverage.

    Args:
      leverage: Leverage value, range [2, 10].
      currency: Coin name, uppercase only. Omit to set the account-wide leverage.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://bybit-exchange.github.io/docs/v5/spot-margin-uta/set-leverage)
    """
    request: Request = Request(leverage=leverage)
    if currency is not None:
      request['currency'] = currency
    return await self.request(
      request,
      method='POST',
      path='/v5/spot-margin-trade/set-leverage',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=SetLeverageResult,
    )
