# Generated by typed-dev — see CONTRIBUTING.md.
"""`DELETE /api/v1/stopOrders` — Cancel All Stop Orders."""

from typed_core.validation import validator
from typed_kucoin.types import FuturesCancelResult
from typed_kucoin.core import RpcEndpoint


_Type = FuturesCancelResult
adapter = validator[_Type](_Type)  # type: ignore


class CancelAllStopOrders(RpcEndpoint):
  """`Cancel All Stop Orders` — mixed into `Orders`, the product exposing `futures.orders.cancel_all_stop_orders`."""

  async def cancel_all_stop_orders(
    self,
    *,
    symbol: str | None = None,
    validate: bool | None = None,
  ) -> FuturesCancelResult:
    """Cancel all untriggered stop orders. Optionally scoped to one contract symbol. A triggered stop order behaves like a normal order at that point and must be cancelled through Cancel Order By OrderId/ClientOid or Cancel All Orders instead.

    Args:
      symbol: Cancel only this contract's untriggered stop orders; cancels every untriggered stop order account-wide when omitted.
      validate: Validate the response against the generated schema.

    References:
      - [KuCoin API docs](https://www.kucoin.com/docs-new)
    """
    params = {}
    if symbol is not None:
      params['symbol'] = symbol
    return await self.authed_request(
      'DELETE',
      '/api/v1/stopOrders',
      params=params,
      validator=adapter,
      validate=validate,
    )
