# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import TypedDict
from typed_kucoin.core.endpoint.rpc import RpcEndpoint
from typed_kucoin.schemas import FuturesOrder


RequestKeywords = TypedDict('RequestKeywords', {'order-id': str})
"""
- `order-id`: System-generated id of the order to look up. KuCoin's own path template spells this segment `order-id` (hyphenated), unlike every other order endpoint here which uses `orderId` -- confirmed against the official SDK spec's path key, not a transcription choice.
"""


class Request(RequestKeywords): ...


class GetByOrderId(RpcEndpoint):
  """Get a single futures order (including a stop order) by its system-generated order id. Historical (filled/cancelled) orders are only queryable within a limited time window."""

  async def get_by_order_id(
    self,
    order_id: str,
    *,
    validate: bool | None = None,
  ) -> FuturesOrder:
    """Get a single futures order (including a stop order) by its system-generated order id. Historical (filled/cancelled) orders are only queryable within a limited time window.

    Args:
      order_id: System-generated id of the order to look up. KuCoin's own path template spells this segment `order-id` (hyphenated), unlike every other order endpoint here which uses `orderId` -- confirmed against the official SDK spec's path key, not a transcription choice.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.kucoin.com/docs-new/rest/futures-trading/orders/get-order-by-orderld)
    """
    request: Request = {'order-id': order_id}
    return await self.request(
      request,
      method='GET',
      path='/api/v1/orders/{order-id}',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=FuturesOrder,
    )
