# Generated by typed-dev — see CONTRIBUTING.md.
"""`GET /api/v1/recentDoneOrders` — Get Recent Closed Orders."""

from typed_core.validation import validator
from typed_kucoin.types import FuturesOrder
from typed_kucoin.core import RpcEndpoint


_Type = list[FuturesOrder]
adapter = validator[_Type](_Type)  # type: ignore


class GetRecentClosedOrders(RpcEndpoint):
  """`Get Recent Closed Orders` — mixed into `Orders`, the product exposing `futures.orders.get_recent_closed_orders`."""

  async def get_recent_closed_orders(
    self,
    *,
    symbol: str | None = None,
    validate: bool | None = None,
  ) -> list[FuturesOrder]:
    """Get up to 1000 orders closed (filled or cancelled) in the last 24 hours -- a lower-latency alternative to Get Order List for recent activity.

    Args:
      symbol: Contract symbol to filter by.
      validate: Validate the response against the generated schema.

    References:
      - [KuCoin API docs](https://www.kucoin.com/docs-new)
    """
    params = {}
    if symbol is not None:
      params['symbol'] = symbol
    return await self.authed_request(
      'GET',
      '/api/v1/recentDoneOrders',
      params=params,
      validator=adapter,
      validate=validate,
    )
