# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class EliteAssetProject(TypedDict):
  """One underlying on-chain project this holding is deployed into."""

  projectName: str
  """Project name."""


class EliteAsset(TypedDict):
  """One Elite holding."""

  productId: str
  """Product identifier."""
  productCoin: str
  """Coin held."""
  holdingAmount: str
  """Amount held, in `productCoin`."""
  usdtHoldingAmount: str
  """Amount held, converted to USDT."""
  exchangeRate: str
  """Exchange rate applied at subscription."""
  apr: str
  """Annual percentage rate currently applied."""
  minApy: NotRequired[str]
  """Minimum APY, when the product has a range."""
  maxApy: NotRequired[str]
  """Maximum APY, when the product has a range."""
  subscriptionCoin: str
  """Coin the subscription payment was made in."""
  exchangeAmount: str
  """Amount after exchange into `productCoin`."""
  projectList: NotRequired[list[EliteAssetProject]]
  """Underlying on-chain projects this holding is deployed into, when applicable."""
  unsettledBGPoints: str
  """BG Points accrued but not yet settled."""
  interestCoin: str
  """Coin interest is paid in."""
  totalProfit: str
  """Cumulative profit on this holding."""


class EliteAssets(TypedDict):
  """The caller's Elite holdings."""

  resultList: list[EliteAsset]
  """The caller's Elite holdings."""


class Assets(RpcEndpoint):
  """List the caller's Elite holdings."""

  async def assets(self, *, validate: bool | None = None) -> EliteAssets:
    """List the caller's Elite holdings.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/earn-classic-elite/classic-earn-elite#get-elite-assets)
    """
    return await self.request(
      None,
      method='GET',
      path='/api/v2/earn/elite/assets',
      meta={'required': True},
      validate=validate,
      response_type=EliteAssets,
    )
