# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class EliteRedeemResult(TypedDict):
  """Result of an Elite redemption request."""

  orderId: str
  """Order identifier for this redemption."""


class Request(TypedDict):
  """Elite redemption request."""

  productId: str
  """Product the holding belongs to."""
  productSubId: str
  """Sub-product identifier."""
  redeemType: Literal['fast', 'standard']
  """Redemption mode to use, from redeem-info."""
  amount: str
  """Amount to redeem."""
  receiveAccount: Literal['spot', 'unified']
  """Account to credit proceeds to."""
  advancedSettle: NotRequired[Literal['yes', 'no']]
  """Whether to use advanced settlement, when offered."""
  coin: NotRequired[str]
  """Coin to receive proceeds in, when the product offers a choice."""


class Redeem(RpcEndpoint):
  """Redeem an amount from an Elite holding."""

  async def redeem(
    self,
    *,
    product_id: str,
    product_sub_id: str,
    redeem_type: Literal['fast', 'standard'],
    amount: str,
    receive_account: Literal['spot', 'unified'],
    advanced_settle: Literal['yes', 'no'] | None = None,
    coin: str | None = None,
    validate: bool | None = None,
  ) -> EliteRedeemResult:
    """Redeem an amount from an Elite holding.

    Args:
      product_id: Product the holding belongs to.
      product_sub_id: Sub-product identifier.
      redeem_type: Redemption mode to use, from redeem-info.
      amount: Amount to redeem.
      receive_account: Account to credit proceeds to.
      advanced_settle: Whether to use advanced settlement, when offered.
      coin: Coin to receive proceeds in, when the product offers a choice.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/earn-classic-elite/classic-earn-elite#elite-redeem)
    """
    request: Request = Request(
      productId=product_id,
      productSubId=product_sub_id,
      redeemType=redeem_type,
      amount=amount,
      receiveAccount=receive_account,
    )
    if advanced_settle is not None:
      request['advancedSettle'] = advanced_settle
    if coin is not None:
      request['coin'] = coin
    return await self.request(
      request,
      method='POST',
      path='/api/v2/earn/elite/redeem',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=EliteRedeemResult,
    )
