# Generated by typed-dev — see CONTRIBUTING.md.
"""`uta/market` router, generated from `spec/endpoints/`."""

from functools import cached_property

from typed_bitget.core.endpoint.rpc import RpcEndpoint
from .candles import Candles
from .cash_dividend_records import CashDividendRecordsEndpoint
from .discount_rate import DiscountRateEndpoint
from .fee_group import FeeGroup
from .fills import Fills
from .funding_rate import FundingRate
from .futures import Futures
from .index_components import IndexComponents
from .instruments import Instruments
from .liquidations import LiquidationsEndpoint
from .margin import Margin
from .oi_limit import OiLimit
from .open_interest import OpenInterestEndpoint
from .orderbook import Orderbook
from .position_tier import PositionTierEndpoint
from .proof_of_reserves import ProofOfReservesEndpoint
from .risk_reserve import RiskReserve
from .rpi import Rpi
from .score_weights import ScoreWeights
from .server_time import ServerTimeEndpoint
from .spot import Spot
from .tickers import Tickers


class Market(
  CashDividendRecordsEndpoint,
  DiscountRateEndpoint,
  FeeGroup,
  Fills,
  IndexComponents,
  Instruments,
  LiquidationsEndpoint,
  OiLimit,
  OpenInterestEndpoint,
  Orderbook,
  PositionTierEndpoint,
  ProofOfReservesEndpoint,
  ScoreWeights,
  ServerTimeEndpoint,
  Tickers,
  RpcEndpoint,
):
  """`uta/market` endpoints."""

  @cached_property
  def candles(self) -> Candles:
    return Candles(client=self.client)

  @cached_property
  def funding_rate(self) -> FundingRate:
    return FundingRate(client=self.client)

  @cached_property
  def futures(self) -> Futures:
    return Futures(client=self.client)

  @cached_property
  def margin(self) -> Margin:
    return Margin(client=self.client)

  @cached_property
  def risk_reserve(self) -> RiskReserve:
    return RiskReserve(client=self.client)

  @cached_property
  def rpi(self) -> Rpi:
    return Rpi(client=self.client)

  @cached_property
  def spot(self) -> Spot:
    return Spot(client=self.client)
