# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import Literal, NotRequired, TypedDict
from typed_hyperliquid.core import TimestampMillis
from typed_hyperliquid.info.core import InfoCore


class L2BookLevel0Item(TypedDict):
  n: int
  """Number of individual orders aggregated into this level."""
  px: Decimal
  """Level price, as a decimal string."""
  sz: Decimal
  """Total size resting at this level, as a decimal string."""


class L2BookLevel1Item(TypedDict):
  n: int
  """Number of individual orders aggregated into this level."""
  px: Decimal
  """Level price, as a decimal string."""
  sz: Decimal
  """Total size resting at this level, as a decimal string."""


class Request(TypedDict):
  coin: str
  """Coin to fetch the order book for."""
  nSigFigs: NotRequired[Literal[2, 3, 4, 5]]
  """Aggregate levels to this many significant figures. Omit for full precision."""
  mantissa: NotRequired[Literal[1, 2, 5]]
  """Further aggregate levels by this mantissa. Only allowed when `nSigFigs` is 5."""


class L2Book(TypedDict):
  """Level-2 order book snapshot for a coin."""

  coin: str
  """Coin the snapshot is for."""
  levels: tuple[list[L2BookLevel0Item], list[L2BookLevel1Item]]
  """Two-element array of `[bids, asks]`, each a list of aggregated price levels ordered from best to worst."""
  time: TimestampMillis
  """Snapshot time, in milliseconds since epoch."""


class L2BookEndpoint(InfoCore):
  """Retrieve a level-2 order book snapshot for a coin: bids and asks, each as a list of aggregated price levels."""

  async def l2_book(
    self,
    coin: str,
    *,
    n_sig_figs: Literal[2, 3, 4, 5] | None = None,
    mantissa: Literal[1, 2, 5] | None = None,
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> L2Book:
    """Retrieve a level-2 order book snapshot for a coin: bids and asks, each as a list of aggregated price levels.

    Args:
      coin: Coin to fetch the order book for.
      n_sig_figs: Aggregate levels to this many significant figures. Omit for full precision.
      mantissa: Further aggregate levels by this mantissa. Only allowed when `nSigFigs` is 5.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint)
    """
    request: Request = Request(coin=coin)
    if n_sig_figs is not None:
      request['nSigFigs'] = n_sig_figs
    if mantissa is not None:
      request['mantissa'] = mantissa
    return await self.request(
      request,
      method='POST',
      path='l2Book',
      validate=validate,
      transport=transport,
      request_type=Request,
      response_type=L2Book,
    )
