# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_hyperliquid.info.core import InfoCore


class annotation(TypedDict):
  """Compact annotation: `category` (required), plus `displayName`/`keywords` when set -- unlike `perpAnnotation`'s full shape, `description` is omitted."""

  category: str
  """Category tag assigned to the coin."""
  displayName: NotRequired[str]
  """Short display name for the coin, when one was set."""
  keywords: NotRequired[list[str]]
  """Search keywords for the coin, when any were set."""


PerpConciseAnnotationsResponse = list[tuple[str, annotation]]


class PerpConciseAnnotations(InfoCore):
  """Retrieve every deployer-set perp annotation across all perp dexs in one compact call, keyed by coin. Unlike `perpAnnotation`, which looks up one coin's full annotation, this returns the whole annotated set at once with only the two fields that fit the compact shape."""

  async def perp_concise_annotations(
    self,
    *,
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> PerpConciseAnnotationsResponse:
    """Retrieve every deployer-set perp annotation across all perp dexs in one compact call, keyed by coin. Unlike `perpAnnotation`, which looks up one coin's full annotation, this returns the whole annotated set at once with only the two fields that fit the compact shape.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint/perpetuals)
    """
    return await self.request(
      None,
      method='POST',
      path='perpConciseAnnotations',
      validate=validate,
      transport=transport,
      response_type=PerpConciseAnnotationsResponse,
    )
