# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import Literal, TypedDict
from typed_hyperliquid.core import TimestampMillis
from typed_hyperliquid.info.core import InfoCore


class CrossLeverage(TypedDict):
  """Leverage for a cross-margined position."""

  type: Literal['cross']
  """Margin mode."""
  value: int
  """Leverage multiplier."""


class CumulativeFunding(TypedDict):
  """Cumulative funding paid (positive) or received (negative) by the position, tracked over three windows."""

  allTime: Decimal
  """Cumulative funding since the asset was listed."""
  sinceChange: Decimal
  """Cumulative funding since the position size last changed."""
  sinceOpen: Decimal
  """Cumulative funding since the position was opened."""


class IsolatedLeverage(TypedDict):
  """Leverage for an isolated-margin position."""

  type: Literal['isolated']
  """Margin mode."""
  value: int
  """Leverage multiplier."""
  rawUsd: Decimal
  """USD margin allocated to the isolated position, before unrealized PnL."""


class Request(TypedDict):
  user: str
  """Address to look up, as a 42-character hexadecimal string."""


class SubAccountMarginSummaryCrossMarginSummary(TypedDict):
  """Cross-margin-only summary for this subaccount."""

  accountValue: Decimal
  """Total account value, as a decimal string."""
  totalNtlPos: Decimal
  """Total notional position size, as a decimal string."""
  totalRawUsd: Decimal
  """Total raw USD value of positions, as a decimal string."""
  totalMarginUsed: Decimal
  """Total margin currently used, as a decimal string."""


class SubAccountMarginSummaryMarginSummary(TypedDict):
  """Isolated + cross margin summary for this subaccount."""

  accountValue: Decimal
  """Total account value, as a decimal string."""
  totalNtlPos: Decimal
  """Total notional position size, as a decimal string."""
  totalRawUsd: Decimal
  """Total raw USD value of positions, as a decimal string."""
  totalMarginUsed: Decimal
  """Total margin currently used, as a decimal string."""


class SubAccountSpotBalance(TypedDict):
  """Spot balance for one coin in this subaccount."""

  coin: str
  """Spot coin symbol."""
  token: int
  """Spot token index."""
  total: Decimal
  """Total balance, as a decimal string."""
  hold: Decimal
  """Portion of the balance currently held by open orders, as a decimal string."""
  entryNtl: Decimal
  """Entry notional value of the held balance, as a decimal string."""


class PerpPosition(TypedDict):
  """The details of the open position."""

  coin: str
  """Perpetual asset symbol, e.g. "ETH"."""
  cumFunding: CumulativeFunding
  entryPx: Decimal
  """Volume-weighted average entry price of the position."""
  leverage: CrossLeverage | IsolatedLeverage
  """The position's leverage settings. Cross-margined positions share account-wide margin; isolated positions carry their own dedicated margin, reported as `rawUsd`."""
  liquidationPx: Decimal
  """Estimated liquidation price for the position."""
  marginUsed: Decimal
  """Margin currently allocated to the position."""
  maxLeverage: int
  """Maximum leverage allowed for this asset at the account's current settings."""
  positionValue: Decimal
  """Notional value of the position, in USD."""
  returnOnEquity: Decimal
  """Position return on equity, as a decimal fraction."""
  szi: Decimal
  """Signed position size: positive for long, negative for short."""
  unrealizedPnl: Decimal
  """Unrealized profit or loss on the position."""


class SubAccountSpotState(TypedDict):
  """Spot account state for this subaccount (same shape as `info.spot_clearinghouse_state`)."""

  balances: list[SubAccountSpotBalance]
  """Spot balances held by this subaccount."""


class AssetPosition(TypedDict):
  """A single open perpetual position (same shape as `info.clearinghouse_state`'s own `AssetPosition`)."""

  position: PerpPosition
  type: Literal['oneWay']
  """Position mode. Hyperliquid currently supports only one-way (non-hedge) positions."""


class SubAccountClearinghouseState(TypedDict):
  """Perpetuals clearinghouse state for this subaccount (same shape as `info.clearinghouse_state`)."""

  marginSummary: SubAccountMarginSummaryMarginSummary
  crossMarginSummary: SubAccountMarginSummaryCrossMarginSummary
  crossMaintenanceMarginUsed: Decimal
  """Cross-margin maintenance margin currently used, as a decimal string."""
  withdrawable: Decimal
  """Amount withdrawable from this subaccount, as a decimal string."""
  assetPositions: list[AssetPosition]
  """Open perpetual positions for this subaccount."""
  time: TimestampMillis
  """State snapshot time, in milliseconds since epoch."""


class SubAccount(TypedDict):
  """One subaccount belonging to the queried master account."""

  name: str
  """Subaccount display name, as set by the master account. Not a fixed set of values."""
  subAccountUser: str
  """The subaccount's own address."""
  master: str
  """Address of the master account that owns this subaccount."""
  clearinghouseState: SubAccountClearinghouseState
  spotState: SubAccountSpotState


Response = list[SubAccount] | None


class SubAccounts(InfoCore):
  """Retrieve the subaccounts belonging to a master account, including each subaccount's perpetuals clearinghouse state and spot balances."""

  async def sub_accounts(
    self,
    user: str,
    *,
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> Response:
    """Retrieve the subaccounts belonging to a master account, including each subaccount's perpetuals clearinghouse state and spot balances.

    Args:
      user: Address to look up, as a 42-character hexadecimal string.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint)
    """
    return await self.request(
      Request(user=user),
      method='POST',
      path='subAccounts',
      validate=validate,
      transport=transport,
      request_type=Request,
      response_type=Response,
    )
