# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_bit2me.core import TimestampMillis
from typed_bit2me.core.endpoint.rpc import RpcEndpoint


class Point(TypedDict):
  time: TimestampMillis
  """Unix timestamp in milliseconds for this data point."""
  price: str
  """Price at this point in time, as a decimal string, denominated in the request's `rateCurrency`."""
  interval: Literal['one_hour', 'one_day', 'one_week', 'one_month', 'one_year']
  """Time interval this data point represents, matching one of the requested `interval` values."""
  marketCap: NotRequired[str]
  """Market capitalization at this point in time, as a decimal string."""
  totalVolume: NotRequired[str]
  """Total trading volume at this point in time, as a decimal string."""
  fullyDilutedMarketCap: NotRequired[str]
  """Fully diluted market capitalization at this point in time, as a decimal string."""
  maxSupply: NotRequired[str]
  """Maximum possible supply of the cryptocurrency, as a decimal string."""
  totalSupply: NotRequired[str]
  """Circulating total supply of the cryptocurrency at this point in time, as a decimal string."""


class Request(TypedDict):
  symbol: str
  """ISO 4217 cryptocurrency code to fetch ticker data for, e.g. `BTC`."""
  rateCurrency: NotRequired[str]
  """Currency to express the ticker's price and market data in, as an ISO 4217 code."""
  interval: NotRequired[
    list[Literal['one_hour', 'one_day', 'one_week', 'one_month', 'one_year']]
  ]
  """Period(s) of time to fetch price/market data points for. Repeatable to request multiple intervals in one call."""
  extended: NotRequired[bool]
  """Whether to include extended market data (market cap, volume, supply) alongside price. Defaults to `true`."""


CurrencyTickerV3Response = dict[str, dict[str, list[Point]]]


class Ticker(RpcEndpoint):
  """Return ticker data for the selected cryptocurrency."""

  async def ticker(
    self,
    *,
    symbol: str,
    rate_currency: str | None = None,
    interval: list[Literal['one_hour', 'one_day', 'one_week', 'one_month', 'one_year']]
    | None = None,
    extended: bool | None = None,
    validate: bool | None = None,
  ) -> CurrencyTickerV3Response:
    """Return ticker data for the selected cryptocurrency.

    Args:
      symbol: ISO 4217 cryptocurrency code to fetch ticker data for, e.g. `BTC`.
      rate_currency: Currency to express the ticker's price and market data in, as an ISO 4217 code.
      interval: Period(s) of time to fetch price/market data points for. Repeatable to request multiple intervals in one call.
      extended: Whether to include extended market data (market cap, volume, supply) alongside price. Defaults to `true`.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://api.bit2me.com/doc#tag/market/GET/v3/currency/ticker/{symbol})
    """
    request: Request = Request(symbol=symbol)
    if rate_currency is not None:
      request['rateCurrency'] = rate_currency
    if interval is not None:
      request['interval'] = interval
    if extended is not None:
      request['extended'] = extended
    return await self.request(
      request,
      method='GET',
      path='/v3/currency/ticker/{symbol}',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=CurrencyTickerV3Response,
    )
