# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint
from typed_bitget.schemas import SpotBatchMode


class SpotBatchCancelOrderItem(TypedDict):
  """One order to cancel."""

  symbol: NotRequired[str]
  """Trading pair symbol, when `batchMode` is `multiple`."""
  orderId: NotRequired[str]
  """Exchange order ID. Either this or `clientOid` is required."""
  clientOid: NotRequired[str]
  """Client order ID. Either this or `orderId` is required."""


class SpotBatchOrderFailure(TypedDict):
  """One order that failed."""

  orderId: str
  """Exchange order ID, if one was assigned before failing."""
  clientOid: str
  """Client order ID."""
  errorMsg: str
  """Failure reason."""
  errorCode: NotRequired[str]
  """Failure error code."""


class SpotBatchOrderSuccess(TypedDict):
  """One order that succeeded."""

  orderId: str
  """Exchange order ID."""
  clientOid: str
  """Client order ID."""


class Request(TypedDict):
  """A batch of orders to cancel."""

  symbol: NotRequired[str]
  """Trading pair symbol shared by every order in the batch, when `batchMode` is `single`."""
  batchMode: NotRequired[SpotBatchMode]
  orderList: list[SpotBatchCancelOrderItem]
  """Orders to cancel, up to 50."""


class SpotBatchOrdersResult(TypedDict):
  """Per-order results of a batch operation."""

  successList: list[SpotBatchOrderSuccess]
  """Orders that succeeded."""
  failureList: list[SpotBatchOrderFailure]
  """Orders that failed."""


class Cancel(RpcEndpoint):
  """Cancel up to 50 open spot orders in one call."""

  async def cancel(
    self,
    symbol: str | None = None,
    *,
    batch_mode: SpotBatchMode | None = None,
    order_list: list[SpotBatchCancelOrderItem],
    validate: bool | None = None,
  ) -> SpotBatchOrdersResult:
    """Cancel up to 50 open spot orders in one call.

    Args:
      symbol: Trading pair symbol shared by every order in the batch, when `batchMode` is `single`.
      batch_mode:
      order_list: Orders to cancel, up to 50.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-spot-trade/classic-spot-trade#batch-cancel-orders)
    """
    request: Request = Request(orderList=order_list)
    if symbol is not None:
      request['symbol'] = symbol
    if batch_mode is not None:
      request['batchMode'] = batch_mode
    return await self.request(
      request,
      method='POST',
      path='/api/v2/spot/trade/batch-cancel-order',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=SpotBatchOrdersResult,
    )
