# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_core.validation import validator
from binance.core.endpoint.rpc import RpcEndpoint


class PmChangeAutoRepayFuturesStatus(TypedDict):
  """Change Auto-repay-futures Status."""

  msg: NotRequired[str]
  """Msg."""


class SetAutoRepayFuturesStatus(RpcEndpoint):
  """Change Auto-repay-futures Status"""

  async def set_auto_repay_futures_status(
    self,
    *,
    auto_repay: Literal['true', 'false'],
    validate: bool | None = None,
  ) -> PmChangeAutoRepayFuturesStatus:
    """Change Auto-repay-futures Status.

    Args:
      auto_repay: `false` for turn off the auto-repay futures negative balance function.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/advanced-trading-derivatives-trading-portfolio-margin/api/rest-api/account#change-auto-repay-futures-status)
    """
    params: dict = {
      'autoRepay': auto_repay,
    }
    _Response = PmChangeAutoRepayFuturesStatus
    _validator = validator[_Response](_Response)
    return await self.authed_request(
      'POST',
      '/papi/v1/repay-futures-switch',
      params=params,
      validator=_validator,
      validate=validate,
    )
