# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_binance.core import TimestampMillis
from typed_binance.core.endpoint.rpc import RpcEndpoint


class Request(TypedDict):
  """Request parameters."""

  symbol: NotRequired[str]
  """Symbol to filter by."""
  autoCloseType: NotRequired[Literal['LIQUIDATION', 'ADL']]
  """Type of forced close to filter by. If omitted, orders of both types are returned."""
  startTime: NotRequired[TimestampMillis]
  """Query window start, as milliseconds since epoch."""
  endTime: NotRequired[TimestampMillis]
  """Query window end, as milliseconds since epoch."""
  limit: NotRequired[int]
  """Number of orders to return."""


class UsdMFuturesForceOrder(TypedDict):
  """A single force-liquidation or ADL order."""

  orderId: NotRequired[int]
  """Order ID assigned by Binance."""
  symbol: NotRequired[str]
  """Symbol this order was placed on."""
  pair: NotRequired[str]
  """Underlying pair this order was placed on."""
  status: NotRequired[
    Literal[
      'NEW',
      'PARTIALLY_FILLED',
      'FILLED',
      'CANCELED',
      'REJECTED',
      'EXPIRED',
      'EXPIRED_IN_MATCH',
    ]
  ]
  """Order status. Not confirmed as a closed set in this docs-only pass — see notes."""
  clientOrderId: NotRequired[str]
  """Client-supplied order ID."""
  price: NotRequired[str]
  """Order price, as a decimal string."""
  avgPrice: NotRequired[str]
  """Average fill price, as a decimal string."""
  origQty: NotRequired[str]
  """Original order quantity, as a decimal string."""
  executedQty: NotRequired[str]
  """Quantity that has been filled, as a decimal string."""
  cumQuote: NotRequired[str]
  """Cumulative quote asset quantity filled, as a decimal string."""
  cumBase: NotRequired[str]
  """Cumulative base asset quantity filled, as a decimal string."""
  timeInForce: NotRequired[Literal['GTC', 'IOC', 'FOK', 'GTX', 'GTD', 'RPI']]
  """Time in force."""
  type: NotRequired[
    Literal[
      'LIMIT',
      'MARKET',
      'STOP',
      'STOP_MARKET',
      'TAKE_PROFIT',
      'TAKE_PROFIT_MARKET',
      'TRAILING_STOP_MARKET',
    ]
  ]
  """Order type."""
  reduceOnly: NotRequired[bool]
  """Whether this order was reduce-only."""
  closePosition: NotRequired[bool]
  """Whether this order was a close-position order."""
  side: NotRequired[Literal['BUY', 'SELL']]
  """Order side."""
  positionSide: NotRequired[Literal['BOTH', 'LONG', 'SHORT']]
  """Position side this order applies to."""
  stopPrice: NotRequired[str]
  """Stop trigger price, as a decimal string."""
  workingType: NotRequired[Literal['MARK_PRICE', 'CONTRACT_PRICE']]
  """Price type used to trigger conditional orders."""
  origType: NotRequired[
    Literal[
      'LIMIT',
      'MARKET',
      'STOP',
      'STOP_MARKET',
      'TAKE_PROFIT',
      'TAKE_PROFIT_MARKET',
      'TRAILING_STOP_MARKET',
    ]
  ]
  """Original order type as submitted."""
  time: NotRequired[TimestampMillis]
  """Order creation time, as milliseconds since epoch."""
  updateTime: NotRequired[TimestampMillis]
  """Order last-update time, as milliseconds since epoch."""


Response = list[UsdMFuturesForceOrder]


class ForceOrders(RpcEndpoint):
  """Query user's force liquidation and ADL orders. If `autoCloseType` is omitted, orders of both types are returned. If `startTime` is omitted, data within the 7 days before `endTime` can be queried."""

  async def force_orders(
    self,
    symbol: str | None = None,
    *,
    auto_close_type: Literal['LIQUIDATION', 'ADL'] | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> Response:
    """Query user's force liquidation and ADL orders. If `autoCloseType` is omitted, orders of both types are returned. If `startTime` is omitted, data within the 7 days before `endTime` can be queried.

    Args:
      symbol: Symbol to filter by.
      auto_close_type: Type of forced close to filter by. If omitted, orders of both types are returned.
      start_time: Query window start, as milliseconds since epoch.
      end_time: Query window end, as milliseconds since epoch.
      limit: Number of orders to return.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/rest-api/trade#users-force-orders)
    """
    request: Request = Request()
    if symbol is not None:
      request['symbol'] = symbol
    if auto_close_type is not None:
      request['autoCloseType'] = auto_close_type
    if start_time is not None:
      request['startTime'] = start_time
    if end_time is not None:
      request['endTime'] = end_time
    if limit is not None:
      request['limit'] = limit
    return await self.request(
      request,
      method='GET',
      path='/fapi/v1/forceOrders',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
