# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_core.validation import validator
from typed_binance.core import TimestampMillis, timestamp_millis
from typed_binance.core.endpoint.rpc import RpcEndpoint


class UsdMFuturesIncomeHistoryDownloadRequest(TypedDict):
  """A newly requested futures transaction (income) history export job's download id."""

  avgCostTimestampOfLast30d: NotRequired[int]
  """Average time taken to generate a download, over the past 30 days, in milliseconds."""
  downloadId: NotRequired[str]
  """Download id for this export job, used to poll for the download link."""


class IncomeAsyn(RpcEndpoint):
  """Request a download id for this account's futures transaction (income) history, generated as an asynchronous export job. The time between `startTime` and `endTime` cannot be longer than 1 year. Rate-limited to 5 requests per month, shared with the front-end download page."""

  async def income_asyn(
    self,
    *,
    start_time: TimestampMillis,
    end_time: TimestampMillis,
    validate: bool | None = None,
  ) -> UsdMFuturesIncomeHistoryDownloadRequest:
    """Request a download id for this account's futures transaction (income) history, generated as an asynchronous export job. The time between `startTime` and `endTime` cannot be longer than 1 year. Rate-limited to 5 requests per month, shared with the front-end download page.

    Args:
      start_time: Export window start, as milliseconds since epoch.
      end_time: Export window end, as milliseconds since epoch.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/rest-api/account#get-download-id-for-futures-transaction-history)
    """
    params: dict = {
      'startTime': timestamp_millis.dump(start_time),
      'endTime': timestamp_millis.dump(end_time),
    }
    _Response = UsdMFuturesIncomeHistoryDownloadRequest
    _validator = validator[_Response](_Response)
    return await self.authed_request(
      'GET',
      '/fapi/v1/income/asyn',
      params=params,
      validator=_validator,
      validate=validate,
    )
