# Generated by typed-dev — see CONTRIBUTING.md.
"""`GET /v5/pre-upgrade/order/history` — Get Pre-upgrade Order History."""

from typing_extensions import AsyncIterator, Literal, NotRequired, TypedDict
from typed_bybit.core import Endpoint, TimestampMillis, timestamp_millis, validator
from typed_bybit.types import CancelType, OrderStatus, RejectReason, StopOrderType


class PreUpgradeOrder(TypedDict):
  """One order placed before this account's upgrade to a Unified account."""

  orderId: str
  """Order ID."""
  orderLinkId: str
  """User-customised order ID."""
  blockTradeId: str
  """Paradigm block trade ID."""
  symbol: str
  """Symbol name."""
  price: str
  """Order price."""
  qty: str
  """Order quantity."""
  side: Literal['Buy', 'Sell']
  """Side."""
  isLeverage: str
  """Whether the order borrows. `"0"`: false, `"1"`: true."""
  positionIdx: Literal[0, 1, 2]
  """Position index for hedge-mode positions."""
  orderStatus: OrderStatus
  cancelType: CancelType
  rejectReason: RejectReason
  avgPrice: str
  """Average filled price. Empty string for orders without an average price."""
  leavesQty: str
  """Remaining quantity not executed."""
  leavesValue: str
  """Estimated value not executed."""
  cumExecQty: str
  """Cumulative executed quantity."""
  cumExecValue: str
  """Cumulative executed value."""
  cumExecFee: str
  """Cumulative executed trading fee."""
  timeInForce: Literal['GTC', 'IOC', 'FOK', 'PostOnly', 'RPI']
  """Time in force."""
  orderType: Literal['Market', 'Limit', 'UNKNOWN']
  """Order type."""
  stopOrderType: StopOrderType
  orderIv: str
  """Implied volatility."""
  triggerPrice: str
  """Trigger price. Activation price when `stopOrderType=TrailingStop`, otherwise the trigger price."""
  takeProfit: str
  """Take profit price."""
  stopLoss: str
  """Stop loss price."""
  tpTriggerBy: Literal['LastPrice', 'IndexPrice', 'MarkPrice', 'UNKNOWN']
  """Trigger price type for take profit."""
  slTriggerBy: Literal['LastPrice', 'IndexPrice', 'MarkPrice', 'UNKNOWN']
  """Trigger price type for stop loss."""
  triggerDirection: Literal[1, 2]
  """Direction that triggers the conditional order."""
  triggerBy: Literal['LastPrice', 'IndexPrice', 'MarkPrice', 'UNKNOWN']
  """Trigger price type."""
  lastPriceOnCreated: str
  """Last price when the order was placed. Not applicable to spot."""
  reduceOnly: bool
  """Whether the order can only reduce position size."""
  closeOnTrigger: bool
  """Whether the order is a close-on-trigger order."""
  placeType: Literal['iv', 'price', '']
  """Option-specific placement type."""
  smpType: Literal['None', 'CancelMaker', 'CancelTaker', 'CancelBoth']
  """Self-match prevention execution type."""
  smpGroup: str
  """SMP group ID. `"0"` when the UID has no group."""
  smpOrderId: str
  """Counterparty order ID that triggered this SMP execution."""
  createdTime: TimestampMillis
  """Order creation time."""
  updatedTime: TimestampMillis
  """Order last-update time."""


class PreUpgradeOrderListResult(TypedDict):
  """Page of matching pre-upgrade orders."""

  category: Literal['linear', 'inverse', 'option', 'spot']
  """Product type."""
  nextPageCursor: NotRequired[str]
  """Opaque cursor for the next page. Pass it back as `cursor`; an empty string means there are no further pages."""
  list: list[PreUpgradeOrder]
  """Matching pre-upgrade orders, newest first."""


adapter = validator[PreUpgradeOrderListResult](PreUpgradeOrderListResult)


class OrderList(Endpoint):
  """`Get Pre-upgrade Order History` — mixed into the router that owns `pre_upgrade.order_list`."""

  async def order_list(
    self,
    *,
    category: Literal['linear', 'inverse', 'option', 'spot'],
    symbol: str | None = None,
    base_coin: str | None = None,
    order_id: str | None = None,
    order_link_id: str | None = None,
    order_filter: Literal['Order', 'StopOrder'] | None = None,
    order_status: OrderStatus | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    limit: int | None = None,
    cursor: str | None = None,
    validate: bool | None = None,
  ) -> PreUpgradeOrderListResult:
    """Query orders placed before this account upgraded to a Unified account, from classic accounts and UTA 1.0. Data availability varies by product type.

    Args:
      category: Product type.
      symbol: Symbol name, uppercase only. Defaults to USDT settlement if omitted.
      base_coin: Base coin, uppercase only. Option only.
      order_id: Order ID.
      order_link_id: User-customised order ID.
      order_filter: Order kind to return. Omit to return every kind.
      order_status: Order status. Not supported for spot.
      start_time: Start of the queried range, as a millisecond timestamp. Must pair with `endTime`; range at most 7 days.
      end_time: End of the queried range, as a millisecond timestamp. Must pair with `startTime`; defaults to the most recent 7 days.
      limit: Number of orders per page. Range [1, 50]; defaults to 20.
      cursor: Opaque pagination cursor. Pass the `nextPageCursor` returned by the previous page; omit for the first page.
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/pre-upgrade/order-list)
    """
    params: dict = {
      'category': category,
    }
    if symbol is not None:
      params['symbol'] = symbol
    if base_coin is not None:
      params['baseCoin'] = base_coin
    if order_id is not None:
      params['orderId'] = order_id
    if order_link_id is not None:
      params['orderLinkId'] = order_link_id
    if order_filter is not None:
      params['orderFilter'] = order_filter
    if order_status is not None:
      params['orderStatus'] = order_status
    if start_time is not None:
      params['startTime'] = timestamp_millis.dump(start_time)
    if end_time is not None:
      params['endTime'] = timestamp_millis.dump(end_time)
    if limit is not None:
      params['limit'] = limit
    if cursor is not None:
      params['cursor'] = cursor
    r = await self.authed_request('GET', '/v5/pre-upgrade/order/history', params=params)
    return self.result(r, adapter, validate)

  async def order_list_paged(
    self,
    *,
    category: Literal['linear', 'inverse', 'option', 'spot'],
    symbol: str | None = None,
    base_coin: str | None = None,
    order_id: str | None = None,
    order_link_id: str | None = None,
    order_filter: Literal['Order', 'StopOrder'] | None = None,
    order_status: OrderStatus | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    limit: int | None = None,
    max_pages: int | None = None,
    validate: bool | None = None,
  ) -> AsyncIterator[PreUpgradeOrderListResult]:
    """Yield successive pages of `order_list`.

    Passes each page's token back as `cursor` and stops when a response carries no
    `nextPageCursor`, or after `max_pages` pages when one is given.
    """
    cursor: str | None = None
    pages = 0
    while True:
      response = await self.order_list(
        category=category,
        symbol=symbol,
        base_coin=base_coin,
        order_id=order_id,
        order_link_id=order_link_id,
        order_filter=order_filter,
        order_status=order_status,
        start_time=start_time,
        end_time=end_time,
        limit=limit,
        cursor=cursor,
        validate=validate,
      )
      yield response
      pages += 1
      if max_pages is not None and pages >= max_pages:
        break
      cursor = response.get('nextPageCursor') if response is not None else None
      if not cursor:
        break
