# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typed_core import PaginatedResponse
from typing_extensions import NotRequired, TypedDict
from typed_bitget.core import TimestampMillis
from typed_bitget.core.endpoint.rpc import RpcEndpoint
from typed_bitget.schemas import MixProductType


class MixAccountBill(TypedDict):
  """One ledger entry."""

  billId: str
  """Ledger entry ID."""
  symbol: str
  """Futures symbol this entry concerns."""
  amount: Decimal
  """Amount of this entry, signed."""
  fee: Decimal
  """Fee charged by this entry, if any."""
  feeByCoupon: str
  """Portion of the fee paid from coupon (bonus) balance."""
  businessType: str
  """Ledger entry type, e.g. a funding-fee or transfer category. Venue does not publish a closed set for this field."""
  coin: str
  """Coin this entry concerns."""
  balance: Decimal
  """Account balance after this entry was applied."""
  cTime: TimestampMillis
  """Entry time."""


class MixAccountBills(TypedDict):
  """One page of ledger entries."""

  bills: list[MixAccountBill] | None
  """Ledger entries, most recent first. Confirmed live as `null` (not an empty array) when there are no rows."""
  endId: str | None
  """Cursor: pass as `idLessThan` to fetch the next page. Confirmed live as `null` when there is no further page (e.g. the result set is empty)."""


class Request(TypedDict):
  productType: MixProductType
  symbol: NotRequired[str]
  """Restrict to one futures symbol, e.g. "BTCUSDT"."""
  coin: NotRequired[str]
  """Restrict to one coin, e.g. "USDT"."""
  businessType: NotRequired[str]
  """Restrict to one ledger entry type, e.g. a funding-fee or transfer category. Venue does not publish a closed set for this field."""
  idLessThan: NotRequired[str]
  """Pagination cursor: return entries with a bill ID before this one. Pass the last page's oldest `billId` to walk further back."""
  startTime: NotRequired[TimestampMillis]
  """Window lower bound, inclusive."""
  endTime: NotRequired[TimestampMillis]
  """Window upper bound, inclusive."""
  limit: NotRequired[int]
  """Rows per page. Range [1, 100]; defaults to 20."""


class Bills(RpcEndpoint):
  """List futures account ledger entries (funding, fees, transfers, PnL settlement, etc.), private."""

  def bills_paged(
    self,
    product_type: MixProductType,
    *,
    symbol: str | None = None,
    coin: str | None = None,
    business_type: str | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[MixAccountBill, str]:
    """List futures account ledger entries (funding, fees, transfers, PnL settlement, etc.), private.

    Paged variant of `bills`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      product_type:
      symbol: Restrict to one futures symbol, e.g. "BTCUSDT".
      coin: Restrict to one coin, e.g. "USDT".
      business_type: Restrict to one ledger entry type, e.g. a funding-fee or transfer category. Venue does not publish a closed set for this field.
      start_time: Window lower bound, inclusive.
      end_time: Window upper bound, inclusive.
      limit: Rows per page. Range [1, 100]; defaults to 20.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-account-bills)
    """

    async def next(id_less_than: str) -> tuple[list[MixAccountBill], str | None]:
      response = await self.bills(
        product_type,
        symbol=symbol,
        coin=coin,
        business_type=business_type,
        start_time=start_time,
        end_time=end_time,
        limit=limit,
        id_less_than=(id_less_than or None),
        validate=validate,
      )
      rows = response.get('bills')
      state = response.get('endId')
      return rows or [], state or None

    return PaginatedResponse('', next)

  async def bills(
    self,
    product_type: MixProductType,
    *,
    symbol: str | None = None,
    coin: str | None = None,
    business_type: str | None = None,
    id_less_than: str | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> MixAccountBills:
    """List futures account ledger entries (funding, fees, transfers, PnL settlement, etc.), private.

    Args:
      product_type:
      symbol: Restrict to one futures symbol, e.g. "BTCUSDT".
      coin: Restrict to one coin, e.g. "USDT".
      business_type: Restrict to one ledger entry type, e.g. a funding-fee or transfer category. Venue does not publish a closed set for this field.
      id_less_than: Pagination cursor: return entries with a bill ID before this one. Pass the last page's oldest `billId` to walk further back.
      start_time: Window lower bound, inclusive.
      end_time: Window upper bound, inclusive.
      limit: Rows per page. Range [1, 100]; defaults to 20.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#get-account-bills)
    """
    request: Request = Request(productType=product_type)
    if symbol is not None:
      request['symbol'] = symbol
    if coin is not None:
      request['coin'] = coin
    if business_type is not None:
      request['businessType'] = business_type
    if id_less_than is not None:
      request['idLessThan'] = id_less_than
    if start_time is not None:
      request['startTime'] = start_time
    if end_time is not None:
      request['endTime'] = end_time
    if limit is not None:
      request['limit'] = limit
    return await self.request(
      request,
      method='GET',
      path='/api/v2/mix/account/bill',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=MixAccountBills,
    )
