# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class Request(TypedDict):
  """Asset-mode update request."""

  productType: Literal['USDT-FUTURES', 'SUSDT-FUTURES']
  """Which futures product family this applies to."""
  assetMode: Literal['single', 'union']
  """Asset mode to switch to: `single` (margin held per-symbol) or `union` (margin shared across symbols)."""


Response = str


class SetAssetMode(RpcEndpoint):
  """Switch between single-asset and union (multi-asset) margin mode, private."""

  async def set_asset_mode(
    self,
    product_type: Literal['USDT-FUTURES', 'SUSDT-FUTURES'],
    *,
    asset_mode: Literal['single', 'union'],
    validate: bool | None = None,
  ) -> Response:
    """Switch between single-asset and union (multi-asset) margin mode, private.

    Args:
      product_type: Which futures product family this applies to.
      asset_mode: Asset mode to switch to: `single` (margin held per-symbol) or `union` (margin shared across symbols).
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-contract-account/classic-contract-account#set-usdt-m-futures-asset-mode)
    """
    return await self.request(
      Request(productType=product_type, assetMode=asset_mode),
      method='POST',
      path='/api/v2/mix/account/set-asset-mode',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
