# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core.util import StreamManager
from typing_extensions import Any, Literal, TypedDict
from typed_bybit.core import TimestampMillis
from typed_bybit.core.ws import StreamsEndpoint


class InsurancePoolBalance(TypedDict):
  """One insurance pool's balance, covering one or more symbols."""

  coin: str
  """Settlement coin the pool is denominated in."""
  symbols: str
  """Comma-separated symbols sharing this pool."""
  balance: str
  """Pool balance."""
  updateTime: TimestampMillis
  """Time this balance was last updated."""


InsurancePoolUpdates = list[InsurancePoolBalance]


class InsurancePool(StreamsEndpoint):
  """Subscribe to insurance pool balance changes for one settlement coin."""

  def insurance_pool(
    self,
    coin: Literal['USDT', 'USDC'],
    *,
    validate: bool | None = None,
  ) -> StreamManager[InsurancePoolUpdates, Any, Any]:
    """Subscribe to insurance pool balance changes for one settlement coin.

    Args:
      coin: Settlement coin the insurance pool is denominated in.
      validate: Override this call's pushed-payload validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://bybit-exchange.github.io/docs/v5/websocket/public/insurance)
    """
    return self.subscribe(
      f'insurance.{coin}',
      validate=validate,
      response_type=InsurancePoolUpdates,
    )
