# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import AsyncIterator, NotRequired, TypedDict
from typed_core.validation import validator
from binance.core.endpoint.rpc import RpcEndpoint


class WbethUnwrap(TypedDict):
  """One WBETH-to-BETH unwrap event."""

  time: NotRequired[int]
  """Millisecond epoch time the unwrap was requested."""
  fromAsset: NotRequired[str]
  """Asset unwrapped from (WBETH)."""
  fromAmount: NotRequired[str]
  """Amount of `fromAsset` unwrapped, as a decimal string."""
  toAsset: NotRequired[str]
  """Asset unwrapped into (BETH)."""
  toAmount: NotRequired[str]
  """Amount of `toAsset` received, as a decimal string."""
  exchangeRate: NotRequired[str]
  """Exchange rate applied to this unwrap, as a decimal string."""
  status: NotRequired[str]
  """Unwrap status."""


class WbethUnwrapHistoryPage(TypedDict):
  """One page of WBETH unwrap history."""

  rows: NotRequired[list[WbethUnwrap]]
  """Matching wbethunwrap records on this page."""
  total: NotRequired[int]
  """Total number of matching records across all pages."""


class UnwrapHistory(RpcEndpoint):
  """Query this account's WBETH-to-BETH unwrap history."""

  async def unwrap_history(
    self,
    *,
    start_time: int | None = None,
    end_time: int | None = None,
    current: int | None = None,
    size: int | None = None,
    validate: bool | None = None,
  ) -> WbethUnwrapHistoryPage:
    """Query this account's WBETH-to-BETH unwrap history.

    Args:
      start_time: Millisecond epoch start of the queried window. See the endpoint notes for the default window applied when this and `endTime` are omitted.
      end_time: Millisecond epoch end of the queried window. See the endpoint notes for the default window applied when this and `startTime` are omitted.
      current: Page index, starting from 1.
      size: Number of records to return per page.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#get-wbeth-unwrap-history)
    """
    params = {}
    if start_time is not None:
      params['startTime'] = start_time
    if end_time is not None:
      params['endTime'] = end_time
    if current is not None:
      params['current'] = current
    if size is not None:
      params['size'] = size
    _Response = WbethUnwrapHistoryPage
    _validator = validator[_Response](_Response)
    return await self.authed_request(
      'GET',
      '/sapi/v1/eth-staking/wbeth/history/unwrapHistory',
      params=params,
      validator=_validator,
      validate=validate,
    )

  async def unwrap_history_paged(
    self,
    *,
    start_time: int | None = None,
    end_time: int | None = None,
    size: int | None = None,
    max_pages: int | None = None,
    validate: bool | None = None,
  ) -> AsyncIterator[WbethUnwrapHistoryPage]:
    """Yield successive pages of `unwrap_history`.

    Requests `current` from 1 upwards and stops once it has covered the `total` items
    the response reports, or after `max_pages` pages when one is given.
    """
    current = 1
    pages = 0
    while True:
      response = await self.unwrap_history(
        start_time=start_time,
        end_time=end_time,
        size=size,
        current=current,
        validate=validate,
      )
      yield response
      pages += 1
      if max_pages is not None and pages >= max_pages:
        break
      total = response.get('total') if response is not None else None
      total = int(total) if total is not None else None
      if total is None or size is None or pages * size >= total:
        break
      current += 1
