# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_deribit.core.endpoint.rpc import RpcEndpoint
from typed_deribit.schemas import BookSummary


class Request(TypedDict):
  currency: Literal['BTC', 'ETH', 'USDC', 'USDT', 'EURR']
  """Currency, i.e `"BTC"`, `"ETH"`, `"USDC"`"""
  kind: NotRequired[Literal['future', 'option', 'spot', 'future_combo', 'option_combo']]
  """Instrument kind: `"future"`, `"option"`, `"spot"`, `"future_combo"`, `"option_combo"`"""


BookSummaryResponse = list[BookSummary]


class GetBookSummaryByCurrency(RpcEndpoint):
  """Retrieves summary information such as open interest, 24-hour volume, best bid/ask prices, last trade price, and other market statistics for all instruments in a given currency.

  Results can be filtered by instrument kind (future, option, etc.). This method provides a quick overview of market activity across all instruments for a currency.

  **Note:** For real-time updates, we recommend using the WebSocket subscription to `ticker.{instrument_name}.{interval}` instead of polling this endpoint."""

  async def get_book_summary_by_currency(
    self,
    currency: Literal['BTC', 'ETH', 'USDC', 'USDT', 'EURR'],
    *,
    kind: Literal['future', 'option', 'spot', 'future_combo', 'option_combo']
    | None = None,
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> BookSummaryResponse:
    """Retrieves summary information such as open interest, 24-hour volume, best bid/ask prices, last trade price, and other market statistics for all instruments in a given currency.

    Results can be filtered by instrument kind (future, option, etc.). This method provides a quick overview of market activity across all instruments for a currency.

    **Note:** For real-time updates, we recommend using the WebSocket subscription to `ticker.{instrument_name}.{interval}` instead of polling this endpoint.

    Args:
      currency: Currency, i.e `"BTC"`, `"ETH"`, `"USDC"`
      kind: Instrument kind: `"future"`, `"option"`, `"spot"`, `"future_combo"`, `"option_combo"`
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://docs.deribit.com/api-reference/market-data/public-get_book_summary_by_currency)
    """
    request: Request = Request(currency=currency)
    if kind is not None:
      request['kind'] = kind
    return await self.request(
      request,
      method='POST',
      path='public/get_book_summary_by_currency',
      meta={'public': True},
      validate=validate,
      transport=transport,
      request_type=Request,
      response_type=BookSummaryResponse,
    )
