# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_deribit.core.endpoint.rpc import RpcEndpoint
from typed_deribit.schemas import OrderBookSnapshot


class Request(TypedDict):
  instrument_id: int
  """The instrument ID for which to retrieve the order book, see [`public/get_instruments`](#public-get_instruments) to obtain instrument IDs."""
  depth: NotRequired[Literal[1, 5, 10, 20, 50, 100, 1000, 10000]]
  """The number of entries to return for bids and asks, maximum - `10000`."""


class GetOrderBookByInstrumentId(RpcEndpoint):
  """Retrieves the order book (bids and asks) for a given instrument ID, along with other market values such as best bid/ask prices, last trade price, mark price, and index price.

  This method is similar to `get_order_book` but uses instrument ID instead of instrument name. The order book depth can be controlled using the `depth` parameter, which accepts values from 1 to 10000."""

  async def get_order_book_by_instrument_id(
    self,
    instrument_id: int,
    *,
    depth: Literal[1, 5, 10, 20, 50, 100, 1000, 10000] | None = None,
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> OrderBookSnapshot:
    """Retrieves the order book (bids and asks) for a given instrument ID, along with other market values such as best bid/ask prices, last trade price, mark price, and index price.

    This method is similar to `get_order_book` but uses instrument ID instead of instrument name. The order book depth can be controlled using the `depth` parameter, which accepts values from 1 to 10000.

    Args:
      instrument_id: The instrument ID for which to retrieve the order book, see [`public/get_instruments`](#public-get_instruments) to obtain instrument IDs.
      depth: The number of entries to return for bids and asks, maximum - `10000`.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://docs.deribit.com/api-reference/market-data/public-get_order_book_by_instrument_id)
    """
    request: Request = Request(instrument_id=instrument_id)
    if depth is not None:
      request['depth'] = depth
    return await self.request(
      request,
      method='POST',
      path='public/get_order_book_by_instrument_id',
      meta={'public': True},
      validate=validate,
      transport=transport,
      request_type=Request,
      response_type=OrderBookSnapshot,
    )
