# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class IsolatedMarginMaxBorrowable(TypedDict):
  """Maximum borrowable amounts for one trading pair under isolated margin."""

  symbol: str
  """Trading pair."""
  baseCoin: str
  """Base coin of the pair."""
  baseCoinMaxBorrowAmount: Decimal
  """Maximum amount of the base coin currently borrowable. Changes in real time."""
  quoteCoin: str
  """Quote coin of the pair."""
  quoteCoinMaxBorrowAmount: Decimal
  """Maximum amount of the quote coin currently borrowable."""


class Request(TypedDict):
  symbol: str
  """Trading pair."""


class MaxBorrowable(RpcEndpoint):
  """Query the maximum amount currently borrowable under isolated margin. Rate limit: 10 requests/second per UID."""

  async def max_borrowable(
    self,
    symbol: str,
    *,
    validate: bool | None = None,
  ) -> IsolatedMarginMaxBorrowable:
    """Query the maximum amount currently borrowable under isolated margin. Rate limit: 10 requests/second per UID.

    Args:
      symbol: Trading pair.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-margin-isolated-account/classic-margin-isolated-account#get-isolated-max-borrowable)
    """
    return await self.request(
      Request(symbol=symbol),
      method='GET',
      path='/api/v2/margin/isolated/account/max-borrowable-amount',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=IsolatedMarginMaxBorrowable,
    )
