# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core.util import StreamManager
from typing_extensions import Any, Literal, TypedDict
from typed_deribit.core import TimestampMillis
from typed_deribit.core.endpoint.stream import StreamEndpoint


class VolatilityIndexUpdate(TypedDict):
  """Deribit Volatility Index (DVOL) update for the given `index_name`."""

  timestamp: TimestampMillis
  """The timestamp (milliseconds since the Unix epoch)."""
  volatility: float
  """Value of the volatility index."""
  index_name: Literal['btc_usd', 'eth_usd']
  """Index identifier supported for DVOL."""


class VolatilityIndex(StreamEndpoint):
  """Volatility index (DVOL) updates for the given `index_name`."""

  def volatility_index(
    self,
    index_name: Literal[
      'btc_usd',
      'eth_usd',
      'ada_usdc',
      'algo_usdc',
      'avax_usdc',
      'bch_usdc',
      'bnb_usdc',
      'btc_usdc',
      'btcdvol_usdc',
      'buidl_usdc',
      'doge_usdc',
      'dot_usdc',
      'eurr_usdc',
      'eth_usdc',
      'ethdvol_usdc',
      'link_usdc',
      'ltc_usdc',
      'near_usdc',
      'paxg_usdc',
      'shib_usdc',
      'sol_usdc',
      'steth_usdc',
      'ton_usdc',
      'trump_usdc',
      'trx_usdc',
      'uni_usdc',
      'usde_usdc',
      'usyc_usdc',
      'xrp_usdc',
      'btc_usdt',
      'eth_usdt',
      'eurr_usdt',
      'sol_usdt',
      'steth_usdt',
      'usdc_usdt',
      'usde_usdt',
      'btc_eurr',
      'btc_usde',
      'btc_usyc',
      'eth_btc',
      'eth_eurr',
      'eth_usde',
      'eth_usyc',
      'steth_eth',
      'paxg_btc',
      'drbfix-btc_usdc',
      'drbfix-eth_usdc',
    ],
    *,
    validate: bool | None = None,
  ) -> StreamManager[VolatilityIndexUpdate, Any, Any]:
    """Volatility index (DVOL) updates for the given `index_name`.

    Args:
      index_name: Index identifier, matching a (base) cryptocurrency to a quote currency.
      validate: Override this call's pushed-payload validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.deribit.com/subscriptions/market-data/deribit_volatility_indexindex_name)
    """
    return self.subscribe(
      f'deribit_volatility_index.{index_name}',
      meta={'public': True},
      validate=validate,
      response_type=VolatilityIndexUpdate,
    )
