# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typed_core.util import StreamManager
from typing_extensions import Any, Literal, TypedDict
from typed_kucoin.core import TimestampNanos, TimestampSeconds
from typed_kucoin.core.endpoint.stream import PublicStreamEndpoint


class KlineUpdate(TypedDict):
  """One K-Line update -- the unwrapped `data` field of the raw WebSocket frame (`SocketStreamClient.subscribe` extracts `data` before handing the stream to the caller; see `spec/core.md`'s WebSocket section)."""

  symbol: str
  """Trading pair symbol."""
  candles: tuple[TimestampSeconds, Decimal, Decimal, Decimal, Decimal, Decimal, Decimal]
  """The current (possibly still-forming) candle."""
  time: TimestampNanos
  """Unix nanoseconds when this push was generated -- not the candle's own time (see `candles[0]`)."""


class Klines(PublicStreamEndpoint):
  """Subscribe to K-Line (candle) updates for one symbol and interval, in real time -- the current, still-forming candle is pushed on every trade that updates it."""

  def klines(
    self,
    symbol: str,
    *,
    type: Literal[
      '1min',
      '3min',
      '15min',
      '30min',
      '1hour',
      '2hour',
      '4hour',
      '6hour',
      '8hour',
      '12hour',
      '1day',
      '1week',
    ],
    validate: bool | None = None,
  ) -> StreamManager[KlineUpdate, Any, Any]:
    """Subscribe to K-Line (candle) updates for one symbol and interval, in real time -- the current, still-forming candle is pushed on every trade that updates it.

    Args:
      symbol: Trading pair symbol, for example `BTC-USDT`.
      type: Candle interval.
      validate: Override this call's pushed-payload validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.kucoin.com/docs-new/3470071w0)
    """
    return self.subscribe(
      f'/market/candles:{symbol}_{type}',
      validate=validate,
      response_type=KlineUpdate,
    )
