# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import AsyncIterator, Literal, NotRequired, TypedDict
from typed_kucoin.core import TimestampMillis
from typed_kucoin.core.endpoint.rpc import RpcEndpoint


class AffiliateInvitedUser(TypedDict):
  """One invited user and their commission/milestone status."""

  uid: str
  """Invitee's UID."""
  nickName: str
  """Invitee's nickname. If no nickname exists, a desensitized phone number or email."""
  referralCode: str
  """The referral code the invitee registered with."""
  country: str
  """Invitee's country."""
  registrationTime: TimestampMillis
  """Invitee's registration time, Unix milliseconds."""
  completedKyc: bool
  """Whether the invitee has completed KYC."""
  completedFirstDeposit: bool
  """Whether the invitee has completed their first deposit."""
  completedFirstTrade: bool
  """Whether the invitee has completed their first trade."""
  past7dFees: Decimal
  """Fees the invitee generated in the past 7 days."""
  past7dCommission: Decimal
  """Commission this invitee contributed in the past 7 days."""
  totalCommission: Decimal
  """Total commission this invitee has contributed. KuCoin's own docs page mislabels this field's description as the affiliate's commission rate (the description that belongs to `myCommissionRate`) -- see notes."""
  myCommissionRate: Decimal
  """The affiliate's own commission rate against this invitee, percentage-based (e.g. `70` means 70%). KuCoin's own docs page mislabels this field's description as the invitee's cashback rate (the description that belongs to `cashbackRate`) -- see notes."""
  cashbackRate: Decimal
  """Invitee's cashback rate, percentage-based (e.g. `10` means 10%). KuCoin's own docs page mislabels this field's description as the invitee's total contributed commission (the description that belongs to `totalCommission`) -- see notes."""
  currency: Literal['USDT', 'USDC']
  """Denomination unit for the amounts above."""


class Request(TypedDict):
  userType: NotRequired[Literal['1', '2', '3']]
  """Filter by user type. KuCoin's docs list the allowed values without stating what each one means."""
  referralCode: NotRequired[str]
  """Restrict to invitees who registered with this referral code."""
  uid: NotRequired[str]
  """Restrict to one or more invitee UIDs, comma-separated."""
  registrationStartAt: NotRequired[TimestampMillis]
  """Restrict to invitees who registered at or after this Unix millisecond timestamp."""
  registrationEndAt: NotRequired[TimestampMillis]
  """Restrict to invitees who registered at or before this Unix millisecond timestamp."""
  page: NotRequired[int]
  """Page number."""
  pageSize: NotRequired[int]
  """Max number of records per page."""


class AffiliateInvitedPage(TypedDict):
  """One page of invited users."""

  currentPage: int
  """Current page number."""
  pageSize: int
  """Results per page, as applied."""
  totalNum: int
  """Total matching invitees."""
  totalPage: int
  """Total number of pages."""
  items: list[AffiliateInvitedUser]
  """Invited users on this page."""


Response = AffiliateInvitedPage | None


class Invited(RpcEndpoint):
  """Page through the users this affiliate account has invited, with KYC/deposit/trade milestones and commission-to-date per invitee."""

  async def invited_paged(
    self,
    user_type: Literal['1', '2', '3'] | None = None,
    *,
    referral_code: str | None = None,
    uid: str | None = None,
    registration_start_at: TimestampMillis | None = None,
    registration_end_at: TimestampMillis | None = None,
    page_size: int | None = None,
    max_pages: int | None = None,
    validate: bool | None = None,
  ) -> AsyncIterator[Response]:
    """Page through the users this affiliate account has invited, with KYC/deposit/trade milestones and commission-to-date per invitee.

    Paged variant of `invited`: Requests `page` from 1 upwards and stops once it has covered the `totalPage` pages the response reports, or after `max_pages` pages when one is given.

    Args:
      user_type: Filter by user type. KuCoin's docs list the allowed values without stating what each one means.
      referral_code: Restrict to invitees who registered with this referral code.
      uid: Restrict to one or more invitee UIDs, comma-separated.
      registration_start_at: Restrict to invitees who registered at or after this Unix millisecond timestamp.
      registration_end_at: Restrict to invitees who registered at or before this Unix millisecond timestamp.
      page_size: Max number of records per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      max_pages: Stop after this many pages, even if the walk is not done.

    References:
      - [Official docs](https://www.kucoin.com/docs-new/rest/affiliate/get-invited)
    """
    page = 1
    pages = 0
    while True:
      response = await self.invited(
        user_type,
        referral_code=referral_code,
        uid=uid,
        registration_start_at=registration_start_at,
        registration_end_at=registration_end_at,
        page_size=page_size,
        page=page,
        validate=validate,
      )
      yield response
      pages += 1
      if max_pages is not None and pages >= max_pages:
        break
      total = response.get('totalPage') if response is not None else None
      total = int(total) if total is not None else None
      if total is None or pages >= total:
        break
      page += 1

  async def invited(
    self,
    user_type: Literal['1', '2', '3'] | None = None,
    *,
    referral_code: str | None = None,
    uid: str | None = None,
    registration_start_at: TimestampMillis | None = None,
    registration_end_at: TimestampMillis | None = None,
    page: int | None = None,
    page_size: int | None = None,
    validate: bool | None = None,
  ) -> Response:
    """Page through the users this affiliate account has invited, with KYC/deposit/trade milestones and commission-to-date per invitee.

    Args:
      user_type: Filter by user type. KuCoin's docs list the allowed values without stating what each one means.
      referral_code: Restrict to invitees who registered with this referral code.
      uid: Restrict to one or more invitee UIDs, comma-separated.
      registration_start_at: Restrict to invitees who registered at or after this Unix millisecond timestamp.
      registration_end_at: Restrict to invitees who registered at or before this Unix millisecond timestamp.
      page: Page number.
      page_size: Max number of records per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.kucoin.com/docs-new/rest/affiliate/get-invited)
    """
    request: Request = Request()
    if user_type is not None:
      request['userType'] = user_type
    if referral_code is not None:
      request['referralCode'] = referral_code
    if uid is not None:
      request['uid'] = uid
    if registration_start_at is not None:
      request['registrationStartAt'] = registration_start_at
    if registration_end_at is not None:
      request['registrationEndAt'] = registration_end_at
    if page is not None:
      request['page'] = page
    if page_size is not None:
      request['pageSize'] = page_size
    return await self.request(
      request,
      method='GET',
      path='/api/v2/affiliate/queryInvitees',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
