# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import TypedDict
from typed_bybit.core.http import RpcEndpoint


class Request(TypedDict):
  coin: str
  """Coin name."""
  chainType: str
  """Chain identifier."""
  subMemberId: str
  """Sub-account UID."""


class SubDepositAddressChain(TypedDict):
  """Deposit address for one chain."""

  chainType: str
  """Human-readable chain name."""
  addressDeposit: str
  """Deposit address on this chain."""
  tagDeposit: str
  """Deposit tag/memo, when this chain uses one; empty otherwise."""
  chain: str
  """Chain identifier."""
  batchReleaseLimit: str
  """Deposit limit for this coin on this chain; `-1` means unlimited."""
  contractAddress: str
  """Coin's contract address on this chain, last 6 characters only; empty when there is none."""


class SubDepositAddressResult(TypedDict):
  """Deposit address for one coin, per chain, on one sub-account."""

  coin: str
  """Coin name."""
  chains: list[SubDepositAddressChain]
  """One entry per matching chain."""


class SubAddress(RpcEndpoint):
  """Query a sub-account's deposit address for one coin on one chain, using the master account's API key."""

  async def sub_address(
    self,
    *,
    coin: str,
    chain_type: str,
    sub_member_id: str,
    validate: bool | None = None,
  ) -> SubDepositAddressResult:
    """Query a sub-account's deposit address for one coin on one chain, using the master account's API key.

    Args:
      coin: Coin name.
      chain_type: Chain identifier.
      sub_member_id: Sub-account UID.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://bybit-exchange.github.io/docs/v5/asset/deposit/sub-deposit-addr)
    """
    return await self.request(
      Request(coin=coin, chainType=chain_type, subMemberId=sub_member_id),
      method='GET',
      path='/v5/asset/deposit/query-sub-member-address',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=SubDepositAddressResult,
    )
