# Generated by typed-dev — see CONTRIBUTING.md.
"""`private/get_broker_trade_requests` — `private/get_broker_trade_requests`."""

from typing_extensions import Literal, NotRequired, TypedDict
from typed_deribit.core import RpcEndpoint, TimestampMillis
from typed_core.validation import validator


class BrokerTradeRequestLeg(TypedDict):
  """One leg of a broker block trade request."""

  amount: NotRequired[float]
  """Trade amount."""
  direction: NotRequired[Literal['buy', 'sell']]
  """Trade direction."""
  price: NotRequired[float]
  """Trade price."""
  instrument_name: NotRequired[str]
  """Name of the traded instrument."""


class BrokerTradeRequestPartyMaker(TypedDict):
  """The maker side of the request."""

  state: NotRequired[Literal['initial', 'approved', 'rejected']]
  """State of the request from this side."""
  client_id: NotRequired[int]
  """ID of a client; available to broker. Represents a group of users under a common name."""
  user_id: NotRequired[str]
  """Obscured user id of this side."""
  client_name: NotRequired[str]
  """Name of the client; available to broker."""
  client_link_name: NotRequired[str]
  """Name of the linked user within the client; available to broker."""
  client_link_id: NotRequired[int]
  """ID assigned to a single user in a client; available to broker."""


class BrokerTradeRequestPartyTaker(TypedDict):
  """The taker side of the request."""

  state: NotRequired[Literal['initial', 'approved', 'rejected']]
  """State of the request from this side."""
  client_id: NotRequired[int]
  """ID of a client; available to broker. Represents a group of users under a common name."""
  user_id: NotRequired[str]
  """Obscured user id of this side."""
  client_name: NotRequired[str]
  """Name of the client; available to broker."""
  client_link_name: NotRequired[str]
  """Name of the linked user within the client; available to broker."""
  client_link_id: NotRequired[int]
  """ID assigned to a single user in a client; available to broker."""


class BrokerTradeRequest(TypedDict):
  """One broker block trade request."""

  timestamp: NotRequired[TimestampMillis]
  """Timestamp of the broker block trade request (milliseconds since the UNIX epoch)."""
  state: NotRequired[str]
  """State of the broker block trade request."""
  trades: NotRequired[list[BrokerTradeRequestLeg]]
  """The legs of the broker block trade request."""
  maker: NotRequired[BrokerTradeRequestPartyMaker]
  taker: NotRequired[BrokerTradeRequestPartyTaker]
  nonce: NotRequired[str]
  """Nonce for approving or rejecting the broker block trade request."""


class BrokerTradeRequests(TypedDict):
  """Broker block trade requests for the broker account."""

  requests: list[BrokerTradeRequest]
  """Pending, declined, and expired broker block trade requests."""


validate_get_broker_trade_requests = validator[BrokerTradeRequests](BrokerTradeRequests)


class GetBrokerTradeRequests(RpcEndpoint):
  """`private/get_broker_trade_requests`."""

  async def get_broker_trade_requests(
    self,
    *,
    validate: bool | None = None,
  ) -> BrokerTradeRequests:
    """Broker Method. Provides a list of broker block trade requests including pending approvals, declined trades, and expired trades. `timestamp` and `nonce` received in response can be used to approve or reject the pending broker block trade. This method takes no parameters.

    Scope: `block_trade:read`.

    Args:
      validate: Validate the response against the generated schema.

    References:
      - [Deribit API docs](https://docs.deribit.com/api-reference/block-trade/private-get_broker_trade_requests)
    """
    return await self.authed_request(
      'private/get_broker_trade_requests',
      validator=validate_get_broker_trade_requests,
      validate=validate,
    )
