# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_bybit.core.http import RpcEndpoint


class Request(TypedDict):
  loanCurrency: NotRequired[str]
  """Coin name."""


class UnpaidLoan(TypedDict):
  """One coin's ongoing flexible loan."""

  hourlyInterestRate: str
  """Current hourly interest rate."""
  loanCurrency: str
  """Borrowed coin."""
  totalDebt: str
  """Unpaid principal and interest, combined."""
  unpaidAmount: str
  """Unpaid principal."""
  unpaidInterest: str
  """Unpaid interest."""


class UnpaidLoanOrderResult(TypedDict):
  """Ongoing flexible loans."""

  list: list[UnpaidLoan]
  """Ongoing loans, one per borrowed coin."""


class UnpaidLoanOrder(RpcEndpoint):
  """Get this account's ongoing (unpaid) flexible loans."""

  async def unpaid_loan_order(
    self,
    loan_currency: str | None = None,
    *,
    validate: bool | None = None,
  ) -> UnpaidLoanOrderResult:
    """Get this account's ongoing (unpaid) flexible loans.

    Args:
      loan_currency: Coin name.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://bybit-exchange.github.io/docs/v5/new-crypto-loan/flexible/unpaid-loan-order)
    """
    request: Request = Request()
    if loan_currency is not None:
      request['loanCurrency'] = loan_currency
    return await self.request(
      request,
      method='GET',
      path='/v5/crypto-loan-flexible/ongoing-coin',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=UnpaidLoanOrderResult,
    )
