# Generated by typed-dev — see CONTRIBUTING.md.
from dataclasses import dataclass
from typed_coinbase.core.endpoint.rpc import RpcClient
from .list import List


@dataclass(frozen=True, kw_only=True)
class ExchangeRates(List):
  """`exchange_rates` endpoints."""

  @classmethod
  def new(cls, *, client: RpcClient) -> 'ExchangeRates':
    return cls(client=client)
