# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Any, AsyncIterator, Literal, NotRequired, TypedDict
from typed_etherscan.core.rest import RpcEndpoint


class MinedBlock(TypedDict):
  """Result item returned by Etherscan."""

  blockNumber: NotRequired[Any]
  """blockNumber field returned by Etherscan."""
  timeStamp: NotRequired[Any]
  """timeStamp field returned by Etherscan."""
  blockReward: NotRequired[Any]
  """blockReward field returned by Etherscan."""


class Request(TypedDict):
  chainid: NotRequired[str]
  """Chain ID of the Etherscan-supported network to query, such as `1` for Ethereum mainnet."""
  module: Literal['account']
  """Fixed Etherscan API module selector for this operation; use `account`."""
  action: Literal['getminedblocks']
  """Fixed Etherscan API action selector for this operation; use `getminedblocks`."""
  address: str
  """Validator or miner address whose produced blocks should be returned."""
  blocktype: NotRequired[str]
  """Type of blocks to return for the validator address, such as blocks or uncles."""
  page: NotRequired[int]
  """Page number for paginated results, starting at 1."""
  offset: NotRequired[int]
  """Maximum number of records to return per page."""


class EtherscanResponse(TypedDict):
  status: Literal['0', '1']
  """Etherscan status code."""
  message: str
  """Etherscan status message."""
  result: list[MinedBlock]
  """List of result objects returned by Etherscan."""


class MinedBlocks(RpcEndpoint):
  """Get blocks or uncles validated by a specific address."""

  async def mined_blocks_paged(
    self,
    *,
    chainid: str | None = None,
    module: Literal['account'] = 'account',
    action: Literal['getminedblocks'] = 'getminedblocks',
    address: str,
    blocktype: str | None = None,
    offset: int | None = None,
    max_pages: int | None = None,
    validate: bool | None = None,
  ) -> AsyncIterator[EtherscanResponse]:
    """Get blocks or uncles validated by a specific address.

    Paged variant of `mined_blocks`: Requests `page` from 1 upwards and stops on the first page shorter than `offset`, or after `max_pages` pages when one is given.

    Args:
      chainid: Chain ID of the Etherscan-supported network to query, such as `1` for Ethereum mainnet.
      module: Fixed Etherscan API module selector for this operation; use `account`.
      action: Fixed Etherscan API action selector for this operation; use `getminedblocks`.
      address: Validator or miner address whose produced blocks should be returned.
      blocktype: Type of blocks to return for the validator address, such as blocks or uncles.
      offset: Maximum number of records to return per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      max_pages: Stop after this many pages, even if the walk is not done.

    References:
      - [Official docs](https://docs.etherscan.io/api-reference/endpoint/getminedblocks)
    """
    page = 1
    pages = 0
    while True:
      response = await self.mined_blocks(
        chainid=chainid,
        module=module,
        action=action,
        address=address,
        blocktype=blocktype,
        offset=offset,
        page=page,
        validate=validate,
      )
      yield response
      pages += 1
      if max_pages is not None and pages >= max_pages:
        break
      rows = response.get('result') if response is not None else None
      if not rows or (offset is not None and len(rows) < offset):
        break
      page += 1

  async def mined_blocks(
    self,
    *,
    chainid: str | None = None,
    module: Literal['account'] = 'account',
    action: Literal['getminedblocks'] = 'getminedblocks',
    address: str,
    blocktype: str | None = None,
    page: int | None = None,
    offset: int | None = None,
    validate: bool | None = None,
  ) -> EtherscanResponse:
    """Get blocks or uncles validated by a specific address.

    Args:
      chainid: Chain ID of the Etherscan-supported network to query, such as `1` for Ethereum mainnet.
      module: Fixed Etherscan API module selector for this operation; use `account`.
      action: Fixed Etherscan API action selector for this operation; use `getminedblocks`.
      address: Validator or miner address whose produced blocks should be returned.
      blocktype: Type of blocks to return for the validator address, such as blocks or uncles.
      page: Page number for paginated results, starting at 1.
      offset: Maximum number of records to return per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.etherscan.io/api-reference/endpoint/getminedblocks)
    """
    request: Request = Request(module=module, action=action, address=address)
    if chainid is not None:
      request['chainid'] = chainid
    if blocktype is not None:
      request['blocktype'] = blocktype
    if page is not None:
      request['page'] = page
    if offset is not None:
      request['offset'] = offset
    return await self.request(
      request,
      method='GET',
      path='/v2/api',
      meta={'credentials': True},
      validate=validate,
      request_type=Request,
      response_type=EtherscanResponse,
    )
