# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/crypto/ed25519/keys.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "PrivKey",
    "PubKey",
)

from dataclasses import dataclass

import betterproto2

from dydx.protos.message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class PrivKey(betterproto2.Message):
    """
    PrivKey defines a ed25519 private key.
    NOTE: ed25519 keys must not be used in SDK apps except in a tendermint validator context.
    """

    key: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)


default_message_pool.register_message("cosmos.crypto.ed25519", "PrivKey", PrivKey)


@dataclass(eq=False, repr=False)
class PubKey(betterproto2.Message):
    """
    PubKey is an ed25519 public key for handling Tendermint keys in SDK.
    It's needed for Any serialization and SDK compatibility.
    It must not be used in a non Tendermint key context because it doesn't implement
    ADR-28. Nevertheless, you will like to use ed25519 in app user level
    then you must create a new proto message and follow ADR-28 for Address construction.
    """

    key: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)


default_message_pool.register_message("cosmos.crypto.ed25519", "PubKey", PubKey)
