# Generated by typed-dev — see CONTRIBUTING.md.
"""`classic.broker.subaccount.create` -- generated from `spec/endpoints/`."""

from typed_core.validation import TypedDict, validator
from typed_bitget.core import TimestampMillis
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class CreateSubaccountRequest(TypedDict):
  """Broker sub-account to create."""

  subaccountName: str
  """Name for the new sub-account."""
  label: str
  """Label for the new sub-account."""


class CreatedSubaccount(TypedDict):
  """A broker sub-account created successfully."""

  subUid: str
  """Uid assigned to the new sub-account."""
  subaccountName: str
  """The sub-account name."""
  status: str
  """Sub-account status. Closed set not confirmed for this response field; see notes."""
  permList: list[str]
  """Permissions granted to the sub-account."""
  label: str
  """Sub-account label."""
  cTime: TimestampMillis
  """Creation time, Unix millisecond timestamp."""


class Create(RpcEndpoint):
  """`classic.broker.subaccount.create`."""

  async def create(
    self,
    create_subaccount_request: CreateSubaccountRequest,
    *,
    validate: bool | None = None,
  ) -> CreatedSubaccount:
    """Create a new broker sub-account.

    Args:
      create_subaccount_request: Broker sub-account to create.

    References:
      - [Official docs](https://www.bitget.com/api-doc/classic/broker/subaccount/Create-Subaccount)
    """
    return await self.authed_request(
      'POST',
      '/api/v2/broker/account/create-subaccount',
      json=create_subaccount_request,
      validator=validator(CreatedSubaccount),
      validate=validate,
    )
