# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_binance.core.endpoint.ws_rpc import WsRpcEndpoint
from typed_binance.schemas import TickerTradingDayFull, TickerTradingDayMini


class Request(TypedDict):
  """Request parameters."""

  symbol: NotRequired[str]
  """Single symbol to query. Either `symbol` or `symbols` must be provided; the two cannot be combined."""
  symbols: NotRequired[list[str]]
  """Symbols to query, e.g. ["BTCUSDT","BNBUSDT"]. Either `symbol` or `symbols` must be provided; the two cannot be combined."""
  timeZone: NotRequired[str]
  """Timezone the trading day is defined in, as hours and minutes (e.g. '-1:00', '05:45') or just hours (e.g. '0', '8')."""
  type: NotRequired[Literal['FULL', 'MINI']]
  """Response field set."""
  symbolStatus: NotRequired[Literal['TRADING', 'HALT', 'BREAK']]
  """Filter for symbols with this trading status. For a single symbol, a status mismatch returns error -1220 SYMBOL_DOES_NOT_MATCH_STATUS; for multiple symbols, non-matching ones are simply excluded from the response."""


Response = (
  TickerTradingDayFull
  | list[TickerTradingDayFull]
  | TickerTradingDayMini
  | list[TickerTradingDayMini]
)


class TickerTradingDay(WsRpcEndpoint):
  """Price change statistics for a trading day."""

  async def ticker_trading_day(
    self,
    *,
    symbol: str | None = None,
    symbols: list[str] | None = None,
    time_zone: str | None = None,
    type: Literal['FULL', 'MINI'] | None = None,
    symbol_status: Literal['TRADING', 'HALT', 'BREAK'] | None = None,
    validate: bool | None = None,
  ) -> Response:
    """Price change statistics for a trading day.

    Args:
      symbol: Single symbol to query. Either `symbol` or `symbols` must be provided; the two cannot be combined.
      symbols: Symbols to query, e.g. ["BTCUSDT","BNBUSDT"]. Either `symbol` or `symbols` must be provided; the two cannot be combined.
      time_zone: Timezone the trading day is defined in, as hours and minutes (e.g. '-1:00', '05:45') or just hours (e.g. '0', '8').
      type: Response field set.
      symbol_status: Filter for symbols with this trading status. For a single symbol, a status mismatch returns error -1220 SYMBOL_DOES_NOT_MATCH_STATUS; for multiple symbols, non-matching ones are simply excluded from the response.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md#trading-day-ticker)
    """
    request: Request = Request()
    if symbol is not None:
      request['symbol'] = symbol
    if symbols is not None:
      request['symbols'] = symbols
    if time_zone is not None:
      request['timeZone'] = time_zone
    if type is not None:
      request['type'] = type
    if symbol_status is not None:
      request['symbolStatus'] = symbol_status
    return await self.request(
      request,
      path='ticker.tradingDay',
      meta={'security': 'NONE', 'signed': False},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
