# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import NotRequired, TypedDict
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class QuotedPrice(TypedDict):
  """A quoted Convert price, request-for-quote (RFQ) style: valid for a short window and consumed by the trade endpoint."""

  fromCoin: str
  """Coin converted from."""
  fromCoinSize: Decimal
  """Quantity of `fromCoin` being exchanged."""
  toCoin: str
  """Coin converted to."""
  toCoinSize: Decimal
  """Resulting quantity of `toCoin`."""
  cnvtPrice: Decimal
  """Swap price: `fromCoin` price divided by `toCoin` price."""
  fee: Decimal
  """Transaction fee."""
  traceId: str
  """RFQ id for this quoted price; pass it to the trade endpoint to execute this quote."""


class Request(TypedDict):
  fromCoin: str
  """Coin to convert from, e.g. `"USDT"`."""
  fromCoinSize: NotRequired[Decimal]
  """Amount of `fromCoin` to convert. Only one of `fromCoinSize`/`toCoinSize` is allowed."""
  toCoin: str
  """Coin to convert to, e.g. `"ETH"`."""
  toCoinSize: NotRequired[Decimal]
  """Desired amount of `toCoin` to receive. Only one of `fromCoinSize`/`toCoinSize` is allowed."""


class QuotedPriceEndpoint(RpcEndpoint):
  """Get a quoted conversion price (RFQ) for a Convert (instant-swap) trade. Exactly one of `fromCoinSize`/`toCoinSize` is given; the quoted price and `traceId` this returns are then passed to the trade endpoint to execute the swap."""

  async def quoted_price(
    self,
    *,
    from_coin: str,
    from_coin_size: Decimal | None = None,
    to_coin: str,
    to_coin_size: Decimal | None = None,
    validate: bool | None = None,
  ) -> QuotedPrice:
    """Get a quoted conversion price (RFQ) for a Convert (instant-swap) trade. Exactly one of `fromCoinSize`/`toCoinSize` is given; the quoted price and `traceId` this returns are then passed to the trade endpoint to execute the swap.

    Args:
      from_coin: Coin to convert from, e.g. `"USDT"`.
      from_coin_size: Amount of `fromCoin` to convert. Only one of `fromCoinSize`/`toCoinSize` is allowed.
      to_coin: Coin to convert to, e.g. `"ETH"`.
      to_coin_size: Desired amount of `toCoin` to receive. Only one of `fromCoinSize`/`toCoinSize` is allowed.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-spot-convert/classic-spot-convert#get-quoted-price)
    """
    request: Request = Request(fromCoin=from_coin, toCoin=to_coin)
    if from_coin_size is not None:
      request['fromCoinSize'] = from_coin_size
    if to_coin_size is not None:
      request['toCoinSize'] = to_coin_size
    return await self.request(
      request,
      method='GET',
      path='/api/v2/convert/quoted-price',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=QuotedPrice,
    )
