# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core import PaginatedResponse
from typed_core.grpc import GrpcEndpoint, wrap_exceptions
from typed_dydx.protos.cosmos.bank.v1beta1 import (
  QuerySpendableBalancesRequest,
  QuerySpendableBalancesResponse,
  QueryStub,
)
from typed_dydx.protos.cosmos.base.query.v1beta1 import PageRequest
from typed_dydx.protos.cosmos.base.v1beta1 import Coin


class SpendableBalances(GrpcEndpoint):
  """Query the spendable balance of all coins for a single account address."""

  def spendable_balances_paged(
    self,
    address: str,
    *,
    limit: int | None = None,
  ) -> PaginatedResponse[Coin, bytes]:
    """Query the spendable balance of all coins for a single account address.

    Paged variant of `spendable_balances`: Awaitable (flattens every page) or async-iterable (one page at a time).

    References:
      - [Official docs](https://docs.cosmos.network/main/build/modules/bank)
    """

    async def next(key: bytes) -> tuple[list[Coin], bytes | None]:
      response = await self.spendable_balances(
        address,
        pagination=PageRequest(key=key, limit=(limit if limit is not None else 0)),
      )
      rows = response.balances
      state_0 = response.pagination
      state = getattr(state_0, 'next_key', None) if state_0 is not None else None
      return rows or [], state or None

    return PaginatedResponse(b'', next)

  @wrap_exceptions
  async def spendable_balances(
    self,
    address: str,
    *,
    pagination: PageRequest | None = None,
  ) -> QuerySpendableBalancesResponse:
    """Query the spendable balance of all coins for a single account address.

    References:
      - [Official docs](https://docs.cosmos.network/main/build/modules/bank)
    """
    return await QueryStub(self.channel).spendable_balances(
      QuerySpendableBalancesRequest(address=address, pagination=pagination)
    )
