# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core.grpc import GrpcEndpoint, wrap_exceptions
from typed_dydx.protos.cosmos.bank.v1beta1 import (
  QueryStub,
  QuerySupplyOfRequest,
  QuerySupplyOfResponse,
)


class SupplyOf(GrpcEndpoint):
  """Query the supply of a single coin denomination."""

  @wrap_exceptions
  async def supply_of(self, denom: str) -> QuerySupplyOfResponse:
    """Query the supply of a single coin denomination.

    References:
      - [Official docs](https://docs.cosmos.network/main/build/modules/bank)
    """
    return await QueryStub(self.channel).supply_of(QuerySupplyOfRequest(denom=denom))
