# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Any, Literal, TypedDict
from typed_bybit.core.http import RpcEndpoint


FixedSavingSetAutoInvestResult = dict[str, Any]


class Request(TypedDict):
  """Fixed saving position auto-reinvest change."""

  productId: str
  """Product identifier."""
  category: Literal['FixedTermSaving', 'FundPool', 'FundPoolPremium']
  """Product sub-type."""
  positionId: str
  """Position identifier."""
  status: Literal['Enable', 'Disable']
  """Desired auto-reinvest setting."""


class SetAutoInvest(RpcEndpoint):
  """Toggle auto-reinvestment on a fixed-term saving position. Requires API key "Earn" permission."""

  async def set_auto_invest(
    self,
    *,
    product_id: str,
    category: Literal['FixedTermSaving', 'FundPool', 'FundPoolPremium'],
    position_id: str,
    status: Literal['Enable', 'Disable'],
    validate: bool | None = None,
  ) -> FixedSavingSetAutoInvestResult:
    """Toggle auto-reinvestment on a fixed-term saving position. Requires API key "Earn" permission.

    Args:
      product_id: Product identifier.
      category: Product sub-type.
      position_id: Position identifier.
      status: Desired auto-reinvest setting.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://bybit-exchange.github.io/docs/v5/finance/earn/fixed-saving/set-auto-invest)
    """
    return await self.request(
      Request(
        productId=product_id, category=category, positionId=position_id, status=status
      ),
      method='POST',
      path='/v5/earn/fixed-term/position/auto-invest',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=FixedSavingSetAutoInvestResult,
    )
