# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dydxprotocol/indexer/indexer_manager/event.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "IndexerEventsStoreValue",
    "IndexerTendermintBlock",
    "IndexerTendermintEvent",
    "IndexerTendermintEventBlockEvent",
    "IndexerTendermintEventWrapper",
)

import datetime
from dataclasses import dataclass

import betterproto2

from typed_dydx.protos.message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class IndexerTendermintEventBlockEvent(betterproto2.Enum):
    """
    enum to specify that the IndexerTendermintEvent is a block event.
    """

    UNSPECIFIED = 0
    """
    Default value. This value is invalid and unused.
    """

    BEGIN_BLOCK = 1
    """
    BLOCK_EVENT_BEGIN_BLOCK indicates that the event was generated during
    BeginBlock.
    """

    END_BLOCK = 2
    """
    BLOCK_EVENT_END_BLOCK indicates that the event was generated during
    EndBlock.
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "BLOCK_EVENT_UNSPECIFIED",
            1: "BLOCK_EVENT_BEGIN_BLOCK",
            2: "BLOCK_EVENT_END_BLOCK",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "BLOCK_EVENT_UNSPECIFIED": 0,
            "BLOCK_EVENT_BEGIN_BLOCK": 1,
            "BLOCK_EVENT_END_BLOCK": 2,
        }


@dataclass(eq=False, repr=False)
class IndexerEventsStoreValue(betterproto2.Message):
    """
    IndexerEventsStoreValue represents the type of the value of the
    `IndexerEventsStore` in state.
    """

    events: "list[IndexerTendermintEventWrapper]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "dydxprotocol.indexer.indexer_manager",
    "IndexerEventsStoreValue",
    IndexerEventsStoreValue,
)


@dataclass(eq=False, repr=False)
class IndexerTendermintBlock(betterproto2.Message):
    """
    IndexerTendermintBlock contains all the events for the block along with
    metadata for the block height, timestamp of the block and a list of all the
    hashes of the transactions within the block. The transaction hashes follow
    the ordering of the transactions as they appear within the block.
    """

    height: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    time: "datetime.datetime | None" = betterproto2.field(
        2,
        betterproto2.TYPE_MESSAGE,
        unwrap=lambda: ___google__protobuf__.Timestamp,
        optional=True,
    )

    events: "list[IndexerTendermintEvent]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    tx_hashes: "list[str]" = betterproto2.field(
        4, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message(
    "dydxprotocol.indexer.indexer_manager",
    "IndexerTendermintBlock",
    IndexerTendermintBlock,
)


@dataclass(eq=False, repr=False)
class IndexerTendermintEvent(betterproto2.Message):
    """
    IndexerTendermintEvent contains the base64 encoded event proto emitted from
    the dYdX application as well as additional metadata to determine the ordering
    of the event within the block and the subtype of the event.

    Oneofs:
        - ordering_within_block: ordering_within_block is either the transaction index or a boolean
            indicating the event was generated during processing the block rather than
            any specific transaction e.g. during FinalizeBlock.
    """

    subtype: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    Subtype of the event e.g. "order_fill", "subaccount_update", etc.
    """

    transaction_index: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_UINT32, optional=True, group="ordering_within_block"
    )

    block_event: "IndexerTendermintEventBlockEvent | None" = betterproto2.field(
        4, betterproto2.TYPE_ENUM, optional=True, group="ordering_within_block"
    )

    event_index: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    """
    Index of the event within the list of events that happened either during a
    transaction or during processing of a block.
    TODO(DEC-537): Deprecate this field because events are already ordered.
    """

    version: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)
    """
    Version of the event.
    """

    data_bytes: "bytes" = betterproto2.field(7, betterproto2.TYPE_BYTES)
    """
    Tendermint event bytes.
    """


default_message_pool.register_message(
    "dydxprotocol.indexer.indexer_manager",
    "IndexerTendermintEvent",
    IndexerTendermintEvent,
)


@dataclass(eq=False, repr=False)
class IndexerTendermintEventWrapper(betterproto2.Message):
    """
    IndexerTendermintEventWrapper is a wrapper around IndexerTendermintEvent,
    with an additional txn_hash field.
    """

    event: "IndexerTendermintEvent | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    txn_hash: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "dydxprotocol.indexer.indexer_manager",
    "IndexerTendermintEventWrapper",
    IndexerTendermintEventWrapper,
)


from ....google import protobuf as ___google__protobuf__
