# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_binance.core.endpoint.rpc import RpcEndpoint


class Request(TypedDict):
  """Request parameters."""

  orderId: int
  """Loan order ID to repay."""
  amount: float
  """Amount to repay."""


class VipLoanRepayResult(TypedDict):
  """The result of a VIP loan repayment."""

  loanCoin: NotRequired[str]
  """Borrowed coin."""
  repayAmount: NotRequired[str]
  """Amount repaid."""
  remainingPrincipal: NotRequired[str]
  """Remaining unpaid principal after this repayment."""
  remainingInterest: NotRequired[str]
  """Remaining unpaid interest after this repayment."""
  collateralCoin: NotRequired[str]
  """Collateral coin(s), comma-separated."""
  currentLTV: NotRequired[str]
  """Current loan-to-value ratio after this repayment, as a decimal string."""
  repayStatus: NotRequired[Literal['Repaid', 'Repaying', 'Failed']]
  """Repayment status."""


class Repay(RpcEndpoint):
  """Repay an existing VIP loan order. Available to VIP users only."""

  async def repay(
    self,
    order_id: int,
    *,
    amount: float,
    validate: bool | None = None,
  ) -> VipLoanRepayResult:
    """Repay an existing VIP loan order. Available to VIP users only.

    Args:
      order_id: Loan order ID to repay.
      amount: Amount to repay.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/investment-and-services-vip-loan/api/rest-api/trade#vip-loan-repay)
    """
    return await self.request(
      Request(orderId=order_id, amount=amount),
      method='POST',
      path='/sapi/v1/loan/vip/repay',
      meta={'security': 'TRADE', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=VipLoanRepayResult,
    )
