# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal
from typed_deribit.core.endpoint.rpc import RpcEndpoint
from typed_deribit.schemas import (
  LimitOrderRequest,
  MarketOrderRequest,
  OrderTradesResult,
  StopLimitOrderRequest,
  StopMarketOrderRequest,
  TrailingStopOrderRequest,
)


Request = (
  LimitOrderRequest
  | MarketOrderRequest
  | StopLimitOrderRequest
  | StopMarketOrderRequest
  | TrailingStopOrderRequest
)


class Buy(RpcEndpoint):
  """Places a buy order for an instrument. Supports various order types including limit, market, stop, and advanced order types (stop-limit, take-profit, take-profit-limit, trailing-stop, etc.).

  You can specify order parameters such as price, quantity, time-in-force, post-only, reduce-only, and trigger conditions. Orders can be labeled for easier management and tracking."""

  async def buy(
    self,
    buy_order_params: Request,
    *,
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> OrderTradesResult:
    """Places a buy order for an instrument. Supports various order types including limit, market, stop, and advanced order types (stop-limit, take-profit, take-profit-limit, trailing-stop, etc.).

    You can specify order parameters such as price, quantity, time-in-force, post-only, reduce-only, and trigger conditions. Orders can be labeled for easier management and tracking.

    Args:
      buy_order_params: Parameters for `private/buy`, one variant per order `type`: a limit-priced order (`limit`/`market_limit`) requires `price`; a plain `market` order takes neither `price` nor trigger fields; a stop/take order requires `trigger` and either `trigger_price` (`stop_limit`/`take_limit`, which also require `price`, or `stop_market`/`take_market`) or `trigger_offset` (`trailing_stop`). `type` defaults to `limit` when omitted. Exactly one of `amount`/`contracts` is normally supplied (documented as mutually validated, not modeled here).
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://docs.deribit.com/api-reference/trading/private-buy)
    """
    return await self.request(
      buy_order_params,
      method='POST',
      path='private/buy',
      meta={},
      validate=validate,
      transport=transport,
      request_type=Request,
      response_type=OrderTradesResult,
    )
