# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_deribit.core.endpoint.rpc import RpcEndpoint


class Request(TypedDict):
  label: str
  """user defined label for the order (maximum 64 characters)"""
  currency: NotRequired[Literal['BTC', 'ETH', 'USDC', 'USDT', 'EURR']]
  """Currency, i.e `"BTC"`, `"ETH"`, `"USDC"`"""


Response = float


class CancelByLabel(RpcEndpoint):
  """Cancels all orders (including trigger orders) that have a specific label. This is useful for managing groups of related orders that share the same label.

  Orders can be cancelled across all currencies or filtered to a specific currency. When cancelling by currency, the currency queue is used for processing.

  **Rate Limits:** When called without the `currency` parameter, this method is subject to `cancel_all` rate limits. Different rate limit values may apply for per-currency cancels versus calls without providing the currency parameter."""

  async def cancel_by_label(
    self,
    label: str,
    *,
    currency: Literal['BTC', 'ETH', 'USDC', 'USDT', 'EURR'] | None = None,
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> Response:
    """Cancels all orders (including trigger orders) that have a specific label. This is useful for managing groups of related orders that share the same label.

    Orders can be cancelled across all currencies or filtered to a specific currency. When cancelling by currency, the currency queue is used for processing.

    **Rate Limits:** When called without the `currency` parameter, this method is subject to `cancel_all` rate limits. Different rate limit values may apply for per-currency cancels versus calls without providing the currency parameter.

    Args:
      label: user defined label for the order (maximum 64 characters)
      currency: Currency, i.e `"BTC"`, `"ETH"`, `"USDC"`
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://docs.deribit.com/api-reference/trading/private-cancel_by_label)
    """
    request: Request = Request(label=label)
    if currency is not None:
      request['currency'] = currency
    return await self.request(
      request,
      method='POST',
      path='private/cancel_by_label',
      meta={},
      validate=validate,
      transport=transport,
      request_type=Request,
      response_type=Response,
    )
