# Generated by typed-dev — see CONTRIBUTING.md.
"""`private/reset_mmp` — `private/reset_mmp`."""

from typing_extensions import Literal
from typed_core.validation import validator
from typed_deribit.core import RpcEndpoint

validate_reset_mmp = validator[Literal['ok']](Literal['ok'])  # pyright: ignore[reportArgumentType]  # fmt: skip


class ResetMmp(RpcEndpoint):
  """`private/reset_mmp`."""

  async def reset_mmp(
    self,
    *,
    index_name: str,
    mmp_group: str | None = None,
    block_rfq: bool | None = None,
    validate: bool | None = None,
  ) -> Literal['ok']:
    """Resets Market Maker Protection (MMP) limits for the specified currency pair or MMP group. If MMP protection has been triggered and quoting is frozen, this method allows you to manually resume quoting.

    If the configured `frozen_time` has expired, the system will automatically reset MMP. If `frozen_time` is set to `0` (automatic reset disabled), you must call this method to re-enable quoting. You can also perform a manual reset during the frozen period if you want to resume quoting early.

    For regular MMP (`block_rfq = false`), the `index_name` must be a specific currency pair (e.g., "btc_usd", "eth_usd"). For Block RFQ MMP (`block_rfq = true`), you can set `index_name` to `"all"` to reset limits across all currency pairs. Use the `mmp_group` parameter to reset limits for a specific MMP group.

     or `block_rfq:read_write` (when `block_rfq` = `true`)

    Args:
      index_name: Currency pair for which to reset MMP limits.

    **For regular MMP (`block_rfq = false`):** Must be a specific currency pair (e.g., "btc_usd", "eth_usd"). The value `"all"` is not allowed.

    **For Block RFQ MMP (`block_rfq = true`):** Can be either a specific currency pair or `"all"` to reset MMP limits across all currency pairs.
      mmp_group: Specifies the MMP group for which limits are being reset.

    **Omitting this parameter is explicitly allowed** and targets the **orders MMP group** — the default group used for regular orders with the `mmp` flag set. This is not an error or an incomplete request; it is the correct way to reset the orders MMP group.

    Passing an explicit empty string (`""`) is **not** allowed and returns an error. Only omitting the parameter reaches the orders MMP group.

    **📖 Related Article:** [Mass Quotes Specifications](https://docs.deribit.com/articles/mass-quotes-specifications)
      block_rfq: If true, resets MMP for Block RFQ. When set, requires `block_rfq` scope instead of `trade` scope. Block RFQ MMP settings are completely separate from normal order/quote MMP settings. When `block_rfq = true`, the `index_name` parameter can be set to `"all"` to reset limits across all currency pairs.
      validate: Validate the response against the generated schema.

    References:
      - [Deribit API docs](https://docs.deribit.com/api-reference/trading/private-reset_mmp)
    """
    params: dict = {
      'index_name': index_name,
    }
    if mmp_group is not None:
      params['mmp_group'] = mmp_group
    if block_rfq is not None:
      params['block_rfq'] = block_rfq
    return await self.authed_request(
      'private/reset_mmp',
      params=params,
      validator=validate_reset_mmp,
      validate=validate,
    )
