# Generated by typed-dev — see CONTRIBUTING.md.
from typed_bit2me.core.endpoint.rpc import RpcEndpoint
from typed_bit2me.schemas import BooleanResultResponse


class Submit(RpcEndpoint):
  """Send the data to be verified (change the status to pending)"""

  async def submit(self, *, validate: bool | None = None) -> BooleanResultResponse:
    """Send the data to be verified (change the status to pending)

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://api.bit2me.com/doc#tag/account/POST/v1/account/verify/identity)
    """
    return await self.request(
      None,
      method='POST',
      path='/v1/account/verify/identity',
      meta={},
      validate=validate,
      response_type=BooleanResultResponse,
    )
