# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import TypedDict
from typed_kucoin.core.endpoint.rpc import RpcEndpoint


class IsolatedMarginSymbolRow(TypedDict):
  symbol: str
  """Symbol."""
  symbolName: str
  """Symbol name."""
  baseCurrency: str
  """Base currency, e.g. `BTC`."""
  quoteCurrency: str
  """Quote currency, e.g. `USDT`."""
  maxLeverage: int
  """Maximum leverage of this symbol."""
  flDebtRatio: Decimal
  """Forced-liquidation debt ratio."""
  tradeEnable: bool
  """Whether trading is enabled for this symbol."""
  autoRenewMaxDebtRatio: Decimal
  """Maximum debt ratio at which an existing loan may auto-renew."""
  baseBorrowEnable: bool
  """Whether borrowing the base currency is enabled."""
  quoteBorrowEnable: bool
  """Whether borrowing the quote currency is enabled."""
  baseTransferInEnable: bool
  """Whether transferring the base currency into this isolated symbol is enabled."""
  quoteTransferInEnable: bool
  """Whether transferring the quote currency into this isolated symbol is enabled."""
  baseBorrowCoefficient: str
  """Borrow-interest coefficient for the base currency."""
  quoteBorrowCoefficient: str
  """Borrow-interest coefficient for the quote currency."""


IsolatedMarginSymbol = list[IsolatedMarginSymbolRow]


class IsolatedMarginSymbols(RpcEndpoint):
  """Get the trading configuration of isolated-margin symbols: per-symbol max leverage, forced-liquidation debt ratio, and borrow/transfer-in enablement per side."""

  async def isolated_margin_symbols(
    self,
    *,
    validate: bool | None = None,
  ) -> IsolatedMarginSymbol:
    """Get the trading configuration of isolated-margin symbols: per-symbol max leverage, forced-liquidation debt ratio, and borrow/transfer-in enablement per side.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.kucoin.com/docs-new/api-3470194)
    """
    return await self.request(
      None,
      method='GET',
      path='/api/v1/isolated/symbols',
      meta={},
      validate=validate,
      response_type=IsolatedMarginSymbol,
    )
