# Generated by typed-dev — see CONTRIBUTING.md.
"""`spot.funding.withdraw_status` -- private Spot endpoint."""

from typing_extensions import Literal, NotRequired
from typed_core.validation import TypedDict, validator
from typed_kraken.core import TimestampSeconds
from ...core.endpoint.rpc import RpcEndpoint


class Withdrawal0Item(TypedDict):
  """One withdrawal record."""

  method: str
  """Name of withdrawal method."""
  network: NotRequired[str]
  """Network name based on the funding method used."""
  aclass: str
  """Asset class."""
  asset: str
  """Asset."""
  refid: str
  """Reference ID."""
  txid: str
  """Method transaction ID."""
  info: str
  """Method transaction information."""
  amount: str
  """Amount withdrawn."""
  fee: str
  """Fees paid. Type inferred as `string` by analogy with every other `fee` field in this operation family, since upstream declares no `type` for this property."""
  time: TimestampSeconds
  """Unix timestamp when the request was made."""
  status: Literal['Initial', 'Pending', 'Settled', 'Success', 'Failure']
  """Status of the withdrawal. See the IFEX financial transaction states reference linked from upstream docs for background."""
  key: str
  """Withdrawal key name, as set up on the account."""


class WithdrawalWithdrawalsItem(TypedDict):
  """One withdrawal record."""

  method: str
  """Name of withdrawal method."""
  network: NotRequired[str]
  """Network name based on the funding method used."""
  aclass: str
  """Asset class."""
  asset: str
  """Asset."""
  refid: str
  """Reference ID."""
  txid: str
  """Method transaction ID."""
  info: str
  """Method transaction information."""
  amount: str
  """Amount withdrawn."""
  fee: str
  """Fees paid. Type inferred as `string` by analogy with every other `fee` field in this operation family, since upstream declares no `type` for this property."""
  time: TimestampSeconds
  """Unix timestamp when the request was made."""
  status: Literal['Initial', 'Pending', 'Settled', 'Success', 'Failure']
  """Status of the withdrawal. See the IFEX financial transaction states reference linked from upstream docs for background."""
  key: str
  """Withdrawal key name, as set up on the account."""


class WithdrawStatusPage(TypedDict):
  """Paginated withdrawal results, returned when the `cursor` request parameter is set -- confirmed live; upstream's own OpenAPI schema only documents the bare-array shape for this endpoint (unlike deposit_status, which documents both)."""

  withdrawals: list[WithdrawalWithdrawalsItem]
  """Page of withdrawal records."""
  next_cursor: NotRequired[str | None]
  """Cursor to pass back as `cursor` to fetch the next page of results. `null` once there is no further page -- confirmed live."""


_withdraw_status_type = list[Withdrawal0Item] | WithdrawStatusPage
validate_withdraw_status = validator[_withdraw_status_type](_withdraw_status_type)  # type: ignore


class WithdrawStatus(RpcEndpoint):
  """`spot.funding.withdraw_status`."""

  async def withdraw_status(
    self,
    *,
    asset: str | None = None,
    aclass: Literal['currency', 'tokenized_asset'] | None = None,
    method: str | None = None,
    start: str | None = None,
    end: str | None = None,
    cursor: bool | str | None = None,
    limit: int | None = None,
    rebase_multiplier: Literal['rebased', 'base'] | None = None,
    validate: bool | None = None,
  ) -> list[Withdrawal0Item] | WithdrawStatusPage:
    """Retrieve information about recent withdrawals. Results are sorted by recency; use the `cursor` parameter to iterate through the list of withdrawals (page size equal to the value of `limit`) from newest to oldest. Requires the `Funds permissions - Withdraw` or `Data - Query ledger entries` API key permission.

    Args:
      asset: Filter for a specific asset being withdrawn.
      aclass: Filter for a specific asset class being withdrawn.
      method: Filter for a specific name of withdrawal method.
      start: Start timestamp; withdrawals created strictly before this will not be included in the response.
      end: End timestamp; withdrawals created strictly after this will not be included in the response.
      cursor: `true`/`false` to enable/disable the paginated response shape, or a cursor string (returned by a previous call) to fetch the next page. Default `false`.
      limit: Number of results to include per page.
      rebase_multiplier: Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity; `base` displays in terms of SPV tokens.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.kraken.com/api-reference/funding/get-status-of-recent-withdrawals)
    """
    data = {}
    if asset is not None:
      data['asset'] = asset
    if aclass is not None:
      data['aclass'] = aclass
    if method is not None:
      data['method'] = method
    if start is not None:
      data['start'] = start
    if end is not None:
      data['end'] = end
    if cursor is not None:
      data['cursor'] = cursor
    if limit is not None:
      data['limit'] = limit
    if rebase_multiplier is not None:
      data['rebase_multiplier'] = rebase_multiplier

    return await self.authed_request(
      '/0/private/WithdrawStatus',
      data,
      validator=validate_withdraw_status,
      validate=validate,
    )
