# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import Literal, NotRequired, TypedDict
from typed_kucoin.core import TimestampMillis
from typed_kucoin.core.endpoint.rpc import RpcEndpoint


class Request(TypedDict):
  withdrawalId: str
  """Unique id of the withdrawal to look up."""


class WithdrawalDetail(TypedDict):
  """Full detail of one withdrawal."""

  id: str
  """Unique withdrawal identifier."""
  uid: int
  """Numeric user id the withdrawal belongs to."""
  currency: str
  """Currency code (does not change even if the currency is later renamed)."""
  chainId: str
  """Chain id, e.g. `trx`, `bsc`, `ton` -- the same value space as `WithdrawalHistoryEntry.chain` on the sibling Get Withdrawal History endpoint."""
  chainName: str
  """Chain display name, e.g. `TRC20`, `BEP20`, `TON`."""
  currencyName: str
  """Currency display name; changes if the currency is renamed (unlike `currency`)."""
  status: Literal['REVIEW', 'PROCESSING', 'WALLET_PROCESSING', 'SUCCESS', 'FAILURE']
  """Withdrawal status. Stated only in this field's own description text rather than a machine `enum` on this endpoint's schema, but the identical value set is a declared `enum` on the sibling Get Withdrawal History endpoint's `status` field -- treated as the same closed set here."""
  failureReason: str
  """Failure reason code; empty string when not applicable."""
  failureReasonMsg: NotRequired[str | None]
  """Human-readable failure reason; `null` when not applicable."""
  address: str
  """Withdrawal destination address."""
  memo: str
  """Address remark/tag; empty string if none."""
  isInner: bool
  """Whether this was an internal (KuCoin-to-KuCoin) withdrawal."""
  amount: Decimal
  """Withdrawal amount."""
  fee: Decimal
  """Fee charged for the withdrawal."""
  walletTxId: NotRequired[str | None]
  """On-chain (or wallet-internal) transaction id; `null` observed for some withdrawals."""
  addressRemark: NotRequired[str | None]
  """Address book remark for the destination address; `null` when the address has none saved."""
  remark: str
  """Free-text remark; empty string if none."""
  createdAt: TimestampMillis
  """Record creation time, Unix milliseconds."""
  cancelType: Literal['CANCELABLE', 'CANCELING', 'NON_CANCELABLE']
  """Whether this withdrawal can still be canceled."""
  taxes: NotRequired[list[str] | None]
  """Tax information, relevant to users in some regions; `null` when not applicable."""
  taxDescription: NotRequired[str | None]
  """Tax description; `null` when not applicable."""
  txId: NotRequired[str | None]
  """Internal transaction id. Observed live as `null`; not documented anywhere (absent from both the docs page and the vendored SDK spec's schema)."""
  returnStatus: Literal['NOT_RETURN', 'PROCESSING', 'SUCCESS']
  """Whether a failed/rejected withdrawal's funds have been returned to the account."""
  returnAmount: NotRequired[Decimal | None]
  """Amount returned, if any; `null` when nothing was returned."""
  returnCurrency: str
  """Currency of the returned amount, if any."""


class HistoryById(RpcEndpoint):
  """Request the full detail of one withdrawal by its id."""

  async def history_by_id(
    self,
    withdrawal_id: str,
    *,
    validate: bool | None = None,
  ) -> WithdrawalDetail:
    """Request the full detail of one withdrawal by its id.

    Args:
      withdrawal_id: Unique id of the withdrawal to look up.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.kucoin.com/docs-new/api-3471890)
    """
    return await self.request(
      Request(withdrawalId=withdrawal_id),
      method='GET',
      path='/api/v1/withdrawals/{withdrawalId}',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=WithdrawalDetail,
    )
