# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import AsyncIterator, Literal, NotRequired, TypedDict
from typed_bitget.core import TimestampMillis
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class AdvertisementCertification(TypedDict):
  imageUrl: str
  """Certification badge image URL."""
  desc: str
  """Certification description."""


class AdvertisementPaymentField(TypedDict):
  name: str
  """Field name."""
  required: bool
  """Whether the field is required."""
  type: str
  """Field type. The venue does not document a closed set of values for this generic payment-method-field descriptor."""


class AdvertisementUserLimit(TypedDict):
  """Restrictions placed on counterparties."""

  minCompleteNum: str
  """Minimum completed order count required."""
  maxCompleteNum: str
  """Maximum completed order count allowed."""
  placeOrderNum: str
  """Minimum placed order count required."""
  allowMerchantPlace: str
  """Whether other merchants may place orders."""
  completeRate30d: str
  """Minimum 30-day completion rate required."""
  country: str
  """Country restriction."""


class Request(TypedDict):
  startTime: TimestampMillis
  """Range start, ms epoch."""
  endTime: NotRequired[TimestampMillis]
  """Range end, ms epoch. Must be at most 90 days after startTime."""
  idLessThan: NotRequired[str]
  """Pagination cursor: return advertisements with id less than this value."""
  limit: NotRequired[int]
  """Maximum number of advertisements to return."""
  status: Literal['online', 'offline', 'editing', 'completed']
  """Restrict to advertisements in this status."""
  advNo: NotRequired[str]
  """Restrict to a single advertisement number."""
  side: Literal['buy', 'sell']
  """Restrict to advertisements on this side."""
  coin: str
  """Restrict to advertisements in this coin."""
  language: NotRequired[Literal['zh-CN', 'en-US']]
  """Response message language."""
  fiat: str
  """Restrict to advertisements in this fiat currency."""
  orderBy: NotRequired[Literal['createTime', 'price']]
  """Sort field, descending by default."""
  payMethodId: NotRequired[str]
  """Restrict to advertisements accepting this payment method."""
  sourceType: NotRequired[Literal['owner', 'competitor', 'ownerAndCompetitor']]
  """Restrict the query scope."""


class AdvertisementPaymentMethod(TypedDict):
  paymentMethod: str
  """Payment method name."""
  paymentId: str
  """Payment method id."""
  paymentInfo: list[AdvertisementPaymentField]
  """Payment method fields."""


class Advertisement(TypedDict):
  advId: str
  """Unique advertisement id."""
  advNo: str
  """Advertisement number."""
  side: Literal['buy', 'sell']
  """Advertisement side."""
  advSize: str
  """Total advertised quantity."""
  size: str
  """Remaining quantity."""
  coin: str
  """Cryptocurrency."""
  price: str
  """Listed price."""
  coinPrecision: str
  """Coin decimal precision."""
  fiat: str
  """Fiat currency."""
  fiatPrecision: str
  """Fiat decimal precision."""
  fiatSymbol: str
  """Fiat currency symbol."""
  status: Literal['online', 'offline', 'editing', 'completed']
  """Advertisement status."""
  hide: Literal['yes', 'no']
  """Whether the advertisement is hidden."""
  maxTradeAmount: str
  """Maximum trade amount per order."""
  minTradeAmount: str
  """Minimum trade amount per order."""
  payDuration: str
  """Payment window, in minutes."""
  turnoverNum: str
  """Total number of transactions."""
  turnoverRate: str
  """Completion rate."""
  label: str | None
  """Optional note attached to the advertisement."""
  userLimitList: AdvertisementUserLimit
  paymentMethodList: list[AdvertisementPaymentMethod]
  """Payment methods accepted by this advertisement."""
  merchantCertifiedList: list[AdvertisementCertification]
  """Merchant certification badges shown on this advertisement."""
  utime: str
  """Last update time, ms epoch."""
  ctime: str
  """Creation time, ms epoch."""


class AdvertisementList(TypedDict):
  advList: list[Advertisement] | None
  """Advertisements on this page. `null` when the caller has none."""
  minAdvId: str | None
  """Smallest advertisement id in this page's results; pass as idLessThan to fetch the next page. `null` when `advList` is `null`."""


class Advertisements(RpcEndpoint):
  """List the authenticated merchant's P2P advertisements."""

  async def advertisements_paged(
    self,
    *,
    start_time: TimestampMillis,
    end_time: TimestampMillis | None = None,
    limit: int | None = None,
    status: Literal['online', 'offline', 'editing', 'completed'],
    adv_no: str | None = None,
    side: Literal['buy', 'sell'],
    coin: str,
    language: Literal['zh-CN', 'en-US'] | None = None,
    fiat: str,
    order_by: Literal['createTime', 'price'] | None = None,
    pay_method_id: str | None = None,
    source_type: Literal['owner', 'competitor', 'ownerAndCompetitor'] | None = None,
    max_pages: int | None = None,
    validate: bool | None = None,
  ) -> AsyncIterator[AdvertisementList]:
    """List the authenticated merchant's P2P advertisements.

    Paged variant of `advertisements`: Passes each page's token back as `idLessThan` and stops on the first empty page, or after `max_pages` pages when one is given.

    Args:
      start_time: Range start, ms epoch.
      end_time: Range end, ms epoch. Must be at most 90 days after startTime.
      limit: Maximum number of advertisements to return.
      status: Restrict to advertisements in this status.
      adv_no: Restrict to a single advertisement number.
      side: Restrict to advertisements on this side.
      coin: Restrict to advertisements in this coin.
      language: Response message language.
      fiat: Restrict to advertisements in this fiat currency.
      order_by: Sort field, descending by default.
      pay_method_id: Restrict to advertisements accepting this payment method.
      source_type: Restrict the query scope.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      max_pages: Stop after this many pages, even if the walk is not done.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-p2p-p2p/classic-p2p#get-merchant-advertisement-list)
    """
    id_less_than: str | None = None
    pages = 0
    while True:
      response = await self.advertisements(
        start_time=start_time,
        end_time=end_time,
        limit=limit,
        status=status,
        adv_no=adv_no,
        side=side,
        coin=coin,
        language=language,
        fiat=fiat,
        order_by=order_by,
        pay_method_id=pay_method_id,
        source_type=source_type,
        id_less_than=id_less_than,
        validate=validate,
      )
      yield response
      pages += 1
      if max_pages is not None and pages >= max_pages:
        break
      rows = response.get('advList') if response is not None else None
      if not rows:
        break
      id_less_than = response.get('minAdvId') if response is not None else None

  async def advertisements(
    self,
    *,
    start_time: TimestampMillis,
    end_time: TimestampMillis | None = None,
    id_less_than: str | None = None,
    limit: int | None = None,
    status: Literal['online', 'offline', 'editing', 'completed'],
    adv_no: str | None = None,
    side: Literal['buy', 'sell'],
    coin: str,
    language: Literal['zh-CN', 'en-US'] | None = None,
    fiat: str,
    order_by: Literal['createTime', 'price'] | None = None,
    pay_method_id: str | None = None,
    source_type: Literal['owner', 'competitor', 'ownerAndCompetitor'] | None = None,
    validate: bool | None = None,
  ) -> AdvertisementList:
    """List the authenticated merchant's P2P advertisements.

    Args:
      start_time: Range start, ms epoch.
      end_time: Range end, ms epoch. Must be at most 90 days after startTime.
      id_less_than: Pagination cursor: return advertisements with id less than this value.
      limit: Maximum number of advertisements to return.
      status: Restrict to advertisements in this status.
      adv_no: Restrict to a single advertisement number.
      side: Restrict to advertisements on this side.
      coin: Restrict to advertisements in this coin.
      language: Response message language.
      fiat: Restrict to advertisements in this fiat currency.
      order_by: Sort field, descending by default.
      pay_method_id: Restrict to advertisements accepting this payment method.
      source_type: Restrict the query scope.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.bitget.com/docs/catalog/classic-p2p-p2p/classic-p2p#get-merchant-advertisement-list)
    """
    request: Request = Request(
      startTime=start_time, status=status, side=side, coin=coin, fiat=fiat
    )
    if end_time is not None:
      request['endTime'] = end_time
    if id_less_than is not None:
      request['idLessThan'] = id_less_than
    if limit is not None:
      request['limit'] = limit
    if adv_no is not None:
      request['advNo'] = adv_no
    if language is not None:
      request['language'] = language
    if order_by is not None:
      request['orderBy'] = order_by
    if pay_method_id is not None:
      request['payMethodId'] = pay_method_id
    if source_type is not None:
      request['sourceType'] = source_type
    return await self.request(
      request,
      method='GET',
      path='/api/v2/p2p/advList',
      meta={'required': True},
      validate=validate,
      request_type=Request,
      response_type=AdvertisementList,
    )
