# Generated by typed-dev — see CONTRIBUTING.md.
"""`uta.loan.pledge_rate_history` -- generated from `spec/endpoints/`."""

from typing_extensions import AsyncIterator, Literal
from typed_core.validation import TypedDict, validator
from typed_bitget.core import TimestampMillis, timestamp_millis
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class LoanPledgeRateHistoryEntry(TypedDict):
  """One historical collateral (pledge rate) adjustment."""

  loanCoin: str
  """Borrowed coin of the adjusted loan order."""
  pledgeCoin: str
  """Pledged collateral coin that was adjusted."""
  orderId: str
  """Identifier of the loan order that was adjusted."""
  reviseTime: TimestampMillis
  """Millisecond epoch timestamp the adjustment was made."""
  reviseSide: str
  """Direction of the adjustment."""
  reviseAmount: str
  """Amount of `pledgeCoin` adjusted, as a decimal string."""
  afterPledgeRate: str
  """Pledge rate after this adjustment, as a decimal string."""
  beforePledgeRate: str
  """Pledge rate before this adjustment, as a decimal string."""


class PledgeRateHistory(RpcEndpoint):
  """`uta.loan.pledge_rate_history`."""

  async def pledge_rate_history(
    self,
    *,
    order_id: str | None = None,
    revise_side: Literal['down', 'up'] | None = None,
    pledge_coin: str | None = None,
    start_time: TimestampMillis,
    end_time: TimestampMillis,
    page_num: int | None = None,
    page_size: int | None = None,
    validate: bool | None = None,
  ) -> list[LoanPledgeRateHistoryEntry]:
    """Query the caller's collateral (pledge rate) adjustment history within a time range.

    Args:
      order_id: Restrict to a single loan order.
      revise_side: Restrict to adjustments in this direction.
      pledge_coin: Restrict to a single pledged coin.
      start_time: Start of the time range to query, as a millisecond epoch timestamp.
      end_time: End of the time range to query, as a millisecond epoch timestamp.
      page_num: Page number to fetch.
      page_size: Number of records per page.

    References:
      - [Official docs](https://www.bitget.com/api-doc/uta/loan/Pledge-Rate-History)
    """
    params: dict = {
      'startTime': timestamp_millis.dump(start_time),
      'endTime': timestamp_millis.dump(end_time),
    }
    if order_id is not None:
      params['orderId'] = order_id
    if revise_side is not None:
      params['reviseSide'] = revise_side
    if pledge_coin is not None:
      params['pledgeCoin'] = pledge_coin
    if page_num is not None:
      params['pageNum'] = page_num
    if page_size is not None:
      params['pageSize'] = page_size
    return await self.authed_request(
      'GET',
      '/api/v3/loan/pledge-rate-history',
      params=params,
      validator=validator(list[LoanPledgeRateHistoryEntry]),
      validate=validate,
    )

  async def pledge_rate_history_paged(
    self,
    *,
    order_id: str | None = None,
    revise_side: Literal['down', 'up'] | None = None,
    pledge_coin: str | None = None,
    start_time: TimestampMillis,
    end_time: TimestampMillis,
    page_size: int | None = None,
    max_pages: int | None = None,
    validate: bool | None = None,
  ) -> AsyncIterator[list[LoanPledgeRateHistoryEntry]]:
    """Yield successive pages of `pledge_rate_history`.

    Requests `pageNum` from 1 upwards and stops on the first page shorter than
    `page_size`, or after `max_pages` pages when one is given.
    """
    page_num = 1
    pages = 0
    while True:
      response = await self.pledge_rate_history(
        order_id=order_id,
        revise_side=revise_side,
        pledge_coin=pledge_coin,
        start_time=start_time,
        end_time=end_time,
        page_size=page_size,
        page_num=page_num,
        validate=validate,
      )
      yield response
      pages += 1
      if max_pages is not None and pages >= max_pages:
        break
      if not response or (page_size is not None and len(response) < page_size):
        break
      page_num += 1
