# Generated by typed-dev — see CONTRIBUTING.md.
"""`POST /v5/earn/liquidity-mining/claim-interest` — Claim Liquidity Mining Interest."""

from typing_extensions import Any, TypedDict
from typed_bybit.core import Endpoint, validator


class LiquidityMiningClaimInterestRequest(TypedDict):
  """Liquidity Mining yield claim."""

  productId: str
  """Product identifier to claim yield for. `-1` claims across every open Liquidity Mining position at once."""


adapter = validator[dict[str, Any]](dict[str, Any])


class ClaimInterest(Endpoint):
  """`Claim Liquidity Mining Interest` — mixed into the router that owns `finance.advanced_earn.liquidity_mining.claim_interest`."""

  async def claim_interest(
    self,
    liquidity_mining_claim_interest_request: LiquidityMiningClaimInterestRequest,
    *,
    validate: bool | None = None,
  ) -> dict[str, Any]:
    """Claim accrued yield from one Liquidity Mining position, or every position at once. Requires API key "Earn" permission.

    Args:
      liquidity_mining_claim_interest_request: Product to claim accrued yield for.
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/finance/advanced-earn/liquidity-mining/claim-interest)
    """
    r = await self.authed_request(
      'POST',
      '/v5/earn/liquidity-mining/claim-interest',
      json=liquidity_mining_claim_interest_request,
    )
    return self.result(r, adapter, validate)
