# Generated by typed-dev — see CONTRIBUTING.md.
"""`GET /v5/earn/liquidity-mining/position` — Get Liquidity Mining Position."""

from typing_extensions import Literal, NotRequired, TypedDict
from typed_bybit.core import Endpoint, TimestampMillis, validator


class LiquidityMiningPosition(TypedDict):
  """One open Liquidity Mining position."""

  positionId: str
  """Unique position identifier."""
  productId: str
  """Product identifier."""
  baseCoin: str
  """Base coin of the pool."""
  quoteCoin: str
  """Quote coin of the pool."""
  quoteAmount: str
  """Current quote coin balance, dynamically calculated with leverage."""
  baseAmount: str
  """Current base coin balance, dynamically calculated with leverage."""
  principalQuoteAmount: str
  """Total quote coin principal invested."""
  principalBaseAmount: str
  """Total base coin principal invested."""
  principalLiquidityValue: NotRequired[str]
  """Real-time principal liquidity value, in quote coin."""
  leveragedValue: NotRequired[str]
  """Real-time total leveraged position value, in quote coin."""
  loan: NotRequired[str]
  """Borrowed amount, in quote coin."""
  claimableYield: NotRequired[str]
  """Yield currently available to claim."""
  currentApr: NotRequired[str]
  """Current APR, e8 precision. Divide by 10^8 for the actual rate."""
  leverage: str
  """Active leverage multiplier."""
  margin: NotRequired[str]
  """Current margin amount."""
  liquidationPrice: NotRequired[str]
  """Price that would trigger liquidation."""
  currentPriceY: NotRequired[str]
  """Real-time base coin market price."""
  status: Literal['Active', 'Liquidating']
  """Position status."""
  createdTime: TimestampMillis
  """Position creation time, as a millisecond timestamp."""


class LiquidityMiningPositionList(TypedDict):
  """Open Liquidity Mining positions."""

  positions: list[LiquidityMiningPosition]
  """Position records."""


adapter = validator[LiquidityMiningPositionList](LiquidityMiningPositionList)


class Position(Endpoint):
  """`Get Liquidity Mining Position` — mixed into the router that owns `finance.advanced_earn.liquidity_mining.position`."""

  async def position(
    self,
    *,
    product_id: str | None = None,
    base_coin: str | None = None,
    validate: bool | None = None,
  ) -> LiquidityMiningPositionList:
    """Get the caller's open Liquidity Mining positions. Requires API key "Earn" permission.

    Args:
      product_id: Product identifier to filter by.
      base_coin: Base coin to filter by, e.g. `BTC`, `ETH`.
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/finance/advanced-earn/liquidity-mining/position)
    """
    params = {}
    if product_id is not None:
      params['productId'] = product_id
    if base_coin is not None:
      params['baseCoin'] = base_coin
    r = await self.authed_request(
      'GET', '/v5/earn/liquidity-mining/position', params=params
    )
    return self.result(r, adapter, validate)
