# Generated by typed-dev — see CONTRIBUTING.md.
"""`POST /api/v1/broker/nd/account` — Add sub-account."""

from typed_core.validation import TypedDict, validator
from typed_kucoin.core import RpcEndpoint, TimestampMillis


class AddSubAccountRequest(TypedDict):
  accountName: str
  """Sub-account name. Unique across the exchange -- add a distinguishing identifier to avoid collisions."""


class BrokerSubAccountCreated(TypedDict):
  """A newly created broker sub-account."""

  accountName: str
  """Sub-account name."""
  uid: str
  """Sub-account UID."""
  createdAt: TimestampMillis
  """Creation time, Unix milliseconds."""
  level: int
  """Sub-account VIP level."""


_Type = BrokerSubAccountCreated
adapter = validator[_Type](_Type)  # type: ignore


class SubAccountAdd(RpcEndpoint):
  """`Add sub-account` — mixed into `Broker`, the product exposing `broker.sub_account_add`."""

  async def sub_account_add(
    self,
    add_sub_account_request: AddSubAccountRequest,
    *,
    validate: bool | None = None,
  ) -> BrokerSubAccountCreated:
    """Create a new sub-account under the authenticated Exchange (ND) Broker.

    Args:
      add_sub_account_request: New sub-account's name.
      validate: Validate the response against the generated schema.

    References:
      - [KuCoin API docs](https://www.kucoin.com/docs-new)
    """
    return await self.authed_request(
      'POST',
      '/api/v1/broker/nd/account',
      json=add_sub_account_request,
      validator=adapter,
      validate=validate,
    )
