# Generated by typed-dev — see CONTRIBUTING.md.
"""`uta.transfers.withdraw.cancel` -- generated from `spec/endpoints/`."""

from typing_extensions import Literal, NotRequired
from typed_core.validation import TypedDict, validator
from typed_bitget.core.endpoint.rpc import RpcEndpoint


class CancelWithdrawalRequest(TypedDict):
  """Which withdrawal to cancel."""

  orderId: NotRequired[str]
  """Withdrawal order id to cancel. Either this or `clientOid` must be supplied; `orderId` takes precedence when both are."""
  clientOid: NotRequired[str]
  """Caller-supplied withdrawal order id to cancel."""


class Cancel(RpcEndpoint):
  """`uta.transfers.withdraw.cancel`."""

  async def cancel(
    self,
    cancel_withdrawal_request: CancelWithdrawalRequest,
    *,
    validate: bool | None = None,
  ) -> Literal['success']:
    """Cancel a withdrawal still within its preliminary review period, authenticated.

    Args:
      cancel_withdrawal_request: Which withdrawal to cancel.

    References:
      - [Official docs](https://www.bitget.com/api-doc/uta/account/withdrawal/Cancel-Withdrawal)
    """
    _ResponseType = Literal['success']
    adapter = validator[_ResponseType](_ResponseType)  # type: ignore
    return await self.authed_request(
      'POST',
      '/api/v3/account/cancel-withdrawal',
      json=cancel_withdrawal_request,
      validator=adapter,
      validate=validate,
    )
