# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core import PaginatedResponse
from typed_core.grpc import GrpcEndpoint, wrap_exceptions
from typing_extensions import Sequence
from typed_dydx.protos.cosmos.base.query.v1beta1 import PageRequest
from typed_dydx.protos.dydxprotocol.prices import (
  MarketPrice,
  QueryAllMarketPricesRequest,
  QueryAllMarketPricesResponse,
  QueryStub,
)


class MarketPrices(GrpcEndpoint):
  """Query all market prices."""

  def market_prices_paged(
    self,
    limit: int | None = None,
  ) -> PaginatedResponse[MarketPrice, bytes]:
    """Query all market prices.

    Paged variant of `market_prices`: Passes each page's token back as `key` and stops when a response carries no `pagination.next_key`. Awaitable (flattens every page) or async-iterable (one page at a time).

    References:
      - [Official docs](https://docs.dydx.exchange/)
    """

    async def next(key: bytes) -> tuple[Sequence[MarketPrice], bytes | None]:
      response = await self.market_prices(
        pagination=PageRequest(key=key, limit=(limit if limit is not None else 0))
      )
      rows = response.market_prices
      rows = rows if rows is not None else []
      state_0 = response.pagination
      state = getattr(state_0, 'next_key', None) if state_0 is not None else None
      return rows, state or None

    return PaginatedResponse(b'', next)

  @wrap_exceptions
  async def market_prices(
    self,
    pagination: PageRequest | None = None,
  ) -> QueryAllMarketPricesResponse:
    """Query all market prices.

    References:
      - [Official docs](https://docs.dydx.exchange/)
    """
    return await QueryStub(self.channel).all_market_prices(
      QueryAllMarketPricesRequest(pagination=pagination)
    )
