# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core import PaginatedResponse
from typing_extensions import Literal, NotRequired, TypedDict
from typed_deribit.core import TimestampMillis
from typed_deribit.core.endpoint.rpc import RpcEndpoint
from typed_deribit.schemas import BlockRfqHedge, BlockRfqQuoteLeg


class BlockRfqTradeFill(TypedDict):
  """One fill within a Block RFQ trade."""

  direction: Literal['buy', 'sell']
  """Direction: `buy`, or `sell`."""
  price: float
  """Price in base currency."""
  amount: float
  """Trade amount. Denominated in underlying base currency coin for options/linear futures/linear perpetuals/spots, in USD units for inverse perpetuals/futures."""
  hedge_amount: NotRequired[float]
  """Amount of the hedge leg, when present. Same currency convention as `amount`."""


class Request(TypedDict):
  currency: Literal['BTC', 'ETH', 'USDC', 'USDT', 'EURR', 'any']
  """Currency name or "any" if don't care"""
  continuation: NotRequired[str]
  """Continuation token for pagination. Consists of `timestamp` and `block_rfq_id`."""
  count: NotRequired[int]
  """Count of Block RFQs returned, maximum `1000` per the docs; live testnet only accepts `[10, 50]`, see notes."""


class BlockRfqTrade(TypedDict):
  """One executed Block RFQ trade."""

  id: int
  """ID of the Block RFQ."""
  timestamp: TimestampMillis
  """The timestamp of the trade (milliseconds since the UNIX epoch)."""
  direction: Literal['buy', 'sell']
  """Direction: `buy`, or `sell`."""
  amount: float
  """This value multiplied by the ratio of a leg gives trade size on that leg."""
  mark_price: float
  """Mark price at the moment of trade."""
  legs: list[BlockRfqQuoteLeg]
  """The instrument legs making up this Block RFQ."""
  combo_id: NotRequired[str]
  """Unique combo identifier (equals the sole leg's `instrument_name` for a single-leg RFQ)."""
  hedge: NotRequired[BlockRfqHedge]
  index_prices: NotRequired[dict[str, float]]
  """A map of index prices for the underlying instrument(s) at the time of trade execution, keyed by price index name."""
  trades: list[BlockRfqTradeFill]
  """The individual fill(s) that make up this Block RFQ trade."""


class GetBlockRfqTradesResult(TypedDict):
  """A page of recent Block RFQ trades."""

  block_rfqs: list[BlockRfqTrade]
  """Recent Block RFQ trades, newest first."""
  continuation: NotRequired[str | None]
  """Continuation token for the next page; `null` when there is no further page."""


class GetBlockRfqTrades(RpcEndpoint):
  """Returns a list of recent Block RFQ trades across the venue, optionally filtered by currency. Public market data about completed Block RFQ trades; for the caller's own (including unfilled) Block RFQs, use `private/get_block_rfqs`."""

  def get_block_rfq_trades_paged(
    self,
    currency: Literal['BTC', 'ETH', 'USDC', 'USDT', 'EURR', 'any'],
    *,
    count: int | None = None,
    transport: Literal['http', 'ws'] = 'http',
    validate: bool | None = None,
  ) -> PaginatedResponse[BlockRfqTrade, str]:
    """Returns a list of recent Block RFQ trades across the venue, optionally filtered by currency. Public market data about completed Block RFQ trades; for the caller's own (including unfilled) Block RFQs, use `private/get_block_rfqs`.

    Paged variant of `get_block_rfq_trades`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      currency: Currency name or "any" if don't care
      count: Count of Block RFQs returned, maximum `1000` per the docs; live testnet only accepts `[10, 50]`, see notes.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://docs.deribit.com/api-reference/block-rfq/public-get_block_rfq_trades)
    """

    async def next(continuation: str) -> tuple[list[BlockRfqTrade], str | None]:
      response = await self.get_block_rfq_trades(
        currency,
        count=count,
        transport=transport,
        continuation=(continuation or None),
        validate=validate,
      )
      rows = response.get('block_rfqs')
      state = response.get('continuation')
      return rows or [], state or None

    return PaginatedResponse('', next)

  async def get_block_rfq_trades(
    self,
    currency: Literal['BTC', 'ETH', 'USDC', 'USDT', 'EURR', 'any'],
    *,
    continuation: str | None = None,
    count: int | None = None,
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> GetBlockRfqTradesResult:
    """Returns a list of recent Block RFQ trades across the venue, optionally filtered by currency. Public market data about completed Block RFQ trades; for the caller's own (including unfilled) Block RFQs, use `private/get_block_rfqs`.

    Args:
      currency: Currency name or "any" if don't care
      continuation: Continuation token for pagination. Consists of `timestamp` and `block_rfq_id`.
      count: Count of Block RFQs returned, maximum `1000` per the docs; live testnet only accepts `[10, 50]`, see notes.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://docs.deribit.com/api-reference/block-rfq/public-get_block_rfq_trades)
    """
    request: Request = Request(currency=currency)
    if continuation is not None:
      request['continuation'] = continuation
    if count is not None:
      request['count'] = count
    return await self.request(
      request,
      method='POST',
      path='public/get_block_rfq_trades',
      meta={'public': True},
      validate=validate,
      transport=transport,
      request_type=Request,
      response_type=GetBlockRfqTradesResult,
    )
