# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typed_core.util import StreamManager
from typing_extensions import Any, Literal, NotRequired, TypedDict
from typed_hyperliquid.core import TimestampMillis
from typed_hyperliquid.streams.core import StreamsCore


class FillLiquidation(TypedDict):
  """Liquidation detail attached to a fill that closed a liquidated position."""

  liquidatedUser: NotRequired[str]
  """Account address of the user who was liquidated."""
  markPx: Decimal
  """Mark price at the time of liquidation."""
  method: Literal['market', 'backstop']
  """How the liquidation was executed."""


class Parameters(TypedDict):
  """Identifies the account whose TWAP slice fills to subscribe to."""

  user: str
  """The account address whose activity this subscription tracks."""


class WsFill(TypedDict):
  """One trade fill."""

  coin: str
  """Coin symbol traded."""
  px: Decimal
  """Fill price."""
  sz: Decimal
  """Fill size."""
  side: Literal['B', 'A']
  """Side of the fill: `B` (bid/buy) or `A` (ask/sell)."""
  time: TimestampMillis
  """Millisecond epoch timestamp of the fill."""
  startPosition: str
  """Position size immediately before this fill."""
  dir: str
  """Human-readable fill direction used for frontend display, e.g. "Open Long"; not a documented closed set."""
  closedPnl: str
  """Realized PnL closed by this fill."""
  hash: str
  """L1 transaction hash of the fill."""
  oid: int
  """Order id that generated this fill."""
  crossed: bool
  """Whether the order crossed the spread (was taker)."""
  fee: Decimal
  """Fee paid for this fill; negative means a rebate."""
  tid: int
  """Unique trade id."""
  liquidation: NotRequired[FillLiquidation]
  feeToken: str
  """Token the fee was paid in."""
  builderFee: NotRequired[str]
  """Amount paid to the order's builder, already included in `fee`."""


class WsTwapSliceFill(TypedDict):
  """One fill generated by a slice of a TWAP order."""

  fill: WsFill
  twapId: int
  """Id of the TWAP order this slice fill belongs to."""


class UserTwapSliceFillsUpdate(TypedDict):
  """Snapshot or incremental update of the user's TWAP slice fills."""

  isSnapshot: bool
  """True on the initial snapshot message; false on each subsequent streamed update."""
  user: str
  """The account address whose activity this subscription tracks."""
  twapSliceFills: list[WsTwapSliceFill]
  """TWAP slice fills in this snapshot or update, oldest first."""


class UserTwapSliceFills(StreamsCore):
  """Subscribe to a user's TWAP slice fills: an initial snapshot followed by streamed fills as TWAP order slices execute."""

  def user_twap_slice_fills(
    self,
    user: str,
    *,
    validate: bool | None = None,
  ) -> StreamManager[UserTwapSliceFillsUpdate, Any, Any]:
    """Subscribe to a user's TWAP slice fills: an initial snapshot followed by streamed fills as TWAP order slices execute.

    Args:
      user: The account address whose activity this subscription tracks.
      validate: Override this call's pushed-payload validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions)
    """
    return self.subscribe(
      'userTwapSliceFills',
      Parameters(user=user),
      validate=validate,
      request_type=Parameters,
      response_type=UserTwapSliceFillsUpdate,
    )
