# Generated by typed-dev — see CONTRIBUTING.md.
"""`classic.public.all_account_balance` -- generated from `spec/endpoints/`."""

from typing_extensions import Literal
from typed_core.validation import TypedDict, validator
from bitget.core.endpoint.rpc import RpcEndpoint


class AccountTypeBalance(TypedDict):
  """USDT-denominated balance of one product account."""

  accountType: Literal['spot', 'futures', 'funding', 'earn', 'bots', 'margin']
  """Product account, e.g. `spot`, `futures`, `funding`, `earn`, `bots`, `margin`."""
  usdtBalance: str
  """Balance of this account, denominated in USDT."""


class AllAccountBalance(RpcEndpoint):
  """`classic.public.all_account_balance`."""

  async def all_account_balance(self) -> list[AccountTypeBalance]:
    """Get the caller's USDT-denominated balance across every product account (spot, futures, funding, earn, bots, margin).

    References:
      - [Official docs](https://www.bitget.com/api-doc/classic/common/account/All-Account-Balance)
    """
    return await self.authed_request(
      'GET',
      '/api/v2/account/all-account-balance',
      validator=validator(list[AccountTypeBalance]),
    )
