# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import TypedDict
from typed_kucoin.core import TimestampMillis
from typed_kucoin.core.endpoint.rpc import RpcEndpoint


class HfDcpConfig(TypedDict):
  """Disconnection Protect configuration."""

  timeout: int
  """Seconds of silence before every order on the protected symbols is auto-cancelled."""
  symbols: str
  """Comma-separated trading pair symbols protected by this setting."""
  currentTime: TimestampMillis
  """Server time at query."""
  triggerTime: TimestampMillis
  """Time at which the auto-cancellation would trigger, absent another Set DCP call resetting it."""


Response = HfDcpConfig | None


class GetDcp(RpcEndpoint):
  """Get the authenticated account's current Disconnection Protect (DCP, a.k.a. dead-cancel-all / deadman switch) configuration -- the venue's own automatic-cancel-on-disconnect safety setting."""

  async def get_dcp(self, *, validate: bool | None = None) -> Response:
    """Get the authenticated account's current Disconnection Protect (DCP, a.k.a. dead-cancel-all / deadman switch) configuration -- the venue's own automatic-cancel-on-disconnect safety setting.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-dcp)
    """
    return await self.request(
      None,
      method='GET',
      path='/api/v1/hf/orders/dead-cancel-all/query',
      meta={'signed': True},
      validate=validate,
      response_type=Response,
    )
