# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_bybit.core import TimestampMillis
from typed_bybit.core.http import RpcEndpoint


class RepaymentOrder(TypedDict):
  """One loan repayment order."""

  repayOrderId: str
  """Repayment order identifier."""
  repaidTime: TimestampMillis
  """When the repayment was made."""
  token: str
  """Coin repaid."""
  quantity: str
  """Principal amount repaid."""
  interest: str
  """Interest amount repaid."""
  businessType: Literal['1', '2']
  """Kind of repayment. `1`: normal repayment. `2`: liquidation."""
  status: Literal['1', '2']
  """Result of the repayment. `1`: success. `2`: fail."""


class Request(TypedDict):
  startTime: NotRequired[TimestampMillis]
  """Millisecond timestamp."""
  endTime: NotRequired[TimestampMillis]
  """Millisecond timestamp."""
  limit: NotRequired[int]
  """Page size."""


class RepayInfoResult(TypedDict):
  """Matching repayment orders."""

  repayInfo: list[RepaymentOrder]
  """Matching repayment orders."""


class RepayInfo(RpcEndpoint):
  """Get up to 2 years of historical loan repayment orders -- orders that repaid a loan."""

  async def repay_info(
    self,
    *,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> RepayInfoResult:
    """Get up to 2 years of historical loan repayment orders -- orders that repaid a loan.

    Args:
      start_time: Millisecond timestamp.
      end_time: Millisecond timestamp.
      limit: Page size.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://bybit-exchange.github.io/docs/v5/otc/repay-info)
    """
    request: Request = Request()
    if start_time is not None:
      request['startTime'] = start_time
    if end_time is not None:
      request['endTime'] = end_time
    if limit is not None:
      request['limit'] = limit
    return await self.request(
      request,
      method='GET',
      path='/v5/ins-loan/repaid-history',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=RepayInfoResult,
    )
