# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Any, Literal, NotRequired, TypedDict
from typed_etherscan.core.rest import RpcEndpoint


class JsonRpcError(TypedDict):
  """JSON-RPC error object for failed proxy calls."""

  code: int
  """JSON-RPC error code."""
  message: str
  """JSON-RPC error message."""


class Request(TypedDict):
  chainid: NotRequired[str]
  """Chain ID of the Etherscan-supported network to query, such as `1` for Ethereum mainnet."""
  module: Literal['proxy']
  """Fixed Etherscan API module selector for this operation; use `proxy`."""
  action: Literal['eth_getTransactionByHash']
  """Fixed Etherscan API action selector for this operation; use `eth_getTransactionByHash`."""
  txhash: str
  """Transaction hash whose status, receipt, or internal transactions should be returned."""


class EtherscanJsonRpcResponse(TypedDict):
  jsonrpc: Literal['2.0']
  """JSON-RPC protocol version."""
  id: int
  """JSON-RPC request identifier returned by Etherscan."""
  result: NotRequired[dict[str, Any] | None]
  """JSON-RPC result object, or null when not found."""
  error: NotRequired[JsonRpcError]


class EthGetTransactionByHash(RpcEndpoint):
  """Fetch a transaction by transaction hash."""

  async def eth_get_transaction_by_hash(
    self,
    *,
    chainid: str | None = None,
    module: Literal['proxy'] = 'proxy',
    action: Literal['eth_getTransactionByHash'] = 'eth_getTransactionByHash',
    txhash: str,
    validate: bool | None = None,
  ) -> EtherscanJsonRpcResponse:
    """Fetch a transaction by transaction hash.

    Args:
      chainid: Chain ID of the Etherscan-supported network to query, such as `1` for Ethereum mainnet.
      module: Fixed Etherscan API module selector for this operation; use `proxy`.
      action: Fixed Etherscan API action selector for this operation; use `eth_getTransactionByHash`.
      txhash: Transaction hash whose status, receipt, or internal transactions should be returned.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.etherscan.io/api-reference/endpoint/ethgettransactionbyhash)
    """
    request: Request = Request(module=module, action=action, txhash=txhash)
    if chainid is not None:
      request['chainid'] = chainid
    return await self.request(
      request,
      method='GET',
      path='/v2/api',
      meta={'credentials': True},
      validate=validate,
      request_type=Request,
      response_type=EtherscanJsonRpcResponse,
    )
