# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_etherscan.core.rest import RpcEndpoint


class JsonRpcError(TypedDict):
  """JSON-RPC error object for failed proxy calls."""

  code: int
  """JSON-RPC error code."""
  message: str
  """JSON-RPC error message."""


class Request(TypedDict):
  chainid: NotRequired[str]
  """Chain ID of the Etherscan-supported network to query, such as `1` for Ethereum mainnet."""
  module: Literal['proxy']
  """Fixed Etherscan API module selector for this operation; use `proxy`."""
  action: Literal['eth_getBlockTransactionCountByNumber']
  """Fixed Etherscan API action selector for this operation; use `eth_getBlockTransactionCountByNumber`."""
  tag: NotRequired[str]
  """Block number encoded as hex, or a supported block tag."""


class EtherscanJsonRpcResponse(TypedDict):
  jsonrpc: Literal['2.0']
  """JSON-RPC protocol version."""
  id: int
  """JSON-RPC request identifier returned by Etherscan."""
  result: NotRequired[str]
  """Hex-encoded JSON-RPC result."""
  error: NotRequired[JsonRpcError]


class EthGetBlockTransactionCountByNumber(RpcEndpoint):
  """Fetch the number of transactions in a block by block number."""

  async def eth_get_block_transaction_count_by_number(
    self,
    *,
    chainid: str | None = None,
    module: Literal['proxy'] = 'proxy',
    action: Literal[
      'eth_getBlockTransactionCountByNumber'
    ] = 'eth_getBlockTransactionCountByNumber',
    tag: str | None = None,
    validate: bool | None = None,
  ) -> EtherscanJsonRpcResponse:
    """Fetch the number of transactions in a block by block number.

    Args:
      chainid: Chain ID of the Etherscan-supported network to query, such as `1` for Ethereum mainnet.
      module: Fixed Etherscan API module selector for this operation; use `proxy`.
      action: Fixed Etherscan API action selector for this operation; use `eth_getBlockTransactionCountByNumber`.
      tag: Block number encoded as hex, or a supported block tag.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.etherscan.io/api-reference/endpoint/ethgetblocktransactioncountbynumber)
    """
    request: Request = Request(module=module, action=action)
    if chainid is not None:
      request['chainid'] = chainid
    if tag is not None:
      request['tag'] = tag
    return await self.request(
      request,
      method='GET',
      path='/v2/api',
      meta={'credentials': True},
      validate=validate,
      request_type=Request,
      response_type=EtherscanJsonRpcResponse,
    )
