# Generated by typed-dev — see CONTRIBUTING.md.
from .announcement import Announcement
from .execution import Execution
from .instrument import Instrument
from .klines import Klines
from .orderbook_increment import OrderbookIncrement
from .orderbook_level5 import OrderbookLevel5
from .orderbook_level50 import OrderbookLevel50
from .symbol_snapshot import SymbolSnapshot
from .ticker_v1 import TickerV1
from .ticker_v2 import TickerV2


class FuturesPublic(
  Announcement,
  Execution,
  Instrument,
  Klines,
  OrderbookIncrement,
  OrderbookLevel5,
  OrderbookLevel50,
  SymbolSnapshot,
  TickerV1,
  TickerV2,
):
  """Futures Trading (Classic) — public, unauthenticated market-data push channels: ticker (v1/v2), incremental and leveled order books, klines, trade execution, symbol snapshot, instrument (mark/index price), and announcements.

  References:
    - [Upstream docs](https://www.kucoin.com/docs-new/3470080w0)
  """
