# Generated by typed-dev — see CONTRIBUTING.md.
from decimal import Decimal
from typing_extensions import Literal, NotRequired, TypedDict
from typed_binance.core import TimestampMillis
from typed_binance.core.endpoint.rpc import RpcEndpoint


class Request(TypedDict):
  """Request parameters."""

  symbol: str
  """Symbol to query."""
  orderId: NotRequired[int]
  """Order ID to start from (inclusive) — orders with `orderId` >= this value are returned. If omitted, the most recent orders are returned."""
  startTime: NotRequired[TimestampMillis]
  """Start of the time range, in milliseconds. The range between `startTime` and `endTime` can't exceed 24 hours."""
  endTime: NotRequired[TimestampMillis]
  """End of the time range, in milliseconds. The range between `startTime` and `endTime` can't exceed 24 hours."""
  limit: NotRequired[int]
  """Maximum number of orders to return."""


class SpotOrder(TypedDict):
  """A spot order, in the shape returned by order-query endpoints."""

  symbol: str
  """Symbol this order was placed on."""
  orderId: int
  """Order ID assigned by Binance."""
  orderListId: int
  """ID of the order list this order belongs to, or -1 if it is not part of one."""
  clientOrderId: str
  """Client-supplied order ID."""
  price: Decimal
  """Order price, as a decimal string."""
  origQty: Decimal
  """Original order quantity, as a decimal string."""
  executedQty: Decimal
  """Quantity that has been filled, as a decimal string."""
  cummulativeQuoteQty: Decimal
  """Cumulative quote asset quantity filled, as a decimal string. For some historical orders this is negative, meaning the data is not available."""
  status: Literal[
    'NEW',
    'PENDING_NEW',
    'PARTIALLY_FILLED',
    'FILLED',
    'CANCELED',
    'PENDING_CANCEL',
    'REJECTED',
    'EXPIRED',
    'EXPIRED_IN_MATCH',
  ]
  """Order status."""
  timeInForce: Literal['GTC', 'IOC', 'FOK']
  """Time in force."""
  type: Literal[
    'LIMIT',
    'MARKET',
    'STOP_LOSS',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT',
    'TAKE_PROFIT_LIMIT',
    'LIMIT_MAKER',
  ]
  """Order type."""
  side: Literal['BUY', 'SELL']
  """Order side."""
  stopPrice: Decimal
  """Stop price, as a decimal string. `0.0` when not a stop/take-profit order."""
  icebergQty: Decimal
  """Iceberg order quantity, as a decimal string. `0.0` when not an iceberg order."""
  time: TimestampMillis
  """Millisecond timestamp the order was created."""
  updateTime: TimestampMillis
  """Millisecond timestamp the order was last updated."""
  isWorking: bool
  """Whether the order is currently working on the order book."""
  origQuoteOrderQty: Decimal
  """Original quote order quantity, as a decimal string."""
  workingTime: TimestampMillis
  """Millisecond timestamp the order started working on the order book."""
  selfTradePreventionMode: Literal[
    'NONE', 'EXPIRE_MAKER', 'EXPIRE_TAKER', 'EXPIRE_BOTH', 'DECREMENT', 'TRANSFER'
  ]
  """Self-trade prevention mode applied to this order."""


Response = list[SpotOrder]


class AllOrders(RpcEndpoint):
  """Get all account orders on a symbol — active, canceled, or filled. If `orderId` is set, orders with `orderId` >= that value are returned; otherwise the most recent orders are returned. If `startTime` and/or `endTime` are provided, `orderId` is not required, but the time between `startTime` and `endTime` can't be longer than 24 hours."""

  async def all_orders(
    self,
    symbol: str,
    *,
    order_id: int | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> Response:
    """Get all account orders on a symbol — active, canceled, or filled. If `orderId` is set, orders with `orderId` >= that value are returned; otherwise the most recent orders are returned. If `startTime` and/or `endTime` are provided, `orderId` is not required, but the time between `startTime` and `endTime` can't be longer than 24 hours.

    Args:
      symbol: Symbol to query.
      order_id: Order ID to start from (inclusive) — orders with `orderId` >= this value are returned. If omitted, the most recent orders are returned.
      start_time: Start of the time range, in milliseconds. The range between `startTime` and `endTime` can't exceed 24 hours.
      end_time: End of the time range, in milliseconds. The range between `startTime` and `endTime` can't exceed 24 hours.
      limit: Maximum number of orders to return.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)
    """
    request: Request = Request(symbol=symbol)
    if order_id is not None:
      request['orderId'] = order_id
    if start_time is not None:
      request['startTime'] = start_time
    if end_time is not None:
      request['endTime'] = end_time
    if limit is not None:
      request['limit'] = limit
    return await self.request(
      request,
      method='GET',
      path='/api/v3/allOrders',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
