# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, TypedDict, cast
from typed_deribit.core.endpoint.rpc import RpcEndpoint


class Request(TypedDict):
  sid: int
  """Subaccount user id."""
  state: Literal['enable', 'disable']
  """Enable or disable direct login."""


Response = Literal['ok']


class ToggleSubaccountLogin(RpcEndpoint):
  """Enables or disables direct email/password login for a subaccount. When login is disabled, the subaccount is only reachable through the main account; disabling it while an active session exists for the subaccount immediately terminates that session. Requires two-factor authentication on the calling session."""

  async def toggle_subaccount_login(
    self,
    sid: int,
    *,
    state: Literal['enable', 'disable'],
    validate: bool | None = None,
    transport: Literal['http', 'ws'] = 'http',
  ) -> Response:
    """Enables or disables direct email/password login for a subaccount. When login is disabled, the subaccount is only reachable through the main account; disabling it while an active session exists for the subaccount immediately terminates that session. Requires two-factor authentication on the calling session.

    Args:
      sid: Subaccount user id.
      state: Enable or disable direct login.
      validate: Override this call's response validation; falls back to the client-level default when omitted.
      transport: Transport to send this call over. Defaults to 'http'.

    References:
      - [Official docs](https://docs.deribit.com/api-reference/account-management/private-toggle_subaccount_login)
    """
    return await self.request(
      Request(sid=sid, state=state),
      method='POST',
      path='private/toggle_subaccount_login',
      meta={},
      validate=validate,
      transport=transport,
      request_type=Request,
      response_type=cast(type, Response),
    )
