# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import TypedDict
from typed_kucoin.core.endpoint.rpc import RpcEndpoint
from typed_kucoin.schemas import ConvertOrderResult


class Request(TypedDict):
  """Parameters to execute a market currency conversion."""

  clientOrderId: str
  """Client-chosen order id, unique per account."""
  quoteId: str
  """Quote id from a prior Get Convert Quote call."""
  accountType: str
  """Account to draw from and settle into, for example `BOTH`. KuCoin does not publish a closed set for this field in an accessible parameter table, so it's left as a plain string rather than a guessed enum."""


class AddOrder(RpcEndpoint):
  """Execute a market currency conversion at a previously fetched quote's price."""

  async def add_order(
    self,
    *,
    client_order_id: str,
    quote_id: str,
    account_type: str,
    validate: bool | None = None,
  ) -> ConvertOrderResult:
    """Execute a market currency conversion at a previously fetched quote's price.

    Args:
      client_order_id: Client-chosen order id, unique per account.
      quote_id: Quote id from a prior Get Convert Quote call.
      account_type: Account to draw from and settle into, for example `BOTH`. KuCoin does not publish a closed set for this field in an accessible parameter table, so it's left as a plain string rather than a guessed enum.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://www.kucoin.com/docs-new/rest/convert/add-convert-order)
    """
    return await self.request(
      Request(
        clientOrderId=client_order_id, quoteId=quote_id, accountType=account_type
      ),
      method='POST',
      path='/api/v1/convert/order',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=ConvertOrderResult,
    )
