# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_core.validation import validator
from typed_binance.core import TimestampMillis, timestamp_millis
from typed_binance.core.endpoint.rpc import RpcEndpoint


class BlockTradeOrderLeg(TypedDict):
  """One leg of the block trade order as accepted by the venue."""

  symbol: NotRequired[str]
  """Option trading pair, formatted UNDERLYING-EXPIRYDATE-STRIKE-C|P, e.g. BTC-260925-145000-C (a BTC call expiring 2026-09-25 with strike 145000)."""
  side: NotRequired[Literal['BUY', 'SELL']]
  """Buy/sell direction."""
  quantity: NotRequired[str]
  """Order quantity."""
  price: NotRequired[str]
  """Order price."""


class BlockTradeOrder(TypedDict):
  """One block trade order."""

  blockTradeSettlementKey: NotRequired[str]
  """Key identifying this block trade for settlement/counterparty acceptance."""
  expireTime: NotRequired[TimestampMillis]
  """Time the block trade order expires if not accepted."""
  liquidity: NotRequired[Literal['MAKER', 'TAKER']]
  """Whether this side of the block trade is the maker or the taker."""
  status: NotRequired[str]
  """Block trade order status."""
  createTime: NotRequired[TimestampMillis]
  """Time the block trade order was created."""
  legs: NotRequired[list[BlockTradeOrderLeg]]
  """Legs of the block trade order."""


class OrdersQuery(RpcEndpoint):
  """Check block trade order status."""

  async def orders_query(
    self,
    *,
    block_order_matching_key: str | None = None,
    start_time: TimestampMillis | None = None,
    end_time: TimestampMillis | None = None,
    underlying: str | None = None,
    validate: bool | None = None,
  ) -> list[BlockTradeOrder]:
    """Check block trade order status.

    Args:
      block_order_matching_key: If specified, returns the specific block trade associated with this matching key.
      start_time: Start time.
      end_time: End time.
      underlying: Underlying asset, e.g. BTCUSDT.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-options/api/rest-api/market-maker-block-trade#query-block-trade-order)
    """
    params = {}
    if block_order_matching_key is not None:
      params['blockOrderMatchingKey'] = block_order_matching_key
    if start_time is not None:
      params['startTime'] = timestamp_millis.dump(start_time)
    if end_time is not None:
      params['endTime'] = timestamp_millis.dump(end_time)
    if underlying is not None:
      params['underlying'] = underlying
    _Response = list[BlockTradeOrder]
    _validator = validator[_Response](_Response)
    return await self.authed_request(
      'GET',
      '/eapi/v1/block/order/orders',
      params=params,
      validator=_validator,
      validate=validate,
    )
