# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import Literal, NotRequired, TypedDict
from typed_binance.core.endpoint.ws_rpc import WsRpcEndpoint


class CommissionDiscount(TypedDict):
  """Discount applied to standard commissions when paying fees in BNB."""

  enabledForAccount: bool
  """Whether the BNB fee discount is enabled for the account."""
  enabledForSymbol: bool
  """Whether the BNB fee discount is enabled for the symbol."""
  discountAsset: str
  """Asset the discount is denominated in."""
  discount: str
  """Rate the standard commission is reduced by when paying in discountAsset."""


class LimitMakerOrder(TypedDict):
  """A limit order that is rejected if it would immediately match as a taker. Requires quantity and price. If pegPriceType is set, price is not required by the venue despite being listed here as required; see the pegged-order notes below."""

  symbol: str
  """Trading pair symbol."""
  side: Literal['BUY', 'SELL']
  """Order side."""
  type: Literal['LIMIT_MAKER']
  """Order type."""
  quantity: str
  """Order quantity, in the base asset."""
  price: str
  """Order price. Required for LIMIT, STOP_LOSS_LIMIT, TAKE_PROFIT_LIMIT and LIMIT_MAKER orders, unless pegPriceType is set."""
  newClientOrderId: NotRequired[str]
  """Caller-supplied id for the order. Automatically generated if not sent. An order sharing a newClientOrderId with an existing one is only accepted once the existing order has filled."""
  strategyId: NotRequired[int]
  """Id labeling the order strategy this order is part of."""
  strategyType: NotRequired[int]
  """Type labeling the order strategy this order is part of. Cannot be less than 1000000."""
  newOrderRespType: NotRequired[Literal['ACK', 'RESULT', 'FULL']]
  """Response shape to return. MARKET and LIMIT orders default to FULL; all other order types default to ACK."""
  selfTradePreventionMode: NotRequired[
    Literal[
      'NONE', 'EXPIRE_MAKER', 'EXPIRE_TAKER', 'EXPIRE_BOTH', 'DECREMENT', 'TRANSFER'
    ]
  ]
  """Self-trade prevention mode. The allowed values depend on the symbol's configuration."""
  pegPriceType: NotRequired[Literal['PRIMARY_PEG', 'MARKET_PEG']]
  """Peg reference for a pegged order: the best same-side price (PRIMARY_PEG) or the best opposite-side price (MARKET_PEG). Usable with LIMIT, LIMIT_MAKER, STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT orders; makes price optional when set."""
  pegOffsetValue: NotRequired[int]
  """Price level offset from the peg reference, up to 100. Must be sent together with pegOffsetType."""
  pegOffsetType: NotRequired[Literal['PRICE_LEVEL']]
  """Peg offset type. Only PRICE_LEVEL is supported. Must be sent together with pegOffsetValue."""
  computeCommissionRates: NotRequired[bool]
  """Return the commission rates that would apply to the order, at 20x the weight. Default: false."""


class LimitOrder(TypedDict):
  """A limit order: filled at price or better. Requires timeInForce, quantity and price. If pegPriceType is set, price is not required by the venue despite being listed here as required by this variant's own required fields -- see the pegged-order notes below; this spec keeps price required for the common, non-pegged case rather than adding a further pegged/non-pegged split."""

  symbol: str
  """Trading pair symbol."""
  side: Literal['BUY', 'SELL']
  """Order side."""
  type: Literal['LIMIT']
  """Order type."""
  timeInForce: Literal['GTC', 'IOC', 'FOK']
  """Time in force. Required for LIMIT, STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT orders."""
  quantity: str
  """Order quantity, in the base asset."""
  price: str
  """Order price. Required for LIMIT, STOP_LOSS_LIMIT, TAKE_PROFIT_LIMIT and LIMIT_MAKER orders, unless pegPriceType is set."""
  newClientOrderId: NotRequired[str]
  """Caller-supplied id for the order. Automatically generated if not sent. An order sharing a newClientOrderId with an existing one is only accepted once the existing order has filled."""
  strategyId: NotRequired[int]
  """Id labeling the order strategy this order is part of."""
  strategyType: NotRequired[int]
  """Type labeling the order strategy this order is part of. Cannot be less than 1000000."""
  icebergQty: NotRequired[str]
  """Quantity per leg of an iceberg order. Usable with LIMIT, STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT orders; any order carrying it must set timeInForce to GTC."""
  newOrderRespType: NotRequired[Literal['ACK', 'RESULT', 'FULL']]
  """Response shape to return. MARKET and LIMIT orders default to FULL; all other order types default to ACK."""
  selfTradePreventionMode: NotRequired[
    Literal[
      'NONE', 'EXPIRE_MAKER', 'EXPIRE_TAKER', 'EXPIRE_BOTH', 'DECREMENT', 'TRANSFER'
    ]
  ]
  """Self-trade prevention mode. The allowed values depend on the symbol's configuration."""
  pegPriceType: NotRequired[Literal['PRIMARY_PEG', 'MARKET_PEG']]
  """Peg reference for a pegged order: the best same-side price (PRIMARY_PEG) or the best opposite-side price (MARKET_PEG). Usable with LIMIT, LIMIT_MAKER, STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT orders; makes price optional when set."""
  pegOffsetValue: NotRequired[int]
  """Price level offset from the peg reference, up to 100. Must be sent together with pegOffsetType."""
  pegOffsetType: NotRequired[Literal['PRICE_LEVEL']]
  """Peg offset type. Only PRICE_LEVEL is supported. Must be sent together with pegOffsetValue."""
  computeCommissionRates: NotRequired[bool]
  """Return the commission rates that would apply to the order, at 20x the weight. Default: false."""


class MarketOrder(TypedDict):
  """A market order: filled immediately at the best available price(s). Requires quantity (in the base asset) or quoteOrderQty (in the quote asset) -- the venue requires at least one of the two, which this variant leaves both optional to express rather than splitting further into quantity-only/quoteOrderQty-only sub-variants."""

  symbol: str
  """Trading pair symbol."""
  side: Literal['BUY', 'SELL']
  """Order side."""
  type: Literal['MARKET']
  """Order type."""
  quantity: NotRequired[str]
  """Order quantity, in the base asset."""
  quoteOrderQty: NotRequired[str]
  """Order quantity, in the quote asset. Usable in place of quantity for MARKET orders."""
  newClientOrderId: NotRequired[str]
  """Caller-supplied id for the order. Automatically generated if not sent. An order sharing a newClientOrderId with an existing one is only accepted once the existing order has filled."""
  strategyId: NotRequired[int]
  """Id labeling the order strategy this order is part of."""
  strategyType: NotRequired[int]
  """Type labeling the order strategy this order is part of. Cannot be less than 1000000."""
  newOrderRespType: NotRequired[Literal['ACK', 'RESULT', 'FULL']]
  """Response shape to return. MARKET and LIMIT orders default to FULL; all other order types default to ACK."""
  selfTradePreventionMode: NotRequired[
    Literal[
      'NONE', 'EXPIRE_MAKER', 'EXPIRE_TAKER', 'EXPIRE_BOTH', 'DECREMENT', 'TRANSFER'
    ]
  ]
  """Self-trade prevention mode. The allowed values depend on the symbol's configuration."""
  computeCommissionRates: NotRequired[bool]
  """Return the commission rates that would apply to the order, at 20x the weight. Default: false."""


class OrderTestEmpty(TypedDict):
  """Empty response when computeCommissionRates is false or omitted."""


class SpecialCommissionRates(TypedDict):
  """Special commission rates on trades from the order."""

  maker: str
  """Maker commission rate."""
  taker: str
  """Taker commission rate."""


class StandardCommissionRates(TypedDict):
  """Standard commission rates on trades from the order."""

  maker: str
  """Maker commission rate."""
  taker: str
  """Taker commission rate."""


class StopLossLimitOrder(TypedDict):
  """A stop-loss order that becomes a limit order once stopPrice trades. Requires timeInForce, quantity and price, and either stopPrice or trailingDelta -- the venue requires at least one of the two, which this variant leaves both optional to express. If pegPriceType is set, price is not required by the venue despite being listed here as required; see the pegged-order notes below."""

  symbol: str
  """Trading pair symbol."""
  side: Literal['BUY', 'SELL']
  """Order side."""
  type: Literal['STOP_LOSS_LIMIT']
  """Order type."""
  timeInForce: Literal['GTC', 'IOC', 'FOK']
  """Time in force. Required for LIMIT, STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT orders."""
  quantity: str
  """Order quantity, in the base asset."""
  price: str
  """Order price. Required for LIMIT, STOP_LOSS_LIMIT, TAKE_PROFIT_LIMIT and LIMIT_MAKER orders, unless pegPriceType is set."""
  stopPrice: NotRequired[str]
  """Price at which a STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT or TAKE_PROFIT_LIMIT order triggers."""
  trailingDelta: NotRequired[int]
  """Delta for a trailing stop order, combinable with stopPrice."""
  icebergQty: NotRequired[str]
  """Quantity per leg of an iceberg order. Usable with LIMIT, STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT orders; any order carrying it must set timeInForce to GTC."""
  newClientOrderId: NotRequired[str]
  """Caller-supplied id for the order. Automatically generated if not sent. An order sharing a newClientOrderId with an existing one is only accepted once the existing order has filled."""
  strategyId: NotRequired[int]
  """Id labeling the order strategy this order is part of."""
  strategyType: NotRequired[int]
  """Type labeling the order strategy this order is part of. Cannot be less than 1000000."""
  newOrderRespType: NotRequired[Literal['ACK', 'RESULT', 'FULL']]
  """Response shape to return. MARKET and LIMIT orders default to FULL; all other order types default to ACK."""
  selfTradePreventionMode: NotRequired[
    Literal[
      'NONE', 'EXPIRE_MAKER', 'EXPIRE_TAKER', 'EXPIRE_BOTH', 'DECREMENT', 'TRANSFER'
    ]
  ]
  """Self-trade prevention mode. The allowed values depend on the symbol's configuration."""
  pegPriceType: NotRequired[Literal['PRIMARY_PEG', 'MARKET_PEG']]
  """Peg reference for a pegged order: the best same-side price (PRIMARY_PEG) or the best opposite-side price (MARKET_PEG). Usable with LIMIT, LIMIT_MAKER, STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT orders; makes price optional when set."""
  pegOffsetValue: NotRequired[int]
  """Price level offset from the peg reference, up to 100. Must be sent together with pegOffsetType."""
  pegOffsetType: NotRequired[Literal['PRICE_LEVEL']]
  """Peg offset type. Only PRICE_LEVEL is supported. Must be sent together with pegOffsetValue."""
  computeCommissionRates: NotRequired[bool]
  """Return the commission rates that would apply to the order, at 20x the weight. Default: false."""


class StopLossOrder(TypedDict):
  """A stop-loss order: becomes a market order once stopPrice trades. Requires quantity, and either stopPrice or trailingDelta -- the venue requires at least one of the two, which this variant leaves both optional to express."""

  symbol: str
  """Trading pair symbol."""
  side: Literal['BUY', 'SELL']
  """Order side."""
  type: Literal['STOP_LOSS']
  """Order type."""
  quantity: str
  """Order quantity, in the base asset."""
  stopPrice: NotRequired[str]
  """Price at which a STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT or TAKE_PROFIT_LIMIT order triggers."""
  trailingDelta: NotRequired[int]
  """Delta for a trailing stop order, combinable with stopPrice."""
  newClientOrderId: NotRequired[str]
  """Caller-supplied id for the order. Automatically generated if not sent. An order sharing a newClientOrderId with an existing one is only accepted once the existing order has filled."""
  strategyId: NotRequired[int]
  """Id labeling the order strategy this order is part of."""
  strategyType: NotRequired[int]
  """Type labeling the order strategy this order is part of. Cannot be less than 1000000."""
  newOrderRespType: NotRequired[Literal['ACK', 'RESULT', 'FULL']]
  """Response shape to return. MARKET and LIMIT orders default to FULL; all other order types default to ACK."""
  selfTradePreventionMode: NotRequired[
    Literal[
      'NONE', 'EXPIRE_MAKER', 'EXPIRE_TAKER', 'EXPIRE_BOTH', 'DECREMENT', 'TRANSFER'
    ]
  ]
  """Self-trade prevention mode. The allowed values depend on the symbol's configuration."""
  computeCommissionRates: NotRequired[bool]
  """Return the commission rates that would apply to the order, at 20x the weight. Default: false."""


class TakeProfitLimitOrder(TypedDict):
  """A take-profit order that becomes a limit order once stopPrice trades. Requires timeInForce, quantity and price, and either stopPrice or trailingDelta -- the venue requires at least one of the two, which this variant leaves both optional to express. If pegPriceType is set, price is not required by the venue despite being listed here as required; see the pegged-order notes below."""

  symbol: str
  """Trading pair symbol."""
  side: Literal['BUY', 'SELL']
  """Order side."""
  type: Literal['TAKE_PROFIT_LIMIT']
  """Order type."""
  timeInForce: Literal['GTC', 'IOC', 'FOK']
  """Time in force. Required for LIMIT, STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT orders."""
  quantity: str
  """Order quantity, in the base asset."""
  price: str
  """Order price. Required for LIMIT, STOP_LOSS_LIMIT, TAKE_PROFIT_LIMIT and LIMIT_MAKER orders, unless pegPriceType is set."""
  stopPrice: NotRequired[str]
  """Price at which a STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT or TAKE_PROFIT_LIMIT order triggers."""
  trailingDelta: NotRequired[int]
  """Delta for a trailing stop order, combinable with stopPrice."""
  icebergQty: NotRequired[str]
  """Quantity per leg of an iceberg order. Usable with LIMIT, STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT orders; any order carrying it must set timeInForce to GTC."""
  newClientOrderId: NotRequired[str]
  """Caller-supplied id for the order. Automatically generated if not sent. An order sharing a newClientOrderId with an existing one is only accepted once the existing order has filled."""
  strategyId: NotRequired[int]
  """Id labeling the order strategy this order is part of."""
  strategyType: NotRequired[int]
  """Type labeling the order strategy this order is part of. Cannot be less than 1000000."""
  newOrderRespType: NotRequired[Literal['ACK', 'RESULT', 'FULL']]
  """Response shape to return. MARKET and LIMIT orders default to FULL; all other order types default to ACK."""
  selfTradePreventionMode: NotRequired[
    Literal[
      'NONE', 'EXPIRE_MAKER', 'EXPIRE_TAKER', 'EXPIRE_BOTH', 'DECREMENT', 'TRANSFER'
    ]
  ]
  """Self-trade prevention mode. The allowed values depend on the symbol's configuration."""
  pegPriceType: NotRequired[Literal['PRIMARY_PEG', 'MARKET_PEG']]
  """Peg reference for a pegged order: the best same-side price (PRIMARY_PEG) or the best opposite-side price (MARKET_PEG). Usable with LIMIT, LIMIT_MAKER, STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT orders; makes price optional when set."""
  pegOffsetValue: NotRequired[int]
  """Price level offset from the peg reference, up to 100. Must be sent together with pegOffsetType."""
  pegOffsetType: NotRequired[Literal['PRICE_LEVEL']]
  """Peg offset type. Only PRICE_LEVEL is supported. Must be sent together with pegOffsetValue."""
  computeCommissionRates: NotRequired[bool]
  """Return the commission rates that would apply to the order, at 20x the weight. Default: false."""


class TakeProfitOrder(TypedDict):
  """A take-profit order: becomes a market order once stopPrice trades. Requires quantity, and either stopPrice or trailingDelta -- the venue requires at least one of the two, which this variant leaves both optional to express."""

  symbol: str
  """Trading pair symbol."""
  side: Literal['BUY', 'SELL']
  """Order side."""
  type: Literal['TAKE_PROFIT']
  """Order type."""
  quantity: str
  """Order quantity, in the base asset."""
  stopPrice: NotRequired[str]
  """Price at which a STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT or TAKE_PROFIT_LIMIT order triggers."""
  trailingDelta: NotRequired[int]
  """Delta for a trailing stop order, combinable with stopPrice."""
  newClientOrderId: NotRequired[str]
  """Caller-supplied id for the order. Automatically generated if not sent. An order sharing a newClientOrderId with an existing one is only accepted once the existing order has filled."""
  strategyId: NotRequired[int]
  """Id labeling the order strategy this order is part of."""
  strategyType: NotRequired[int]
  """Type labeling the order strategy this order is part of. Cannot be less than 1000000."""
  newOrderRespType: NotRequired[Literal['ACK', 'RESULT', 'FULL']]
  """Response shape to return. MARKET and LIMIT orders default to FULL; all other order types default to ACK."""
  selfTradePreventionMode: NotRequired[
    Literal[
      'NONE', 'EXPIRE_MAKER', 'EXPIRE_TAKER', 'EXPIRE_BOTH', 'DECREMENT', 'TRANSFER'
    ]
  ]
  """Self-trade prevention mode. The allowed values depend on the symbol's configuration."""
  computeCommissionRates: NotRequired[bool]
  """Return the commission rates that would apply to the order, at 20x the weight. Default: false."""


class TaxCommissionRates(TypedDict):
  """Tax commission rates for trades from the order."""

  maker: str
  """Maker commission rate."""
  taker: str
  """Taker commission rate."""


class OrderTestCommission(TypedDict):
  """Estimated commission rates for the order, returned when computeCommissionRates is true."""

  standardCommissionForOrder: StandardCommissionRates
  specialCommissionForOrder: SpecialCommissionRates
  taxCommissionForOrder: TaxCommissionRates
  discount: CommissionDiscount


Request = (
  LimitOrder
  | MarketOrder
  | StopLossOrder
  | StopLossLimitOrder
  | TakeProfitOrder
  | TakeProfitLimitOrder
  | LimitMakerOrder
)


Response = OrderTestEmpty | OrderTestCommission


class OrderTest(WsRpcEndpoint):
  """Test order placement. Validates new order parameters and verifies the signature but does not send the order into the matching engine. Accepts every parameter order.place does, plus computeCommissionRates. Additional parameters become mandatory depending on type, the same as order.place: LIMIT requires timeInForce, quantity and price; MARKET requires quantity or quoteOrderQty; STOP_LOSS and TAKE_PROFIT require quantity and either stopPrice or trailingDelta; STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT require timeInForce, quantity, price and either stopPrice or trailingDelta; LIMIT_MAKER requires quantity and price. See upstream.md for the full type-conditional parameter table and Pegged Orders notes."""

  async def order_test(
    self,
    trading_order_test_request: Request,
    *,
    validate: bool | None = None,
  ) -> Response:
    """Test order placement. Validates new order parameters and verifies the signature but does not send the order into the matching engine. Accepts every parameter order.place does, plus computeCommissionRates. Additional parameters become mandatory depending on type, the same as order.place: LIMIT requires timeInForce, quantity and price; MARKET requires quantity or quoteOrderQty; STOP_LOSS and TAKE_PROFIT require quantity and either stopPrice or trailingDelta; STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT require timeInForce, quantity, price and either stopPrice or trailingDelta; LIMIT_MAKER requires quantity and price. See upstream.md for the full type-conditional parameter table and Pegged Orders notes.

    Args:
      trading_order_test_request:
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md#test-new-order-trade)
    """
    return await self.request(
      trading_order_test_request,
      path='order.test',
      meta={'security': 'TRADE', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
