# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_binance.core.endpoint.rpc import RpcEndpoint


class FlexibleLoanBorrowOrder(TypedDict):
  """The submitted flexible rate crypto loan borrow order."""

  loanCoin: NotRequired[str]
  """Borrowed coin."""
  loanAmount: NotRequired[str]
  """Borrowed amount."""
  collateralCoin: NotRequired[str]
  """Collateral coin."""
  collateralAmount: NotRequired[str]
  """Pledged collateral amount."""
  status: NotRequired[str]
  """Borrow result."""


class Request(TypedDict):
  """Request parameters."""

  loanCoin: str
  """Coin to borrow."""
  collateralCoin: str
  """Collateral coin."""
  loanAmount: NotRequired[float]
  """Amount to borrow. Mandatory when `collateralAmount` is empty; the two are mutually exclusive ways of sizing the loan."""
  collateralAmount: NotRequired[float]
  """Amount of collateral to pledge. Mandatory when `loanAmount` is empty; the two are mutually exclusive ways of sizing the loan."""


class Borrow(RpcEndpoint):
  """Borrow a flexible rate crypto loan against collateral. Available for both master and sub-accounts."""

  async def borrow(
    self,
    *,
    loan_coin: str,
    collateral_coin: str,
    loan_amount: float | None = None,
    collateral_amount: float | None = None,
    validate: bool | None = None,
  ) -> FlexibleLoanBorrowOrder:
    """Borrow a flexible rate crypto loan against collateral. Available for both master and sub-accounts.

    Args:
      loan_coin: Coin to borrow.
      collateral_coin: Collateral coin.
      loan_amount: Amount to borrow. Mandatory when `collateralAmount` is empty; the two are mutually exclusive ways of sizing the loan.
      collateral_amount: Amount of collateral to pledge. Mandatory when `loanAmount` is empty; the two are mutually exclusive ways of sizing the loan.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/investment-and-services-crypto-loan/api/rest-api/flexible-rate#flexible-loan-borrow)
    """
    request: Request = Request(loanCoin=loan_coin, collateralCoin=collateral_coin)
    if loan_amount is not None:
      request['loanAmount'] = loan_amount
    if collateral_amount is not None:
      request['collateralAmount'] = collateral_amount
    return await self.request(
      request,
      method='POST',
      path='/sapi/v2/loan/flexible/borrow',
      meta={'security': 'TRADE', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=FlexibleLoanBorrowOrder,
    )
