# Generated by typed-dev — see CONTRIBUTING.md.
"""Shapes shared by several endpoints of this client."""

from typing_extensions import Literal, NotRequired, TypedDict
from typed_lighter.core import (
  TimestampIso,
  TimestampMicros,
  TimestampMillis,
  TimestampSeconds,
)
from decimal import Decimal


class AccountAsset(TypedDict):
  """One spot asset balance of an account."""

  symbol: str
  """Asset symbol."""
  asset_id: int
  """Asset id (`1` ETH, `2` LIT, `3` USDC on both networks)."""
  balance: Decimal
  """Spot balance."""
  locked_balance: Decimal
  """Part of the balance locked by open spot orders."""
  margin_mode: Literal['enabled', 'disabled']
  """Whether the asset counts as perps margin."""
  margin_balance: Decimal
  """Balance counted as perps margin (USDC collateral in a unified account)."""
  multiplier: Decimal
  """Balance multiplier; `1` for most assets, above `1` for interest-bearing ones."""


class AccountPosition(TypedDict):
  """One market entry of an account's positions, including markets it only traded before."""

  market_id: int
  """Market id."""
  symbol: str
  """Market symbol."""
  initial_margin_fraction: Decimal
  """Initial margin fraction set for this market, in percent (`5.00` = 20x leverage)."""
  open_order_count: int
  """Open orders in this market."""
  pending_order_count: int
  """Untriggered conditional orders in this market."""
  position_tied_order_count: int
  """Orders tied to the position (reduce-only stop-loss/take-profit)."""
  sign: Literal[-1, 1]
  """`1` for long, `-1` for short (also `1` on a flat entry)."""
  position: Decimal
  """Position size, in base units (unsigned; see `sign`)."""
  avg_entry_price: Decimal
  """Average entry price."""
  position_value: Decimal
  """Position value at the mark price."""
  unrealized_pnl: Decimal
  """Unrealized PnL."""
  realized_pnl: Decimal
  """Realized PnL."""
  liquidation_price: Decimal
  """Estimated liquidation price; `0` when none."""
  total_funding_paid_out: NotRequired[Decimal]
  """Cumulative funding paid out on this position; absent on markets the account never held."""
  margin_mode: Literal[0, 1]
  """`0` cross margin, `1` isolated margin (lighter-go's position margin modes `CrossMargin`/`IsolatedMargin`)."""
  margin_set_flag: int
  """Whether leverage/margin settings were set for this market (`1`), meaning it was traded at least once."""
  allocated_margin: Decimal
  """Isolated margin allocated to the position (`0` in cross mode)."""
  total_discount: NotRequired[Decimal]
  """Total funding discount."""


class BurnedSharesPubData(TypedDict):
  """Public-pool shares redeemed (`BurnedShares`)."""

  account_index: int
  """Account redeeming the shares."""
  public_pool_index: int
  """Public pool account index."""
  shares_to_burn: int
  """Shares redeemed."""
  shares_to_burn_usdc: Decimal
  """USDC value of the redeemed shares."""
  operator_fee_share_amount: Decimal
  """Shares paid to the pool operator as fee."""


class Candle(TypedDict):
  """One OHLCV candle. The venue documents that zero values are omitted, so every field but `t` is optional."""

  t: TimestampMillis
  """Open time of the candle."""
  o: NotRequired[float]
  """Open price; omitted when zero."""
  h: NotRequired[float]
  """High price; omitted when zero."""
  l: NotRequired[float]
  """Low price; omitted when zero."""
  c: NotRequired[float]
  """Close price; omitted when zero."""
  v: NotRequired[float]
  """Volume in base units; omitted when zero."""
  V: NotRequired[float]
  """Volume in quote units; omitted when zero."""
  i: NotRequired[int]
  """Id of the last trade in the candle; omitted when zero."""


class DeleveragePubData(TypedDict):
  """An auto-deleverage (`Deleverage`)."""

  bankrupt_account_index: int
  """Bankrupt account index."""
  deleverager_account_index: int
  """Account taking over the position."""
  is_taker_ask: int
  """`1` when the bankrupt side sold, `0` when it bought, as observed; Lighter types it as a bare integer and documents no value set."""
  market_index: int
  """Market id."""
  quote: Decimal
  """Quote amount of the deleveraged position."""
  size: Decimal
  """Deleveraged size, in base units."""


class DeleveragePubDataWithFunding(TypedDict):
  """An auto-deleverage that also settled funding (`DeleverageWithFunding`)."""

  bankrupt_account_index: int
  """Bankrupt account index."""
  deleverager_account_index: int
  """Account taking over the position (the LLP on every observed log)."""
  is_taker_ask: int
  """`1` when the bankrupt side sold, `0` when it bought, as observed; Lighter types it as a bare integer and documents no value set."""
  market_index: int
  """Market id."""
  quote: Decimal
  """Quote amount of the deleveraged position (observed as a whole number, in quote base units)."""
  size: Decimal
  """Deleveraged size, in base units."""
  funding_rate_prefix_sum: int
  """Cumulative funding-rate index of the market at execution, in the venue's fixed-point integer units."""


class EnrichedTx(TypedDict):
  """One L2 transaction looked up by hash or sequence index, with its L1 commit/verify times."""

  code: int
  """`200` on success."""
  message: NotRequired[str]
  """Optional detail message."""
  hash: str
  """Transaction hash (hex). L1 priority and internal transactions carry a synthetic, zero-padded hash."""
  type: int
  """Transaction type (`tx_type`): 1-7, 30-32, 37 and 38 are L1 priority operations (1 = deposit); 8-20, 28, 29, 35, 36, 41 and 42 are user L2 transactions (8 change pub key, 9 create sub-account, 12 transfer, 14 create order, 15 cancel order, 20 update leverage, ...); 21-27 are internal sequencer operations (claim, cancel, deleverage, exit, cancel-all, liquidate, create order). Observed live as `0` for an L2ApproveIntegrator (type 45) transaction."""
  info: str
  """The transaction itself, JSON-encoded: the Go `L2*TxInfo` struct of its type (e.g. `AccountIndex`, `MarketIndex`, `Nonce`, `Sig`), as signed."""
  event_info: str
  """What executing the transaction did, JSON-encoded with compact keys (e.g. a trade `t`, the maker order `mo` and taker order `to` of a fill); empty for some types."""
  status: Literal[0, 1, 2, 3]
  """Transaction status: `0` failed, `1` pending (queued, not yet executed), `2` executed, `3` final: executed and settled, no longer changing (the venue's docs call it "Pending - Final State")."""
  transaction_index: int
  """Position of the transaction within its block."""
  l1_address: str
  """L1 address of the account that sent the transaction."""
  account_index: int
  """Account that sent the transaction."""
  nonce: int
  """Nonce of the signing API key; `-1` for L1 priority and internal transactions. Some clients use timestamps as nonces with skip-nonce."""
  expire_at: int
  """When the sequencer stops accepting the transaction, in epoch milliseconds (`ExpiredAt`); `9223372036854775807` (int64 max) for L1 priority and internal transactions that never expire, so it is kept a plain integer."""
  block_height: int
  """Height of the block that includes the transaction."""
  queued_at: TimestampMillis
  """When the sequencer queued the transaction."""
  executed_at: TimestampMillis
  """When the transaction was executed."""
  sequence_index: int
  """Global, strictly increasing (but sparse) sequence number of the transaction; `txs`/`accountTxs` paginate on it."""
  parent_hash: str
  """Hash of the transaction that triggered this one (internal transactions such as a fill claim or a triggered cancel); empty otherwise."""
  api_key_index: int
  """API key that signed the transaction; `0` for deposits and `255` for internal transactions."""
  transaction_time: TimestampMicros
  """When the transaction was processed."""
  committed_at: int
  """When the block holding the transaction was committed on L1; `0` when not reported. The unit is undocumented."""
  verified_at: int
  """When the block holding the transaction was verified on L1; `0` when not reported. The unit is undocumented."""


class ExecutedPendingUnlockPubData(TypedDict):
  """A pending unlock (e.g. unstaked LIT) released to the account (`ExecutedPendingUnlock`)."""

  account_index: int
  """Account index."""
  asset_symbol: str
  """Released asset symbol."""
  amount: Decimal
  """Amount released, in asset units."""


class ExitPositionPubData(TypedDict):
  """A position closed at settlement when a market is delisted (`ExitPosition`)."""

  account_index: int
  """Account index."""
  market_index: int
  """Market id."""
  settlement_price: Decimal
  """Settlement price."""


class ExitPositionPubDataWithFunding(TypedDict):
  """A position closed at settlement that also settled funding (`ExitPositionWithFunding`)."""

  account_index: int
  """Account index."""
  market_index: int
  """Market id."""
  settlement_price: Decimal
  """Settlement price."""
  funding_rate_prefix_sum: int
  """Cumulative funding-rate index of the market at execution, in the venue's fixed-point integer units."""


class ExplorerAsset(TypedDict):
  """A spot balance."""

  asset_id: int
  """Asset id."""
  symbol: str
  """Asset symbol."""
  balance: Decimal
  """Balance, in asset units."""
  locked_balance: Decimal
  """Balance locked in open orders, in asset units."""


class ExplorerBatchBlock(TypedDict):
  """A block of a batch."""

  block_number: int
  """Block height."""
  updated_at: TimestampIso
  """When the block was produced."""
  total_transactions: int
  """Transactions in the block."""


class ExplorerBatchDetails(TypedDict):
  """L1 transactions of a batch."""

  commit_tx_hash: str | None
  """L1 commit transaction hash; `null` until committed."""
  verify_tx_hash: str | None
  """L1 verify transaction hash; `null` until verified."""
  execute_tx_hash: str | None
  """L1 execute transaction hash; `null` until executed."""


class ExplorerBatchStatusChange(TypedDict):
  """One L1 status transition of a batch."""

  batch_status: Literal['nothing_to_execute', 'committed', 'verified', 'executed']
  """Status reached."""
  hash: str
  """L1 transaction hash that caused it."""
  updated_at: TimestampIso
  """When it happened."""


class ExplorerMarketState(TypedDict):
  """Market state at a block."""

  market_index: int
  """Market id."""
  market_price: Decimal
  """Mark price."""
  index_price: Decimal
  """Index price."""
  open_interest: Decimal
  """Open interest, in base units."""
  last_funding_rate: Decimal
  """Last funding rate."""


class ExplorerPosition(TypedDict):
  """An open position."""

  market_index: int
  """Market id."""
  side: Literal['short', 'long']
  """Position side."""
  size: Decimal
  """Signed size, in base units (negative for shorts)."""
  entry_price: Decimal
  """Average entry price."""
  pnl: Decimal
  """Unrealized PnL, in USDC."""


class ExportData(TypedDict):
  """Link to an exported file."""

  code: int
  """`200` on success."""
  message: NotRequired[str]
  """Optional human-readable detail; usually absent on success."""
  data_url: str
  """Link to the exported file; its format and lifetime depend on the endpoint."""


class GroupLimitOrder(TypedDict):
  """A limit primary, resting (good-till-time, post-only) or immediate-or-cancel."""

  order_type: Literal['limit']
  """Order type."""
  market_index: int
  """Market id (`orderBooks` `market_id`); the whole group trades it."""
  base_amount: int
  """Order size in base units, scaled by the market's `supported_size_decimals`."""
  is_ask: bool
  """True to sell, false to buy."""
  price: int
  """Limit price, scaled by the market's `supported_price_decimals`."""
  time_in_force: Literal['good-till-time', 'post-only', 'immediate-or-cancel']
  """Time in force. A resting primary shares the group's `order_expiry`; an `immediate-or-cancel` one has none."""
  client_order_index: NotRequired[int]
  """Caller-chosen order id (uint48), unique within the group and among the account's open orders."""
  reduce_only: NotRequired[bool]
  """Only ever reduce the position. Defaults to false."""


class GroupMarketOrder(TypedDict):
  """A market primary: immediate-or-cancel, bounded by a worst acceptable price."""

  order_type: Literal['market']
  """Order type."""
  market_index: int
  """Market id (`orderBooks` `market_id`); the whole group trades it."""
  base_amount: int
  """Order size in base units, scaled by the market's `supported_size_decimals`."""
  is_ask: bool
  """True to sell, false to buy."""
  price: int
  """Worst acceptable execution price, scaled by the market's `supported_price_decimals`."""
  client_order_index: NotRequired[int]
  """Caller-chosen order id (uint48), unique within the group and among the account's open orders."""
  reduce_only: NotRequired[bool]
  """Only ever reduce the position. Defaults to false."""


class L1CreateMarketPubData(TypedDict):
  """A perp market created (`L1CreateMarket`)."""

  market_index: int
  """Market id."""
  quote_multiplier: int
  """Quote multiplier."""
  taker_fee: int
  """Taker fee, fixed-point."""
  maker_fee: int
  """Maker fee, fixed-point."""
  liquidation_fee: int
  """Liquidation fee, fixed-point."""
  min_base_amount: int
  """Minimum order size, scaled."""
  min_quote_amount: int
  """Minimum order notional, scaled."""
  default_initial_margin_fraction: int
  """Default initial margin fraction, fixed-point."""
  min_initial_margin_fraction: int
  """Minimum initial margin fraction, fixed-point."""
  maintenance_margin_fraction: int
  """Maintenance margin fraction, fixed-point."""
  close_out_margin_fraction: int
  """Close-out margin fraction, fixed-point."""
  interest_rate: int
  """Interest rate, fixed-point."""


class L1CreateMarketPubDataV2(TypedDict):
  """A perp market created, v2 layout (`L1CreateMarketV2`)."""

  market_index: int
  """Market id."""
  quote_multiplier: int
  """Quote multiplier."""
  taker_fee: int
  """Taker fee, fixed-point."""
  maker_fee: int
  """Maker fee, fixed-point."""
  liquidation_fee: int
  """Liquidation fee, fixed-point."""
  min_base_amount: int
  """Minimum order size, scaled."""
  min_quote_amount: int
  """Minimum order notional, scaled."""
  order_quote_limit: int
  """Maximum order notional, scaled."""
  open_interest_limit: int
  """Open-interest cap, scaled."""
  default_initial_margin_fraction: int
  """Default initial margin fraction, fixed-point."""
  min_initial_margin_fraction: int
  """Minimum initial margin fraction, fixed-point."""
  maintenance_margin_fraction: int
  """Maintenance margin fraction, fixed-point."""
  close_out_margin_fraction: int
  """Close-out margin fraction, fixed-point."""
  interest_rate: int
  """Interest rate, fixed-point."""
  funding_clamp_small: int
  """Small funding clamp, fixed-point."""
  funding_clamp_big: int
  """Big funding clamp, fixed-point."""


class L1CreateSpotMarketPubData(TypedDict):
  """A spot market created (`L1CreateSpotMarket`)."""

  market_index: int
  """Market id."""
  base_asset_id: int
  """Base asset id."""
  quote_asset_id: int
  """Quote asset id."""
  size_extension_multiplier: int
  """Size extension multiplier."""
  quote_extension_multiplier: int
  """Quote extension multiplier."""
  taker_fee: int
  """Taker fee, fixed-point."""
  maker_fee: int
  """Maker fee, fixed-point."""
  min_base_amount: int
  """Minimum order size, scaled."""
  min_quote_amount: int
  """Minimum order notional, scaled."""
  order_quote_limit: int
  """Maximum order notional, scaled."""


class L1DepositPubData(TypedDict):
  """A USDC deposit from L1, legacy layout (`L1Deposit`)."""

  account_index: int
  """Credited account index."""
  l1_address: str
  """Depositing L1 address."""
  usdc_amount: Decimal
  """USDC deposited."""


class L1DepositPubDataV2(TypedDict):
  """A deposit from L1 (`L1DepositV2`)."""

  account_index: int
  """Credited account index."""
  l1_address: str
  """Depositing L1 address."""
  asset_index: str
  """Deposited asset. Despite the name, this is the asset symbol (`USDC`, `ETH`, `LIT`), not its id."""
  route_type: Literal['PERPS', 'SPOT']
  """Credited balance: perps or spot."""
  accepted_amount: Decimal
  """Amount credited, in asset units."""


class L1RegisterAssetPubData(TypedDict):
  """An asset registered (`L1RegisterAsset`)."""

  asset_index: int
  """Asset id."""
  extension_multiplier: int
  """Extension multiplier."""
  margin_mode: Literal[0, 1]
  """Asset margin mode: `0` disabled, `1` enabled (lighter-go's `AssetMarginMode_Disabled`/`AssetMarginMode_Enabled`)."""
  min_transfer_amount: int
  """Minimum transfer amount, scaled."""
  min_withdrawal_amount: int
  """Minimum withdrawal amount, scaled."""


class L1SetSystemConfigPubData(TypedDict):
  """System configuration set (`L1SetSystemConfig`)."""

  liquidity_pool_index: int
  """Liquidity pool (LLP) account index."""
  staking_pool_index: int
  """Staking pool index."""
  liquidity_pool_cooldown_period: int
  """Liquidity pool cooldown period."""
  staking_pool_lockup_period: int
  """Staking pool lockup period."""
  max_integrator_perps_taker_fee: int
  """Maximum integrator perps taker fee, fixed-point."""
  max_integrator_perps_maker_fee: int
  """Maximum integrator perps maker fee, fixed-point."""
  max_integrator_spot_taker_fee: int
  """Maximum integrator spot taker fee, fixed-point."""
  max_integrator_spot_maker_fee: int
  """Maximum integrator spot maker fee, fixed-point."""


class L1UpdateAssetPubData(TypedDict):
  """An asset updated (`L1UpdateAsset`)."""

  asset_index: int
  """Asset id."""
  margin_mode: Literal[0, 1]
  """Asset margin mode: `0` disabled, `1` enabled (lighter-go's `AssetMarginMode_Disabled`/`AssetMarginMode_Enabled`)."""
  min_transfer_amount: int
  """Minimum transfer amount, scaled."""
  min_withdrawal_amount: int
  """Minimum withdrawal amount, scaled."""


class L1UpdateMarketPubData(TypedDict):
  """A perp market updated (`L1UpdateMarket`)."""

  market_index: int
  """Market id."""
  status: int
  """Market status code."""
  taker_fee: int
  """Taker fee, fixed-point."""
  maker_fee: int
  """Maker fee, fixed-point."""
  liquidation_fee: int
  """Liquidation fee, fixed-point."""
  min_base_amount: int
  """Minimum order size, scaled."""
  min_quote_amount: int
  """Minimum order notional, scaled."""
  default_initial_margin_fraction: int
  """Default initial margin fraction, fixed-point."""
  min_initial_margin_fraction: int
  """Minimum initial margin fraction, fixed-point."""
  maintenance_margin_fraction: int
  """Maintenance margin fraction, fixed-point."""
  close_out_margin_fraction: int
  """Close-out margin fraction, fixed-point."""
  interest_rate: int
  """Interest rate, fixed-point."""


class L1UpdateSpotMarketPubData(TypedDict):
  """A spot market updated (`L1UpdateSpotMarket`)."""

  market_index: int
  """Market id."""
  status: int
  """Market status code."""
  taker_fee: int
  """Taker fee, fixed-point."""
  maker_fee: int
  """Maker fee, fixed-point."""
  min_base_amount: int
  """Minimum order size, scaled."""
  min_quote_amount: int
  """Minimum order notional, scaled."""
  order_quote_limit: int
  """Maximum order notional, scaled."""


class L2CreatePublicPoolPubData(TypedDict):
  """A public pool created (`L2CreatePublicPool`)."""

  account_index: int
  """Operator account index."""
  public_pool_index: int
  """New pool account index."""
  operator_fee: int
  """Operator fee, fixed-point."""
  min_operator_share_rate: int
  """Minimum operator share rate, fixed-point."""
  initial_total_shares: int
  """Initial share supply."""


class L2CreateStakingPoolPubData(TypedDict):
  """A staking pool created (`L2CreateStakingPool`)."""

  account_index: int
  """Operator account index."""
  staking_pool_index: int
  """New staking pool index."""
  min_operator_share_rate: int
  """Minimum operator share rate, fixed-point."""
  initial_total_shares: int
  """Initial share supply."""


class L2CreateSubAccountPubData(TypedDict):
  """A sub-account created (`L2CreateSubAccount`)."""

  account_index: int
  """Master account index."""
  subAccount_index: int
  """New sub-account index."""


class L2MintSharesPubData(TypedDict):
  """Public-pool shares bought (`L2MintShares`)."""

  account_index: int
  """Account buying the shares."""
  public_pool_index: int
  """Public pool account index."""
  share_amount: int
  """Shares minted."""
  usdc_amount: Decimal
  """USDC paid."""


class L2StakeAssetsPubData(TypedDict):
  """LIT staked into a staking pool (`L2StakeAssets`)."""

  account_index: int
  """Account index."""
  staking_pool_index: int
  """Staking pool index."""
  lit_amount: Decimal
  """LIT staked."""
  share_amount: int
  """Pool shares received."""


class L2TransferPubData(TypedDict):
  """A USDC transfer between accounts, legacy layout (`L2Transfer`)."""

  from_account_index: int
  """Sender account index."""
  to_account_index: int
  """Receiver account index."""
  usdc_amount: Decimal
  """USDC transferred."""


class L2TransferPubDataV2(TypedDict):
  """A transfer between accounts or between an account's perps and spot balances (`L2TransferV2`)."""

  from_account_index: int
  """Sender account index."""
  to_account_index: int
  """Receiver account index."""
  asset_index: str
  """Transferred asset. Despite the name, this is the asset symbol (`USDC`, `LIT`), not its id."""
  amount: Decimal
  """Amount transferred, in asset units."""
  from_route_type: Literal['PERPS', 'SPOT']
  """Debited balance: perps or spot."""
  to_route_type: Literal['PERPS', 'SPOT']
  """Credited balance: perps or spot."""
  fee_account_index: int
  """Account receiving the transfer fee (`0` when none)."""
  usdc_fee: Decimal
  """Transfer fee, in USDC."""


class L2UpdateLeveragePubData(TypedDict):
  """A leverage or margin-mode change (`L2UpdateLeverage`)."""

  account_index: int
  """Account index."""
  market_index: int
  """Market id."""
  initial_margin_fraction: int
  """New initial margin fraction, in the venue's fixed-point integer units (`10000` = 100%)."""
  margin_mode: Literal[0, 1]
  """New margin mode: `0` cross margin, `1` isolated margin (lighter-go's position margin modes `CrossMargin`/`IsolatedMargin`)."""


class L2UpdateMarginPubData(TypedDict):
  """Collateral added to or removed from an isolated position (`L2UpdateMargin`)."""

  account_index: int
  """Account index."""
  market_index: int
  """Market id."""
  usdc_amount: Decimal
  """USDC moved."""
  direction: int
  """Direction code of the margin move."""


class L2UpdatePublicPoolPubData(TypedDict):
  """A public pool updated (`L2UpdatePublicPool`)."""

  public_pool_index: int
  """Pool account index."""
  status: int
  """Pool status code."""
  operator_fee: int
  """Operator fee, fixed-point."""
  min_operator_share_rate: int
  """Minimum operator share rate, fixed-point."""


class MarkPriceCandle(TypedDict):
  """One mark-price candle. Like `Candle`, zero values are omitted, so every field but `t` is optional."""

  t: TimestampMillis
  """Open time of the candle."""
  o: NotRequired[float]
  """Open mark price; omitted when zero."""
  h: NotRequired[float]
  """High mark price; omitted when zero."""
  l: NotRequired[float]
  """Low mark price; omitted when zero."""
  c: NotRequired[float]
  """Close mark price; omitted when zero."""
  sc: NotRequired[int]
  """Number of mark-price samples in the candle (undocumented); omitted when zero."""


MarketSelector = int | Literal['all']


class MarketStats(TypedDict):
  """Live statistics of one perp market."""

  symbol: str
  """Market symbol."""
  market_id: int
  """Market id."""
  index_price: Decimal
  """Index price."""
  mark_price: Decimal
  """Mark price."""
  mid_price: Decimal | Literal['']
  """Mid price; `""` when missing."""
  best_ask_price: Decimal | Literal['']
  """Best ask; `""` when missing."""
  best_bid_price: Decimal | Literal['']
  """Best bid; `""` when missing."""
  open_interest: Decimal
  """Open interest, in USDC."""
  open_interest_limit: Decimal
  """Open interest cap, in USDC (`72057594037927936` when uncapped)."""
  funding_clamp_small: Decimal
  """Small funding clamp, in percent."""
  funding_clamp_big: Decimal
  """Big funding clamp, in percent."""
  last_trade_price: Decimal
  """Last traded price."""
  current_funding_rate: Decimal
  """Estimate of the next funding payment's rate, in percent."""
  funding_rate: Decimal
  """Rate of the last funding payment, in percent."""
  funding_timestamp: TimestampMillis
  """Time of the last funding payment."""
  daily_base_token_volume: float
  """24-hour volume, in base units."""
  daily_quote_token_volume: float
  """24-hour volume, in quote units."""
  daily_price_low: float
  """24-hour low."""
  daily_price_high: float
  """24-hour high."""
  daily_price_change: float
  """24-hour price change, in percent."""
  base_interest_rate: Decimal
  """Base interest rate used in funding, in percent."""
  premium: Decimal
  """Premium of the mark over the index, in percent."""


class MovedAsset(TypedDict):
  """An asset balance moved by an account-config change."""

  asset_index: int
  """Asset id."""
  moved_asset_amount: Decimal
  """Amount moved, in asset units."""


class Order(TypedDict):
  """One order, as the REST order endpoints report it."""

  order_index: int
  """Venue-assigned order id, unique per market; `cancel_order` takes it."""
  client_order_index: int
  """Caller-chosen order id (uint48) set when the order was placed; `0` when none was given."""
  order_id: str
  """`order_index` as a decimal string (it can exceed JavaScript double precision)."""
  client_order_id: str
  """`client_order_index` as a decimal string."""
  market_index: int
  """Market id the order rests on."""
  owner_account_index: int
  """Account that placed the order."""
  initial_base_amount: Decimal
  """Original order size, in base units."""
  price: Decimal
  """Limit price (for market and triggered orders, the worst acceptable execution price)."""
  nonce: int
  """Venue-internal ordering value of the order; not the API key nonce that signed it."""
  remaining_base_amount: Decimal
  """Size still open, in base units."""
  is_ask: bool
  """True for a sell order, false for a buy order."""
  base_size: int
  """Remaining size as a scaled integer (`supported_size_decimals`); `0` once the order is closed."""
  base_price: int
  """Price as a scaled integer (`supported_price_decimals`)."""
  filled_base_amount: Decimal
  """Size filled so far, in base units."""
  filled_quote_amount: Decimal
  """Notional filled so far, in quote units."""
  side: str
  """Always `""`: the venue leaves it empty in every response (and upstream marks it for removal). Read the side from `is_ask`."""
  type: Literal[
    'limit',
    'market',
    'stop-loss',
    'stop-loss-limit',
    'take-profit',
    'take-profit-limit',
    'twap',
    'twap-sub',
    'liquidation',
  ]
  """Order type."""
  time_in_force: Literal[
    'good-till-time', 'immediate-or-cancel', 'post-only', 'Unknown'
  ]
  """Time in force; market and stop-loss/take-profit orders report `immediate-or-cancel`."""
  reduce_only: bool
  """Whether the order can only reduce a position."""
  trigger_price: Decimal
  """Trigger price of a stop-loss/take-profit order; `0.00` for other order types."""
  order_expiry: TimestampMillis
  """When a resting order expires; `0` for immediate-or-cancel and market orders."""
  status: Literal[
    'in-progress',
    'pending',
    'open',
    'filled',
    'canceled',
    'canceled-post-only',
    'canceled-reduce-only',
    'canceled-position-not-allowed',
    'canceled-margin-not-allowed',
    'canceled-too-much-slippage',
    'canceled-not-enough-liquidity',
    'canceled-self-trade',
    'canceled-expired',
    'canceled-oco',
    'canceled-child',
    'canceled-liquidation',
    'canceled-invalid-balance',
  ]
  """Lifecycle status: `pending` for an untriggered conditional order, `open` while resting, then `filled` or a `canceled-*` reason."""
  trigger_status: Literal['na', 'ready', 'mark-price', 'twap', 'parent-order']
  """What a conditional order waits for: `na` for plain orders, `mark-price` for stop-loss/take-profit orders watching the mark price, `parent-order` for grouped (OTO/OCO) children."""
  trigger_time: int
  """When a conditional order triggered; `0` while it has not. The unit is undocumented."""
  parent_order_index: int
  """Parent order of a grouped (OTO/OCO/OTOCO) child order; `0` when none."""
  parent_order_id: str
  """`parent_order_index` as a decimal string."""
  to_trigger_order_id_0: str
  """First child order this order triggers when filled (grouped orders); `"0"` when none."""
  to_trigger_order_id_1: str
  """Second child order this order triggers when filled (grouped orders); `"0"` when none."""
  to_cancel_order_id_0: str
  """Sibling order cancelled when this one fills (OCO); `"0"` when none."""
  integrator_fee_collector_index: int | Literal['']
  """Integrator account collecting fees on this order; `""` (active orders) or `"0"` (closed orders) when none."""
  integrator_taker_fee: int | Literal['']
  """Integrator taker fee on this order; `""` or `"0"` when none."""
  integrator_maker_fee: int | Literal['']
  """Integrator maker fee on this order; `""` or `"0"` when none."""
  order_flags: int
  """Bit flags of the order (undocumented; normally `0`)."""
  order_version: int
  """Version of the order, bumped by each modify (`L2ModifyOrder`)."""
  block_height: int
  """L2 block that last changed the order."""
  timestamp: TimestampSeconds
  """When the order was last updated."""
  created_at: TimestampSeconds
  """When the order was created."""
  updated_at: TimestampSeconds
  """When the order was last updated."""
  transaction_time: TimestampMicros
  """Time of the transaction that last changed the order; runs ahead of `created_at`/`updated_at`, which are taken from a different clock."""


class PoolDailyReturn(TypedDict):
  """One day's return of a pool."""

  timestamp: TimestampSeconds
  """Day the return is for."""
  daily_return: float
  """Return over that day, as a fraction (`0.01` = 1%)."""


class PoolSharePrice(TypedDict):
  """One day's share price of a pool."""

  timestamp: TimestampSeconds
  """Day of the price."""
  share_price: float
  """Share price, in USDC."""


class PoolStrategy(TypedDict):
  """Collateral allocated to one strategy of a pool."""

  collateral: Decimal
  """Collateral allocated to the strategy."""


class PositionFunding(TypedDict):
  """One funding payment on a position."""

  timestamp: TimestampSeconds
  """Funding round the payment belongs to."""
  market_id: int
  """Market id."""
  funding_id: int
  """Funding payment id."""
  change: Decimal
  """Funding paid (negative) or received (positive), in USDC."""
  rate: Decimal
  """Funding rate of the round."""
  position_size: Decimal
  """Position size at the funding round, in base units."""
  position_side: Literal['long', 'short']
  """Side of the position."""
  discount: Decimal
  """Funding discount applied, in USDC."""


class PriceLevel(TypedDict):
  """One price level of a book or a best bid/offer."""

  price: Decimal
  """Price, in quote units."""
  size: Decimal
  """Size at this price, in base units. In an `order_book` update, `0` deletes the level."""


class PublicPoolShare(TypedDict):
  """Shares an account holds in one public or staking pool."""

  public_pool_index: int
  """Pool account index."""
  shares_amount: int
  """Shares held."""
  entry_usdc: Decimal
  """USDC paid for the shares; `0` for staking-pool shares."""
  principal_amount: Decimal
  """Principal the shares stand for."""
  entry_timestamp: TimestampMillis
  """When the shares were bought; `0` for staking-pool shares."""


class RFQMetadata(TypedDict):
  """Pricing context the venue attaches to an RFQ (an empty object on testnet)."""

  requested_est_price: NotRequired[str]
  """Estimated execution price at request time."""
  requested_max_slippage: NotRequired[str]
  """Maximum slippage the requester accepts."""
  requested_slippage: NotRequired[str]
  """Slippage of the estimated price against the mark price."""
  worst_price: NotRequired[str]
  """Worst acceptable execution price."""
  mark_price: NotRequired[str]
  """Mark price when the RFQ was created."""


class RFQResponseEntry(TypedDict):
  """One market maker's response to an RFQ."""

  account_index: int
  """Account index of the responding market maker."""
  status: Literal['acknowledged', 'liquidity_provided', 'not_interested']
  """What the maker answered."""
  responded_at: TimestampMillis
  """When the maker first responded."""
  updated_at: TimestampMillis
  """When the response last changed."""


class ReferralCode(TypedDict):
  """An account's referral code."""

  code: int
  """`200` on success."""
  message: NotRequired[str]
  """Optional detail message."""
  referral_code: str
  """The referral code (8 uppercase alphanumeric characters when generated, e.g. `47663VRZ`)."""


class ResultCode(TypedDict):
  """A bare acknowledgement: the venue's result code and an optional message."""

  code: int
  """`200` on success."""
  message: NotRequired[str]
  """Optional human-readable detail; absent on most successful replies."""


class RiskParameters(TypedDict):
  """Risk parameters of cross margin, or of one isolated position."""

  market_id: NotRequired[int]
  """Market id (`255` for the cross-margin aggregate)."""
  collateral: NotRequired[Decimal]
  """Collateral."""
  total_account_value: NotRequired[Decimal]
  """Account value."""
  initial_margin_req: NotRequired[Decimal]
  """Initial margin requirement."""
  maintenance_margin_req: NotRequired[Decimal]
  """Maintenance margin requirement."""
  close_out_margin_req: NotRequired[Decimal]
  """Close-out margin requirement."""
  total_account_liquidation_threshold: NotRequired[Decimal]
  """Liquidation threshold."""
  usdc_collateral_with_funding: NotRequired[Decimal]
  """USDC collateral including unsettled funding."""
  usdc_portfolio_value: NotRequired[Decimal]
  """USDC portfolio value."""
  total_portfolio_value: NotRequired[Decimal]
  """Total portfolio value."""


class SendTxResponse(TypedDict):
  """The API server's acceptance of one signed transaction (HTTP `sendTx` or WS `jsonapi/sendtx`). Acceptance is not execution: the sequencer can still reject it later."""

  code: int
  """`200` when accepted."""
  message: NotRequired[str]
  """HTTP only: a JSON-encoded string of extra detail, e.g. `{"ratelimit": "Ratelimit is off"}`."""
  tx_hash: str
  """Hash of the accepted transaction; equal to the locally computed hash."""
  predicted_execution_time_ms: TimestampMillis
  """When the sequencer is expected to execute the transaction."""
  volume_quota_remaining: NotRequired[int]
  """Premium accounts' remaining volume quota; absent otherwise."""
  id: NotRequired[str]
  """WS only: the request's correlation id, echoed."""
  type: NotRequired[Literal['jsonapi/sendtx']]
  """WS only: the RPC frame type, echoed."""


class SignedTxWire(TypedDict):
  """One signed transaction, as the signer produced it (`SignedTx.tx_type`, `SignedTx.tx_info`)."""

  tx_type: int
  """Transaction type id."""
  tx_info: str
  """The signed transaction JSON (`SignedTx.tx_info`)."""


class SimpleOrder(TypedDict):
  """One resting order."""

  order_index: int
  """Order index (unique id of the order)."""
  order_id: str
  """`order_index` as a string (it can exceed JavaScript's safe-integer range)."""
  owner_account_index: int
  """Account that placed the order."""
  initial_base_amount: Decimal
  """Original size, in base units."""
  remaining_base_amount: Decimal
  """Unfilled size, in base units."""
  price: Decimal
  """Limit price."""
  order_expiry: TimestampMillis
  """When the order expires."""
  transaction_time: TimestampMicros
  """Time of the order's last transaction; normally `0` here."""


class SpotMarketStats(TypedDict):
  """Live statistics of one spot market."""

  symbol: str
  """Market symbol (`BASE/QUOTE`)."""
  market_id: int
  """Market id."""
  index_price: Decimal
  """Index price."""
  mid_price: Decimal | Literal['']
  """Mid price; `""` when missing."""
  best_ask_price: Decimal | Literal['']
  """Best ask; `""` when missing."""
  best_bid_price: Decimal | Literal['']
  """Best bid; `""` when missing."""
  last_trade_price: Decimal
  """Last traded price."""
  daily_base_token_volume: float
  """24-hour volume, in base units."""
  daily_quote_token_volume: float
  """24-hour volume, in quote units."""
  daily_price_low: float
  """24-hour low."""
  daily_price_high: float
  """24-hour high."""
  daily_price_change: float
  """24-hour price change, in percent."""


class StopLossLeg(TypedDict):
  """The stop-loss of an OCO or OTOCO group; its market, side and size come from the group."""

  order_type: Literal['stop-loss', 'stop-loss-limit']
  """Send a market order (`stop-loss`) or place a limit order (`stop-loss-limit`) once triggered."""
  trigger_price: int
  """Trigger price, scaled by the market's `supported_price_decimals`; compared against the mark price."""
  price: int
  """Limit price of a `stop-loss-limit`, else the worst acceptable execution price; scaled by the market's `supported_price_decimals`."""
  client_order_index: NotRequired[int]
  """Caller-chosen order id (uint48), unique within the group and among the account's open orders."""


class SubAccountMetadata(TypedDict):
  """Free-form account metadata set with `setAccountMetadata`."""

  color: str
  """Display colour set with `setAccountMetadata`; `""` when unset."""


class TakeProfitLeg(TypedDict):
  """The take-profit of an OCO or OTOCO group; its market, side and size come from the group."""

  order_type: Literal['take-profit', 'take-profit-limit']
  """Send a market order (`take-profit`) or place a limit order (`take-profit-limit`) once triggered."""
  trigger_price: int
  """Trigger price, scaled by the market's `supported_price_decimals`; compared against the mark price."""
  price: int
  """Limit price of a `take-profit-limit`, else the worst acceptable execution price; scaled by the market's `supported_price_decimals`."""
  client_order_index: NotRequired[int]
  """Caller-chosen order id (uint48), unique within the group and among the account's open orders."""


class Trade(TypedDict):
  """One executed trade. Zero-valued optional fields are omitted by the venue."""

  trade_id: int
  """Trade id."""
  trade_id_str: str
  """`trade_id` as a decimal string."""
  tx_hash: str
  """Hash of the L2 transaction that produced the trade."""
  type: Literal['trade', 'liquidation', 'deleverage', 'market-settlement']
  """How the trade happened."""
  market_id: int
  """Market id."""
  market_kind: NotRequired[str]
  """Market kind (`perps` observed); present on some trades only."""
  size: Decimal
  """Trade size, in base units."""
  price: Decimal
  """Execution price."""
  usd_amount: Decimal
  """Trade notional, in USD."""
  ask_id: int
  """`order_index` of the sell order."""
  ask_id_str: str
  """`ask_id` as a decimal string."""
  bid_id: int
  """`order_index` of the buy order."""
  bid_id_str: str
  """`bid_id` as a decimal string."""
  ask_client_id: int
  """`client_order_index` of the sell order."""
  ask_client_id_str: str
  """`ask_client_id` as a decimal string."""
  bid_client_id: int
  """`client_order_index` of the buy order."""
  bid_client_id_str: str
  """`bid_client_id` as a decimal string."""
  ask_account_id: int
  """Account that sold."""
  bid_account_id: int
  """Account that bought."""
  is_maker_ask: bool
  """True when the sell order was the resting (maker) side."""
  block_height: int
  """L2 block containing the trade."""
  timestamp: TimestampMillis
  """Time of the L2 block holding the trade (the clock `Order.timestamp` uses too). It precedes `transaction_time`, by up to about 20 seconds, and can precede the order's own submission."""
  taker_fee: NotRequired[int]
  """Taker fee rate, in parts per million of the trade's notional (`280` = 0.028%); absent when zero."""
  maker_fee: NotRequired[int]
  """Maker fee rate, in parts per million of the trade's notional (`40` = 0.004%); absent when zero."""
  taker_position_size_before: Decimal
  """Taker's position size in this market before the trade (only for trades the queried account is part of; zero otherwise)."""
  taker_entry_quote_before: Decimal
  """Taker's position entry notional before the trade."""
  taker_initial_margin_fraction_before: NotRequired[int]
  """Taker's initial margin fraction before the trade, in basis points (`500` = 5%); absent when zero."""
  taker_position_sign_changed: NotRequired[bool]
  """Whether the trade flipped or opened the taker's position; absent when false."""
  maker_position_size_before: Decimal
  """Maker's position size in this market before the trade."""
  maker_entry_quote_before: Decimal
  """Maker's position entry notional before the trade."""
  maker_initial_margin_fraction_before: NotRequired[int]
  """Maker's initial margin fraction before the trade, in basis points; absent when zero."""
  maker_position_sign_changed: NotRequired[bool]
  """Whether the trade flipped or opened the maker's position; absent when false."""
  transaction_time: TimestampMicros
  """Time of the transaction that produced the trade."""
  ask_account_pnl: NotRequired[Decimal]
  """Realized PnL of the queried account from this trade reducing a long position, or a spot position; present only then."""
  bid_account_pnl: NotRequired[Decimal]
  """Realized PnL of the queried account from this trade reducing a short position; present only then."""
  integrator_taker_fee: NotRequired[int]
  """Integrator fee charged to the taker; absent when none."""
  integrator_taker_fee_collector_index: NotRequired[int]
  """Integrator account collecting the taker fee; absent when none."""
  integrator_maker_fee: NotRequired[int]
  """Integrator fee charged to the maker; absent when none."""
  integrator_maker_fee_collector_index: NotRequired[int]
  """Integrator account collecting the maker fee; absent when none."""
  taker_allocated_margin_usdc_before: NotRequired[int]
  """Isolated margin allocated to the taker's position before the trade; absent when zero."""
  taker_allocated_margin_usdc_after: NotRequired[int]
  """Isolated margin allocated to the taker's position after the trade; absent when zero."""
  maker_allocated_margin_usdc_before: NotRequired[int]
  """Isolated margin allocated to the maker's position before the trade; absent when zero."""
  maker_allocated_margin_usdc_after: NotRequired[int]
  """Isolated margin allocated to the maker's position after the trade; absent when zero."""
  ask_order_version: int
  """`order_version` of the sell order at the time of the trade."""
  bid_order_version: int
  """`order_version` of the buy order at the time of the trade."""


class TradePubData(TypedDict):
  """A trade or liquidation trade (`Trade`, `LiquidationTrade`)."""

  trade_type: int
  """Trade kind, as the venue's integer code (`0` observed for trades and liquidations)."""
  market_index: int
  """Market id."""
  is_taker_ask: int
  """`1` when the taker sold (ask), `0` when it bought, as observed; Lighter types it as a bare integer and documents no value set."""
  maker_fee: int
  """Maker fee rate, in the venue's fixed-point integer units."""
  taker_fee: int
  """Taker fee rate, in the venue's fixed-point integer units."""
  integrator_taker_fee: NotRequired[int]
  """Integrator taker fee rate, in the venue's fixed-point integer units. Only on trades routed through an integrator."""
  integrator_taker_fee_collector_index: NotRequired[int]
  """Account collecting the integrator taker fee. Only on trades routed through an integrator."""
  taker_account_index: int
  """Taker account index."""
  maker_account_index: int
  """Maker account index."""
  fee_account_index: int
  """Account receiving the fees (`0` for regular trades; the LLP on liquidations)."""
  price: Decimal
  """Execution price."""
  size: Decimal
  """Executed size, in base units."""


class TradePubDataWithFunding(TypedDict):
  """A trade that also settled funding (`TradeWithFunding`, `LiquidationTradeWithFunding`)."""

  trade_type: int
  """Trade kind, as the venue's integer code (`0` observed for trades and liquidations)."""
  market_index: int
  """Market id."""
  is_taker_ask: int
  """`1` when the taker sold (ask), `0` when it bought, as observed; Lighter types it as a bare integer and documents no value set."""
  maker_fee: int
  """Maker fee rate, in the venue's fixed-point integer units."""
  taker_fee: int
  """Taker fee rate, in the venue's fixed-point integer units."""
  integrator_taker_fee: NotRequired[int]
  """Integrator taker fee rate, in the venue's fixed-point integer units. Only on trades routed through an integrator."""
  integrator_taker_fee_collector_index: NotRequired[int]
  """Account collecting the integrator taker fee. Only on trades routed through an integrator."""
  taker_account_index: int
  """Taker account index."""
  maker_account_index: int
  """Maker account index."""
  fee_account_index: int
  """Account receiving the fees (`0` for regular trades; the LLP on liquidations)."""
  price: Decimal
  """Execution price."""
  size: Decimal
  """Executed size, in base units."""
  funding_rate_prefix_sum: int
  """Cumulative funding-rate index of the market at execution, in the venue's fixed-point integer units."""


class TradeStats(TypedDict):
  """Trade counts, volumes and fees, split by client platform and fee tier."""

  count: int
  """Number of trades."""
  volume: Decimal
  """Traded volume, in USDC."""
  web_count: int
  """Trades placed from the web app."""
  web_volume: Decimal
  """Volume traded from the web app, in USDC."""
  mobile_app_count: int
  """Trades placed from the mobile app."""
  mobile_app_volume: Decimal
  """Volume traded from the mobile app, in USDC."""
  mobile_browser_count: int
  """Trades placed from a mobile browser."""
  mobile_browser_volume: Decimal
  """Volume traded from a mobile browser, in USDC."""
  free_maker_volume: Decimal
  """Maker volume that paid no fee, in USDC."""
  free_taker_volume: Decimal
  """Taker volume that paid no fee, in USDC."""
  non_free_maker_volume: Decimal
  """Maker volume that paid fees, in USDC."""
  non_free_taker_volume: Decimal
  """Taker volume that paid fees, in USDC."""
  maker_fees_paid: Decimal
  """Maker fees paid, in USDC."""
  taker_fees_paid: Decimal
  """Taker fees paid, in USDC."""


class Tx(TypedDict):
  """One L2 transaction, as listed by `txs`, `accountTxs` and `blockTxs`."""

  hash: str
  """Transaction hash (hex). L1 priority and internal transactions carry a synthetic, zero-padded hash."""
  type: int
  """Transaction type (`tx_type`): 1-7, 30-32, 37 and 38 are L1 priority operations (1 = deposit); 8-20, 28, 29, 35, 36, 41 and 42 are user L2 transactions (8 change pub key, 9 create sub-account, 12 transfer, 14 create order, 15 cancel order, 20 update leverage, ...); 21-27 are internal sequencer operations (claim, cancel, deleverage, exit, cancel-all, liquidate, create order). Observed live as `0` for an L2ApproveIntegrator (type 45) transaction."""
  info: str
  """The transaction itself, JSON-encoded: the Go `L2*TxInfo` struct of its type (e.g. `AccountIndex`, `MarketIndex`, `Nonce`, `Sig`), as signed."""
  event_info: str
  """What executing the transaction did, JSON-encoded with compact keys (e.g. a trade `t`, the maker order `mo` and taker order `to` of a fill); empty for some types."""
  status: Literal[0, 1, 2, 3]
  """Transaction status: `0` failed, `1` pending (queued, not yet executed), `2` executed, `3` final: executed and settled, no longer changing (the venue's docs call it "Pending - Final State")."""
  transaction_index: int
  """Position of the transaction within its block."""
  l1_address: str
  """L1 address of the account that sent the transaction."""
  account_index: int
  """Account that sent the transaction."""
  nonce: int
  """Nonce of the signing API key; `-1` for L1 priority and internal transactions. Some clients use timestamps as nonces with skip-nonce."""
  expire_at: int
  """When the sequencer stops accepting the transaction, in epoch milliseconds (`ExpiredAt`); `9223372036854775807` (int64 max) for L1 priority and internal transactions that never expire, so it is kept a plain integer."""
  block_height: int
  """Height of the block that includes the transaction."""
  queued_at: TimestampMillis
  """When the sequencer queued the transaction."""
  executed_at: TimestampMillis
  """When the transaction was executed."""
  sequence_index: int
  """Global, strictly increasing (but sparse) sequence number of the transaction; `txs`/`accountTxs` paginate on it."""
  parent_hash: str
  """Hash of the transaction that triggered this one (internal transactions such as a fill claim or a triggered cancel); empty otherwise."""
  api_key_index: int
  """API key that signed the transaction; `0` for deposits and `255` for internal transactions."""
  transaction_time: TimestampMicros
  """When the transaction was processed."""


class TxHash(TypedDict):
  """A REST endpoint's acceptance of the signed transaction it took (`litLease`, `fastwithdraw`)."""

  code: int
  """`200` when accepted."""
  message: NotRequired[str]
  """Extra detail, when the venue sends any."""
  tx_hash: str
  """Hash of the accepted transaction; equal to the locally computed hash."""


class UnstakeAssetsPubData(TypedDict):
  """LIT unstaked from a staking pool (`UnstakeAssets`)."""

  account_index: int
  """Account index."""
  staking_pool_index: int
  """Staking pool index."""
  lit_amount: Decimal
  """LIT unstaked."""
  share_amount: int
  """Pool shares redeemed."""


class UpdateResult(TypedDict):
  """Result of a referral setting change."""

  code: int
  """`200` on success."""
  message: NotRequired[str]
  """Optional human-readable detail; absent on most successful replies."""
  success: bool
  """Whether the change was applied."""


class WithdrawPubData(TypedDict):
  """A USDC withdrawal to L1, legacy layout (`Withdraw`)."""

  from_account_index: int
  """Withdrawing account index."""
  usdc_amount: Decimal
  """USDC withdrawn."""


class WithdrawPubDataV2(TypedDict):
  """A withdrawal to L1 (`WithdrawV2`)."""

  from_account_index: int
  """Withdrawing account index."""
  asset_index: str
  """Withdrawn asset. Despite the name, this is the asset symbol (`USDC`), not its id."""
  amount: Decimal
  """Amount withdrawn, in asset units."""
  route_type: Literal['PERPS', 'SPOT']
  """Debited balance: perps or spot."""


class Block(TypedDict):
  """One L2 block."""

  commitment: str
  """Block commitment (hex); empty on testnet, where blocks are not committed to L1."""
  height: int
  """Block height."""
  state_root: str
  """State root after the block (hex); empty on testnet."""
  priority_operations: int
  """Number of L1 priority operations in the block."""
  on_chain_l2_operations: int
  """Number of L2 operations with on-chain public data in the block."""
  pending_on_chain_operations_pub_data: str
  """Public data of the pending on-chain operations (hex); empty when none."""
  committed_tx_hash: str
  """L1 transaction hash that committed the block; empty until committed."""
  committed_at: int
  """When the block was committed on L1; `0` until committed (always `0` on testnet), unit undocumented."""
  verified_tx_hash: str
  """L1 transaction hash that verified the block; empty until verified."""
  verified_at: int
  """When the block was verified on L1; `0` until verified (always `0` on testnet), unit undocumented."""
  txs: list[Tx]
  """Transactions of the block; the venue returns it empty (use `blockTxs`, or `txs` by sequence index)."""
  status: int
  """Block status code (values undocumented)."""
  size: int
  """Number of transactions in the block."""


class ExplorerAccountAssets(TypedDict):
  """Spot balances of an account."""

  assets: dict[str, ExplorerAsset]
  """Balances, keyed by asset id (as a string)."""


class ExplorerAccountPositions(TypedDict):
  """Open positions of an account."""

  positions: dict[str, ExplorerPosition]
  """Open positions, keyed by market id (as a string). Empty for an account with none, or an unknown account index."""


class ExplorerBatch(TypedDict):
  """One batch of blocks committed to L1."""

  batch_number: int
  """Batch number."""
  updated_at: TimestampIso
  """Last update of the batch."""
  batch_details: ExplorerBatchDetails | None
  """L1 transactions of the batch; `null` until committed (and always on testnet)."""
  blocks: list[ExplorerBatchBlock]
  """Every block in the batch."""
  status_changes: list[ExplorerBatchStatusChange]
  """L1 status transitions of the batch, oldest first (empty until committed)."""


GroupPrimaryOrder = GroupLimitOrder | GroupMarketOrder


class L2UpdateAccountConfigPubData(TypedDict):
  """An account trading-mode change (`L2UpdateAccountConfig`)."""

  account_index: int
  """Account index."""
  account_trading_mode: Literal[0, 1]
  """New trading mode: `0` classic, `1` unified."""
  asset_amounts: list[MovedAsset]
  """Asset balances moved by the change."""


class Orders(TypedDict):
  """A list of orders (`accountActiveOrders`, `accountInactiveOrders`, `accountOrders`)."""

  code: int
  """`200` on success."""
  message: NotRequired[str]
  """Optional human-readable detail; usually absent on success."""
  next_cursor: NotRequired[str]
  """Cursor of the next page (`accountInactiveOrders` only); absent on the last page."""
  orders: list[Order]
  """Orders, newest first."""


class PublicPoolInfo(TypedDict):
  """A public or staking pool: fees, shares, returns and strategies."""

  status: Literal[0, 1]
  """Pool status: `0` active, `1` frozen (a frozen pool only allows burning shares)."""
  operator_fee: Decimal
  """Operator fee, in percent of profits."""
  min_operator_share_rate: Decimal
  """Minimum share of the pool the operator must keep, in percent."""
  total_shares: int
  """Shares outstanding."""
  operator_shares: int
  """Shares held by the operator."""
  annual_percentage_yield: float
  """Annualized yield, in percent."""
  daily_returns: list[PoolDailyReturn]
  """Daily returns, oldest first."""
  share_prices: list[PoolSharePrice]
  """Daily share prices, oldest first."""
  sharpe_ratio: float
  """Sharpe ratio of the daily returns."""
  strategies: list[PoolStrategy | None]
  """Per-strategy collateral (the LLP has several strategies); a pool without strategies lists `null` slots."""


class RFQ(TypedDict):
  """One request for quote."""

  id: int
  """RFQ id, global and increasing."""
  account_index: int
  """Account that requested the quote."""
  market_index: int
  """Market id the quote is for."""
  direction: int
  """Direction the requester chose (`0` or `1` on creation; older RFQs by other accounts report `-1`, whose meaning is undocumented)."""
  base_amount: int | Literal['']
  """Requested base amount as an integer string, or `""` when the RFQ was sized by the other amount."""
  quote_amount: int | Literal['']
  """Requested quote amount as an integer string, or `""` when the RFQ was sized by the other amount."""
  status: Literal['opened', 'order_created', 'closed']
  """Lifecycle state: open for responses, an order was created from it, or closed."""
  metadata: RFQMetadata
  """Pricing context the venue attaches to the RFQ."""
  responses: list[RFQResponseEntry]
  """Market maker responses, if any."""
  created_at: TimestampMillis
  """When the RFQ was created."""
  updated_at: TimestampMillis
  """When the RFQ last changed (e.g. was closed)."""


class RFQResult(TypedDict):
  """One request for quote, as returned by create, get, respond and update (the RFQ's fields beside the result code)."""

  code: int
  """`200` on success."""
  message: NotRequired[str]
  """Optional human-readable detail; absent on most successful replies."""
  id: int
  """RFQ id, global and increasing."""
  account_index: int
  """Account that requested the quote."""
  market_index: int
  """Market id the quote is for."""
  direction: int
  """Direction the requester chose (`0` or `1` on creation; older RFQs by other accounts report `-1`, whose meaning is undocumented)."""
  base_amount: int | Literal['']
  """Requested base amount as an integer string, or `""` when the RFQ was sized by the other amount."""
  quote_amount: int | Literal['']
  """Requested quote amount as an integer string, or `""` when the RFQ was sized by the other amount."""
  status: Literal['opened', 'order_created', 'closed']
  """Lifecycle state: open for responses, an order was created from it, or closed."""
  metadata: RFQMetadata
  """Pricing context the venue attaches to the RFQ."""
  responses: list[RFQResponseEntry]
  """Market maker responses, if any."""
  created_at: TimestampMillis
  """When the RFQ was created."""
  updated_at: TimestampMillis
  """When the RFQ last changed (e.g. was closed)."""


class RiskInfo(TypedDict):
  """An account's cross and isolated risk parameters at one point in time."""

  cross_risk_parameters: NotRequired[RiskParameters]
  """Cross-margin risk parameters."""
  isolated_risk_parameters: NotRequired[list[RiskParameters]]
  """Risk parameters per isolated position."""


class Trades(TypedDict):
  """A page of trades (`trades`)."""

  code: int
  """`200` on success."""
  message: NotRequired[str]
  """Optional human-readable detail; usually absent on success."""
  next_cursor: NotRequired[str]
  """Cursor of the next page (`trades` only); absent on the last page."""
  trades: list[Trade]
  """Trades, newest first."""


class Txs(TypedDict):
  """A list of L2 transactions."""

  code: int
  """`200` on success."""
  message: NotRequired[str]
  """Optional detail message."""
  txs: list[Tx]
  """Transactions, in ascending sequence index."""


class Blocks(TypedDict):
  """A list of L2 blocks."""

  code: int
  """`200` on success."""
  message: NotRequired[str]
  """Optional detail message."""
  total: int
  """Total number of blocks (about the current height)."""
  blocks: list[Block]
  """Blocks, in the requested order."""


class ExplorerPubData(TypedDict):
  """Decoded public data of a log. At most one key is present, named after the log's `pubdata_type`; logs that carry no public data (e.g. `L2UpdateMarketConfig`) have an empty object."""

  trade_pubdata: NotRequired[TradePubData]
  trade_pubdata_with_funding: NotRequired[TradePubDataWithFunding]
  deleverage_pubdata: NotRequired[DeleveragePubData]
  deleverage_pubdata_with_funding: NotRequired[DeleveragePubDataWithFunding]
  exit_position_pubdata: NotRequired[ExitPositionPubData]
  exit_position_pubdata_with_funding: NotRequired[ExitPositionPubDataWithFunding]
  burned_shares_pubdata: NotRequired[BurnedSharesPubData]
  l2_mint_shares_pubdata: NotRequired[L2MintSharesPubData]
  l1_deposit_pubdata: NotRequired[L1DepositPubData]
  l1_deposit_pubdata_v2: NotRequired[L1DepositPubDataV2]
  l2_create_sub_account_pubdata: NotRequired[L2CreateSubAccountPubData]
  l2_transfer_pubdata: NotRequired[L2TransferPubData]
  l2_transfer_pubdata_v2: NotRequired[L2TransferPubDataV2]
  withdraw_pubdata: NotRequired[WithdrawPubData]
  withdraw_pubdata_v2: NotRequired[WithdrawPubDataV2]
  l2_update_leverage_pubdata: NotRequired[L2UpdateLeveragePubData]
  l2_update_margin_pubdata: NotRequired[L2UpdateMarginPubData]
  l2_update_account_config_pubdata: NotRequired[L2UpdateAccountConfigPubData]
  l2_stake_assets_pubdata: NotRequired[L2StakeAssetsPubData]
  unstake_assets_pubdata: NotRequired[UnstakeAssetsPubData]
  executed_pending_unlock_pubdata: NotRequired[ExecutedPendingUnlockPubData]
  l1_create_market_pubdata: NotRequired[L1CreateMarketPubData]
  l1_create_market_pubdata_v2: NotRequired[L1CreateMarketPubDataV2]
  l1_update_market_pubdata: NotRequired[L1UpdateMarketPubData]
  l1_create_spot_market_pubdata: NotRequired[L1CreateSpotMarketPubData]
  l1_update_spot_market_pubdata: NotRequired[L1UpdateSpotMarketPubData]
  l1_register_asset_pubdata: NotRequired[L1RegisterAssetPubData]
  l1_update_asset_pubdata: NotRequired[L1UpdateAssetPubData]
  l1_set_system_config_pubdata: NotRequired[L1SetSystemConfigPubData]
  l2_create_public_pool_pubdata: NotRequired[L2CreatePublicPoolPubData]
  l2_update_public_pool_pubdata: NotRequired[L2UpdatePublicPoolPubData]
  l2_create_staking_pool_pubdata: NotRequired[L2CreateStakingPoolPubData]


class ExplorerLog(TypedDict):
  """One log (an executed transaction that produced public data)."""

  tx_type: str
  """Transaction type (`L2CreateOrder`, `InternalClaimOrder`, `L1Deposit`, ...). The documented set is incomplete (it lacks `InternalLiquidateSpot`, which the venue sends), so it stays a string."""
  hash: str
  """Transaction hash (hex, no `0x`)."""
  time: TimestampIso
  """When the transaction executed."""
  pubdata: ExplorerPubData
  """Decoded public data of the log."""
  pubdata_type: Literal[
    'Empty',
    'L1Deposit',
    'L1CreateMarket',
    'L1UpdateMarket',
    'L2CreateSubAccount',
    'L2CreatePublicPool',
    'L2UpdatePublicPool',
    'L2MintShares',
    'L2UpdateLeverage',
    'L2UpdateMargin',
    'L2Transfer',
    'Withdraw',
    'Trade',
    'TradeWithFunding',
    'LiquidationTrade',
    'LiquidationTradeWithFunding',
    'BurnedShares',
    'ExitPosition',
    'ExitPositionWithFunding',
    'Deleverage',
    'DeleverageWithFunding',
    'L1RegisterAsset',
    'L1UpdateAsset',
    'L1CreateSpotMarket',
    'L1UpdateSpotMarket',
    'WithdrawV2',
    'L1CreateMarketV2',
    'L1DepositV2',
    'L1UpdateMarketV2',
    'L2TransferV2',
    'L2CreateStakingPool',
    'L2UpdateStakingPool',
    'L2StakeAssets',
    'UnstakeAssets',
    'L1SetSystemConfig',
    'ExecutedPendingUnlock',
    'L2UpdateAccountConfig',
    'L2UpdateMarketConfig',
  ]
  """Kind of public data the log carries; names the one `pubdata` key present."""
  status: Literal['nothing_to_execute', 'committed', 'verified', 'executed'] | None
  """L1 status of the batch holding the log; `null` until the log's block is in a batch that reached L1."""


class ExplorerLogDetailed(TypedDict):
  """One log, with the block and batch holding it."""

  tx_type: str
  """Transaction type (`L2CreateOrder`, `InternalClaimOrder`, `L1Deposit`, ...). The documented set is incomplete (it lacks `InternalLiquidateSpot`, which the venue sends), so it stays a string."""
  hash: str
  """Transaction hash (hex, no `0x`)."""
  time: TimestampIso
  """When the transaction executed."""
  pubdata: ExplorerPubData
  """Decoded public data of the log."""
  pubdata_type: Literal[
    'Empty',
    'L1Deposit',
    'L1CreateMarket',
    'L1UpdateMarket',
    'L2CreateSubAccount',
    'L2CreatePublicPool',
    'L2UpdatePublicPool',
    'L2MintShares',
    'L2UpdateLeverage',
    'L2UpdateMargin',
    'L2Transfer',
    'Withdraw',
    'Trade',
    'TradeWithFunding',
    'LiquidationTrade',
    'LiquidationTradeWithFunding',
    'BurnedShares',
    'ExitPosition',
    'ExitPositionWithFunding',
    'Deleverage',
    'DeleverageWithFunding',
    'L1RegisterAsset',
    'L1UpdateAsset',
    'L1CreateSpotMarket',
    'L1UpdateSpotMarket',
    'WithdrawV2',
    'L1CreateMarketV2',
    'L1DepositV2',
    'L1UpdateMarketV2',
    'L2TransferV2',
    'L2CreateStakingPool',
    'L2UpdateStakingPool',
    'L2StakeAssets',
    'UnstakeAssets',
    'L1SetSystemConfig',
    'ExecutedPendingUnlock',
    'L2UpdateAccountConfig',
    'L2UpdateMarketConfig',
  ]
  """Kind of public data the log carries; names the one `pubdata` key present."""
  block_number: int
  """Height of the block holding the log."""
  batch_number: int | None
  """Number of the batch holding the block; `null` until the block is batched."""
  status: Literal['nothing_to_execute', 'committed', 'verified', 'executed'] | None
  """L1 status of the batch holding the log; `null` until the log's block is in a batch that reached L1."""


class ExplorerBlock(TypedDict):
  """One L2 block, with its logs and the market state at the block."""

  block_number: int
  """Block height."""
  batch_number: int | None
  """Number of the batch holding the block; `null` until the block is batched."""
  batch_status: (
    Literal['nothing_to_execute', 'committed', 'verified', 'executed'] | None
  )
  """L1 status of the batch; `null` until the batch reached L1."""
  batch_status_time: TimestampIso | None
  """When the batch reached `batch_status`; `null` alongside it."""
  batch_details: ExplorerBatchDetails | None
  """L1 transactions of the batch; `null` until committed."""
  total_transactions: int
  """Transactions in the block."""
  logs: list[ExplorerLog]
  """Logs of the block: only transactions that produced public data, not every transaction of the block."""
  markets: list[ExplorerMarketState]
  """State of every perp market at the block."""
