# Generated by typed-dev — see CONTRIBUTING.md.
from typed_core import PaginatedResponse
from typing_extensions import Literal, NotRequired, TypedDict
from typed_binance.core.endpoint.rpc import RpcEndpoint


class FuturesOrderRateLimitPageEntry(TypedDict):
  """Order rate limit for one account."""

  userId: NotRequired[int]
  """Account user ID this rate limit applies to."""
  userEmail: NotRequired[str]
  """Email address of the account this rate limit applies to."""
  limit: NotRequired[int]
  """Order rate limit assigned to this account."""


class Request(TypedDict):
  """Request parameters."""

  productType: Literal['CM', 'UM']
  """Futures product type to query user order rate limits for."""
  pageIndex: int
  """Page number, starting from 1."""
  pageSize: int
  """Number of records per page."""


class FuturesOrderRateLimitsPage(TypedDict):
  """One page of order rate limit entries."""

  total: NotRequired[int]
  """Total number of matching order rate limit entries across all pages."""
  rows: NotRequired[list[FuturesOrderRateLimitPageEntry]]
  """Order rate limit entries for this page."""


class FuturesOrderRateLimitsPageResult(TypedDict):
  """A page of futures user order rate limits."""

  status: NotRequired[str]
  """Response status, e.g. `OK`."""
  type: NotRequired[str]
  """Response category, e.g. `GENERAL`."""
  code: NotRequired[str]
  """Response code; `"000000000"` on success."""
  data: NotRequired[FuturesOrderRateLimitsPage]


class FuturesOrderRateLimitsPaged(RpcEndpoint):
  """Query futures user order rate limits, paginated."""

  def futures_order_rate_limits_paged_paged(
    self,
    product_type: Literal['CM', 'UM'],
    *,
    page_size: int,
    validate: bool | None = None,
  ) -> PaginatedResponse[FuturesOrderRateLimitPageEntry, int]:
    """Query futures user order rate limits, paginated.

    Paged variant of `futures_order_rate_limits_paged`: Awaitable (flattens every page) or async-iterable (one page at a time).

    Args:
      product_type: Futures product type to query user order rate limits for.
      page_size: Number of records per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/vip-and-institutional-vip-service/api/rest-api/~#query-futures-userorder-rate-limits-with-pagination)
    """

    async def next(
      page_index: int,
    ) -> tuple[list[FuturesOrderRateLimitPageEntry], int | None]:
      response = await self.futures_order_rate_limits_paged(
        product_type, page_size=page_size, page_index=page_index, validate=validate
      )
      rows_0 = response.get('data')
      rows = rows_0.get('rows') if rows_0 is not None else None
      rows = rows if rows is not None else []
      total_0 = response.get('data')
      total = total_0.get('total') if total_0 is not None else None
      total = int(total) if total is not None else None
      if total is None or (page_index - 1 + 1) * page_size >= total:
        return rows, None
      return rows, page_index + 1

    return PaginatedResponse(1, next)

  async def futures_order_rate_limits_paged(
    self,
    product_type: Literal['CM', 'UM'],
    *,
    page_index: int,
    page_size: int,
    validate: bool | None = None,
  ) -> FuturesOrderRateLimitsPageResult:
    """Query futures user order rate limits, paginated.

    Args:
      product_type: Futures product type to query user order rate limits for.
      page_index: Page number, starting from 1.
      page_size: Number of records per page.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/vip-and-institutional-vip-service/api/rest-api/~#query-futures-userorder-rate-limits-with-pagination)
    """
    return await self.request(
      Request(productType=product_type, pageIndex=page_index, pageSize=page_size),
      method='GET',
      path='/sapi/v1/vip/vip-portal/futures/rate-limits/orders/pages',
      meta={'security': 'USER_DATA', 'signed': True},
      validate=validate,
      request_type=Request,
      response_type=FuturesOrderRateLimitsPageResult,
    )
