# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import TypedDict
from typed_core.validation import validator
from binance.core.endpoint.rpc import RpcEndpoint


class MarkPriceInfo0(TypedDict):
  """Mark price, index price, and latest funding rate for one symbol."""

  symbol: str
  """Trading symbol."""
  markPrice: str
  """Mark price."""
  indexPrice: str
  """Index price."""
  estimatedSettlePrice: str
  """Estimated settlement price. Only meaningful in the last hour before settlement."""
  lastFundingRate: str
  """Latest funding rate."""
  interestRate: str
  """Interest rate used in the funding rate calculation."""
  nextFundingTime: int
  """Next funding time, in milliseconds since epoch."""
  time: int
  """Current time, in milliseconds since epoch."""


class MarkPriceInfoItem(TypedDict):
  """Mark price, index price, and latest funding rate for one symbol."""

  symbol: str
  """Trading symbol."""
  markPrice: str
  """Mark price."""
  indexPrice: str
  """Index price."""
  estimatedSettlePrice: str
  """Estimated settlement price. Only meaningful in the last hour before settlement."""
  lastFundingRate: str
  """Latest funding rate."""
  interestRate: str
  """Interest rate used in the funding rate calculation."""
  nextFundingTime: int
  """Next funding time, in milliseconds since epoch."""
  time: int
  """Current time, in milliseconds since epoch."""


class PremiumIndex(RpcEndpoint):
  """Mark price, index price, and latest funding rate for a symbol, or for every symbol when omitted."""

  async def premium_index(
    self,
    *,
    symbol: str | None = None,
    validate: bool | None = None,
  ) -> MarkPriceInfo0 | list[MarkPriceInfoItem]:
    """Mark price, index price, and latest funding rate for a symbol, or for every symbol when omitted.

    Args:
      symbol: Trading symbol, e.g. BTCUSDT. Omit to get every symbol as an array.

    References:
      - [Official docs](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/rest-api/market-data#mark-price)
    """
    params = {}
    if symbol is not None:
      params['symbol'] = symbol
    _Response = MarkPriceInfo0 | list[MarkPriceInfoItem]
    _validator = validator[_Response](_Response)  # type: ignore
    return await self.request(
      'GET',
      '/fapi/v1/premiumIndex',
      params=params,
      validator=_validator,
      validate=validate,
    )
