# Generated by typed-dev — see CONTRIBUTING.md.
"""`POST /v5/grid/query-grid-detail` — Get Spot Grid Bot Detail."""

from typing_extensions import Literal, NotRequired, TypedDict
from typed_bybit.core import Endpoint, TimestampMillis, validator


class GetSpotGridBotDetailRequest(TypedDict):
  """Spot grid bot detail query parameters."""

  grid_id: str
  """Grid bot ID to query, obtained from the Create Spot Grid Bot response or a grid listing endpoint."""


class SpotGridBotDetail(TypedDict):
  """Spot grid bot detail."""

  grid_id: int
  """Grid bot ID."""
  symbol: str
  """Trading pair, for example `BTCUSDT`."""
  base_token: str
  """Base token symbol, for example `BTC`."""
  quote_token: str
  """Quote token symbol, for example `USDT`."""
  status: Literal[
    'RAW', 'REJECTED', 'NEW', 'INITIALIZING', 'RUNNING', 'CANCELLING', 'COMPLETED'
  ]
  """Bot lifecycle status."""
  max_price: str
  """Grid upper price bound."""
  min_price: str
  """Grid lower price bound."""
  cell_number: int
  """Number of active grid intervals."""
  total_investment: str
  """Total investment amount in the quote token."""
  total_profit: str
  """Total profit in the quote token."""
  grid_profit: str
  """Grid arbitrage profit in the quote token."""
  grid_apr: str
  """Grid APR as a decimal ratio, for example `"0.15"` means 15%."""
  total_apr: str
  """Total APR as a decimal ratio, for example `"0.2"` means 20%."""
  arbitrage_num: int
  """Total number of completed arbitrage trades."""
  arbitrage_num_24: int
  """Number of arbitrage trades in the last 24 hours."""
  current_price: str
  """Current market price."""
  current_profit: NotRequired[str]
  """Current unrealized P&L. Only present for bots in `RUNNING` state."""
  current_per: NotRequired[str]
  """Current P&L as a decimal ratio, for example `"0.05"` means 5%. Only present for bots in `RUNNING` state."""
  equity: str
  """Current equity in the quote token."""
  entry_price: str
  """Entry trigger price, if set."""
  stop_loss_price: str
  """Stop-loss price, if set."""
  take_profit_price: str
  """Take-profit price, if set."""
  close_reason: str
  """Reason for closure, for example manual close, failed initiation, symbol delisted, stop-loss/take-profit triggered, user banned, trailing stop."""
  bot_close_code: str
  """Close code describing how the bot was closed."""
  ts_percent: str
  """Trailing stop callback as a decimal ratio, for example `"0.05"` means 5%."""
  is_support_ts: bool
  """Whether the symbol supports trailing stop."""
  enable_trailing: bool
  """Whether grid trailing is enabled."""
  limit_up_price: str
  """Upper limit price for grid trailing."""
  ori_max_price: str
  """Original max price before a trailing shift."""
  ori_min_price: str
  """Original min price before a trailing shift."""
  ori_cell_number: int
  """Original grid count before a trailing shift."""
  allow_follow: int
  """Whether copy-trading is allowed: `1` yes, `0` no."""
  follow_num: int
  """Number of copy-trade followers."""
  operation_time: int
  """Milliseconds since bot creation."""
  create_time: TimestampMillis
  """Creation time, as a Unix-milliseconds integer."""
  end_time: TimestampMillis
  """End time, as a Unix-milliseconds integer. `0` if still running."""
  used_reward_amount: str
  """Total voucher amount used, in the quote token."""
  settlement_assets: str
  """Settlement asset information on close."""
  account_type: str
  """Account funding source, for example a derivatives, unified, spot or fund account."""
  cum_withdrew_amount: str
  """Cumulative withdrawn profit, in the quote token."""
  spot_symbol_status: NotRequired[str]
  """Trading status of the underlying spot symbol, for example `ONLINE`."""
  used_reward_id: NotRequired[str]
  """ID of the voucher used."""
  taker_fee_rate: NotRequired[str]
  """Taker fee rate as a decimal ratio."""
  maker_fee_rate: NotRequired[str]
  """Maker fee rate as a decimal ratio."""
  ts_exit_equity: NotRequired[str]
  """Equity at trailing stop exit."""


class GetSpotGridBotDetailResult(TypedDict):
  """Result of querying a spot grid bot's detail."""

  status_code: int
  """Business status code; `404` when `grid_id` does not exist."""
  debug_msg: str
  """Debug message, for example a `[...] grid not found`-style note or testnet debug info."""
  detail: SpotGridBotDetail | None
  """Grid bot detail, or `null` when `grid_id` does not exist."""


adapter = validator[GetSpotGridBotDetailResult](GetSpotGridBotDetailResult)


class GetDetail(Endpoint):
  """`Get Spot Grid Bot Detail` — mixed into the router that owns `bot.spot_grid.get_detail`."""

  async def get_detail(
    self,
    get_spot_grid_bot_detail_request: GetSpotGridBotDetailRequest,
    *,
    validate: bool | None = None,
  ) -> GetSpotGridBotDetailResult:
    """Retrieve comprehensive details for a specific spot grid bot, including configuration, status, profit metrics, arbitrage count, TP/SL settings, and close reason.

    Args:
      get_spot_grid_bot_detail_request: Bot to query.
      validate: Validate the response against the generated schema.

    References:
      - [Bybit API docs](https://bybit-exchange.github.io/docs/v5/bot/spot-grid/get-detail)
    """
    r = await self.authed_request(
      'POST', '/v5/grid/query-grid-detail', json=get_spot_grid_bot_detail_request
    )
    return self.result(r, adapter, validate)
