# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import NotRequired, TypedDict
from typed_aster.chain.rpc.schemas import ChainFills
from typed_aster.core import TimestampMillis
from typed_aster.core.endpoint.jsonrpc import JsonRpcEndpoint


RequestKeywords = TypedDict('RequestKeywords', {'from': NotRequired[TimestampMillis]})
"""
- `from`: Start time. Omitted: `to` minus 7 days, or 7 days ago when `to` is also `null`. Must not be before the block-1 genesis time `1772678119418`.
"""


class Request(RequestKeywords):
  address: str
  """Wallet address to query. The fills and open-orders methods match it case-sensitively: pass the EIP-55 checksum form (a lowercase address silently returns no rows)."""
  symbol: NotRequired[str]
  """Trading pair symbol, e.g. `BTCUSDT`; omit (or `""`) for every symbol."""
  to: NotRequired[TimestampMillis]
  """End time. Omitted: `from` plus 7 days, or now when `from` is also `null`. The range must not exceed 7 days."""
  blockTag: NotRequired[str]
  """Block tag; `latest` for the most recent state. Ignored by the venue: every tag, and an omitted one, returns the current state."""


class UserFills(JsonRpcEndpoint):
  """Get the futures trade fills of an address within a time range of at most 7 days (at most 1000, newest first)."""

  async def user_fills(
    self,
    *,
    address: str,
    symbol: str | None = None,
    from_: TimestampMillis | None = None,
    to: TimestampMillis | None = None,
    block_tag: str | None = None,
    validate: bool | None = None,
  ) -> ChainFills:
    """Get the futures trade fills of an address within a time range of at most 7 days (at most 1000, newest first).

    Args:
      address: Wallet address to query. The fills and open-orders methods match it case-sensitively: pass the EIP-55 checksum form (a lowercase address silently returns no rows).
      symbol: Trading pair symbol, e.g. `BTCUSDT`; omit (or `""`) for every symbol.
      from_: Start time. Omitted: `to` minus 7 days, or 7 days ago when `to` is also `null`. Must not be before the block-1 genesis time `1772678119418`.
      to: End time. Omitted: `from` plus 7 days, or now when `from` is also `null`. The range must not exceed 7 days.
      block_tag: Block tag; `latest` for the most recent state. Ignored by the venue: every tag, and an omitted one, returns the current state.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://asterdex.github.io/aster-api-website/rpc/endpoints/#get-user-fills)
    """
    request: Request = Request(address=address)
    if symbol is not None:
      request['symbol'] = symbol
    if from_ is not None:
      request['from'] = from_
    if to is not None:
      request['to'] = to
    if block_tag is not None:
      request['blockTag'] = block_tag
    return await self.request(
      request,
      path='aster_userFills',
      meta={'params': ['address', 'symbol', 'from', 'to', 'blockTag']},
      validate=validate,
      request_type=Request,
      response_type=ChainFills,
    )
