# Generated by typed-dev — see CONTRIBUTING.md.
from .get_loan_market import GetLoanMarket
from .get_loan_market_interest_rate import GetLoanMarketInterestRate
from .get_purchase_orders import GetPurchaseOrders
from .get_redeem_orders import GetRedeemOrders
from .modify_purchase import ModifyPurchase
from .purchase import Purchase
from .redeem import Redeem


class Credit(
  GetLoanMarket,
  GetLoanMarketInterestRate,
  GetPurchaseOrders,
  GetRedeemOrders,
  ModifyPurchase,
  Purchase,
  Redeem,
):
  """Credit — lending assets into KuCoin's margin loan market: browsing market rates, purchasing/redeeming a lending position, and reading the account's purchase/redeem orders.

  References:
    - [Upstream docs](https://www.kucoin.com/docs-new/rest/margin-trading/credit/get-loan-market)
  """
