# Generated by typed-dev — see CONTRIBUTING.md.
from typing_extensions import TypedDict
from typed_aster.core.endpoint.rpc import RpcEndpoint


class Request(TypedDict):
  """Symbol whose MMP configuration to delete."""

  symbol: str
  """Symbol, e.g. `BTCUSDT`."""


Response = bool


class Delete(RpcEndpoint):
  """Delete a symbol's MMP configuration."""

  async def delete(self, symbol: str, *, validate: bool | None = None) -> Response:
    """Delete a symbol's MMP configuration.

    Args:
      symbol: Symbol, e.g. `BTCUSDT`.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://asterdex.github.io/aster-api-website/futures-v3/account&trades/#delete-user-mmp-user_data)
    """
    return await self.request(
      Request(symbol=symbol),
      method='DELETE',
      path='mmp',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
